package app.bean;
// Generated 17 Sep, 2020 2:35:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.validator.constraints.NotEmpty;

import app.bean.menu.IwmpMMenu;

/**
 * IwmpMenu generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_submenu")
public class IwmpMenu  implements java.io.Serializable {


	 private int menuId;
     private IwmpMMenu iwmpMMenu;
     @NotEmpty(message = "Please enter Menu Name.")
     private String submenuName;
     @NotNull(message = "Please enter Sequence Number.")
     private BigDecimal seqNo;
     private String target;
     private String submenuHindiName;
     private Boolean isactive;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Set<IwmpRoleMenuMap> iwmpRoleMenuMaps = new HashSet<IwmpRoleMenuMap>(0);

     @Transient
     int [] mapRoleId;
     
     @Transient
     int isParent;
     
     @Transient
     public int getIsParent() {
		return isParent;
	}
     @Transient
     public int[] getMapRoleId() {
   		return mapRoleId;
   	}
   	public void setMapRoleId(int[] mapRoleId) {
   		this.mapRoleId = mapRoleId;
   	}
	public void setIsParent(int isParent) {
		this.isParent = isParent;
	}
	
    public IwmpMenu() {
    }

	
    public IwmpMenu(int submenuId, String submenuName, String target, String submenuHindiName) {
        this.menuId = submenuId;
        this.submenuName = submenuName;
        this.target = target;
        this.submenuHindiName = submenuHindiName;
    }
    public IwmpMenu(int submenuId, IwmpMMenu iwmpMMenu, String submenuName, BigDecimal seqNo, String target, String submenuHindiName, Boolean isactive, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Set<IwmpRoleMenuMap> iwmpRoleMenuMaps) {
       this.menuId = submenuId;
       this.iwmpMMenu = iwmpMMenu;
       this.submenuName = submenuName;
       this.seqNo = seqNo;
       this.target = target;
       this.submenuHindiName = submenuHindiName;
       this.isactive = isactive;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.iwmpRoleMenuMaps = iwmpRoleMenuMaps;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="submenu_id", unique=true, nullable=false)
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int submenuId) {
        this.menuId = submenuId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="parent_id")
    public IwmpMMenu getIwmpMMenu() {
        return this.iwmpMMenu;
    }
    
    public void setIwmpMMenu(IwmpMMenu iwmpMMenu) {
        this.iwmpMMenu = iwmpMMenu;
    }

    
    @Column(name="submenu_name", nullable=false, length=100)
    public String getSubmenuName() {
        return this.submenuName;
    }
    
    public void setSubmenuName(String submenuName) {
        this.submenuName = submenuName;
    }

    
    @Column(name="seq_no", precision=6)
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }

    
    @Column(name="target", nullable=false, length=250)
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }

    
    @Column(name="submenu_hindi_name",  length=500)
    public String getSubmenuHindiName() {
		return submenuHindiName;
	}
	public void setSubmenuHindiName(String submenuHindiName) {
		this.submenuHindiName = submenuHindiName;
	}
	@Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMenu" ,cascade=CascadeType.REMOVE,orphanRemoval = true)
    public Set<IwmpRoleMenuMap> getIwmpRoleMenuMaps() {
        return this.iwmpRoleMenuMaps;
    }
    
    public void setIwmpRoleMenuMaps(Set<IwmpRoleMenuMap> iwmpRoleMenuMaps) {
        this.iwmpRoleMenuMaps = iwmpRoleMenuMaps;
    }




}


