package app.bean;
// Generated 17 Sep, 2020 2:35:44 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.CreationTimestamp;

import app.model.IwmpAppRoleMap;

/**
 * IwmpRoleMenuMap generated by hbm2java
 */
@Entity
@Table(name = "iwmp_role_menu_map")
public class IwmpRoleMenuMap implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private int rolemenuId;
	private IwmpAppRoleMap iwmpAppRoleMap;
	private IwmpMenu iwmpMenu;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
//	@Transient
//	private String roleMenu;

	@Transient
	public String getRoleMenu() {
		return iwmpAppRoleMap.getRoleName() + "-" + iwmpMenu.getSubmenuName();
	}

//	@Transient
//	public void setRoleMenu(String roleMenu) {
//		this.roleMenu = roleMenu;
//	}

	public IwmpRoleMenuMap() {
	}

	public IwmpRoleMenuMap(int rolemenuId, IwmpAppRoleMap iwmpAppRoleMap, IwmpMenu iwmpMenu) {
		this.rolemenuId = rolemenuId;
		this.iwmpAppRoleMap = iwmpAppRoleMap;
		this.iwmpMenu = iwmpMenu;
	}

	public IwmpRoleMenuMap(int rolemenuId, IwmpAppRoleMap iwmpAppRoleMap, IwmpMenu iwmpMenu, String lastUpdatedBy,
			Date lastUpdatedDate, String requestIp) {
		this.rolemenuId = rolemenuId;
		this.iwmpAppRoleMap = iwmpAppRoleMap;
		this.iwmpMenu = iwmpMenu;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
	}

	@Id

	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "rolemenu_id", unique = true, nullable = false)
	public int getRolemenuId() {
		return this.rolemenuId;
	}

	public void setRolemenuId(int rolemenuId) {
		this.rolemenuId = rolemenuId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id", nullable = false)
	@OrderBy("roleName")
	public IwmpAppRoleMap getIwmpAppRoleMap() {
		return this.iwmpAppRoleMap;
	}

	public void setIwmpAppRoleMap(IwmpAppRoleMap iwmpAppRoleMap) {
		this.iwmpAppRoleMap = iwmpAppRoleMap;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "menu_id", nullable = false)
	public IwmpMenu getIwmpMenu() {
		return this.iwmpMenu;
	}

	public void setIwmpMenu(IwmpMenu iwmpMenu) {
		this.iwmpMenu = iwmpMenu;
	}

	@Column(name = "last_updated_by", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	@CreationTimestamp
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

}
