package app.model.project;
// Generated 24 Feb, 2021 11:47:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMProject;
import app.model.master.IwmpVillage;

/**
 * IwmpProjectLocation generated by hbm2java
 */
@Entity
@Table(name="iwmp_project_location"
    ,schema="public"
)
public class IwmpProjectLocation  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long projLocationId;
     private IwmpMProject iwmpMProject;
     private IwmpVillage iwmpVillage;
     private String createdBy;
     private Date createdDt;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Boolean status;
     private Set<IwmpProjectWc> iwmpProjectWcs = new HashSet<IwmpProjectWc>(0);

    public IwmpProjectLocation() {
    }

	
    public IwmpProjectLocation(long projLocationId) {
        this.projLocationId = projLocationId;
    }
    public IwmpProjectLocation(long projLocationId, IwmpMProject iwmpMProject, IwmpVillage iwmpVillage, String createdBy, Date createdDt, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Boolean status, Set<IwmpProjectWc> iwmpProjectWcs) {
       this.projLocationId = projLocationId;
       this.iwmpMProject = iwmpMProject;
       this.iwmpVillage = iwmpVillage;
       this.createdBy = createdBy;
       this.createdDt = createdDt;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.status = status;
       this.iwmpProjectWcs = iwmpProjectWcs;
    }
   
    @Id 
    @Column(name="proj_location_id", unique=true, nullable=false)
    public long getProjLocationId() {
        return this.projLocationId;
    }
    
    public void setProjLocationId(long projLocationId) {
        this.projLocationId = projLocationId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vcode")
    public IwmpVillage getIwmpVillage() {
        return this.iwmpVillage;
    }
    
    public void setIwmpVillage(IwmpVillage iwmpVillage) {
        this.iwmpVillage = iwmpVillage;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_dt", length=29)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="last_updated_by", length=25)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpProjectLocation")
    public Set<IwmpProjectWc> getIwmpProjectWcs() {
        return this.iwmpProjectWcs;
    }
    
    public void setIwmpProjectWcs(Set<IwmpProjectWc> iwmpProjectWcs) {
        this.iwmpProjectWcs = iwmpProjectWcs;
    }




}


