package app.model.project;
// Generated 22 Mar, 2021 5:07:08 PM by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.UserReg;

/**
 * IwmpProjectPhysicalTranx generated by hbm2java
 */
@Entity
@Table(name="iwmp_project_physical_tranx"
    ,schema="public"
)
public class IwmpProjectPhysicalTranx  implements java.io.Serializable {


     private int tranx;
     private IwmpProjectPhysicalPlan iwmpProjectPhysicalPlan;
     private UserReg iwmpUserRegBySentfrom;
     private UserReg iwmpUserRegBySentTo;
     private Timestamp senton;
     private Character action;
     private String remarks;

    public IwmpProjectPhysicalTranx() {
    }

	
    public IwmpProjectPhysicalTranx(int tranx) {
        this.tranx = tranx;
    }
    public IwmpProjectPhysicalTranx(int tranx, IwmpProjectPhysicalPlan iwmpProjectPhysicalPlan, UserReg iwmpUserRegBySentfrom, UserReg iwmpUserRegBySentTo, Timestamp senton, Character action,String remarks) {
       this.tranx = tranx;
       this.iwmpProjectPhysicalPlan = iwmpProjectPhysicalPlan;
       this.iwmpUserRegBySentfrom = iwmpUserRegBySentfrom;
       this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
       this.senton = senton;
       this.action = action;
       this.remarks = remarks;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="tranx", unique=true, nullable=false)
    public int getTranx() {
        return this.tranx;
    }
    
    public void setTranx(int tranx) {
        this.tranx = tranx;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="planid")
    public IwmpProjectPhysicalPlan getIwmpProjectPhysicalPlan() {
        return this.iwmpProjectPhysicalPlan;
    }
    
    public void setIwmpProjectPhysicalPlan(IwmpProjectPhysicalPlan iwmpProjectPhysicalPlan) {
        this.iwmpProjectPhysicalPlan = iwmpProjectPhysicalPlan;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="sentfrom")
    public UserReg getIwmpUserRegBySentfrom() {
        return this.iwmpUserRegBySentfrom;
    }
    
    public void setIwmpUserRegBySentfrom(UserReg iwmpUserRegBySentfrom) {
        this.iwmpUserRegBySentfrom = iwmpUserRegBySentfrom;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="sent_to")
    public UserReg getIwmpUserRegBySentTo() {
        return this.iwmpUserRegBySentTo;
    }
    
    public void setIwmpUserRegBySentTo(UserReg iwmpUserRegBySentTo) {
        this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
    }

    
    @Column(name="senton")
    public Timestamp getSenton() {
        return this.senton;
    }
    
    public void setSenton(Timestamp senton) {
        this.senton = senton;
    }

    
    @Column(name="action", length=1)
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }

    @Column(name="remarks")
	public String getRemarks() {
		return remarks;
	}


	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}




}


