package app.model.project;
// Generated 9 Jul, 2021 3:21:41 PM by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.ConvergenceWorkDetail;
import app.model.IwmpActivityAssetAddonParameterAchievement;
import app.model.IwmpMFinYear;
import app.model.IwmpMProject;
import app.model.IwmpProjectAssetStatus;
import app.model.master.IwmpMPhyActivity;
import app.model.master.IwmpMPhySubactivity;
import app.model.master.IwmpVillage;

/**
 * IwmpProjectPhysicalAsset generated by hbm2java
 */
@Entity
@Table(name="iwmp_project_physical_asset"
    ,schema="public"
)
public class IwmpProjectPhysicalAsset  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigInteger assetid;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMPhyActivity iwmpMPhyActivity;
     private IwmpMProject iwmpMProject;
     private IwmpProjectPhysicalAap iwmpProjectPhysicalAap;
     private IwmpVillage iwmpVillage;
     private Character status;
     private String createdby;
     private Date createdon;
     private String updatedby;
     private String nearby;
     private Date updatedon;
     private String requestIp;
     private IwmpMPhySubactivity iwmpMPhySubactivity;
     private Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements = new HashSet<IwmpActivityAssetAddonParameterAchievement>(0);
     private Set<IwmpProjectAssetStatus> iwmpProjectAssetStatuses = new HashSet<IwmpProjectAssetStatus>(0);
     private Set<WdcpmksyProjectPhyAssetAchievement> wdcpmksyProjectPhyAssetAchievements = new HashSet<WdcpmksyProjectPhyAssetAchievement>(0);
     private Set<ConvergenceWorkDetail> convergenceWorkDetail = new HashSet<ConvergenceWorkDetail>(0);
     
    public IwmpProjectPhysicalAsset() {
    }

	
    public IwmpProjectPhysicalAsset(BigInteger assetid) {
        this.assetid = assetid;
    }
    public IwmpProjectPhysicalAsset(BigInteger assetid, IwmpMFinYear iwmpMFinYear, IwmpMPhyActivity iwmpMPhyActivity, IwmpMProject iwmpMProject, IwmpProjectPhysicalAap iwmpProjectPhysicalAap, IwmpVillage iwmpVillage, Character status, String createdby, Date createdon, String nearby, String updatedby, Date updatedon, String requestIp) {
       this.assetid = assetid;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMPhyActivity = iwmpMPhyActivity;
       this.iwmpMProject = iwmpMProject;
       this.iwmpProjectPhysicalAap = iwmpProjectPhysicalAap;
       this.iwmpVillage = iwmpVillage;
       this.status = status;
       this.createdby = createdby;
       this.createdon = createdon;
       this.nearby = nearby;
       this.updatedby = updatedby;
       this.updatedon = updatedon;
       this.requestIp = requestIp;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="assetid", unique=true, nullable=false)
    public BigInteger getAssetid() {
        return this.assetid;
    }
    
    public void setAssetid(BigInteger assetid) {
        this.assetid = assetid;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="phy_activity_code")
    public IwmpMPhyActivity getIwmpMPhyActivity() {
        return this.iwmpMPhyActivity;
    }
    
    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
        this.iwmpMPhyActivity = iwmpMPhyActivity;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="aapid")
    public IwmpProjectPhysicalAap getIwmpProjectPhysicalAap() {
        return this.iwmpProjectPhysicalAap;
    }
    
    public void setIwmpProjectPhysicalAap(IwmpProjectPhysicalAap iwmpProjectPhysicalAap) {
        this.iwmpProjectPhysicalAap = iwmpProjectPhysicalAap;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vcode")
    public IwmpVillage getIwmpVillage() {
        return this.iwmpVillage;
    }
    
    public void setIwmpVillage(IwmpVillage iwmpVillage) {
        this.iwmpVillage = iwmpVillage;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="createdby", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="updatedby", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Column(name="nearby")
    public String getNearby() {
		return nearby;
	}


	public void setNearby(String nearby) {
		this.nearby = nearby;
	}


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpProjectPhysicalAsset")
    public Set<IwmpActivityAssetAddonParameterAchievement> getIwmpAssetParameterAchievements() {
        return this.iwmpAssetParameterAchievements;
    }
    
    public void setIwmpAssetParameterAchievements(Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements) {
        this.iwmpAssetParameterAchievements = iwmpAssetParameterAchievements;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = CascadeType.ALL , mappedBy="iwmpProjectPhysicalAsset")
    public Set<IwmpProjectAssetStatus> getIwmpProjectAssetStatuses() {
        return this.iwmpProjectAssetStatuses;
    }
    
    public void setIwmpProjectAssetStatuses(Set<IwmpProjectAssetStatus> iwmpProjectAssetStatuses) {
        this.iwmpProjectAssetStatuses = iwmpProjectAssetStatuses;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpProjectPhysicalAsset")
    public Set<WdcpmksyProjectPhyAssetAchievement> getWdcpmksyProjectPhyAssetAchievements() {
        return this.wdcpmksyProjectPhyAssetAchievements;
    }
    
    public void setWdcpmksyProjectPhyAssetAchievements(Set<WdcpmksyProjectPhyAssetAchievement> wdcpmksyProjectPhyAssetAchievements) {
        this.wdcpmksyProjectPhyAssetAchievements = wdcpmksyProjectPhyAssetAchievements;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phy_subactivity_code")
    public IwmpMPhySubactivity getIwmpMPhySubactivity() {
        return this.iwmpMPhySubactivity;
    }
    
    public void setIwmpMPhySubactivity(IwmpMPhySubactivity iwmpMPhySubactivity) {
        this.iwmpMPhySubactivity = iwmpMPhySubactivity;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpProjectPhysicalAsset")
	public Set<ConvergenceWorkDetail> getConvergenceWorkDetail() {
		return convergenceWorkDetail;
	}

	public void setConvergenceWorkDetail(Set<ConvergenceWorkDetail> convergenceWorkDetail) {
		this.convergenceWorkDetail = convergenceWorkDetail;
	}
    
}


