package app.model.project;
// Generated 19 Mar, 2021 11:57:08 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMProject;
import app.model.master.IwmpMProjectPrepare;

/**
 * IwmpProjectPrepare generated by hbm2java
 */
@Entity
@Table(name="iwmp_project_prepare"
    ,schema="public"
)
public class IwmpProjectPrepare  implements java.io.Serializable {


     private int projectPrepareId;
     private IwmpMProject iwmpMProject;
     private IwmpMProjectPrepare iwmpMProjectPrepare;
     private Boolean activityStatus;
     private Date createdOn;
     private String createdBy;
     private String updatedBy;
     private Date updatedOn;
     private String requestIp;

    public IwmpProjectPrepare() {
    }

	
    public IwmpProjectPrepare(int projectPrepareId) {
        this.projectPrepareId = projectPrepareId;
    }
    public IwmpProjectPrepare(int projectPrepareId, IwmpMProject iwmpMProject, IwmpMProjectPrepare iwmpMProjectPrepare, Boolean activityStatus, Date createdOn, String createdBy, String updatedBy, Date updatedOn, String requestIp) {
       this.projectPrepareId = projectPrepareId;
       this.iwmpMProject = iwmpMProject;
       this.iwmpMProjectPrepare = iwmpMProjectPrepare;
       this.activityStatus = activityStatus;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="project_prepare_id", unique=true, nullable=false)
    public int getProjectPrepareId() {
        return this.projectPrepareId;
    }
    
    public void setProjectPrepareId(int projectPrepareId) {
        this.projectPrepareId = projectPrepareId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prepare_id")
    public IwmpMProjectPrepare getIwmpMProjectPrepare() {
        return this.iwmpMProjectPrepare;
    }
    
    public void setIwmpMProjectPrepare(IwmpMProjectPrepare iwmpMProjectPrepare) {
        this.iwmpMProjectPrepare = iwmpMProjectPrepare;
    }

    
    @Column(name="activity_status")
    public Boolean getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(Boolean activityStatus) {
        this.activityStatus = activityStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=30)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=30)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=35)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }




}


