package app.model.project;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMFinYear;
import app.model.IwmpMProject;
import app.model.UserReg;
import app.model.master.IwmpMPhyActivity;
import app.model.master.IwmpMPhySubactivity;
import app.model.master.IwmpVillage;

/**
 * IwmpProjectPhysicalAsset generated by hbm2java
 */
@Entity
@Table(name="iwmp_project_physical_asset_temp"
    ,schema="public"
)
public class IwmpProjectPhysicalAssetTemp implements java.io.Serializable{
	     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		 private BigInteger tempassetid;
	     private IwmpMFinYear iwmpMFinYear;
	     private IwmpMPhyActivity iwmpMPhyActivity;
	     private IwmpMProject iwmpMProject;
	     private IwmpProjectPhysicalAap iwmpProjectPhysicalAap;
	     private IwmpVillage iwmpVillage;
	     private Character status;
	     private String createdby;
	     private Date createdon;
	     private String nearby;
	     private String updatedby;
	     private Date updatedon;
	     private String requestIp;
	     private Character action;
	     private Character currentLevel;
	     private String remarks;
	     private UserReg iwmpUserRegBySentTo;
	     private UserReg iwmpUserRegBySentFrom;
	     private IwmpMPhySubactivity iwmpMPhySubactivity;

	    public IwmpProjectPhysicalAssetTemp() {
	    }

		
	    public IwmpProjectPhysicalAssetTemp(BigInteger tempassetid) {
	        this.tempassetid = tempassetid;
	    }
	    public IwmpProjectPhysicalAssetTemp(BigInteger tempassetid,BigInteger assetid, IwmpMFinYear iwmpMFinYear, IwmpMPhyActivity iwmpMPhyActivity, IwmpMProject iwmpMProject, IwmpProjectPhysicalAap iwmpProjectPhysicalAap, IwmpVillage iwmpVillage, Character status, String createdby, String nearby, Date createdon, String updatedby, Date updatedon, String requestIp, Character action,Character currentLevel,String remarks,UserReg iwmpUserRegBySentTo,UserReg iwmpUserRegBySentFrom) {
	       this.tempassetid=tempassetid;
	       this.iwmpMFinYear = iwmpMFinYear;
	       this.iwmpMPhyActivity = iwmpMPhyActivity;
	       this.iwmpMProject = iwmpMProject;
	       this.iwmpProjectPhysicalAap = iwmpProjectPhysicalAap;
	       this.iwmpVillage = iwmpVillage;
	       this.status = status;
	       this.createdby = createdby;
	       this.nearby = nearby;
	       this.createdon = createdon;
	       this.updatedby = updatedby;
	       this.updatedon = updatedon;
	       this.requestIp = requestIp;
	       this.action = action;
	       this.currentLevel=currentLevel;
	       this.remarks = remarks;
	       this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
	       this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
	       
	    }
	   
	    @Id 
	    @GeneratedValue(strategy=GenerationType.AUTO)
	    @Column(name="temp_asset_id", unique=true, nullable=false)
	    public BigInteger getTempassetid() {
			return tempassetid;
		}


		public void setTempassetid(BigInteger tempassetid) {
			this.tempassetid = tempassetid;
		}


	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="fin_yr_cd")
	    public IwmpMFinYear getIwmpMFinYear() {
	        return this.iwmpMFinYear;
	    }
	    
	    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
	        this.iwmpMFinYear = iwmpMFinYear;
	    }

	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="phy_activity_code")
	    public IwmpMPhyActivity getIwmpMPhyActivity() {
	        return this.iwmpMPhyActivity;
	    }
	    
	    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
	        this.iwmpMPhyActivity = iwmpMPhyActivity;
	    }

	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="proj_id")
	    public IwmpMProject getIwmpMProject() {
	        return this.iwmpMProject;
	    }
	    
	    public void setIwmpMProject(IwmpMProject iwmpMProject) {
	        this.iwmpMProject = iwmpMProject;
	    }

	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="aap_id")
	    public IwmpProjectPhysicalAap getIwmpProjectPhysicalAap() {
	        return this.iwmpProjectPhysicalAap;
	    }
	    
	    public void setIwmpProjectPhysicalAap(IwmpProjectPhysicalAap iwmpProjectPhysicalAap) {
	        this.iwmpProjectPhysicalAap = iwmpProjectPhysicalAap;
	    }

	    @ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="vcode")
	    public IwmpVillage getIwmpVillage() {
	        return this.iwmpVillage;
	    }
	    
	    public void setIwmpVillage(IwmpVillage iwmpVillage) {
	        this.iwmpVillage = iwmpVillage;
	    }

	    
	    @Column(name="status", length=1)
	    public Character getStatus() {
	        return this.status;
	    }
	    
	    public void setStatus(Character status) {
	        this.status = status;
	    }

	    
	    @Column(name="createdby", length=20)
	    public String getCreatedby() {
	        return this.createdby;
	    }
	    
	    public void setCreatedby(String createdby) {
	        this.createdby = createdby;
	    }

	    
	    @Column(name="nearby")
	    public String getNearby() {
			return nearby;
		}

        public void setNearby(String nearby) {
			this.nearby = nearby;
		}


		@Temporal(TemporalType.TIMESTAMP)
	    @Column(name="createdon", length=29)
	    public Date getCreatedon() {
	        return this.createdon;
	    }
	    
	    public void setCreatedon(Date createdon) {
	        this.createdon = createdon;
	    }

	    
	    @Column(name="updatedby", length=20)
	    public String getUpdatedby() {
	        return this.updatedby;
	    }
	    
	    public void setUpdatedby(String updatedby) {
	        this.updatedby = updatedby;
	    }

	    @Temporal(TemporalType.TIMESTAMP)
	    @Column(name="updatedon", length=29)
	    public Date getUpdatedon() {
	        return this.updatedon;
	    }
	    
	    public void setUpdatedon(Date updatedon) {
	        this.updatedon = updatedon;
	    }

	    
	    @Column(name="request_ip", length=20)
	    public String getRequestIp() {
	        return this.requestIp;
	    }
	    
	    public void setRequestIp(String requestIp) {
	        this.requestIp = requestIp;
	    }

	    @Column(name="action", length=1)
	    public Character getAction() {
	        return this.action;
	    }
	    
	    public void setAction(Character action) {
	        this.action = action;
	    }

	    @Column(name="current_level", length=1)
		public Character getCurrentLevel() {
			return currentLevel;
		}


		public void setCurrentLevel(Character currentLevel) {
			this.currentLevel = currentLevel;
		}

		@Column(name="remarks", length=1)
		public String getRemarks() {
			return remarks;
		}


		public void setRemarks(String remarks) {
			this.remarks = remarks;
		}

		@ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="sent_to")
		public UserReg getIwmpUserRegBySentTo() {
			return iwmpUserRegBySentTo;
		}


		public void setIwmpUserRegBySentTo(UserReg iwmpUserRegBySentTo) {
			this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
		}
		
		@ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="sent_from")
		public UserReg getIwmpUserRegBySentFrom() {
			return iwmpUserRegBySentFrom;
		}


		public void setIwmpUserRegBySentFrom(UserReg iwmpUserRegBySentFrom) {
			this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
		}

		@ManyToOne(fetch=FetchType.EAGER)
	    @JoinColumn(name="phy_subactivity_code")
	    public IwmpMPhySubactivity getIwmpMPhySubactivity() {
	        return this.iwmpMPhySubactivity;
	    }
	    
	    public void setIwmpMPhySubactivity(IwmpMPhySubactivity iwmpMPhySubactivity) {
	        this.iwmpMPhySubactivity = iwmpMPhySubactivity;
	    }

	}
