package app.model.project;
// Generated 22 Mar, 2021 5:07:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IwmpApprovelLevelHistory generated by hbm2java
 */
@Entity
@Table(name="iwmp_approvel_level_history"
    ,schema="public"
)
public class IwmpApprovelLevelHistory  implements java.io.Serializable {


     private int historyid;
     private IwmpApprovelLevel iwmpApprovelLevel;
     private Integer stCode;
     private Boolean planDistApproval;
     private Boolean outcomeDistApproval;
     private Boolean achievementDistApproval;
     private String createdby;
     private Date createdon;
     private String updatedby;
     private Date updatedon;
     private String requestIp;
     private Date moveon;

    public IwmpApprovelLevelHistory() {
    }

	
    public IwmpApprovelLevelHistory(int historyid) {
        this.historyid = historyid;
    }
    public IwmpApprovelLevelHistory(int historyid, IwmpApprovelLevel iwmpApprovelLevel, Integer stCode, Boolean planDistApproval, Boolean outcomeDistApproval, Boolean achievementDistApproval, String createdby, Date createdon, String updatedby, Date updatedon, String requestIp, Date moveon) {
       this.historyid = historyid;
       this.iwmpApprovelLevel = iwmpApprovelLevel;
       this.stCode = stCode;
       this.planDistApproval = planDistApproval;
       this.outcomeDistApproval = outcomeDistApproval;
       this.achievementDistApproval = achievementDistApproval;
       this.createdby = createdby;
       this.createdon = createdon;
       this.updatedby = updatedby;
       this.updatedon = updatedon;
       this.requestIp = requestIp;
       this.moveon = moveon;
    }
   
     @Id 

    
    @Column(name="historyid", unique=true, nullable=false)
    public int getHistoryid() {
        return this.historyid;
    }
    
    public void setHistoryid(int historyid) {
        this.historyid = historyid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="approval_levelid")
    public IwmpApprovelLevel getIwmpApprovelLevel() {
        return this.iwmpApprovelLevel;
    }
    
    public void setIwmpApprovelLevel(IwmpApprovelLevel iwmpApprovelLevel) {
        this.iwmpApprovelLevel = iwmpApprovelLevel;
    }

    
    @Column(name="st_code")
    public Integer getStCode() {
        return this.stCode;
    }
    
    public void setStCode(Integer stCode) {
        this.stCode = stCode;
    }

    
    @Column(name="plan_dist_approval")
    public Boolean getPlanDistApproval() {
        return this.planDistApproval;
    }
    
    public void setPlanDistApproval(Boolean planDistApproval) {
        this.planDistApproval = planDistApproval;
    }

    
    @Column(name="outcome_dist_approval")
    public Boolean getOutcomeDistApproval() {
        return this.outcomeDistApproval;
    }
    
    public void setOutcomeDistApproval(Boolean outcomeDistApproval) {
        this.outcomeDistApproval = outcomeDistApproval;
    }

    
    @Column(name="achievement_dist_approval")
    public Boolean getAchievementDistApproval() {
        return this.achievementDistApproval;
    }
    
    public void setAchievementDistApproval(Boolean achievementDistApproval) {
        this.achievementDistApproval = achievementDistApproval;
    }

    
    @Column(name="createdby", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="updatedby", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="moveon", length=29)
    public Date getMoveon() {
        return this.moveon;
    }
    
    public void setMoveon(Date moveon) {
        this.moveon = moveon;
    }




}


