package app.model.project;
// Generated 22 Mar, 2021 5:07:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.master.IwmpMPhyActivity;

/**
 * IwmpProjectPhysicalAap generated by hbm2java
 */
@Entity
@Table(name="iwmp_project_physical_aap"
    ,schema="public"
)
public class IwmpProjectPhysicalAap  implements java.io.Serializable {


     private int aapid;
     private IwmpMPhyActivity iwmpMPhyActivity;
     private IwmpProjectPhysicalPlan iwmpProjectPhysicalPlan;
     private BigDecimal qtyPlanned;
     private Character assetIdCreated;
     private String createdby;
     private Date createdon;
     private String updatedby;
     private Date updatedon;
     private String requestIp;
     private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
     private Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAsset = new HashSet<IwmpProjectPhysicalAsset>(0);

    public IwmpProjectPhysicalAap() {
    }

	
    public IwmpProjectPhysicalAap(int aapid) {
        this.aapid = aapid;
    }
    public IwmpProjectPhysicalAap(int aapid, IwmpMPhyActivity iwmpMPhyActivity, IwmpProjectPhysicalPlan iwmpProjectPhysicalPlan, BigDecimal qtyPlanned, Character assetIdCreated, String createdby, Date createdon, String updatedby, Date updatedon, String requestIp) {
       this.aapid = aapid;
       this.iwmpMPhyActivity = iwmpMPhyActivity;
       this.iwmpProjectPhysicalPlan = iwmpProjectPhysicalPlan;
       this.qtyPlanned = qtyPlanned;
       this.assetIdCreated = assetIdCreated;
       this.createdby = createdby;
       this.createdon = createdon;
       this.updatedby = updatedby;
       this.updatedon = updatedon;
       this.requestIp = requestIp;
    }
   
    @Id 
    @Column(name="aapid", unique=true, nullable=false)
    public int getAapid() {
        return this.aapid;
    }
    
    public void setAapid(int aapid) {
        this.aapid = aapid;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="phy_activity_code")
    public IwmpMPhyActivity getIwmpMPhyActivity() {
        return this.iwmpMPhyActivity;
    }
    
    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
        this.iwmpMPhyActivity = iwmpMPhyActivity;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="planid")
    public IwmpProjectPhysicalPlan getIwmpProjectPhysicalPlan() {
        return this.iwmpProjectPhysicalPlan;
    }
    
    public void setIwmpProjectPhysicalPlan(IwmpProjectPhysicalPlan iwmpProjectPhysicalPlan) {
        this.iwmpProjectPhysicalPlan = iwmpProjectPhysicalPlan;
    }

    
    @Column(name="qty_planned")
    public BigDecimal getQtyPlanned() {
        return this.qtyPlanned;
    }
    
    public void setQtyPlanned(BigDecimal qtyPlanned) {
        this.qtyPlanned = qtyPlanned;
    }

    
    @Column(name="asset_id_created", length=1)
    public Character getAssetIdCreated() {
        return this.assetIdCreated;
    }
    
    public void setAssetIdCreated(Character assetIdCreated) {
        this.assetIdCreated = assetIdCreated;
    }

    
    @Column(name="createdby", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="updatedby", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpProjectPhysicalAap")
    public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemp() {
        return this.iwmpProjectPhysicalAssetTemp;
    }
    
    public void setIwmpProjectPhysicalAssetTemp(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp) {
        this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpProjectPhysicalAap")
    public Set<IwmpProjectPhysicalAsset> getIwmpProjectPhysicalAsset() {
        return this.iwmpProjectPhysicalAsset;
    }
    
    public void setIwmpProjectPhysicalAsset(Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAsset) {
        this.iwmpProjectPhysicalAsset = iwmpProjectPhysicalAsset;
    }

}


