package app.model.project;
// Generated 22 Mar, 2021 5:07:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpState;

/**
 * IwmpApprovelLevel generated by hbm2java
 */
@Entity
@Table(name="iwmp_approvel_level"
    ,schema="public"
)
public class IwmpApprovelLevel  implements java.io.Serializable {


     private int approvalLevelid;
     private IwmpState iwmpState;
     private Boolean planDistApproval;
     private Boolean outcomeDistApproval;
     private Boolean achievementDistApproval;
     private String createdby;
     private Date createdon;
     private String updatedby;
     private Date updatedon;
     private String requestIp;
     private Set<IwmpApprovelLevelHistory> iwmpApprovelLevelHistories = new HashSet<IwmpApprovelLevelHistory>(0);

    public IwmpApprovelLevel() {
    }

	
    public IwmpApprovelLevel(int approvalLevelid) {
        this.approvalLevelid = approvalLevelid;
    }
    public IwmpApprovelLevel(int approvalLevelid, IwmpState iwmpState, Boolean planDistApproval, Boolean outcomeDistApproval, Boolean achievementDistApproval, String createdby, Date createdon, String updatedby, Date updatedon, String requestIp, Set<IwmpApprovelLevelHistory> iwmpApprovelLevelHistories) {
       this.approvalLevelid = approvalLevelid;
       this.iwmpState = iwmpState;
       this.planDistApproval = planDistApproval;
       this.outcomeDistApproval = outcomeDistApproval;
       this.achievementDistApproval = achievementDistApproval;
       this.createdby = createdby;
       this.createdon = createdon;
       this.updatedby = updatedby;
       this.updatedon = updatedon;
       this.requestIp = requestIp;
       this.iwmpApprovelLevelHistories = iwmpApprovelLevelHistories;
    }
   
     @Id 

    
    @Column(name="approval_levelid", unique=true, nullable=false)
    public int getApprovalLevelid() {
        return this.approvalLevelid;
    }
    
    public void setApprovalLevelid(int approvalLevelid) {
        this.approvalLevelid = approvalLevelid;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="st_code")
    public IwmpState getIwmpState() {
        return this.iwmpState;
    }
    
    public void setIwmpState(IwmpState iwmpState) {
        this.iwmpState = iwmpState;
    }

    
    @Column(name="plan_dist_approval")
    public Boolean getPlanDistApproval() {
        return this.planDistApproval;
    }
    
    public void setPlanDistApproval(Boolean planDistApproval) {
        this.planDistApproval = planDistApproval;
    }

    
    @Column(name="outcome_dist_approval")
    public Boolean getOutcomeDistApproval() {
        return this.outcomeDistApproval;
    }
    
    public void setOutcomeDistApproval(Boolean outcomeDistApproval) {
        this.outcomeDistApproval = outcomeDistApproval;
    }

    
    @Column(name="achievement_dist_approval")
    public Boolean getAchievementDistApproval() {
        return this.achievementDistApproval;
    }
    
    public void setAchievementDistApproval(Boolean achievementDistApproval) {
        this.achievementDistApproval = achievementDistApproval;
    }

    
    @Column(name="createdby", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="updatedby", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(mappedBy="iwmpApprovelLevel")
    public Set<IwmpApprovelLevelHistory> getIwmpApprovelLevelHistories() {
        return this.iwmpApprovelLevelHistories;
    }
    
    public void setIwmpApprovelLevelHistories(Set<IwmpApprovelLevelHistory> iwmpApprovelLevelHistories) {
        this.iwmpApprovelLevelHistories = iwmpApprovelLevelHistories;
    }




}


