package app.model.project;
// Generated 2 Sep, 2021 3:27:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import app.model.IwmpMFinYear;
import app.model.IwmpMMonth;
import app.model.IwmpMProject;
import app.model.master.IwmpMPhyActivity;

/**
 * IwmpProjectPhysicalAchievementDetails generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_project_phy_ach_details"
    ,schema="public"
)
public class WdcpmksyProjectPhysicalAchievementDetails  implements java.io.Serializable {


	private int achievementDetailsId;
    private IwmpMPhyActivity iwmpMPhyActivity;
    private WdcpmksyProjectPhysicalAchievement wdcpmksyProjectPhysicalAchievement;
    private BigDecimal achievement;

   public WdcpmksyProjectPhysicalAchievementDetails() {
   }

	
   public WdcpmksyProjectPhysicalAchievementDetails(int achievementDetailsId) {
       this.achievementDetailsId = achievementDetailsId;
   }
   public WdcpmksyProjectPhysicalAchievementDetails(int achievementDetailsId, IwmpMPhyActivity iwmpMPhyActivity, WdcpmksyProjectPhysicalAchievement wdcpmksyProjectPhyAchievement, BigDecimal achievement) {
      this.achievementDetailsId = achievementDetailsId;
      this.iwmpMPhyActivity = iwmpMPhyActivity;
      this.wdcpmksyProjectPhysicalAchievement = wdcpmksyProjectPhyAchievement;
      this.achievement = achievement;
   }
  
   @Id 
   @Column(name="achievement_details_id", unique=true, nullable=false)
   public int getAchievementDetailsId() {
       return this.achievementDetailsId;
   }
   
   public void setAchievementDetailsId(int achievementDetailsId) {
       this.achievementDetailsId = achievementDetailsId;
   }

   @ManyToOne(fetch=FetchType.EAGER)
   @JoinColumn(name="activity_code")
   public IwmpMPhyActivity getIwmpMPhyActivity() {
       return this.iwmpMPhyActivity;
   }
   
   public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
       this.iwmpMPhyActivity = iwmpMPhyActivity;
   }

   @ManyToOne(fetch=FetchType.EAGER)
   @JoinColumn(name="achievement_id")
   public WdcpmksyProjectPhysicalAchievement getWdcpmksyProjectPhysicalAchievement() {
       return this.wdcpmksyProjectPhysicalAchievement;
   }
   
   public void setWdcpmksyProjectPhysicalAchievement(WdcpmksyProjectPhysicalAchievement wdcpmksyProjectPhyAchievement) {
       this.wdcpmksyProjectPhysicalAchievement = wdcpmksyProjectPhyAchievement;
   }

   
   @Column(name="achievement", precision=10)
   public BigDecimal getAchievement() {
       return this.achievement;
   }
   
   public void setAchievement(BigDecimal achievement) {
       this.achievement = achievement;
   }




}


