package app.model.project;
// Generated 15 Sep, 2021 11:58:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.UserReg;

/**
 * WdcpmksyOutcomeTargetTranx generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_outcome_target_tranx"
    ,schema="public"
)
public class WdcpmksyOutcomeTargetTranx  implements java.io.Serializable {


     private int tranxId;
     private UserReg iwmpUserRegBySentTo;
     private UserReg iwmpUserRegBySentFrom;
     private WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget;
     private Date sentOn;
     private Character action;
     private String remarks;

    public WdcpmksyOutcomeTargetTranx() {
    }

	
    public WdcpmksyOutcomeTargetTranx(int tranxId, WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget) {
        this.tranxId = tranxId;
        this.wdcpmksyOutcomeTarget = wdcpmksyOutcomeTarget;
    }
    public WdcpmksyOutcomeTargetTranx(int tranxId, UserReg iwmpUserRegBySentTo, UserReg iwmpUserRegBySentFrom, WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget, Date sentOn, Character action, String remarks) {
       this.tranxId = tranxId;
       this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
       this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
       this.wdcpmksyOutcomeTarget = wdcpmksyOutcomeTarget;
       this.sentOn = sentOn;
       this.action = action;
       this.remarks = remarks;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="tranx_id", unique=true, nullable=false)
    public int getTranxId() {
        return this.tranxId;
    }
    
    public void setTranxId(int tranxId) {
        this.tranxId = tranxId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sent_to")
    public UserReg getIwmpUserRegBySentTo() {
        return this.iwmpUserRegBySentTo;
    }
    
    public void setIwmpUserRegBySentTo(UserReg iwmpUserRegBySentTo) {
        this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sent_from")
    public UserReg getIwmpUserRegBySentFrom() {
        return this.iwmpUserRegBySentFrom;
    }
    
    public void setIwmpUserRegBySentFrom(UserReg iwmpUserRegBySentFrom) {
        this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="outcome_target_id", nullable=false)
    public WdcpmksyOutcomeTarget getWdcpmksyOutcomeTarget() {
        return this.wdcpmksyOutcomeTarget;
    }
    
    public void setWdcpmksyOutcomeTarget(WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget) {
        this.wdcpmksyOutcomeTarget = wdcpmksyOutcomeTarget;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sent_on", length=29)
    public Date getSentOn() {
        return this.sentOn;
    }
    
    public void setSentOn(Date sentOn) {
        this.sentOn = sentOn;
    }

    
    @Column(name="action", length=1)
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }

    
    @Column(name="remarks", length=1000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


