package app.model.project;
// Generated 19 Dec, 2022 11:54:43 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMProject;
import app.model.UserReg;
import app.model.master.IwmpVillage;
import app.model.outcome.EpaDetail;
import app.model.outcome.MEpaCoreactivity;

/**
 * WdcpmksyEpaWorkid generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_epa_workid", schema="public")
public class WdcpmksyEpaWorkid  implements java.io.Serializable {


     private int assetid;
     private EpaDetail epaDetail;
     private IwmpMProject iwmpMProject;
     private UserReg iwmpUserRegBySentFrom;
     private UserReg iwmpUserRegBySentTo;
     private IwmpVillage iwmpVillage;
     private MEpaCoreactivity MEpaCoreactivity;
     private Character status;
     private String createdby;
     private Date createdon;
     private String updatedby;
     private Date updatedon;
     private String requestIp;
     private String nearby;
     private Character actionForward;
     private Character currentLevel;
     private String remarks;
  

    public WdcpmksyEpaWorkid() {
    }

	
    public WdcpmksyEpaWorkid(int assetid, UserReg iwmpUserRegBySentFrom, UserReg iwmpUserRegBySentTo) {
        this.assetid = assetid;
        this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
        this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
    }
    public WdcpmksyEpaWorkid(int assetid, EpaDetail epaDetail, IwmpMProject iwmpMProject, IwmpVillage iwmpVillage, MEpaCoreactivity MEpaCoreactivity, Character status, String createdby, Date createdon, String updatedby, Date updatedon, String requestIp, String nearby, Character actionForward, Character currentLevel, String remarks, UserReg iwmpUserRegBySentFrom, UserReg iwmpUserRegBySentTo) {
       this.assetid = assetid;
       this.epaDetail = epaDetail;
       this.iwmpMProject = iwmpMProject;
       this.iwmpVillage = iwmpVillage;
       this.MEpaCoreactivity = MEpaCoreactivity;
       this.status = status;
       this.createdby = createdby;
       this.createdon = createdon;
       this.updatedby = updatedby;
       this.updatedon = updatedon;
       this.requestIp = requestIp;
       this.nearby=nearby;
       this.actionForward=actionForward;
       this.currentLevel=currentLevel;
       this.remarks=remarks;
       this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
       this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)    
    @Column(name="assetid", unique=true, nullable=false)
    public int getAssetid() {
        return this.assetid;
    }
    
    public void setAssetid(int assetid) {
        this.assetid = assetid;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="epa_detail_id")
    public EpaDetail getEpaDetail() {
        return this.epaDetail;
    }
    
    public void setEpaDetail(EpaDetail epaDetail) {
        this.epaDetail = epaDetail;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="sent_from")
    public UserReg getIwmpUserRegBySentFrom() {
        return this.iwmpUserRegBySentFrom;
    }
    
    public void setIwmpUserRegBySentFrom(UserReg iwmpUserRegBySentFrom) {
        this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="sent_to")
    public UserReg getIwmpUserRegBySentTo() {
        return this.iwmpUserRegBySentTo;
    }
    
    public void setIwmpUserRegBySentTo(UserReg iwmpUserRegBySentTo) {
        this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vcode")
    public IwmpVillage getIwmpVillage() {
        return this.iwmpVillage;
    }
    
    public void setIwmpVillage(IwmpVillage iwmpVillage) {
        this.iwmpVillage = iwmpVillage;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="epa_activity_id")
    public MEpaCoreactivity getMEpaCoreactivity() {
        return this.MEpaCoreactivity;
    }
    
    public void setMEpaCoreactivity(MEpaCoreactivity MEpaCoreactivity) {
        this.MEpaCoreactivity = MEpaCoreactivity;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="createdby", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="updatedby", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Column(name="nearby", length=1000)
	public String getNearby() {
		return nearby;
	}


	public void setNearby(String nearby) {
		this.nearby = nearby;
	}

	@Column(name="action_forward", length=1)
	public Character getActionForward() {
		return actionForward;
	}


	public void setActionForward(Character actionForward) {
		this.actionForward = actionForward;
	}


	 @Column(name="current_level", length=1)
		public Character getCurrentLevel() {
			return currentLevel;
		}


		public void setCurrentLevel(Character currentLevel) {
			this.currentLevel = currentLevel;
		}

		@Column(name="remarks", length=1000)
		public String getRemarks() {
			return remarks;
		}


		public void setRemarks(String remarks) {
			this.remarks = remarks;
		}




}


