package app.model.project;
// Generated 13 Oct, 2021 4:54:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import app.model.master.WdcpmksyMOutcome;
import app.model.master.WdcpmksyMOutcomeDetail;

/**
 * WdcpmksyOutcomeAchDetails generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_outcome_ach_details"
    ,schema="public"
)
public class WdcpmksyOutcomeAchDetails  implements java.io.Serializable {


     private int achievementDetailsId;
     private WdcpmksyMOutcome wdcpmksyMOutcome;
     private WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail;
     private WdcpmksyOutcomeAchievement wdcpmksyOutcomeAchievement;
     private BigDecimal achievement;

    public WdcpmksyOutcomeAchDetails() {
    }

	
    public WdcpmksyOutcomeAchDetails(int achievementDetailsId) {
        this.achievementDetailsId = achievementDetailsId;
    }
    public WdcpmksyOutcomeAchDetails(int achievementDetailsId, WdcpmksyMOutcome wdcpmksyMOutcome, WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail, WdcpmksyOutcomeAchievement wdcpmksyOutcomeAchievement, BigDecimal achievement) {
       this.achievementDetailsId = achievementDetailsId;
       this.wdcpmksyMOutcome = wdcpmksyMOutcome;
       this.wdcpmksyMOutcomeDetail = wdcpmksyMOutcomeDetail;
       this.wdcpmksyOutcomeAchievement = wdcpmksyOutcomeAchievement;
       this.achievement = achievement;
    }
   
     @Id 

    
    @Column(name="achievement_details_id", unique=true, nullable=false)
    public int getAchievementDetailsId() {
        return this.achievementDetailsId;
    }
    
    public void setAchievementDetailsId(int achievementDetailsId) {
        this.achievementDetailsId = achievementDetailsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="outcome_id")
    public WdcpmksyMOutcome getWdcpmksyMOutcome() {
        return this.wdcpmksyMOutcome;
    }
    
    public void setWdcpmksyMOutcome(WdcpmksyMOutcome wdcpmksyMOutcome) {
        this.wdcpmksyMOutcome = wdcpmksyMOutcome;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="outcome_detail_id")
    public WdcpmksyMOutcomeDetail getWdcpmksyMOutcomeDetail() {
        return this.wdcpmksyMOutcomeDetail;
    }
    
    public void setWdcpmksyMOutcomeDetail(WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail) {
        this.wdcpmksyMOutcomeDetail = wdcpmksyMOutcomeDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="achievement_id")
    public WdcpmksyOutcomeAchievement getWdcpmksyOutcomeAchievement() {
        return this.wdcpmksyOutcomeAchievement;
    }
    
    public void setWdcpmksyOutcomeAchievement(WdcpmksyOutcomeAchievement wdcpmksyOutcomeAchievement) {
        this.wdcpmksyOutcomeAchievement = wdcpmksyOutcomeAchievement;
    }

    
    @Column(name="achievement", precision=10)
    public BigDecimal getAchievement() {
        return this.achievement;
    }
    
    public void setAchievement(BigDecimal achievement) {
        this.achievement = achievement;
    }




}


