package app.model.project;
// Generated 15 Sep, 2021 11:58:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMFinYear;
import app.model.IwmpMProject;
import app.model.master.WdcpmksyMOutcomeDetail;

/**
 * WdcpmksyOutcomeTarget generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_outcome_target"
    ,schema="public"
)
public class WdcpmksyOutcomeTarget  implements java.io.Serializable {


     private int outcomeTargetId;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMProject iwmpMProject;
     private Character status;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String requestIp;
     private Set<WdcpmksyOutcomeTargetTranx> wdcpmksyOutcomeTargetTranxes = new HashSet<WdcpmksyOutcomeTargetTranx>(0);
     private Set<WdcpmksyOutcomeTargetDetails> wdcpmksyOutcomeTargetDetailses = new HashSet<WdcpmksyOutcomeTargetDetails>(0);

    public WdcpmksyOutcomeTarget() {
    }

	
    public WdcpmksyOutcomeTarget(int outcomeTargetId) {
        this.outcomeTargetId = outcomeTargetId;
    }
    public WdcpmksyOutcomeTarget(int outcomeTargetId, IwmpMFinYear iwmpMFinYear, IwmpMProject iwmpMProject, Character status, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String requestIp, Set wdcpmksyOutcomeTargetTranxes, Set wdcpmksyOutcomeTargetDetailses) {
       this.outcomeTargetId = outcomeTargetId;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMProject = iwmpMProject;
       this.status = status;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.wdcpmksyOutcomeTargetTranxes = wdcpmksyOutcomeTargetTranxes;
       this.wdcpmksyOutcomeTargetDetailses = wdcpmksyOutcomeTargetDetailses;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="outcome_target_id", unique=true, nullable=false)
    public int getOutcomeTargetId() {
        return this.outcomeTargetId;
    }
    
    public void setOutcomeTargetId(int outcomeTargetId) {
        this.outcomeTargetId = outcomeTargetId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=29)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=20)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=29)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyOutcomeTarget")
    public Set<WdcpmksyOutcomeTargetTranx> getWdcpmksyOutcomeTargetTranxes() {
        return this.wdcpmksyOutcomeTargetTranxes;
    }
    
    public void setWdcpmksyOutcomeTargetTranxes(Set<WdcpmksyOutcomeTargetTranx> wdcpmksyOutcomeTargetTranxes) {
        this.wdcpmksyOutcomeTargetTranxes = wdcpmksyOutcomeTargetTranxes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyOutcomeTarget")
    public Set<WdcpmksyOutcomeTargetDetails> getWdcpmksyOutcomeTargetDetailses() {
        return this.wdcpmksyOutcomeTargetDetailses;
    }
    
    public void setWdcpmksyOutcomeTargetDetailses(Set<WdcpmksyOutcomeTargetDetails> wdcpmksyOutcomeTargetDetailses) {
        this.wdcpmksyOutcomeTargetDetailses = wdcpmksyOutcomeTargetDetailses;
    }




}


