package app.model.project;
// Generated 15 Sep, 2021 11:58:41 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import app.model.master.WdcpmksyMOutcome;
import app.model.master.WdcpmksyMOutcomeDetail;

/**
 * WdcpmksyOutcomeTargetDetails generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_outcome_target_details"
    ,schema="public"
)
public class WdcpmksyOutcomeTargetDetails  implements java.io.Serializable {


     private int outcomeTargetDetailsId;
     private WdcpmksyMOutcome wdcpmksyMOutcome;
     private WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail;
     private WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget;
     private BigDecimal target;

    public WdcpmksyOutcomeTargetDetails() {
    }

	
    public WdcpmksyOutcomeTargetDetails(int outcomeTargetDetailsId) {
        this.outcomeTargetDetailsId = outcomeTargetDetailsId;
    }
    public WdcpmksyOutcomeTargetDetails(int outcomeTargetDetailsId, WdcpmksyMOutcome wdcpmksyMOutcome, WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget, BigDecimal target) {
       this.outcomeTargetDetailsId = outcomeTargetDetailsId;
       this.wdcpmksyMOutcome = wdcpmksyMOutcome;
       this.wdcpmksyOutcomeTarget = wdcpmksyOutcomeTarget;
       this.target = target;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="outcome_target_details_id", unique=true, nullable=false)
    public int getOutcomeTargetDetailsId() {
        return this.outcomeTargetDetailsId;
    }
    
    public void setOutcomeTargetDetailsId(int outcomeTargetDetailsId) {
        this.outcomeTargetDetailsId = outcomeTargetDetailsId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="outcome_id")
    public WdcpmksyMOutcome getWdcpmksyMOutcome() {
        return this.wdcpmksyMOutcome;
    }
    
    public void setWdcpmksyMOutcome(WdcpmksyMOutcome wdcpmksyMOutcome) {
        this.wdcpmksyMOutcome = wdcpmksyMOutcome;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="outcome_target_id")
    public WdcpmksyOutcomeTarget getWdcpmksyOutcomeTarget() {
        return this.wdcpmksyOutcomeTarget;
    }
    
    public void setWdcpmksyOutcomeTarget(WdcpmksyOutcomeTarget wdcpmksyOutcomeTarget) {
        this.wdcpmksyOutcomeTarget = wdcpmksyOutcomeTarget;
    }

    
    @Column(name="target", precision=5)
    public BigDecimal getTarget() {
        return this.target;
    }
    
    public void setTarget(BigDecimal target) {
        this.target = target;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="outcome_detail_id")
    public WdcpmksyMOutcomeDetail getWdcpmksyMOutcomeDetail() {
        return this.wdcpmksyMOutcomeDetail;
    }
    
    public void setWdcpmksyMOutcomeDetail(WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail) {
        this.wdcpmksyMOutcomeDetail = wdcpmksyMOutcomeDetail;
    }



}


