package app.model.project;
// Generated 13 Oct, 2021 4:54:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.UserReg;

/**
 * WdcpmksyOutcomeAchTranx generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_outcome_ach_tranx"
    ,schema="public"
)
public class WdcpmksyOutcomeAchTranx  implements java.io.Serializable {


     private int tranxId;
     private UserReg iwmpUserRegBySentFrom;
     private UserReg iwmpUserRegBySentTo;
     private WdcpmksyOutcomeAchievement wdcpmksyOutcomeAchievement;
     private Date sentOn;
     private Character action;
     private String remarks;

    public WdcpmksyOutcomeAchTranx() {
    }

	
    public WdcpmksyOutcomeAchTranx(int tranxId) {
        this.tranxId = tranxId;
    }
    public WdcpmksyOutcomeAchTranx(int tranxId, UserReg iwmpUserRegBySentFrom, UserReg iwmpUserRegBySentTo, WdcpmksyOutcomeAchievement wdcpmksyOutcomeAchievement, Date sentOn, Character action, String remarks) {
       this.tranxId = tranxId;
       this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
       this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
       this.wdcpmksyOutcomeAchievement = wdcpmksyOutcomeAchievement;
       this.sentOn = sentOn;
       this.action = action;
       this.remarks = remarks;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.AUTO)
    
    @Column(name="tranx_id", unique=true, nullable=false)
    public int getTranxId() {
        return this.tranxId;
    }
    
    public void setTranxId(int tranxId) {
        this.tranxId = tranxId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sent_from")
    public UserReg getIwmpUserRegBySentFrom() {
        return this.iwmpUserRegBySentFrom;
    }
    
    public void setIwmpUserRegBySentFrom(UserReg iwmpUserRegBySentFrom) {
        this.iwmpUserRegBySentFrom = iwmpUserRegBySentFrom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sent_to")
    public UserReg getIwmpUserRegBySentTo() {
        return this.iwmpUserRegBySentTo;
    }
    
    public void setIwmpUserRegBySentTo(UserReg iwmpUserRegBySentTo) {
        this.iwmpUserRegBySentTo = iwmpUserRegBySentTo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="achievement_id")
    public WdcpmksyOutcomeAchievement getWdcpmksyOutcomeAchievement() {
        return this.wdcpmksyOutcomeAchievement;
    }
    
    public void setWdcpmksyOutcomeAchievement(WdcpmksyOutcomeAchievement wdcpmksyOutcomeAchievement) {
        this.wdcpmksyOutcomeAchievement = wdcpmksyOutcomeAchievement;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sent_on", length=29)
    public Date getSentOn() {
        return this.sentOn;
    }
    
    public void setSentOn(Date sentOn) {
        this.sentOn = sentOn;
    }

    
    @Column(name="action", length=1)
    public Character getAction() {
        return this.action;
    }
    
    public void setAction(Character action) {
        this.action = action;
    }

    
    @Column(name="remarks", length=5000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


