package app.model.project;
// Generated 2 Sep, 2021 3:27:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMFinYear;
import app.model.IwmpMMonth;
import app.model.IwmpMProject;

/**
 * IwmpProjectPhysicalAchievement generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_project_phy_achievement"
    ,schema="public"
)
public class WdcpmksyProjectPhysicalAchievement  implements java.io.Serializable {


     private int achievementId;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMMonth iwmpMMonth;
     private IwmpMProject iwmpMProject;
     private Character status;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String requestIp;
     private Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxes = new HashSet<WdcpmksyProjectPhysicalAchievementTranx>(0);
     private Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses = new HashSet<WdcpmksyProjectPhysicalAchievementDetails>(0);

    public WdcpmksyProjectPhysicalAchievement() {
    }

	
    public WdcpmksyProjectPhysicalAchievement(int achievementId) {
        this.achievementId = achievementId;
    }
    public WdcpmksyProjectPhysicalAchievement(int achievementId, IwmpMFinYear iwmpMFinYear, IwmpMMonth iwmpMMonth, IwmpMProject iwmpMProject, Character status, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String requestIp, Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxes, Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses) {
       this.achievementId = achievementId;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMMonth = iwmpMMonth;
       this.iwmpMProject = iwmpMProject;
       this.status = status;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.wdcpmksyProjectPhysicalAchievementTranxes = wdcpmksyProjectPhysicalAchievementTranxes;
       this.wdcpmksyProjectPhysicalAchievementDetailses = wdcpmksyProjectPhysicalAchievementDetailses;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="achievement_id", unique=true, nullable=false)
    public int getAchievementId() {
        return this.achievementId;
    }
    
    public void setAchievementId(int achievementId) {
        this.achievementId = achievementId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="month_id")
    public IwmpMMonth getIwmpMMonth() {
        return this.iwmpMMonth;
    }
    
    public void setIwmpMMonth(IwmpMMonth iwmpMMonth) {
        this.iwmpMMonth = iwmpMMonth;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=29)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=20)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=29)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyProjectPhysicalAchievement")
    public Set<WdcpmksyProjectPhysicalAchievementTranx> getWdcpmksyProjectPhysicalAchievementTranxes() {
        return this.wdcpmksyProjectPhysicalAchievementTranxes;
    }
    
    public void setWdcpmksyProjectPhysicalAchievementTranxes(Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxes) {
        this.wdcpmksyProjectPhysicalAchievementTranxes = wdcpmksyProjectPhysicalAchievementTranxes;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyProjectPhysicalAchievement")
    public Set<WdcpmksyProjectPhysicalAchievementDetails> getWdcpmksyProjectPhysicalAchievementDetailses() {
        return this.wdcpmksyProjectPhysicalAchievementDetailses;
    }
    
    public void setWdcpmksyProjectPhysicalAchievementDetailses(Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses) {
        this.wdcpmksyProjectPhysicalAchievementDetailses = wdcpmksyProjectPhysicalAchievementDetailses;
    }




}


