package app.model.project;
// Generated 13 Oct, 2021 4:54:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMFinYear;
import app.model.IwmpMMonth;
import app.model.IwmpMProject;

/**
 * WdcpmksyOutcomeAchievement generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_outcome_achievement"
    ,schema="public"
)
public class WdcpmksyOutcomeAchievement  implements java.io.Serializable {


     private int achievementId;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMMonth iwmpMMonth;
     private IwmpMProject iwmpMProject;
     private Character status;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String requestIp;
     private Set<WdcpmksyOutcomeAchDetails> wdcpmksyOutcomeAchDetailses = new HashSet<WdcpmksyOutcomeAchDetails>(0);
     private Set<WdcpmksyOutcomeAchTranx> wdcpmksyOutcomeAchTranxes = new HashSet<WdcpmksyOutcomeAchTranx>(0);

    public WdcpmksyOutcomeAchievement() {
    }

	
    public WdcpmksyOutcomeAchievement(int achievementId) {
        this.achievementId = achievementId;
    }
    public WdcpmksyOutcomeAchievement(int achievementId, IwmpMFinYear iwmpMFinYear, IwmpMMonth iwmpMMonth, IwmpMProject iwmpMProject, Character status, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String requestIp, Set<WdcpmksyOutcomeAchDetails> wdcpmksyOutcomeAchDetailses, Set<WdcpmksyOutcomeAchTranx> wdcpmksyOutcomeAchTranxes) {
       this.achievementId = achievementId;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMMonth = iwmpMMonth;
       this.iwmpMProject = iwmpMProject;
       this.status = status;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.wdcpmksyOutcomeAchDetailses = wdcpmksyOutcomeAchDetailses;
       this.wdcpmksyOutcomeAchTranxes = wdcpmksyOutcomeAchTranxes;
    }
   
     @Id 

    
    @Column(name="achievement_id", unique=true, nullable=false)
    public int getAchievementId() {
        return this.achievementId;
    }
    
    public void setAchievementId(int achievementId) {
        this.achievementId = achievementId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id")
    public IwmpMMonth getIwmpMMonth() {
        return this.iwmpMMonth;
    }
    
    public void setIwmpMMonth(IwmpMMonth iwmpMMonth) {
        this.iwmpMMonth = iwmpMMonth;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=29)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=20)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_on", length=29)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyOutcomeAchievement")
    public Set<WdcpmksyOutcomeAchDetails> getWdcpmksyOutcomeAchDetailses() {
        return this.wdcpmksyOutcomeAchDetailses;
    }
    
    public void setWdcpmksyOutcomeAchDetailses(Set<WdcpmksyOutcomeAchDetails> wdcpmksyOutcomeAchDetailses) {
        this.wdcpmksyOutcomeAchDetailses = wdcpmksyOutcomeAchDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyOutcomeAchievement")
    public Set<WdcpmksyOutcomeAchTranx> getWdcpmksyOutcomeAchTranxes() {
        return this.wdcpmksyOutcomeAchTranxes;
    }
    
    public void setWdcpmksyOutcomeAchTranxes(Set<WdcpmksyOutcomeAchTranx> wdcpmksyOutcomeAchTranxes) {
        this.wdcpmksyOutcomeAchTranxes = wdcpmksyOutcomeAchTranxes;
    }




}


