package app.model.project;
// Generated 15 Sep, 2021 11:19:42 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMFinYear;
import app.model.IwmpMMonth;

/**
 * WdcpmksyProjectPhyAssetAchievement generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_project_phy_asset_achievement"
    ,schema="public"
)
public class WdcpmksyProjectPhyAssetAchievement  implements java.io.Serializable {


     private long assetAchievementId;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMMonth iwmpMMonth;
     private IwmpProjectPhysicalAsset iwmpProjectPhysicalAsset;
     private BigDecimal achievement;
     private Character status;
     private String createdby;
     private Date createdon;
     private String updatedby;
     private Date updatedon;
     
    public WdcpmksyProjectPhyAssetAchievement() {
    }

	
    public WdcpmksyProjectPhyAssetAchievement(long assetAchievementId) {
        this.assetAchievementId = assetAchievementId;
    }
    public WdcpmksyProjectPhyAssetAchievement(long assetAchievementId, IwmpMFinYear iwmpMFinYear, IwmpMMonth iwmpMMonth, IwmpProjectPhysicalAsset iwmpProjectPhysicalAsset, BigDecimal achievement, Character status, String createdby, Date createdon, String updatedby, Date updatedon) {
       this.assetAchievementId = assetAchievementId;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMMonth = iwmpMMonth;
       this.iwmpProjectPhysicalAsset = iwmpProjectPhysicalAsset;
       this.achievement = achievement;
       this.status=status;
       this.createdby=createdby;
       this.createdon=createdon;
       this.updatedby = updatedby;
       this.updatedon = updatedon;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="asset_achievement_id", unique=true, nullable=false)
    public long getAssetAchievementId() {
        return this.assetAchievementId;
    }
    
    public void setAssetAchievementId(long assetAchievementId) {
        this.assetAchievementId = assetAchievementId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id")
    public IwmpMMonth getIwmpMMonth() {
        return this.iwmpMMonth;
    }
    
    public void setIwmpMMonth(IwmpMMonth iwmpMMonth) {
        this.iwmpMMonth = iwmpMMonth;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="asset_id")
    public IwmpProjectPhysicalAsset getIwmpProjectPhysicalAsset() {
        return this.iwmpProjectPhysicalAsset;
    }
    
    public void setIwmpProjectPhysicalAsset(IwmpProjectPhysicalAsset iwmpProjectPhysicalAsset) {
        this.iwmpProjectPhysicalAsset = iwmpProjectPhysicalAsset;
    }

    
    @Column(name="achievement", precision=10)
    public BigDecimal getAchievement() {
        return this.achievement;
    }
    
    public void setAchievement(BigDecimal achievement) {
        this.achievement = achievement;
    }

    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Column(name="createdby", length=20)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby){
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    @Column(name="updatedby", length=20)
    public String getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedon", length=29)
    public Date getUpdatedon() {
        return this.updatedon;
    }
    
    public void setUpdatedon(Date updatedon) {
        this.updatedon = updatedon;
    }
}


