package app.model;
// Generated 11 Jan, 2022 10:24:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.master.IwmpMPhyActivity;

/**
 * BaseLineSurveyMain generated by hbm2java
 */
@Entity
@Table(name="base_line_survey_main"
    ,schema="public"
)
public class BaseLineSurveyMain  implements java.io.Serializable {


	private int blsId;
    private IwmpMProject iwmpMProject;
    private BigDecimal totalGeoArea;
    private String areaCoveringType;
    private BigDecimal totalDegradedArea;
    private BigDecimal totalWastelandArea;
    private BigDecimal totalForestWastelandArea;
    private BigDecimal totalGrossCroppedArea;
    private BigDecimal totalNetSownArea;
    private Integer totalSc;
    private Integer totalSt;
    private Integer totalOthers;
    private Integer totalPopulation;
    private Integer noOfLandlessHousehold;
    private Integer noOfBplHousehold;
    private Integer smallFarmerHousehold;
    private Integer marginalFarmerHousehold;
    private Integer personDaysMigration;
    private Date createdOn;
    private Date updatedOn;
    private String requestIp;
    private String createdBy;
    private Character status;
    private Integer householdTotal;
    private Integer populationSc;
    private Integer populationSt;
    private Integer populationOther;
    private Integer populationTotal;
    private Integer populationLandlessPeople;
    private Integer populationBpl;
    private Integer populationSmallFarmers;
    private Integer populationMarginalFarmers;
    private Integer whsFarmPond;
    private Integer whsCheckDam;
    private Integer whsNallahBund;
    private Integer whsPercolationTank;
    private Integer whsGwrs;
    private Integer whsGullyPlug;
    private Integer whsOther;
    private Integer piFarmPond;
    private Integer piCheckDam;
    private Integer piNallahBund;
    private Integer piOther;
    private Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses = new HashSet<BaseLineSurveyActivityDetails>(0);

   public BaseLineSurveyMain() {
   }

	
   public BaseLineSurveyMain(int blsId) {
       this.blsId = blsId;
   }
   public BaseLineSurveyMain(int blsId, IwmpMProject iwmpMProject, BigDecimal totalGeoArea, String areaCoveringType, BigDecimal totalDegradedArea, BigDecimal totalWastelandArea, BigDecimal totalForestWastelandArea, BigDecimal totalGrossCroppedArea, BigDecimal totalNetSownArea, Integer totalSc, Integer totalSt, Integer totalOthers, Integer totalPopulation, Integer noOfLandlessHousehold, Integer noOfBplHousehold, Integer smallFarmerHousehold, Integer marginalFarmerHousehold, Integer personDaysMigration, Date createdOn, Date updatedOn, String requestIp, String createdBy, Character status, Integer householdTotal, Integer populationSc, Integer populationSt, Integer populationOther, Integer populationTotal, Integer populationLandlessPeople, Integer populationBpl, Integer populationSmallFarmers, Integer populationMarginalFarmers, Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses) {
      this.blsId = blsId;
      this.iwmpMProject = iwmpMProject;
      this.totalGeoArea = totalGeoArea;
      this.areaCoveringType = areaCoveringType;
      this.totalDegradedArea = totalDegradedArea;
      this.totalWastelandArea = totalWastelandArea;
      this.totalForestWastelandArea = totalForestWastelandArea;
      this.totalGrossCroppedArea = totalGrossCroppedArea;
      this.totalNetSownArea = totalNetSownArea;
      this.totalSc = totalSc;
      this.totalSt = totalSt;
      this.totalOthers = totalOthers;
      this.totalPopulation = totalPopulation;
      this.noOfLandlessHousehold = noOfLandlessHousehold;
      this.noOfBplHousehold = noOfBplHousehold;
      this.smallFarmerHousehold = smallFarmerHousehold;
      this.marginalFarmerHousehold = marginalFarmerHousehold;
      this.personDaysMigration = personDaysMigration;
      this.createdOn = createdOn;
      this.updatedOn = updatedOn;
      this.requestIp = requestIp;
      this.createdBy = createdBy;
      this.status = status;
      this.householdTotal = householdTotal;
      this.populationSc = populationSc;
      this.populationSt = populationSt;
      this.populationOther = populationOther;
      this.populationTotal = populationTotal;
      this.populationLandlessPeople = populationLandlessPeople;
      this.populationBpl = populationBpl;
      this.populationSmallFarmers = populationSmallFarmers;
      this.populationMarginalFarmers = populationMarginalFarmers;
      this.baseLineSurveyActivityDetailses = baseLineSurveyActivityDetailses;
   }
  
    @Id 

    @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name="bls_id", unique=true, nullable=false)
   public int getBlsId() {
       return this.blsId;
   }
   
   public void setBlsId(int blsId) {
       this.blsId = blsId;
   }

@ManyToOne(fetch=FetchType.LAZY)
   @JoinColumn(name="proj_id")
   public IwmpMProject getIwmpMProject() {
       return this.iwmpMProject;
   }
   
   public void setIwmpMProject(IwmpMProject iwmpMProject) {
       this.iwmpMProject = iwmpMProject;
   }

   
   @Column(name="total_geo_area", precision=10)
   public BigDecimal getTotalGeoArea() {
       return this.totalGeoArea;
   }
   
   public void setTotalGeoArea(BigDecimal totalGeoArea) {
       this.totalGeoArea = totalGeoArea;
   }

   
   @Column(name="area_covering_type", length=30)
   public String getAreaCoveringType() {
       return this.areaCoveringType;
   }
   
   public void setAreaCoveringType(String areaCoveringType) {
       this.areaCoveringType = areaCoveringType;
   }

   
   @Column(name="total_degraded_area", precision=10)
   public BigDecimal getTotalDegradedArea() {
       return this.totalDegradedArea;
   }
   
   public void setTotalDegradedArea(BigDecimal totalDegradedArea) {
       this.totalDegradedArea = totalDegradedArea;
   }

   
   @Column(name="total_wasteland_area", precision=10)
   public BigDecimal getTotalWastelandArea() {
       return this.totalWastelandArea;
   }
   
   public void setTotalWastelandArea(BigDecimal totalWastelandArea) {
       this.totalWastelandArea = totalWastelandArea;
   }

   
   @Column(name="total_forest_wasteland_area", precision=10)
   public BigDecimal getTotalForestWastelandArea() {
       return this.totalForestWastelandArea;
   }
   
   public void setTotalForestWastelandArea(BigDecimal totalForestWastelandArea) {
       this.totalForestWastelandArea = totalForestWastelandArea;
   }

   
   @Column(name="total_gross_cropped_area", precision=10)
   public BigDecimal getTotalGrossCroppedArea() {
       return this.totalGrossCroppedArea;
   }
   
   public void setTotalGrossCroppedArea(BigDecimal totalGrossCroppedArea) {
       this.totalGrossCroppedArea = totalGrossCroppedArea;
   }

   
   @Column(name="total_net_sown_area", precision=10)
   public BigDecimal getTotalNetSownArea() {
       return this.totalNetSownArea;
   }
   
   public void setTotalNetSownArea(BigDecimal totalNetSownArea) {
       this.totalNetSownArea = totalNetSownArea;
   }

   
   @Column(name="total_sc")
   public Integer getTotalSc() {
       return this.totalSc;
   }
   
   public void setTotalSc(Integer totalSc) {
       this.totalSc = totalSc;
   }

   
   @Column(name="total_st")
   public Integer getTotalSt() {
       return this.totalSt;
   }
   
   public void setTotalSt(Integer totalSt) {
       this.totalSt = totalSt;
   }

   
   @Column(name="total_others")
   public Integer getTotalOthers() {
       return this.totalOthers;
   }
   
   public void setTotalOthers(Integer totalOthers) {
       this.totalOthers = totalOthers;
   }

   
   @Column(name="total_population")
   public Integer getTotalPopulation() {
       return this.totalPopulation;
   }
   
   public void setTotalPopulation(Integer totalPopulation) {
       this.totalPopulation = totalPopulation;
   }

   
   @Column(name="no_of_landless_household")
   public Integer getNoOfLandlessHousehold() {
       return this.noOfLandlessHousehold;
   }
   
   public void setNoOfLandlessHousehold(Integer noOfLandlessHousehold) {
       this.noOfLandlessHousehold = noOfLandlessHousehold;
   }

   
   @Column(name="no_of_bpl_household")
   public Integer getNoOfBplHousehold() {
       return this.noOfBplHousehold;
   }
   
   public void setNoOfBplHousehold(Integer noOfBplHousehold) {
       this.noOfBplHousehold = noOfBplHousehold;
   }

   
   @Column(name="small_farmer_household")
   public Integer getSmallFarmerHousehold() {
       return this.smallFarmerHousehold;
   }
   
   public void setSmallFarmerHousehold(Integer smallFarmerHousehold) {
       this.smallFarmerHousehold = smallFarmerHousehold;
   }

   
   @Column(name="marginal_farmer_household")
   public Integer getMarginalFarmerHousehold() {
       return this.marginalFarmerHousehold;
   }
   
   public void setMarginalFarmerHousehold(Integer marginalFarmerHousehold) {
       this.marginalFarmerHousehold = marginalFarmerHousehold;
   }

   
   @Column(name="person_days_migration")
   public Integer getPersonDaysMigration() {
       return this.personDaysMigration;
   }
   
   public void setPersonDaysMigration(Integer personDaysMigration) {
       this.personDaysMigration = personDaysMigration;
   }

   @Temporal(TemporalType.DATE)
   @Column(name="created_on", length=13)
   public Date getCreatedOn() {
       return this.createdOn;
   }
   
   public void setCreatedOn(Date createdOn) {
       this.createdOn = createdOn;
   }

   @Temporal(TemporalType.DATE)
   @Column(name="updated_on", length=13)
   public Date getUpdatedOn() {
       return this.updatedOn;
   }
   
   public void setUpdatedOn(Date updatedOn) {
       this.updatedOn = updatedOn;
   }

   
   @Column(name="request_ip", length=20)
   public String getRequestIp() {
       return this.requestIp;
   }
   
   public void setRequestIp(String requestIp) {
       this.requestIp = requestIp;
   }

   
   @Column(name="created_by", length=20)
   public String getCreatedBy() {
       return this.createdBy;
   }
   
   public void setCreatedBy(String createdBy) {
       this.createdBy = createdBy;
   }

   
   @Column(name="status", length=1)
   public Character getStatus() {
       return this.status;
   }
   
   public void setStatus(Character status) {
       this.status = status;
   }

   
   @Column(name="household_total")
   public Integer getHouseholdTotal() {
       return this.householdTotal;
   }
   
   public void setHouseholdTotal(Integer householdTotal) {
       this.householdTotal = householdTotal;
   }

   
   @Column(name="population_sc")
   public Integer getPopulationSc() {
       return this.populationSc;
   }
   
   public void setPopulationSc(Integer populationSc) {
       this.populationSc = populationSc;
   }

   
   @Column(name="population_st")
   public Integer getPopulationSt() {
       return this.populationSt;
   }
   
   public void setPopulationSt(Integer populationSt) {
       this.populationSt = populationSt;
   }

   
   @Column(name="population_other")
   public Integer getPopulationOther() {
       return this.populationOther;
   }
   
   public void setPopulationOther(Integer populationOther) {
       this.populationOther = populationOther;
   }

   
   @Column(name="population_total")
   public Integer getPopulationTotal() {
       return this.populationTotal;
   }
   
   public void setPopulationTotal(Integer populationTotal) {
       this.populationTotal = populationTotal;
   }

   
   @Column(name="population_landless_people")
   public Integer getPopulationLandlessPeople() {
       return this.populationLandlessPeople;
   }
   
   public void setPopulationLandlessPeople(Integer populationLandlessPeople) {
       this.populationLandlessPeople = populationLandlessPeople;
   }

   
   @Column(name="population_bpl")
   public Integer getPopulationBpl() {
       return this.populationBpl;
   }
   
   public void setPopulationBpl(Integer populationBpl) {
       this.populationBpl = populationBpl;
   }

   
   @Column(name="population_small_farmers")
   public Integer getPopulationSmallFarmers() {
       return this.populationSmallFarmers;
   }
   
   public void setPopulationSmallFarmers(Integer populationSmallFarmers) {
       this.populationSmallFarmers = populationSmallFarmers;
   }

   
   @Column(name="population_marginal_farmers")
   public Integer getPopulationMarginalFarmers() {
       return this.populationMarginalFarmers;
   }
   
   public void setPopulationMarginalFarmers(Integer populationMarginalFarmers) {
       this.populationMarginalFarmers = populationMarginalFarmers;
   }
   
   @Column(name="whs_farm_pond")
   public Integer getWhsFarmPond() {
       return this.whsFarmPond;
   }
   
   public void setWhsFarmPond(Integer whsFarmPond) {
       this.whsFarmPond = whsFarmPond;
   }

   
   @Column(name="whs_check_dam")
   public Integer getWhsCheckDam() {
       return this.whsCheckDam;
   }
   
   public void setWhsCheckDam(Integer whsCheckDam) {
       this.whsCheckDam = whsCheckDam;
   }

   
   @Column(name="whs_nallah_bund")
   public Integer getWhsNallahBund() {
       return this.whsNallahBund;
   }
   
   public void setWhsNallahBund(Integer whsNallahBund) {
       this.whsNallahBund = whsNallahBund;
   }

   
   @Column(name="whs_percolation_tank")
   public Integer getWhsPercolationTank() {
       return this.whsPercolationTank;
   }
   
   public void setWhsPercolationTank(Integer whsPercolationTank) {
       this.whsPercolationTank = whsPercolationTank;
   }

   
   @Column(name="whs_gwrs")
   public Integer getWhsGwrs() {
       return this.whsGwrs;
   }
   
   public void setWhsGwrs(Integer whsGwrs) {
       this.whsGwrs = whsGwrs;
   }

   
   @Column(name="whs_gully_plug")
   public Integer getWhsGullyPlug() {
       return this.whsGullyPlug;
   }
   
   public void setWhsGullyPlug(Integer whsGullyPlug) {
       this.whsGullyPlug = whsGullyPlug;
   }

   
   @Column(name="whs_other")
   public Integer getWhsOther() {
       return this.whsOther;
   }
   
   public void setWhsOther(Integer whsOther) {
       this.whsOther = whsOther;
   }

   
   @Column(name="pi_farm_pond")
   public Integer getPiFarmPond() {
       return this.piFarmPond;
   }
   
   public void setPiFarmPond(Integer piFarmPond) {
       this.piFarmPond = piFarmPond;
   }

   
   @Column(name="pi_check_dam")
   public Integer getPiCheckDam() {
       return this.piCheckDam;
   }
   
   public void setPiCheckDam(Integer piCheckDam) {
       this.piCheckDam = piCheckDam;
   }

   
   @Column(name="pi_nallah_bund")
   public Integer getPiNallahBund() {
       return this.piNallahBund;
   }
   
   public void setPiNallahBund(Integer piNallahBund) {
       this.piNallahBund = piNallahBund;
   }

   
   @Column(name="pi_other")
   public Integer getPiOther() {
       return this.piOther;
   }
   
   public void setPiOther(Integer piOther) {
       this.piOther = piOther;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="baseLineSurveyMain")
   public Set<BaseLineSurveyActivityDetails> getBaseLineSurveyActivityDetailses() {
       return this.baseLineSurveyActivityDetailses;
   }
   
   public void setBaseLineSurveyActivityDetailses(Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses) {
       this.baseLineSurveyActivityDetailses = baseLineSurveyActivityDetailses;
   }





}


