package app.model;
// Generated 11 Jan, 2022 11:40:31 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.master.IwmpMPhyActivity;
import app.model.master.IwmpMPhyHeads;
import app.model.master.WdcpmksyMOutcome;
import app.model.master.WdcpmksyMOutcomeDetail;

/**
 * BaseLineSurveyActivityDetails generated by hbm2java
 */
@Entity
@Table(name="base_line_survey_activity_details"
    ,schema="public"
)
public class BaseLineSurveyActivityDetails  implements java.io.Serializable {


     private int blsActivityDetailsId;
     private BaseLineSurveyMain baseLineSurveyMain;
     private IwmpMPhyActivity iwmpMPhyActivity;
     private IwmpMPhyHeads iwmpMPhyHeads;
     private WdcpmksyMOutcome wdcpmksyMOutcome;
     private WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail;
     private BigDecimal areaOfActivity;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;

    public BaseLineSurveyActivityDetails() {
    }

	
    public BaseLineSurveyActivityDetails(int blsActivityDetailsId, BaseLineSurveyMain baseLineSurveyMain) {
        this.blsActivityDetailsId = blsActivityDetailsId;
        this.baseLineSurveyMain = baseLineSurveyMain;
    }
    public BaseLineSurveyActivityDetails(int blsActivityDetailsId, BaseLineSurveyMain baseLineSurveyMain, IwmpMPhyActivity iwmpMPhyActivity, IwmpMPhyHeads iwmpMPhyHeads, WdcpmksyMOutcome wdcpmksyMOutcome, WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail, BigDecimal areaOfActivity, Date createdOn, Date updatedOn, String requestIp, String createdBy) {
       this.blsActivityDetailsId = blsActivityDetailsId;
       this.baseLineSurveyMain = baseLineSurveyMain;
       this.iwmpMPhyActivity = iwmpMPhyActivity;
       this.iwmpMPhyHeads = iwmpMPhyHeads;
       this.wdcpmksyMOutcome = wdcpmksyMOutcome;
       this.wdcpmksyMOutcomeDetail = wdcpmksyMOutcomeDetail;
       this.areaOfActivity = areaOfActivity;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="bls_activity_details_id", unique=true, nullable=false)
    public int getBlsActivityDetailsId() {
        return this.blsActivityDetailsId;
    }
    
    public void setBlsActivityDetailsId(int blsActivityDetailsId) {
        this.blsActivityDetailsId = blsActivityDetailsId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="bls_id", nullable=false)
    public BaseLineSurveyMain getBaseLineSurveyMain() {
        return this.baseLineSurveyMain;
    }
    
    public void setBaseLineSurveyMain(BaseLineSurveyMain baseLineSurveyMain) {
        this.baseLineSurveyMain = baseLineSurveyMain;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="phy_activity")
    public IwmpMPhyActivity getIwmpMPhyActivity() {
        return this.iwmpMPhyActivity;
    }
    
    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
        this.iwmpMPhyActivity = iwmpMPhyActivity;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="phy_head")
    public IwmpMPhyHeads getIwmpMPhyHeads() {
        return this.iwmpMPhyHeads;
    }
    
    public void setIwmpMPhyHeads(IwmpMPhyHeads iwmpMPhyHeads) {
        this.iwmpMPhyHeads = iwmpMPhyHeads;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="outcome_id")
    public WdcpmksyMOutcome getWdcpmksyMOutcome() {
        return this.wdcpmksyMOutcome;
    }
    
    public void setWdcpmksyMOutcome(WdcpmksyMOutcome wdcpmksyMOutcome) {
        this.wdcpmksyMOutcome = wdcpmksyMOutcome;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="outcome_detail_id")
    public WdcpmksyMOutcomeDetail getWdcpmksyMOutcomeDetail() {
        return this.wdcpmksyMOutcomeDetail;
    }
    
    public void setWdcpmksyMOutcomeDetail(WdcpmksyMOutcomeDetail wdcpmksyMOutcomeDetail) {
        this.wdcpmksyMOutcomeDetail = wdcpmksyMOutcomeDetail;
    }

    
    @Column(name="area_of_activity", precision=10)
    public BigDecimal getAreaOfActivity() {
        return this.areaOfActivity;
    }
    
    public void setAreaOfActivity(BigDecimal areaOfActivity) {
        this.areaOfActivity = areaOfActivity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


