package app.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlsOutDetailHis generated by hbm2java
 */
@Entity
@Table(name="bls_out_detail_his" ,schema="public")

public class BlsOutDetailHis  implements java.io.Serializable {


     private int blsOutDetailIdPk;
     private BlsOutMainHis blsOutMainHis;
     private MBlsOutcome MBlsOutcomeByForestLandTypeId;
     private MBlsOutcome MBlsOutcomeByOwnershipId;
     private MBlsOutcome MBlsOutcomeByClassificationLandId;
     private MBlsOutcome MBlsOutcomeByNoOfCropId;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private String ownerName;
     private String landSubClassification;
	private Set<BlsOutDetailCropHis> blsOutDetailCropHises = new HashSet<BlsOutDetailCropHis>(0);

    public BlsOutDetailHis() {
    }

	
    public BlsOutDetailHis(int blsOutDetailIdPk) {
        this.blsOutDetailIdPk = blsOutDetailIdPk;
    }
    public BlsOutDetailHis(int blsOutDetailIdPk, BlsOutMainHis blsOutMainHis, MBlsOutcome MBlsOutcomeByForestLandTypeId, MBlsOutcome MBlsOutcomeByOwnershipId, MBlsOutcome MBlsOutcomeByClassificationLandId, MBlsOutcome MBlsOutcomeByNoOfCropId, Date createdOn, Date updatedOn, String requestIp, String createdBy, String ownerName, Set<BlsOutDetailCropHis> blsOutDetailCropHises) {
       this.blsOutDetailIdPk = blsOutDetailIdPk;
       this.blsOutMainHis = blsOutMainHis;
       this.MBlsOutcomeByForestLandTypeId = MBlsOutcomeByForestLandTypeId;
       this.MBlsOutcomeByOwnershipId = MBlsOutcomeByOwnershipId;
       this.MBlsOutcomeByClassificationLandId = MBlsOutcomeByClassificationLandId;
       this.MBlsOutcomeByNoOfCropId = MBlsOutcomeByNoOfCropId;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.ownerName = ownerName;
       this.blsOutDetailCropHises = blsOutDetailCropHises;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bls_out_detail_id_pk", unique=true, nullable=false)
    public int getBlsOutDetailIdPk() {
        return this.blsOutDetailIdPk;
    }
    
    public void setBlsOutDetailIdPk(int blsOutDetailIdPk) {
        this.blsOutDetailIdPk = blsOutDetailIdPk;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bls_out_main_id")
    public BlsOutMainHis getBlsOutMainHis() {
        return this.blsOutMainHis;
    }
    
    public void setBlsOutMainHis(BlsOutMainHis blsOutMainHis) {
        this.blsOutMainHis = blsOutMainHis;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="forest_land_type_id")
    public MBlsOutcome getMBlsOutcomeByForestLandTypeId() {
        return this.MBlsOutcomeByForestLandTypeId;
    }
    
    public void setMBlsOutcomeByForestLandTypeId(MBlsOutcome MBlsOutcomeByForestLandTypeId) {
        this.MBlsOutcomeByForestLandTypeId = MBlsOutcomeByForestLandTypeId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ownership_id")
    public MBlsOutcome getMBlsOutcomeByOwnershipId() {
        return this.MBlsOutcomeByOwnershipId;
    }
    
    public void setMBlsOutcomeByOwnershipId(MBlsOutcome MBlsOutcomeByOwnershipId) {
        this.MBlsOutcomeByOwnershipId = MBlsOutcomeByOwnershipId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classification_land_id")
    public MBlsOutcome getMBlsOutcomeByClassificationLandId() {
        return this.MBlsOutcomeByClassificationLandId;
    }
    
    public void setMBlsOutcomeByClassificationLandId(MBlsOutcome MBlsOutcomeByClassificationLandId) {
        this.MBlsOutcomeByClassificationLandId = MBlsOutcomeByClassificationLandId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="no_of_crop_id")
    public MBlsOutcome getMBlsOutcomeByNoOfCropId() {
        return this.MBlsOutcomeByNoOfCropId;
    }
    
    public void setMBlsOutcomeByNoOfCropId(MBlsOutcome MBlsOutcomeByNoOfCropId) {
        this.MBlsOutcomeByNoOfCropId = MBlsOutcomeByNoOfCropId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="owner_name", length=100)
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    
    @Column(name="land_sub_classification", length=100)
    public String getLandSubClassification() {
		return landSubClassification;
	}

	public void setLandSubClassification(String landSubClassification) {
		this.landSubClassification = landSubClassification;
	}

    @OneToMany(fetch=FetchType.LAZY, mappedBy="blsOutDetailHis")
    public Set<BlsOutDetailCropHis> getBlsOutDetailCropHises() {
        return this.blsOutDetailCropHises;
    }
    
    public void setBlsOutDetailCropHises(Set<BlsOutDetailCropHis> blsOutDetailCropHises) {
        this.blsOutDetailCropHises = blsOutDetailCropHises;
    }




}


