package app.model;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlsOutDetailCropHis generated by hbm2java
 */
@Entity
@Table(name="bls_out_detail_crop_his" ,schema="public")

public class BlsOutDetailCropHis  implements java.io.Serializable {


     private int blsOutDetailTranxIdPk;
     private BlsOutDetailHis blsOutDetailHis;
     private MBlsOutcome MBlsOutcomeBySeasonId;
     private MBlsOutcome MBlsOutcomeByCropTypeId;
     private BigDecimal cropProduction;
     private BigDecimal avgIncome;
     private BigDecimal cropArea;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;

    public BlsOutDetailCropHis() {
    }

	
    public BlsOutDetailCropHis(int blsOutDetailTranxIdPk) {
        this.blsOutDetailTranxIdPk = blsOutDetailTranxIdPk;
    }
    public BlsOutDetailCropHis(int blsOutDetailTranxIdPk, BlsOutDetailHis blsOutDetailHis, MBlsOutcome MBlsOutcomeBySeasonId, MBlsOutcome MBlsOutcomeByCropTypeId, BigDecimal cropProduction, BigDecimal avgIncome, BigDecimal cropArea, Date createdOn, Date updatedOn, String requestIp, String createdBy) {
       this.blsOutDetailTranxIdPk = blsOutDetailTranxIdPk;
       this.blsOutDetailHis = blsOutDetailHis;
       this.MBlsOutcomeBySeasonId = MBlsOutcomeBySeasonId;
       this.MBlsOutcomeByCropTypeId = MBlsOutcomeByCropTypeId;
       this.cropProduction = cropProduction;
       this.avgIncome = avgIncome;
       this.cropArea = cropArea;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bls_out_detail_tranx_id_pk", unique=true, nullable=false)
    public int getBlsOutDetailTranxIdPk() {
        return this.blsOutDetailTranxIdPk;
    }
    
    public void setBlsOutDetailTranxIdPk(int blsOutDetailTranxIdPk) {
        this.blsOutDetailTranxIdPk = blsOutDetailTranxIdPk;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="bls_out_detail_id")
    public BlsOutDetailHis getBlsOutDetailHis() {
        return this.blsOutDetailHis;
    }
    
    public void setBlsOutDetailHis(BlsOutDetailHis blsOutDetailHis) {
        this.blsOutDetailHis = blsOutDetailHis;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="season_id")
    public MBlsOutcome getMBlsOutcomeBySeasonId() {
        return this.MBlsOutcomeBySeasonId;
    }
    
    public void setMBlsOutcomeBySeasonId(MBlsOutcome MBlsOutcomeBySeasonId) {
        this.MBlsOutcomeBySeasonId = MBlsOutcomeBySeasonId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="crop_type_id")
    public MBlsOutcome getMBlsOutcomeByCropTypeId() {
        return this.MBlsOutcomeByCropTypeId;
    }
    
    public void setMBlsOutcomeByCropTypeId(MBlsOutcome MBlsOutcomeByCropTypeId) {
        this.MBlsOutcomeByCropTypeId = MBlsOutcomeByCropTypeId;
    }

    
    @Column(name="crop_production", precision=10)
    public BigDecimal getCropProduction() {
        return this.cropProduction;
    }
    
    public void setCropProduction(BigDecimal cropProduction) {
        this.cropProduction = cropProduction;
    }

    
    @Column(name="avg_income", precision=10)
    public BigDecimal getAvgIncome() {
        return this.avgIncome;
    }
    
    public void setAvgIncome(BigDecimal avgIncome) {
        this.avgIncome = avgIncome;
    }

    
    @Column(name="crop_area", precision=10)
    public BigDecimal getCropArea() {
        return this.cropArea;
    }
    
    public void setCropArea(BigDecimal cropArea) {
        this.cropArea = cropArea;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


