package app.model;
// Generated 05-Apr-2022, 3:02:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.master.IwmpVillage;

/**
 * BlsOutMain generated by hbm2java
 */
@Entity
@Table(name="bls_out_main"
    ,schema="public"
)
public class BlsOutMain  implements java.io.Serializable {


     private int blsOutMainIdPk;
     private IwmpMProject iwmpMProject;
     private IwmpVillage iwmpVillage;
     
     private MBlsOutcome MBlsOutcomeByIrrigationStatusId;
     private String plotNo;
     private BigDecimal area;
     
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Character status;
     private Character micro_status;
     private BigDecimal micro_irrigation;
     private Set<BlsOutDetail> blsOutDetails = new HashSet<BlsOutDetail>(0);

    public BlsOutMain() {
    }

	
    public BlsOutMain(int blsOutMainIdPk) {
        this.blsOutMainIdPk = blsOutMainIdPk;
    }
    public BlsOutMain(int blsOutMainIdPk, IwmpMProject iwmpMProject, IwmpVillage iwmpVillage, MBlsOutcome MBlsOutcomeByOwnershipId, Character micro_status, BigDecimal micro_irrigation, MBlsOutcome MBlsOutcomeByIrrigationStatusId, String plotNo, BigDecimal area, String ownerName, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<BlsOutDetail> blsOutDetails) {
       this.blsOutMainIdPk = blsOutMainIdPk;
       this.iwmpMProject = iwmpMProject;
       this.iwmpVillage = iwmpVillage;
       this.MBlsOutcomeByIrrigationStatusId = MBlsOutcomeByIrrigationStatusId;
       this.plotNo = plotNo;
       this.area = area;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.micro_status = micro_status;
       this.micro_irrigation = micro_irrigation;
       this.blsOutDetails = blsOutDetails;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bls_out_main_id_pk", unique=true, nullable=false)
    public int getBlsOutMainIdPk() {
        return this.blsOutMainIdPk;
    }
    
    public void setBlsOutMainIdPk(int blsOutMainIdPk) {
        this.blsOutMainIdPk = blsOutMainIdPk;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vcode")
    public IwmpVillage getIwmpVillage() {
        return this.iwmpVillage;
    }
    
    public void setIwmpVillage(IwmpVillage iwmpVillage) {
        this.iwmpVillage = iwmpVillage;
    }



    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="irrigation_status_id")
    public MBlsOutcome getMBlsOutcomeByIrrigationStatusId() {
        return this.MBlsOutcomeByIrrigationStatusId;
    }
    
    public void setMBlsOutcomeByIrrigationStatusId(MBlsOutcome MBlsOutcomeByIrrigationStatusId) {
        this.MBlsOutcomeByIrrigationStatusId = MBlsOutcomeByIrrigationStatusId;
    }

    
    
    
    public Character getMicro_status() {
		return micro_status;
	}


	public void setMicro_status(Character micro_status) {
		this.micro_status = micro_status;
	}


	


	public BigDecimal getMicro_irrigation() {
		return micro_irrigation;
	}


	public void setMicro_irrigation(BigDecimal micro_irrigation) {
		this.micro_irrigation = micro_irrigation;
	}


	@Column(name="plot_no", length=20)
    public String getPlotNo() {
        return this.plotNo;
    }
    
    public void setPlotNo(String plotNo) {
        this.plotNo = plotNo;
    }

    
    @Column(name="area", precision=10)
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    
    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="blsOutMain")
    public Set<BlsOutDetail> getBlsOutDetails() {
        return this.blsOutDetails;
    }
    
    public void setBlsOutDetails(Set<BlsOutDetail> blsOutDetails) {
        this.blsOutDetails = blsOutDetails;
    }

    @Column(name="status", length=1)
	public Character getStatus() {
		return status;
	}


	public void setStatus(Character status) {
		this.status = status;
	}




}


