package app.model;
// Generated 2 May, 2022 3:06:13 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.master.IwmpVillage;
import app.model.BlsOutDetailAchiev;

/**
 * BlsOutMainAchiev generated by hbm2java
 */
@Entity
@Table(name="bls_out_main_achiev",schema="public")

public class BlsOutMainAchiev  implements java.io.Serializable {


     private int blsOutMainIdPk;
     private IwmpMProject iwmpMProject;
     private IwmpVillage iwmpVillage;
     private MBlsOutcome MBlsOutcomeByIrrigationStatusId;
     private String plotNo;
     private BigDecimal area;
     private Character status;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Character micro_status;
     private BigDecimal micro_irrigation;
     private Set<BlsOutDetailAchiev> blsOutDetailAchievs = new HashSet<BlsOutDetailAchiev>(0);

    public BlsOutMainAchiev() {
    }

	
    public BlsOutMainAchiev(int blsOutMainIdPk) {
        this.blsOutMainIdPk = blsOutMainIdPk;
    }
    public BlsOutMainAchiev(int blsOutMainIdPk, IwmpMProject iwmpMProject, IwmpVillage iwmpVillage, MBlsOutcome MBlsOutcome, String plotNo, BigDecimal area, Character status, Date createdOn, Date updatedOn, String requestIp, String createdBy, Character micro_status, BigDecimal micro_irrigation, Set<BlsOutDetailAchiev> blsOutDetailAchievs) {
       this.blsOutMainIdPk = blsOutMainIdPk;
       this.iwmpMProject = iwmpMProject;
       this.iwmpVillage = iwmpVillage;
       this.MBlsOutcomeByIrrigationStatusId = MBlsOutcome;
       this.plotNo = plotNo;
       this.area = area;
       this.status = status;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.micro_status = micro_status;
       this.micro_irrigation = micro_irrigation;
       this.blsOutDetailAchievs = blsOutDetailAchievs;
    }
   
    @Id
    @Column(name="bls_out_main_id_pk", unique=true, nullable=false)
    public int getBlsOutMainIdPk() {
        return this.blsOutMainIdPk;
    }
    
    public void setBlsOutMainIdPk(int blsOutMainIdPk) {
        this.blsOutMainIdPk = blsOutMainIdPk;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vcode")
    public IwmpVillage getIwmpVillage() {
        return this.iwmpVillage;
    }
    
    public void setIwmpVillage(IwmpVillage iwmpVillage) {
        this.iwmpVillage = iwmpVillage;
    }
    
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="irrigation_status_id")
    public MBlsOutcome getMBlsOutcomeByIrrigationStatusId() {
        return this.MBlsOutcomeByIrrigationStatusId;
    }
    
    public void setMBlsOutcomeByIrrigationStatusId(MBlsOutcome MBlsOutcome) {
        this.MBlsOutcomeByIrrigationStatusId = MBlsOutcome;
    }

    
    @Column(name="plot_no", length=20)
    public String getPlotNo() {
        return this.plotNo;
    }
    
    public void setPlotNo(String plotNo) {
        this.plotNo = plotNo;
    }

    
    @Column(name="area", precision=10)
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    public Character getMicro_status() {
		return micro_status;
	}


	public void setMicro_status(Character micro_status) {
		this.micro_status = micro_status;
	}


	public BigDecimal getMicro_irrigation() {
		return micro_irrigation;
	}


	public void setMicro_irrigation(BigDecimal micro_irrigation) {
		this.micro_irrigation = micro_irrigation;
	}

    @OneToMany(fetch=FetchType.LAZY, mappedBy="blsOutMainAchiev")
    public Set<BlsOutDetailAchiev> getBlsOutDetailAchievs() {
        return this.blsOutDetailAchievs;
    }
    
    public void setBlsOutDetailAchievs(Set<BlsOutDetailAchiev> blsOutDetailAchievs) {
        this.blsOutDetailAchievs = blsOutDetailAchievs;
    }




}


