package app.model;
// Generated 05-Apr-2022, 3:02:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlsOutDetailTranx generated by hbm2java
 */
@Entity
@Table(name="bls_out_detail_crop"
    ,schema="public"
)
public class BlsOutDetailCrop  implements java.io.Serializable {


	 private int blsOutDetailTranxIdPk;
     private BlsOutDetail blsOutDetail;
     private MBlsOutcome MBlsOutcomeByCropTypeId;
     private MBlsOutcome MBlsOutcomeBySeasonId;
     private BigDecimal cropProduction;
     private BigDecimal avgIncome;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private BigDecimal cropArea;
     private Character status;

    public BlsOutDetailCrop() {
    }

	
    public BlsOutDetailCrop(int blsOutDetailTranxIdPk) {
        this.blsOutDetailTranxIdPk = blsOutDetailTranxIdPk;
    }
    public BlsOutDetailCrop(int blsOutDetailTranxIdPk, BlsOutDetail blsOutDetail, MBlsOutcome MBlsOutcomeByCropTypeId, MBlsOutcome MBlsOutcomeBySeasonId, BigDecimal cropProduction, BigDecimal avgIncome, Date createdOn, Date updatedOn, String requestIp, String createdBy, BigDecimal cropArea, Character status) {
       this.blsOutDetailTranxIdPk = blsOutDetailTranxIdPk;
       this.blsOutDetail = blsOutDetail;
       this.MBlsOutcomeByCropTypeId = MBlsOutcomeByCropTypeId;
       this.MBlsOutcomeBySeasonId = MBlsOutcomeBySeasonId;
       this.cropProduction = cropProduction;
       this.avgIncome = avgIncome;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.cropArea = cropArea;
       this.status = status;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bls_out_detail_tranx_id_pk", unique=true, nullable=false)
    public int getBlsOutDetailTranxIdPk() {
        return this.blsOutDetailTranxIdPk;
    }
    
    public void setBlsOutDetailTranxIdPk(int blsOutDetailTranxIdPk) {
        this.blsOutDetailTranxIdPk = blsOutDetailTranxIdPk;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="bls_out_detail_id")
    public BlsOutDetail getBlsOutDetail() {
        return this.blsOutDetail;
    }
    
    public void setBlsOutDetail(BlsOutDetail blsOutDetail) {
        this.blsOutDetail = blsOutDetail;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="crop_type_id")
    public MBlsOutcome getMBlsOutcomeByCropTypeId() {
        return this.MBlsOutcomeByCropTypeId;
    }
    
    public void setMBlsOutcomeByCropTypeId(MBlsOutcome MBlsOutcomeByCropTypeId) {
        this.MBlsOutcomeByCropTypeId = MBlsOutcomeByCropTypeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="season_id")
    public MBlsOutcome getMBlsOutcomeBySeasonId() {
        return this.MBlsOutcomeBySeasonId;
    }
    
    public void setMBlsOutcomeBySeasonId(MBlsOutcome MBlsOutcomeBySeasonId) {
        this.MBlsOutcomeBySeasonId = MBlsOutcomeBySeasonId;
    }

    
    @Column(name="crop_production", precision=10)
    public BigDecimal getCropProduction() {
        return this.cropProduction;
    }
    
    public void setCropProduction(BigDecimal cropProduction) {
        this.cropProduction = cropProduction;
    }

    
    @Column(name="avg_income", precision=10)
    public BigDecimal getAvgIncome() {
        return this.avgIncome;
    }
    
    public void setAvgIncome(BigDecimal avgIncome) {
        this.avgIncome = avgIncome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="crop_area", precision=10)
    public BigDecimal getCropArea() {
        return this.cropArea;
    }
    
    public void setCropArea(BigDecimal cropArea) {
        this.cropArea = cropArea;
    }

    @Column(name="status", length=1)
	public Character getStatus() {
		return status;
	}


	public void setStatus(Character status) {
		this.status = status;
	}




}


