package app.model;
// Generated 2 May, 2022 3:06:13 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlsOutDetailCropAchiev generated by hbm2java
 */
@Entity
@Table(name="bls_out_detail_crop_achiev" ,schema="public")

public class BlsOutDetailCropAchiev  implements java.io.Serializable {


     private int blsOutDetailCropIdPk;
     private BlsOutDetailAchiev blsOutDetailAchiev;
     private MBlsOutcome MBlsOutcomeBySeasonId;
     private MBlsOutcome MBlsOutcomeByCropTypeId;
     private BigDecimal cropProduction;
     private BigDecimal avgIncome;
     private BigDecimal cropArea;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Character delStatus;

    public BlsOutDetailCropAchiev() {
    }

	
    public BlsOutDetailCropAchiev(int blsOutDetailCropIdPk) {
        this.blsOutDetailCropIdPk = blsOutDetailCropIdPk;
    }
    public BlsOutDetailCropAchiev(int blsOutDetailCropIdPk, BlsOutDetailAchiev blsOutDetailAchiev, MBlsOutcome MBlsOutcomeBySeasonId, MBlsOutcome MBlsOutcomeByCropTypeId, BigDecimal cropProduction, BigDecimal avgIncome, BigDecimal cropArea, Date createdOn, Date updatedOn, String requestIp, String createdBy, Character delStatus) {
       this.blsOutDetailCropIdPk = blsOutDetailCropIdPk;
       this.blsOutDetailAchiev = blsOutDetailAchiev;
       this.MBlsOutcomeBySeasonId = MBlsOutcomeBySeasonId;
       this.MBlsOutcomeByCropTypeId = MBlsOutcomeByCropTypeId;
       this.cropProduction = cropProduction;
       this.avgIncome = avgIncome;
       this.cropArea = cropArea;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.delStatus=  delStatus;
    }
   
    @Id 
  //  @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="bls_out_detail_crop_id_pk", unique=true, nullable=false)
    public int getBlsOutDetailCropIdPk() {
        return this.blsOutDetailCropIdPk;
    }
    
    public void setBlsOutDetailCropIdPk(int blsOutDetailCropIdPk) {
        this.blsOutDetailCropIdPk = blsOutDetailCropIdPk;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="bls_out_detail_id")
    public BlsOutDetailAchiev getBlsOutDetailAchiev() {
        return this.blsOutDetailAchiev;
    }
    
    public void setBlsOutDetailAchiev(BlsOutDetailAchiev blsOutDetailAchiev) {
        this.blsOutDetailAchiev = blsOutDetailAchiev;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="season_id")
    public MBlsOutcome getMBlsOutcomeBySeasonId() {
        return this.MBlsOutcomeBySeasonId;
    }
    
    public void setMBlsOutcomeBySeasonId(MBlsOutcome MBlsOutcomeBySeasonId) {
        this.MBlsOutcomeBySeasonId = MBlsOutcomeBySeasonId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="crop_type_id")
    public MBlsOutcome getMBlsOutcomeByCropTypeId() {
        return this.MBlsOutcomeByCropTypeId;
    }
    
    public void setMBlsOutcomeByCropTypeId(MBlsOutcome MBlsOutcomeByCropTypeId) {
        this.MBlsOutcomeByCropTypeId = MBlsOutcomeByCropTypeId;
    }

    
    @Column(name="crop_production", precision=10)
    public BigDecimal getCropProduction() {
        return this.cropProduction;
    }
    
    public void setCropProduction(BigDecimal cropProduction) {
        this.cropProduction = cropProduction;
    }

    
    @Column(name="avg_income", precision=10)
    public BigDecimal getAvgIncome() {
        return this.avgIncome;
    }
    
    public void setAvgIncome(BigDecimal avgIncome) {
        this.avgIncome = avgIncome;
    }

    
    @Column(name="crop_area", precision=10)
    public BigDecimal getCropArea() {
        return this.cropArea;
    }
    
    public void setCropArea(BigDecimal cropArea) {
        this.cropArea = cropArea;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name="del_status", length=1)
	public Character getDelStatus() {
		return delStatus;
	}

	public void setDelStatus(Character delStatus) {
		this.delStatus = delStatus;
	}




}


