package app.model;
// Generated 29 Dec, 2020 12:47:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;

/**
 * IwmpMProjectPrd generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_project_prd"
    ,schema="public"
)
public class IwmpMProjectPrd  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Min(value = 1, message = "Select Project Period")
	private int prdCode;
     private String prdDesc;
     private BigDecimal prdValue;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Set<IwmpMProject> iwmpMProjects = new HashSet<IwmpMProject>(0);

    public IwmpMProjectPrd() {
    }

	
    public IwmpMProjectPrd(int prdCode) {
        this.prdCode = prdCode;
    }
    public IwmpMProjectPrd(int prdCode, String prdDesc, BigDecimal prdValue, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Set<IwmpMProject> iwmpMProjects) {
       this.prdCode = prdCode;
       this.prdDesc = prdDesc;
       this.prdValue = prdValue;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.iwmpMProjects = iwmpMProjects;
    }
   
     @Id 

    
    @Column(name="prd_code", unique=true, nullable=false)
    public int getPrdCode() {
        return this.prdCode;
    }
    
    public void setPrdCode(int prdCode) {
        this.prdCode = prdCode;
    }

    
    @Column(name="prd_desc", length=20)
    public String getPrdDesc() {
        return this.prdDesc;
    }
    
    public void setPrdDesc(String prdDesc) {
        this.prdDesc = prdDesc;
    }

    
    @Column(name="prd_value", precision=131089, scale=0)
    public BigDecimal getPrdValue() {
        return this.prdValue;
    }
    
    public void setPrdValue(BigDecimal prdValue) {
        this.prdValue = prdValue;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(mappedBy="iwmpMProjectPrd")
    public Set<IwmpMProject> getIwmpMProjects() {
        return this.iwmpMProjects;
    }
    
    public void setIwmpMProjects(Set<IwmpMProject> iwmpMProjects) {
        this.iwmpMProjects = iwmpMProjects;
    }




}


