package app.model;
// Generated 13 Nov, 2020 1:53:06 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;

import app.model.project.WdcpmksyProjectPhysicalAchievement;
import app.model.project.WdcpmksyProjectPhysicalAchievementDetails;
import app.projectevaluation.model.WdcpmksyProjectProfileEvaluation;
import app.model.master.WdcpmksyMOutcome;
import app.model.outcome.GroundwaterMain;
import app.model.project.IwmpProjectPhysicalAsset;
import app.model.project.IwmpProjectPhysicalAssetTemp;
import app.model.project.IwmpProjectPhysicalPlan;
import app.model.project.WdcpmksyBaselineupdateAchievement;
import app.model.project.WdcpmksyOutcomeTarget;
import app.model.project.WdcpmksyProjectPhyAssetAchievement;

/**
 * IwmpMFinYear generated by hbm2java
 */
@Entity
@Table(name = "iwmp_m_fin_year", schema = "public")
public class IwmpMFinYear implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Min(value = 1, message = "Select Financial Year")
	private int finYrCd;
	private String finYrDesc;
	private Date startFrom;
	private Date endTo;
	private Character actFlag;
	private String createdBy;
	private Date createdDate;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private Integer batchCd;
	private String batch;
	private String batchDesc;
	private Character achievStatus;
	private Set<Outcome2Data> outcome2Datas = new HashSet<Outcome2Data>(0);
	private Set<IwmpMProject> iwmpMProjects = new HashSet<IwmpMProject>(0);
	private Set<IwmpProjectPhysicalPlan> iwmpProjectPhysicalPlans = new HashSet<IwmpProjectPhysicalPlan>(0);
	private Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets = new HashSet<IwmpProjectPhysicalAsset>(0);
	private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
	private Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements = new HashSet<IwmpActivityAssetAddonParameterAchievement>(0);
	private Set<WdcpmksyProjectPhysicalAchievement> wdcpmksyProjectPhysicalAchievements = new HashSet<WdcpmksyProjectPhysicalAchievement>(0);
    //private Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses = new HashSet<WdcpmksyProjectPhysicalAchievementDetails>(0);
    private Set<WdcpmksyMOutcome> wdcpmksyMOutcomes = new HashSet<WdcpmksyMOutcome>(0);
    private Set<WdcpmksyProjectPhyAssetAchievement> wdcpmksyProjectPhyAssetAchievements = new HashSet<WdcpmksyProjectPhyAssetAchievement>(0);
    private Set<WdcpmksyOutcomeTarget> wdcpmksyOutcomeTargets = new HashSet<WdcpmksyOutcomeTarget>(0);
    private Set<GroundwaterMain> groundwaterMains = new HashSet<GroundwaterMain>(0);
    private Set<IwmpActPlan> iwmpActPlans = new HashSet<IwmpActPlan>(0);
//    private Set<WdcpmksyConvergenceDetail> convergenceDetails = new HashSet<>(0);
    private Set<GetGoiReleaseToStateTreasury> getGoiReleaseToStateTreasury = new HashSet<GetGoiReleaseToStateTreasury>(0);
    private Set<WdcpmksyBaselineupdateAchievement> wdcpmksyBaselineupdateAchievements = new HashSet<WdcpmksyBaselineupdateAchievement>(0);
    private Set<WdcpmksyProjectProfileEvaluation> wdcpmksyProjectProfileEvaluation = new HashSet<WdcpmksyProjectProfileEvaluation>(0);
    
	public IwmpMFinYear() {
	}

	public IwmpMFinYear(int finYrCd) {
		this.finYrCd = finYrCd;
	}

	public IwmpMFinYear(int finYrCd, String finYrDesc, Date startFrom, Date endTo, Character actFlag, String createdBy,
			Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Integer batchCd,
			String batch, String batchDesc, Character achievStatus, Set<Outcome2Data> outcome2Datas, Set<IwmpMProject> iwmpMProjects,
			Set<IwmpProjectPhysicalPlan> IwmpProjectPhysicalPlans, Set<WdcpmksyMOutcome> wdcpmksyMOutcomes, 
			Set<GroundwaterMain> groundwaterMains, Set<IwmpActPlan> iwmpActPlans, Set<GetGoiReleaseToStateTreasury> getGoiReleaseToStateTreasury,
			Set<WdcpmksyBaselineupdateAchievement> wdcpmksyBaselineupdateAchievements) {
		this.finYrCd = finYrCd;
		this.finYrDesc = finYrDesc;
		this.startFrom = startFrom;
		this.endTo = endTo;
		this.actFlag = actFlag;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
		this.batchCd = batchCd;
		this.batch = batch;
		this.batchDesc = batchDesc;
		this.achievStatus=achievStatus;
		this.outcome2Datas = outcome2Datas;
		this.iwmpMProjects = iwmpMProjects;
		this.iwmpProjectPhysicalPlans = IwmpProjectPhysicalPlans;
		this.wdcpmksyMOutcomes = wdcpmksyMOutcomes;
		this.groundwaterMains = groundwaterMains;
		this.iwmpActPlans = iwmpActPlans;
		this.getGoiReleaseToStateTreasury = getGoiReleaseToStateTreasury;
		this.wdcpmksyBaselineupdateAchievements = wdcpmksyBaselineupdateAchievements;
	}

	
	@Id
	@Column(name = "fin_yr_cd", unique = true, nullable = false)
	public int getFinYrCd() {
		return this.finYrCd;
	}

	public void setFinYrCd(int finYrCd) {
		this.finYrCd = finYrCd;
	}

	@Column(name = "fin_yr_desc", length = 9)
	public String getFinYrDesc() {
		return this.finYrDesc;
	}

	public void setFinYrDesc(String finYrDesc) {
		this.finYrDesc = finYrDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_from", length = 13)
	public Date getStartFrom() {
		return this.startFrom;
	}

	public void setStartFrom(Date startFrom) {
		this.startFrom = startFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_to", length = 13)
	public Date getEndTo() {
		return this.endTo;
	}

	public void setEndTo(Date endTo) {
		this.endTo = endTo;
	}

	@Column(name = "act_flag", length = 1)
	public Character getActFlag() {
		return this.actFlag;
	}

	public void setActFlag(Character actFlag) {
		this.actFlag = actFlag;
	}

	@Column(name = "created_by", length = 25)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "last_updated_by", length = 25)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "batch_cd")
	public Integer getBatchCd() {
		return this.batchCd;
	}

	public void setBatchCd(Integer batchCd) {
		this.batchCd = batchCd;
	}

	@Column(name = "batch", length = 40)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "batch_desc", length = 50)
	public String getBatchDesc() {
		return this.batchDesc;
	}

	public void setBatchDesc(String batchDesc) {
		this.batchDesc = batchDesc;
	}
	@Column(name = "achiev_status", length = 1)
	public Character getAchievStatus() {
		return achievStatus;
	}

	public void setAchievStatus(Character achievStatus) {
		this.achievStatus = achievStatus;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<Outcome2Data> getOutcome2Datas() {
        return this.outcome2Datas;
    }
    
    public void setOutcome2Datas(Set<Outcome2Data> outcome2Datas) {
        this.outcome2Datas = outcome2Datas;
    }
    
	@OneToMany(fetch=FetchType.LAZY, mappedBy = "iwmpMFinYear")
	public Set<IwmpMProject> getIwmpMProjects() {
		return this.iwmpMProjects;
	}

	public void setIwmpMProjects(Set<IwmpMProject> iwmpMProjects) {
		this.iwmpMProjects = iwmpMProjects;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy = "iwmpMFinYear")
	public Set<IwmpProjectPhysicalPlan> getIwmpProjectPhysicalPlans() {
		return this.iwmpProjectPhysicalPlans;
	}

	public void setIwmpProjectPhysicalPlans(Set<IwmpProjectPhysicalPlan> iwmpProjectPhysicalPlans) {
        this.iwmpProjectPhysicalPlans = iwmpProjectPhysicalPlans;

	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<IwmpProjectPhysicalAsset> getIwmpProjectPhysicalAssets() {
        return this.iwmpProjectPhysicalAssets;
    }
    
    public void setIwmpProjectPhysicalAssets(Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets) {
        this.iwmpProjectPhysicalAssets = iwmpProjectPhysicalAssets;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemp() {
        return this.iwmpProjectPhysicalAssetTemp;
    }
    
    public void setIwmpProjectPhysicalAssetTemp(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp) {
        this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<IwmpActivityAssetAddonParameterAchievement> getIwmpAssetParameterAchievements() {
        return this.iwmpAssetParameterAchievements;
    }
    
    public void setIwmpAssetParameterAchievements(Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements) {
        this.iwmpAssetParameterAchievements = iwmpAssetParameterAchievements;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<WdcpmksyProjectPhysicalAchievement> getWdcpmksyProjectPhysicalAchievements() {
        return this.wdcpmksyProjectPhysicalAchievements;
    }
    
    public void setWdcpmksyProjectPhysicalAchievements(Set<WdcpmksyProjectPhysicalAchievement> wdcpmksyProjectPhysicalAchievements) {
        this.wdcpmksyProjectPhysicalAchievements = wdcpmksyProjectPhysicalAchievements;
    }

	/*
	 * @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear") public
	 * Set<WdcpmksyProjectPhysicalAchievementDetails>
	 * getwdcpmksyProjectPhysicalAchievementDetailses() { return
	 * this.wdcpmksyProjectPhysicalAchievementDetailses; }
	 * 
	 * public void setWdcpmksyProjectPhysicalAchievementDetailses(Set<
	 * WdcpmksyProjectPhysicalAchievementDetails>
	 * wdcpmksyProjectPhysicalAchievementDetailses) {
	 * this.wdcpmksyProjectPhysicalAchievementDetailses =
	 * wdcpmksyProjectPhysicalAchievementDetailses; }
	 */

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<WdcpmksyOutcomeTarget> getWdcpmksyOutcomeTargets() {
        return this.wdcpmksyOutcomeTargets;
    }
    
    public void setWdcpmksyOutcomeTargets(Set<WdcpmksyOutcomeTarget> wdcpmksyOutcomeTargets) {
        this.wdcpmksyOutcomeTargets = wdcpmksyOutcomeTargets;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<WdcpmksyProjectPhyAssetAchievement> getWdcpmksyProjectPhyAssetAchievements() {
        return this.wdcpmksyProjectPhyAssetAchievements;
    }
    
    public void setWdcpmksyProjectPhyAssetAchievements(Set<WdcpmksyProjectPhyAssetAchievement> wdcpmksyProjectPhyAssetAchievements) {
        this.wdcpmksyProjectPhyAssetAchievements = wdcpmksyProjectPhyAssetAchievements;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<WdcpmksyMOutcome> getWdcpmksyMOutcomes() {
        return this.wdcpmksyMOutcomes;
    }
    
    public void setWdcpmksyMOutcomes(Set<WdcpmksyMOutcome> wdcpmksyMOutcomes) {
        this.wdcpmksyMOutcomes = wdcpmksyMOutcomes;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<GroundwaterMain> getGroundwaterMains() {
        return this.groundwaterMains;
    }
    
    public void setGroundwaterMains(Set<GroundwaterMain> groundwaterMains) {
        this.groundwaterMains = groundwaterMains;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
    public Set<IwmpActPlan> getIwmpActPlans() {
		return iwmpActPlans;
	}

	public void setIwmpActPlans(Set<IwmpActPlan> iwmpActPlans) {
		this.iwmpActPlans = iwmpActPlans;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
	public Set<GetGoiReleaseToStateTreasury> getGetGoiReleaseToStateTreasury() {
		return getGoiReleaseToStateTreasury;
	}

	public void setGetGoiReleaseToStateTreasury(Set<GetGoiReleaseToStateTreasury> getGoiReleaseToStateTreasury) {
		this.getGoiReleaseToStateTreasury = getGoiReleaseToStateTreasury;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
	public Set<WdcpmksyBaselineupdateAchievement> getWdcpmksyBaselineupdateAchievements() {
		return wdcpmksyBaselineupdateAchievements;
	}

	public void setWdcpmksyBaselineupdateAchievements(
			Set<WdcpmksyBaselineupdateAchievement> wdcpmksyBaselineupdateAchievements) {
		this.wdcpmksyBaselineupdateAchievements = wdcpmksyBaselineupdateAchievements;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMFinYear")
	public Set<WdcpmksyProjectProfileEvaluation> getWdcpmksyProjectProfileEvaluation() {
		return wdcpmksyProjectProfileEvaluation;
	}

	public void setWdcpmksyProjectProfileEvaluation(
			Set<WdcpmksyProjectProfileEvaluation> wdcpmksyProjectProfileEvaluation) {
		this.wdcpmksyProjectProfileEvaluation = wdcpmksyProjectProfileEvaluation;
	}
	
	
	

	
	
	



}
