package app.model;
// Generated 12 Mar, 2021 11:27:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;

import app.model.master.IwmpBlock;
import app.model.master.PfmsEatmisdataDetail;
import app.watershedyatra.model.NodalOfficer;
import app.watershedyatra.model.WatershedYatraInauguaration;

/**
 * IwmpDistrict generated by hbm2java
 */
@Entity
@Table(name="iwmp_district"
    ,schema="public"
)
public class IwmpDistrict  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dcode;
     private IwmpState iwmpState;
     private int distCode;
     private String distName;
     private Integer noOfBlocksDdp;
     private Integer noOfBlocksDpap;
     private Integer noOfBlocksIwdp;
     private Integer iwdpCount;
     private Integer ddpCount;
     private Integer dpapCount;
     private Integer iwdp;
     private Integer ddp;
     private Integer dpap;
     private BigDecimal iwmp;
     private Character importType;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Character mong;
     private String stateCode2001;
     private String stateCode2011;
     private String districtCode2001;
     private String districtCode2011;
     private String censusCodePortedData;
     private String stateCodelgd;
     private Integer districtCodelgd;
     private String lgdCodePortedData;
     private BigDecimal jalShakati;
     private Boolean distproj;
     private Set<IwmpMProject> iwmpMProjects = new HashSet<IwmpMProject>(0);
     private Set<IwmpBlock> iwmpBlocks = new HashSet<IwmpBlock>(0);
     private Set<IwmpActPlan> iwmpActPlans = new HashSet<IwmpActPlan>(0);
     private Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails = new HashSet<PfmsEatmisdataDetail>(0);
     private List<UserMap> userMaps;
     private Set<NodalOfficer> nodalOfficer = new HashSet<NodalOfficer>(0);
     private Set<WatershedYatraInauguaration> WatershedYatraInauguaration = new HashSet<WatershedYatraInauguaration>(0);

    public IwmpDistrict() {
    }

	
    public IwmpDistrict(int dcode, IwmpState iwmpState, int distCode, String distName) {
        this.dcode = dcode;
        this.iwmpState = iwmpState;
        this.distCode = distCode;
        this.distName = distName;
    }
    public IwmpDistrict(int dcode, IwmpState iwmpState, int distCode, String distName, Integer noOfBlocksDdp, Integer noOfBlocksDpap, 
    		Integer noOfBlocksIwdp, Integer iwdpCount, Integer ddpCount, Integer dpapCount, Integer iwdp, Integer ddp, Integer dpap, 
    		BigDecimal iwmp, Character importType, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Character mong, 
    		String stateCode2001, Boolean distproj, String stateCode2011, String districtCode2001, String districtCode2011, String censusCodePortedData, 
    		String stateCodelgd, Integer districtCodelgd, String lgdCodePortedData, BigDecimal jalShakati, Set<IwmpMProject> iwmpMProjects, 
    		Set<IwmpBlock> iwmpBlocks, Set<IwmpActPlan> iwmpActPlans, Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails, Set<NodalOfficer> nodalOfficer, 
    		Set<WatershedYatraInauguaration> WatershedYatraInauguaration) {
       this.dcode = dcode;
       this.iwmpState = iwmpState;
       this.distCode = distCode;
       this.distName = distName;
       this.noOfBlocksDdp = noOfBlocksDdp;
       this.noOfBlocksDpap = noOfBlocksDpap;
       this.noOfBlocksIwdp = noOfBlocksIwdp;
       this.iwdpCount = iwdpCount;
       this.ddpCount = ddpCount;
       this.dpapCount = dpapCount;
       this.iwdp = iwdp;
       this.ddp = ddp;
       this.dpap = dpap;
       this.iwmp = iwmp;
       this.importType = importType;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.mong = mong;
       this.stateCode2001 = stateCode2001;
       this.distproj = distproj;
       this.stateCode2011 = stateCode2011;
       this.districtCode2001 = districtCode2001;
       this.districtCode2011 = districtCode2011;
       this.censusCodePortedData = censusCodePortedData;
       this.stateCodelgd = stateCodelgd;
       this.districtCodelgd = districtCodelgd;
       this.lgdCodePortedData = lgdCodePortedData;
       this.jalShakati = jalShakati;
       this.iwmpMProjects = iwmpMProjects;
       this.iwmpBlocks = iwmpBlocks;
       this.iwmpActPlans = iwmpActPlans;
       this.pfmsEatmisdataDetails = pfmsEatmisdataDetails;
       this.nodalOfficer=nodalOfficer;
       this.WatershedYatraInauguaration=WatershedYatraInauguaration;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
	@Min(value = 1, message = "Select District")
    @Column(name="dcode", unique=true, nullable=false)
    public int getDcode() {
        return this.dcode;
    }
    
    public void setDcode(int dcode) {
        this.dcode = dcode;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="st_code", nullable=false)
    public IwmpState getIwmpState() {
        return this.iwmpState;
    }
    
    public void setIwmpState(IwmpState iwmpState) {
        this.iwmpState = iwmpState;
    }

    
    @Column(name="dist_code", nullable=false)
    public int getDistCode() {
        return this.distCode;
    }
    
    public void setDistCode(int distCode) {
        this.distCode = distCode;
    }

    
    @Column(name="dist_name", nullable=false, length=50)
    public String getDistName() {
        return this.distName;
    }
    
    public void setDistName(String distName) {
        this.distName = distName;
    }

    
    @Column(name="no_of_blocks_ddp")
    public Integer getNoOfBlocksDdp() {
        return this.noOfBlocksDdp;
    }
    
    public void setNoOfBlocksDdp(Integer noOfBlocksDdp) {
        this.noOfBlocksDdp = noOfBlocksDdp;
    }

    
    @Column(name="no_of_blocks_dpap")
    public Integer getNoOfBlocksDpap() {
        return this.noOfBlocksDpap;
    }
    
    public void setNoOfBlocksDpap(Integer noOfBlocksDpap) {
        this.noOfBlocksDpap = noOfBlocksDpap;
    }

    
    @Column(name="no_of_blocks_iwdp")
    public Integer getNoOfBlocksIwdp() {
        return this.noOfBlocksIwdp;
    }
    
    public void setNoOfBlocksIwdp(Integer noOfBlocksIwdp) {
        this.noOfBlocksIwdp = noOfBlocksIwdp;
    }

    
    @Column(name="iwdp_count")
    public Integer getIwdpCount() {
        return this.iwdpCount;
    }
    
    public void setIwdpCount(Integer iwdpCount) {
        this.iwdpCount = iwdpCount;
    }

    
    @Column(name="ddp_count")
    public Integer getDdpCount() {
        return this.ddpCount;
    }
    
    public void setDdpCount(Integer ddpCount) {
        this.ddpCount = ddpCount;
    }

    
    @Column(name="dpap_count")
    public Integer getDpapCount() {
        return this.dpapCount;
    }
    
    public void setDpapCount(Integer dpapCount) {
        this.dpapCount = dpapCount;
    }

    
    @Column(name="iwdp")
    public Integer getIwdp() {
        return this.iwdp;
    }
    
    public void setIwdp(Integer iwdp) {
        this.iwdp = iwdp;
    }

    
    @Column(name="ddp")
    public Integer getDdp() {
        return this.ddp;
    }
    
    public void setDdp(Integer ddp) {
        this.ddp = ddp;
    }

    
    @Column(name="dpap")
    public Integer getDpap() {
        return this.dpap;
    }
    
    public void setDpap(Integer dpap) {
        this.dpap = dpap;
    }

    
    @Column(name="iwmp", precision=131089, scale=0)
    public BigDecimal getIwmp() {
        return this.iwmp;
    }
    
    public void setIwmp(BigDecimal iwmp) {
        this.iwmp = iwmp;
    }

    
    @Column(name="import_type", length=1)
    public Character getImportType() {
        return this.importType;
    }
    
    public void setImportType(Character importType) {
        this.importType = importType;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="mong", length=1)
    public Character getMong() {
        return this.mong;
    }
    
    public void setMong(Character mong) {
        this.mong = mong;
    }

    
    @Column(name="state_code2001", length=200)
    public String getStateCode2001() {
        return this.stateCode2001;
    }
    
    public void setStateCode2001(String stateCode2001) {
        this.stateCode2001 = stateCode2001;
    }

    @Column(name="dist_proj")
    public Boolean getDistproj() {
		return distproj;
	}


	public void setDistproj(Boolean distproj) {
		this.distproj = distproj;
	}


	@Column(name="state_code2011", length=200)
    public String getStateCode2011() {
        return this.stateCode2011;
    }
    
    public void setStateCode2011(String stateCode2011) {
        this.stateCode2011 = stateCode2011;
    }

    
    @Column(name="district_code2001", length=200)
    public String getDistrictCode2001() {
        return this.districtCode2001;
    }
    
    public void setDistrictCode2001(String districtCode2001) {
        this.districtCode2001 = districtCode2001;
    }

    
    @Column(name="district_code2011", length=200)
    public String getDistrictCode2011() {
        return this.districtCode2011;
    }
    
    public void setDistrictCode2011(String districtCode2011) {
        this.districtCode2011 = districtCode2011;
    }

    
    @Column(name="census_code_ported_data", length=1)
    public String getCensusCodePortedData() {
        return this.censusCodePortedData;
    }
    
    public void setCensusCodePortedData(String censusCodePortedData) {
        this.censusCodePortedData = censusCodePortedData;
    }

    
    @Column(name="state_codelgd", length=200)
    public String getStateCodelgd() {
        return this.stateCodelgd;
    }
    
    public void setStateCodelgd(String stateCodelgd) {
        this.stateCodelgd = stateCodelgd;
    }

    
    @Column(name="district_codelgd")
    public Integer getDistrictCodelgd() {
        return this.districtCodelgd;
    }
    
    public void setDistrictCodelgd(Integer districtCodelgd) {
        this.districtCodelgd = districtCodelgd;
    }

    
    @Column(name="lgd_code_ported_data", length=1)
    public String getLgdCodePortedData() {
        return this.lgdCodePortedData;
    }
    
    public void setLgdCodePortedData(String lgdCodePortedData) {
        this.lgdCodePortedData = lgdCodePortedData;
    }

    
    @Column(name="jal_shakati", precision=131089, scale=0)
    public BigDecimal getJalShakati() {
        return this.jalShakati;
    }
    
    public void setJalShakati(BigDecimal jalShakati) {
        this.jalShakati = jalShakati;
    }

    @OneToMany( mappedBy="iwmpDistrict",fetch = FetchType.LAZY)
    public Set<IwmpMProject> getIwmpMProjects() {
        return this.iwmpMProjects;
    }
    
    public void setIwmpMProjects(Set<IwmpMProject> iwmpMProjects) {
        this.iwmpMProjects = iwmpMProjects;
    }

    @OneToMany( mappedBy="iwmpDistrict",fetch=FetchType.LAZY)
    public Set<IwmpBlock> getIwmpBlocks() {
        return this.iwmpBlocks;
    }
    
    public void setIwmpBlocks(Set<IwmpBlock> iwmpBlocks) {
        this.iwmpBlocks = iwmpBlocks;
    }
    
    @OneToMany(mappedBy="iwmpDistrict",fetch=FetchType.LAZY)
    public Set<IwmpActPlan> getIwmpActPlans() {
		return iwmpActPlans;
	}
    
	public void setIwmpActPlans(Set<IwmpActPlan> iwmpActPlans) {
		this.iwmpActPlans = iwmpActPlans;
	}
	
    @OneToMany(mappedBy="iwmpDistrict",fetch=FetchType.LAZY)
    public List<UserMap> getUserMaps() {
		return this.userMaps;
	}

	public void setUserMaps(List<UserMap> userMaps) {
		this.userMaps = userMaps;
	}

	public UserMap addUserMap(UserMap userMap) {
		getUserMaps().add(userMap);
		userMap.setIwmpDistrict(this);

		return userMap;
	}

	public UserMap removeUserMap(UserMap userMap) {
		getUserMaps().remove(userMap);
		userMap.setIwmpDistrict(null);

		return userMap;
	}
        public IwmpBlock addIwmpBlock(IwmpBlock iwmpBlock) {
		getIwmpBlocks().add(iwmpBlock);
		iwmpBlock.setIwmpDistrict(this);

		return iwmpBlock;
	}

	public IwmpBlock removeIwmpBlock(IwmpBlock iwmpBlock) {
		getIwmpBlocks().remove(iwmpBlock);
		iwmpBlock.setIwmpDistrict(null);

		return iwmpBlock;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpDistrict")
    public Set<PfmsEatmisdataDetail> getPfmsEatmisdataDetails() {
        return this.pfmsEatmisdataDetails;
    }
    
    public void setPfmsEatmisdataDetails(Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails) {
        this.pfmsEatmisdataDetails = pfmsEatmisdataDetails;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpDistrict")
	public Set<NodalOfficer> getNodalOfficer() {
		return nodalOfficer;
	}


	public void setNodalOfficer(Set<NodalOfficer> nodalOfficer) {
		this.nodalOfficer = nodalOfficer;
	}
    
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpDistrict")
	public Set<WatershedYatraInauguaration> getWatershedYatraInauguaration() {
		return WatershedYatraInauguaration;
	}

	public void setWatershedYatraInauguaration(Set<WatershedYatraInauguaration> watershedYatraInauguaration) {
		this.WatershedYatraInauguaration = watershedYatraInauguaration;
	}
    
    
    

}


