package app.model;
// Generated 18 Jan, 2021 3:48:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

 // IwmpUserActionLog generated by hbm2java

@Entity
@Table(name="iwmp_user_action_log",schema="public")

public class IwmpUserActionLog  implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private int useractionlogid;
     private UserReg userReg;
     private String actionName;
     private Date createdDate;
     private String requestIp;
     private String sessionId;
     private String userAgent;

    public IwmpUserActionLog() {}

    public IwmpUserActionLog(int useractionlogid, UserReg iwmpUserReg) {
        this.useractionlogid = useractionlogid;
        this.userReg = iwmpUserReg;
    }
    public IwmpUserActionLog(int useractionlogid, UserReg iwmpUserReg, String actionName, Date createdDate, String requestIp, String sessionId, String userAgent) {
       this.useractionlogid = useractionlogid;
       this.userReg = iwmpUserReg;
       this.actionName = actionName;
       this.createdDate = createdDate;
       this.requestIp = requestIp;
       this.sessionId = sessionId;
       this.userAgent = userAgent;
    }
   
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="useractionlogid", unique=true, nullable=false)
    public int getUseractionlogid() {
        return this.useractionlogid;
    }
    
    public void setUseractionlogid(int useractionlogid) {
        this.useractionlogid = useractionlogid;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reg_id", nullable=false)
    public UserReg getUserReg() {
        return this.userReg;
    }
    
    public void setUserReg(UserReg iwmpUserReg) {
        this.userReg = iwmpUserReg;
    }

    
    @Column(name="action_name", length=200)
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=29)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="session_id", length=150)
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    
    @Column(name="user_agent", length=350)
    public String getUserAgent() {
        return this.userAgent;
    }
    
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }




}


