package app.model;
// Generated 29 Dec, 2020 12:47:37 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IwmpMCsShare generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_cs_share"
    ,schema="public"
)
public class IwmpMCsShare  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -854920286848138053L;
	private int stateCentralCd;
     private BigDecimal centralShare;
     private BigDecimal stateShare;
     private String createdBy;
     private Date createdDt;
     private String lastUpdatedBy;
     private Date lastUpdatedDt;
     private String requestIp;
     private Set<IwmpMProject> iwmpMProjects = new HashSet<IwmpMProject>(0);
     private IwmpState iwmpState;

    public IwmpMCsShare() {
    }

	
    public IwmpMCsShare(int stateCentralCd) {
        this.stateCentralCd = stateCentralCd;
    }
    public IwmpMCsShare(int stateCentralCd, BigDecimal centralShare, BigDecimal stateShare, String createdBy, Date createdDt, String lastUpdatedBy, Date lastUpdatedDt, String requestIp, Set<IwmpMProject> iwmpMProjects) {
       this.stateCentralCd = stateCentralCd;
       this.centralShare = centralShare;
       this.stateShare = stateShare;
       this.createdBy = createdBy;
       this.createdDt = createdDt;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDt = lastUpdatedDt;
       this.requestIp = requestIp;
       this.iwmpMProjects = iwmpMProjects;
    }
   
     @Id 

    
    @Column(name="state_central_cd", unique=true, nullable=false)
    public int getStateCentralCd() {
        return this.stateCentralCd;
    }
    
    public void setStateCentralCd(int stateCentralCd) {
        this.stateCentralCd = stateCentralCd;
    }

    
    @Column(name="central_share", precision=5)
    public BigDecimal getCentralShare() {
        return this.centralShare;
    }
    
    public void setCentralShare(BigDecimal centralShare) {
        this.centralShare = centralShare;
    }

    
    @Column(name="state_share", precision=5)
    public BigDecimal getStateShare() {
        return this.stateShare;
    }
    
    public void setStateShare(BigDecimal stateShare) {
        this.stateShare = stateShare;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_dt", length=13)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_dt", length=13)
    public Date getLastUpdatedDt() {
        return this.lastUpdatedDt;
    }
    
    public void setLastUpdatedDt(Date lastUpdatedDt) {
        this.lastUpdatedDt = lastUpdatedDt;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMCsShare")
    public Set<IwmpMProject> getIwmpMProjects() {
        return this.iwmpMProjects;
    }
    
    public void setIwmpMProjects(Set<IwmpMProject> iwmpMProjects) {
        this.iwmpMProjects = iwmpMProjects;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_code")
    public IwmpState getIwmpState() {
        return this.iwmpState;
    }
    
    public void setIwmpState(IwmpState iwmpState) {
        this.iwmpState = iwmpState;
    }


}


