//package app.model;
//
////Generated 7 Jul, 2021 4:22:23 PM by Hibernate Tools 4.3.1
//
//
//import java.util.HashSet;
//import java.util.Set;
//
//import javax.persistence.Basic;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.JoinTable;
//import javax.persistence.ManyToMany;
//import javax.persistence.Table;
//
//import org.hibernate.annotations.Formula;
//
///**
//* IwmpDolrSupport generated by hbm2java
//*/
//@Entity
//@Table(name="iwmp_dolr_support"
// ,schema="public"
//)
//public class IwmpDolrSupport  implements java.io.Serializable {
//
//
//  private int userId;
//  private String userName;
//  private String degination;
//  private String department;
//  private String address;
//  private String phone;
//  private String address1;
//  private Set<IwmpState> iwmpStates = new HashSet<IwmpState>(0);
//
// public IwmpDolrSupport() {
// }
//
//	
// public IwmpDolrSupport(int userId) {
//     this.userId = userId;
// }
// public IwmpDolrSupport(int userId, String userName, String degination, String department, String address, String phone, String address1, Set<IwmpState> iwmpStates) {
//    this.userId = userId;
//    this.userName = userName;
//    this.degination = degination;
//    this.department = department;
//    this.address = address;
//    this.phone = phone;
//    this.address1 = address1;
//    this.iwmpStates = iwmpStates;
// }
//
//  @Id 
//
// 
// @Column(name="user_id", unique=true, nullable=false)
// public int getUserId() {
//     return this.userId;
// }
// 
// public void setUserId(int userId) {
//     this.userId = userId;
// }
//
// 
// @Column(name="user_name")
// public String getUserName() {
//     return this.userName;
// }
// 
// public void setUserName(String userName) {
//     this.userName = userName;
// }
//
// 
// @Column(name="degination")
// public String getDegination() {
//     return this.degination;
// }
// 
// public void setDegination(String degination) {
//     this.degination = degination;
// }
//
// 
// @Column(name="department")
// public String getDepartment() {
//     return this.department;
// }
// 
// public void setDepartment(String department) {
//     this.department = department;
// }
//
// 
// @Column(name="address")
// public String getAddress() {
//     return this.address;
// }
// 
// public void setAddress(String address) {
//     this.address = address;
// }
//
// 
// @Column(name="phone", length=15)
// public String getPhone() {
//     return this.phone;
// }
// 
// public void setPhone(String phone) {
//     this.phone = phone;
// }
//
// 
// @Column(name="address1", length=100)
// public String getAddress1() {
//     return this.address1;
// }
// 
// public void setAddress1(String address1) {
//     this.address1 = address1;
// }
//
//@ManyToMany(fetch=FetchType.LAZY)
// @JoinTable(name="iwmp_dolrsupport_state", schema="public", joinColumns = { 
//     @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
//     @JoinColumn(name="state_cd", nullable=false, updatable=false) })
// public Set<IwmpState> getIwmpStates() {
//     return this.iwmpStates;
// }
// 
// public void setIwmpStates(Set<IwmpState> iwmpStates) {
//     this.iwmpStates = iwmpStates;
// }
// @Formula(value="(select array_to_string(array_agg(st_name), ', ' ) as states from iwmp_state st, iwmp_dolrsupport_state x \r\n" + 
// 		" where st.st_code = x.state_cd and x.user_id =user_id )")
// @Basic(fetch=FetchType.EAGER)
// public String getItemCount() {
//    return this.toString();
// }
//
//
//
//}
//
//
