package app.model;
// Generated 13 Aug, 2021 2:32:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import app.model.master.IwmpMPhyActivity;
import app.model.master.IwmpMUnit;

/**
 * IwmpAssetParameter generated by hbm2java
 */
@Entity
@Table(name="iwmp_activity_asset_addon_parameter"
    ,schema="public"
)
public class IwmpActivityAssetAddonParameter  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int astparameterid;
     private IwmpMPhyActivity iwmpMPhyActivity;
     private IwmpMUnit iwmpMUnit;
     private String parameterdesc;
     private Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements = new HashSet<IwmpActivityAssetAddonParameterAchievement>(0);

    public IwmpActivityAssetAddonParameter() {
    }

	
    public IwmpActivityAssetAddonParameter(int astparameterid) {
        this.astparameterid = astparameterid;
    }
    public IwmpActivityAssetAddonParameter(int astparameterid, IwmpMPhyActivity iwmpMPhyActivity, IwmpMUnit iwmpMUnit, String parameterdesc, Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements) {
       this.astparameterid = astparameterid;
       this.iwmpMPhyActivity = iwmpMPhyActivity;
       this.iwmpMUnit = iwmpMUnit;
       this.parameterdesc = parameterdesc;
       this.iwmpAssetParameterAchievements = iwmpAssetParameterAchievements;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="asset_parameter_id", unique=true, nullable=false)
    public int getAstparameterid() {
        return this.astparameterid;
    }
    
    public void setAstparameterid(int astparameterid) {
        this.astparameterid = astparameterid;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="activity_code")
    public IwmpMPhyActivity getIwmpMPhyActivity() {
        return this.iwmpMPhyActivity;
    }
    
    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
        this.iwmpMPhyActivity = iwmpMPhyActivity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_code")
    public IwmpMUnit getIwmpMUnit() {
        return this.iwmpMUnit;
    }
    
    public void setIwmpMUnit(IwmpMUnit iwmpMUnit) {
        this.iwmpMUnit = iwmpMUnit;
    }

    
    @Column(name="parameter_desc", length=100)
    public String getParameterdesc() {
        return this.parameterdesc;
    }
    
    public void setParameterdesc(String parameterdesc) {
        this.parameterdesc = parameterdesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpAssetParameter")
    public Set<IwmpActivityAssetAddonParameterAchievement> getIwmpAssetParameterAchievements() {
        return this.iwmpAssetParameterAchievements;
    }
    
    public void setIwmpAssetParameterAchievements(Set<IwmpActivityAssetAddonParameterAchievement> iwmpAssetParameterAchievements) {
        this.iwmpAssetParameterAchievements = iwmpAssetParameterAchievements;
    }




}


