package app.model;
// Generated 4 Feb, 2021 11:37:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IwmpActiveUserHistory generated by hbm2java
 */
@Entity
@Table(name="iwmp_active_user_history"
    ,schema="public"
)
public class IwmpActiveUserHistory  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int actuserHisId;
     private UserReg UserReg;
     private String userId;
     private String userName;
     private String designation;
     private String department;
     private String curAddress;
     private String phoneNo;
     private String mobileNo;
     private String faxNo;
     private String email;
     private Date moveOnDate;
     private String moveBy;
     private String moveIp;

    public IwmpActiveUserHistory() {
    }

	
    public IwmpActiveUserHistory(int actuserHisId, UserReg UserReg) {
        this.actuserHisId = actuserHisId;
        this.UserReg = UserReg;
    }
    public IwmpActiveUserHistory(int actuserHisId, UserReg UserReg, String userId, String userName, String designation, String department, String curAddress, String phoneNo, String mobileNo, String faxNo, String email, Date moveOnDate, String moveBy, String moveIp) {
       this.actuserHisId = actuserHisId;
       this.UserReg = UserReg;
       this.userId = userId;
       this.userName = userName;
       this.designation = designation;
       this.department = department;
       this.curAddress = curAddress;
       this.phoneNo = phoneNo;
       this.mobileNo = mobileNo;
       this.faxNo = faxNo;
       this.email = email;
       this.moveOnDate = moveOnDate;
       this.moveBy = moveBy;
       this.moveIp = moveIp;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="actuser_his_id", unique=true, nullable=false)
    public int getActuserHisId() {
        return this.actuserHisId;
    }
    
    public void setActuserHisId(int actuserHisId) {
        this.actuserHisId = actuserHisId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reg_id", nullable=false)
    public UserReg getUserReg() {
        return this.UserReg;
    }
    
    public void setUserReg(UserReg UserReg) {
        this.UserReg = UserReg;
    }

    
    @Column(name="user_id")
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name")
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="designation")
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="department")
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    
    @Column(name="cur_address", length=500)
    public String getCurAddress() {
        return this.curAddress;
    }
    
    public void setCurAddress(String curAddress) {
        this.curAddress = curAddress;
    }

    
    @Column(name="phone_no", length=40)
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="mobile_no", length=40)
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    
    @Column(name="fax_no", length=40)
    public String getFaxNo() {
        return this.faxNo;
    }
    
    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="move_on_date", length=29)
    public Date getMoveOnDate() {
        return this.moveOnDate;
    }
    
    public void setMoveOnDate(Date moveOnDate) {
        this.moveOnDate = moveOnDate;
    }

    
    @Column(name="move_by", length=20)
    public String getMoveBy() {
        return this.moveBy;
    }
    
    public void setMoveBy(String moveBy) {
        this.moveBy = moveBy;
    }

    
    @Column(name="move_ip", length=20)
    public String getMoveIp() {
        return this.moveIp;
    }
    
    public void setMoveIp(String moveIp) {
        this.moveIp = moveIp;
    }
}


