package app.model;
// Generated 8 Jan, 2021 2:58:04 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.ParseException;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.format.annotation.DateTimeFormat;

import app.bean.pfms.PfmsInvoiceProject;
import app.janbhagidariPratiyogita.JanbhagidariPratiyogita;
import app.model.master.IwmpMWc;
import app.model.master.PfmsEatmisdataDetail;
import app.model.outcome.FpoMain;
import app.model.outcome.GroundwaterMain;
import app.model.outcome.LivelihoodEpaProd;
import app.model.outcome.ShgMain;
import app.model.project.IwmpProjectLocation;
import app.model.project.IwmpProjectPhysicalAap;
import app.model.project.WdcpmksyProjectPhysicalAchievement;
import app.model.project.WdcpmksyProjectPhysicalAchievementDetails;
import app.projectevaluation.model.WdcpmksyProjectProfileEvaluation;
import app.model.project.IwmpProjectPhysicalAsset;
import app.model.project.IwmpProjectPhysicalAssetTemp;
import app.model.project.IwmpProjectPhysicalPlan;
import app.model.project.IwmpProjectPrepare;
import app.model.project.WdcpmksyBaselineupdateAchievement;
import app.model.project.WdcpmksyEpaWorkid;
import app.model.project.WdcpmksyLivelihoodWorkid;
import app.model.project.WdcpmksyOutcomeTarget;
import app.model.project.WdcpmksyPrdouctionWorkid;

/**
 * IwmpMProject generated by hbm2java
 */
@Entity
@Table(name = "iwmp_m_project", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "project_cd"))
public class IwmpMProject implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int projectId;
	
	@NotNull(message = "Please Select District.")
	@Valid
	private IwmpDistrict iwmpDistrict;
	@Valid
	private IwmpMAreaType iwmpMAreaType;
	private IwmpMCsShare iwmpMCsShare;
	@Valid
	private IwmpMFinYear iwmpMFinYear;
	
	private IwmpMFinYear projectSanctionYr;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_sanction_yr")
	public IwmpMFinYear getProjectSanctionYr() {
		return projectSanctionYr;
	}

	public void setProjectSanctionYr(IwmpMFinYear projectSanctionYr) {
		this.projectSanctionYr = projectSanctionYr;
	}
	
	
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private Date projectSanctionDt;

	@Temporal(TemporalType.DATE)
	@Column(name = "project_sanction_dt", length = 13)
	public Date getProjectSanctionDt() {
		return projectSanctionDt;
	}

	public void setProjectSanctionDt(Date projectSanctionDt) {
		this.projectSanctionDt = projectSanctionDt;
	}

	@Valid
	private IwmpMProjectPrd iwmpMProjectPrd;
	private String projectCd;
	private String projName;
	@NotNull(message = "Please Enter Area.")
	private BigDecimal areaProposed;
	@NotNull(message = "Please Enter Project Cost.")
	private BigDecimal projectCost;

	@NotNull(message = "Please Enter Central Share Amount.")
	private BigDecimal centralShareAmt;

	@NotNull(message = "Please Enter State Share Amount.")
	private BigDecimal stateShareAmt;
	// private String projectStatus;
	private String createdBy;
	private Date createdDt;
	private BigDecimal centralRelAmt;
	private BigDecimal stateRelAmt;
	private String lstCentralInstlNo;
	private String lstCentralInstlType;
	private String lstStateInstlNo;
	private String lstStateInstlType;
	private BigDecimal centralShareRecSlna;
	private BigDecimal centralShareDistSlna;
	private BigDecimal stateShareRecSlna;
	private BigDecimal stateShareDistSlna;
	private BigDecimal centralShareRecWcdc;
	private BigDecimal stateShareRecWcdc;
	private BigDecimal totShrDistWcdcToPia;
	private BigDecimal totShrDistWcdcToGp;
	private BigDecimal totShrDistWcdcToWc;
	private BigDecimal totShrRecPiaOfWcdc;
	private BigDecimal totShrRecGpOfWcdc;
	private BigDecimal totShrRecWcOfWcdc;
	private BigDecimal totShrDistPiaToGp;
	private BigDecimal totShrDistPiaToWc;
	private BigDecimal totShrRecGpOfPia;
	private BigDecimal totShrRecWcOfPia;
	private BigDecimal totShrDistGpToWc;
	private BigDecimal totShrRecWcOfGp;
	private Character actFlag;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private String isplanvillagewise;
	@NotNull(message = "Please Enter Project Sanction Date.")
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private Date projectStartDt;
	private Date projectEndDt;
	@NotNull(message = "Please Enter Project Sequence.")
	private Integer projectSeqNo;
	private String projNameOld;
	// private String closed;
	private String dpr;
	// private Character status;
	private Character phaseUpdateMis;
	private String remarks;
	private Character neeranchalProject;
	private Set<Outcome2Data> outcome2Datas = new HashSet<Outcome2Data>(0);
	private Set<IwmpUserProjectMap> iwmpUserProjectMaps = new HashSet<IwmpUserProjectMap>(0);
	private Set<IwmpMWc> iwmpMWcs = new HashSet<IwmpMWc>(0);
	private Set<IwmpProjectLocation> iwmpProjectLocations = new HashSet<IwmpProjectLocation>(0);

	private Set<IwmpProjectPrepare> projectPrepares = new HashSet<IwmpProjectPrepare>(0);
	private Set<IwmpProjectPhysicalPlan> iwmpProjectPhysicalPlans = new HashSet<IwmpProjectPhysicalPlan>(0);
	private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
	private Character status;
	private String projectStatus;
	private Character projectPhase;
	private Set<IwmpProjectAssetStatus> iwmpProjectAssetStatuses = new HashSet<IwmpProjectAssetStatus>(0);
	//private Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses = new HashSet<WdcpmksyProjectPhysicalAchievementDetails>(0);
    private Set<WdcpmksyProjectPhysicalAchievement> wdcpmksyProjectPhysicalAchievements = new HashSet<WdcpmksyProjectPhysicalAchievement>(0);
    private Set<WdcpmksyOutcomeTarget> wdcpmksyOutcomeTargets = new HashSet<WdcpmksyOutcomeTarget>(0);
    private Set<GroundwaterMain> groundwaterMains = new HashSet<GroundwaterMain>(0);
    private Set<ShgMain> shgMains = new HashSet<ShgMain>(0);
    private Set<LivelihoodEpaProd> livelihoodEpaProds = new HashSet<LivelihoodEpaProd>(0);
    private Set<FpoMain> fpoMains = new HashSet<FpoMain>(0);
    private Set<BaseLineSurveyMain> baseLineSurveyMains = new HashSet<BaseLineSurveyMain>(0);
    private Set<BlsOutMain> blsOutMains = new HashSet<BlsOutMain>(0);
    private Set<PfmsInvoiceProject> pfmsInvoiceProjects = new HashSet<PfmsInvoiceProject>(0);
    private Set<IwmpActPlan> iwmpActPlans = new HashSet<IwmpActPlan>(0);
    private Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets = new HashSet<IwmpProjectPhysicalAsset>(0);
 //   private Set<WdcpmksyConvergenceDetail> convergenceDetails = new HashSet<>(0);
    private Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails = new HashSet<PfmsEatmisdataDetail>(0);
    private Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids = new HashSet<WdcpmksyLivelihoodWorkid>(0);
    private Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids = new HashSet<WdcpmksyPrdouctionWorkid>(0);
    private Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids = new HashSet<WdcpmksyEpaWorkid>(0);
    private Set<WdcpmksyBaselineupdateAchievement> wdcpmksyBaselineupdateAchievements = new HashSet<WdcpmksyBaselineupdateAchievement>(0);
    private Set<WdcpmksyProjectProfileEvaluation> wdcpmksyProjectProfileEvaluation = new HashSet<WdcpmksyProjectProfileEvaluation>(0); 
    private Set<JanbhagidariPratiyogita> janbhagidariPratiyogita = new HashSet<JanbhagidariPratiyogita>(0);
    
    
    
	@Transient
	private boolean updatestatus;

	@Transient
	public boolean getUpdatestatus() {
		return updatestatus;
	}

	public void setUpdatestatus(boolean updatestatus) {
		this.updatestatus = updatestatus;
	}

	public IwmpMProject() {
	}

	public IwmpMProject(int projId, String projectCd) {
		this.projectId = projId;
		this.projectCd = projectCd;
	}

	 

	public IwmpMProject(int projId, IwmpDistrict iwmpDistrict, IwmpMAreaType iwmpMAreaType, IwmpMCsShare iwmpMCsShare,
			IwmpMFinYear iwmpMFinYear, IwmpMProjectPrd iwmpMProjectPrd, String projectCd, String projName,
			BigDecimal areaProposed, BigDecimal projectCost, BigDecimal centralShareAmt, BigDecimal stateShareAmt,
			Character status, String createdBy, Date createdDt, BigDecimal centralRelAmt, BigDecimal stateRelAmt,
			String lstCentralInstlNo, String lstCentralInstlType, String lstStateInstlNo, String lstStateInstlType,
			BigDecimal centralShareRecSlna, BigDecimal centralShareDistSlna, BigDecimal stateShareRecSlna,
			BigDecimal stateShareDistSlna, BigDecimal centralShareRecWcdc, BigDecimal stateShareRecWcdc,
			BigDecimal totShrDistWcdcToPia, BigDecimal totShrDistWcdcToGp, BigDecimal totShrDistWcdcToWc,
			BigDecimal totShrRecPiaOfWcdc, BigDecimal totShrRecGpOfWcdc, BigDecimal totShrRecWcOfWcdc,
			BigDecimal totShrDistPiaToGp, BigDecimal totShrDistPiaToWc, BigDecimal totShrRecGpOfPia,
			BigDecimal totShrRecWcOfPia, BigDecimal totShrDistGpToWc, BigDecimal totShrRecWcOfGp, Character actFlag,
			String lastUpdatedBy, Date lastUpdatedDate, String requestIp, String isplanvillagewise, Date projectStartDt,
			Date projectEndDt, Integer projectSeqNo, String projNameOld, String projectStatus, String dpr, Character projectPhase,
			Character phaseUpdateMis, String remarks, Character neeranchalProject, Set<Outcome2Data> outcome2Datas,
			Set<GroundwaterMain> groundwaterMains, Set<ShgMain> shgMains, Set<LivelihoodEpaProd> livelihoodEpaProds,
			Set<FpoMain> fpoMains, Set<PfmsInvoiceProject> pfmsInvoiceProjects, Set<IwmpActPlan> iwmpActPlans, 
			Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails, Set<WdcpmksyBaselineupdateAchievement> wdcpmksyBaselineupdateAchievements,
			Set<JanbhagidariPratiyogita> janbhagidariPratiyogita) {
	       this.projectId = projId;
	       this.iwmpDistrict = iwmpDistrict;
	       this.iwmpMAreaType = iwmpMAreaType;
	       this.iwmpMCsShare = iwmpMCsShare;
	       this.iwmpMFinYear = iwmpMFinYear;
	       this.iwmpMProjectPrd = iwmpMProjectPrd;
	       this.projectCd = projectCd;
	       this.projName = projName;
	       this.areaProposed = areaProposed;
	       this.projectCost = projectCost;
	       this.centralShareAmt = centralShareAmt;
	       this.stateShareAmt = stateShareAmt;
	       this.status = status;
	       this.createdBy = createdBy;
	       this.createdDt = createdDt;
	       this.centralRelAmt = centralRelAmt;
	       this.stateRelAmt = stateRelAmt;
	       this.lstCentralInstlNo = lstCentralInstlNo;
	       this.lstCentralInstlType = lstCentralInstlType;
	       this.lstStateInstlNo = lstStateInstlNo;
	       this.lstStateInstlType = lstStateInstlType;
	       this.centralShareRecSlna = centralShareRecSlna;
	       this.centralShareDistSlna = centralShareDistSlna;
	       this.stateShareRecSlna = stateShareRecSlna;
	       this.stateShareDistSlna = stateShareDistSlna;
	       this.centralShareRecWcdc = centralShareRecWcdc;
	       this.stateShareRecWcdc = stateShareRecWcdc;
	       this.totShrDistWcdcToPia = totShrDistWcdcToPia;
	       this.totShrDistWcdcToGp = totShrDistWcdcToGp;
	       this.totShrDistWcdcToWc = totShrDistWcdcToWc;
	       this.totShrRecPiaOfWcdc = totShrRecPiaOfWcdc;
	       this.totShrRecGpOfWcdc = totShrRecGpOfWcdc;
	       this.totShrRecWcOfWcdc = totShrRecWcOfWcdc;
	       this.totShrDistPiaToGp = totShrDistPiaToGp;
	       this.totShrDistPiaToWc = totShrDistPiaToWc;
	       this.totShrRecGpOfPia = totShrRecGpOfPia;
	       this.totShrRecWcOfPia = totShrRecWcOfPia;
	       this.totShrDistGpToWc = totShrDistGpToWc;
	       this.totShrRecWcOfGp = totShrRecWcOfGp;
	       this.actFlag = actFlag;
	       this.lastUpdatedBy = lastUpdatedBy;
	       this.lastUpdatedDate = lastUpdatedDate;
	       this.requestIp = requestIp;
	       this.isplanvillagewise = isplanvillagewise;
	       this.projectStartDt = projectStartDt;
	       this.projectEndDt = projectEndDt;
	       this.projectSeqNo = projectSeqNo;
	       this.projNameOld = projNameOld;
	       this.projectStatus = projectStatus;
	       this.dpr = dpr;
	       this.projectPhase = projectPhase;
	       this.phaseUpdateMis = phaseUpdateMis;
	       this.remarks = remarks;
	       this.neeranchalProject = neeranchalProject;
	       this.outcome2Datas = outcome2Datas;
	       this.groundwaterMains = groundwaterMains;
	       this.shgMains = shgMains;
	       this.livelihoodEpaProds = livelihoodEpaProds;
	       this.fpoMains = fpoMains;
	       this.pfmsInvoiceProjects=pfmsInvoiceProjects;
	       this.iwmpActPlans = iwmpActPlans;
	    //   this.convergenceDetails = convergenceDetails;
	       this.pfmsEatmisdataDetails = pfmsEatmisdataDetails;
	       this.wdcpmksyBaselineupdateAchievements=wdcpmksyBaselineupdateAchievements;
	       this.janbhagidariPratiyogita=janbhagidariPratiyogita;
	    }

	@Id
	@Column(name = "proj_id", unique = true, nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projId) {
		this.projectId = projId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "area_cd")
	public IwmpMAreaType getIwmpMAreaType() {
		return this.iwmpMAreaType;
	}

	public void setIwmpMAreaType(IwmpMAreaType iwmpMAreaType) {
		this.iwmpMAreaType = iwmpMAreaType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sharingid")
	public IwmpMCsShare getIwmpMCsShare() {
		return this.iwmpMCsShare;
	}

	public void setIwmpMCsShare(IwmpMCsShare iwmpMCsShare) {
		this.iwmpMCsShare = iwmpMCsShare;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fin_yr_cd")
	public IwmpMFinYear getIwmpMFinYear() {
		return this.iwmpMFinYear;
	}

	public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
		this.iwmpMFinYear = iwmpMFinYear;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "dcode")
	public IwmpDistrict getIwmpDistrict() {
		return this.iwmpDistrict;
	}

	public void setIwmpDistrict(IwmpDistrict iwmpDistrict) {
		this.iwmpDistrict = iwmpDistrict;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_prd")
	public IwmpMProjectPrd getIwmpMProjectPrd() {
		return this.iwmpMProjectPrd;
	}

	public void setIwmpMProjectPrd(IwmpMProjectPrd iwmpMProjectPrd) {
		this.iwmpMProjectPrd = iwmpMProjectPrd;
	}

	@Column(name = "project_cd", unique = true, nullable = false, length = 50)
	public String getProjectCd() {
		return this.projectCd;
	}

	public void setProjectCd(String projectCd) {
		this.projectCd = projectCd;
	}

	@Column(name = "proj_name", length = 100)
	public String getProjName() {
		return this.projName;
	}

	public void setProjName(String projName) {
		this.projName = projName;
	}

	@Column(name = "area_proposed", precision = 12)
	public BigDecimal getAreaProposed() {
		return this.areaProposed;
	}

	public void setAreaProposed(BigDecimal areaProposed) {
		this.areaProposed = areaProposed;
	}

	@Column(name = "project_cost", precision = 15, scale = 2)
	public BigDecimal getProjectCost() {
		return this.projectCost;
	}

	public void setProjectCost(BigDecimal projectCost) {
		this.projectCost = projectCost;
	}

	@Column(name = "central_share_amt", precision = 15, scale = 2)
	public BigDecimal getCentralShareAmt() {
		return this.centralShareAmt;
	}

	public void setCentralShareAmt(BigDecimal centralShareAmt) {
		this.centralShareAmt = centralShareAmt;
	}

	@Column(name = "state_share_amt", precision = 15, scale = 2)
	public BigDecimal getStateShareAmt() {
		return this.stateShareAmt;
	}

	public void setStateShareAmt(BigDecimal stateShareAmt) {
		this.stateShareAmt = stateShareAmt;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_dt", length = 29)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "central_rel_amt", precision = 15, scale = 5)
	public BigDecimal getCentralRelAmt() {
		return this.centralRelAmt;
	}

	public void setCentralRelAmt(BigDecimal centralRelAmt) {
		this.centralRelAmt = centralRelAmt;
	}

	@Column(name = "state_rel_amt", precision = 15, scale = 5)
	public BigDecimal getStateRelAmt() {
		return this.stateRelAmt;
	}

	public void setStateRelAmt(BigDecimal stateRelAmt) {
		this.stateRelAmt = stateRelAmt;
	}

	@Column(name = "lst_central_instl_no", length = 10)
	public String getLstCentralInstlNo() {
		return this.lstCentralInstlNo;
	}

	public void setLstCentralInstlNo(String lstCentralInstlNo) {
		this.lstCentralInstlNo = lstCentralInstlNo;
	}

	@Column(name = "lst_central_instl_type", length = 10)
	public String getLstCentralInstlType() {
		return this.lstCentralInstlType;
	}

	public void setLstCentralInstlType(String lstCentralInstlType) {
		this.lstCentralInstlType = lstCentralInstlType;
	}

	@Column(name = "lst_state_instl_no", length = 10)
	public String getLstStateInstlNo() {
		return this.lstStateInstlNo;
	}

	public void setLstStateInstlNo(String lstStateInstlNo) {
		this.lstStateInstlNo = lstStateInstlNo;
	}

	@Column(name = "lst_state_instl_type", length = 10)
	public String getLstStateInstlType() {
		return this.lstStateInstlType;
	}

	public void setLstStateInstlType(String lstStateInstlType) {
		this.lstStateInstlType = lstStateInstlType;
	}

	@Column(name = "central_share_rec_slna", precision = 15, scale = 5)
	public BigDecimal getCentralShareRecSlna() {
		return this.centralShareRecSlna;
	}

	public void setCentralShareRecSlna(BigDecimal centralShareRecSlna) {
		this.centralShareRecSlna = centralShareRecSlna;
	}

	@Column(name = "central_share_dist_slna", precision = 15, scale = 5)
	public BigDecimal getCentralShareDistSlna() {
		return this.centralShareDistSlna;
	}

	public void setCentralShareDistSlna(BigDecimal centralShareDistSlna) {
		this.centralShareDistSlna = centralShareDistSlna;
	}

	@Column(name = "state_share_rec_slna", precision = 15, scale = 5)
	public BigDecimal getStateShareRecSlna() {
		return this.stateShareRecSlna;
	}

	public void setStateShareRecSlna(BigDecimal stateShareRecSlna) {
		this.stateShareRecSlna = stateShareRecSlna;
	}

	@Column(name = "state_share_dist_slna", precision = 15, scale = 5)
	public BigDecimal getStateShareDistSlna() {
		return this.stateShareDistSlna;
	}

	public void setStateShareDistSlna(BigDecimal stateShareDistSlna) {
		this.stateShareDistSlna = stateShareDistSlna;
	}

	@Column(name = "central_share_rec_wcdc", precision = 15, scale = 5)
	public BigDecimal getCentralShareRecWcdc() {
		return this.centralShareRecWcdc;
	}

	public void setCentralShareRecWcdc(BigDecimal centralShareRecWcdc) {
		this.centralShareRecWcdc = centralShareRecWcdc;
	}

	@Column(name = "state_share_rec_wcdc", precision = 15, scale = 5)
	public BigDecimal getStateShareRecWcdc() {
		return this.stateShareRecWcdc;
	}

	public void setStateShareRecWcdc(BigDecimal stateShareRecWcdc) {
		this.stateShareRecWcdc = stateShareRecWcdc;
	}

	@Column(name = "tot_shr_dist_wcdc_to_pia", precision = 15, scale = 5)
	public BigDecimal getTotShrDistWcdcToPia() {
		return this.totShrDistWcdcToPia;
	}

	public void setTotShrDistWcdcToPia(BigDecimal totShrDistWcdcToPia) {
		this.totShrDistWcdcToPia = totShrDistWcdcToPia;
	}

	@Column(name = "tot_shr_dist_wcdc_to_gp", precision = 15, scale = 5)
	public BigDecimal getTotShrDistWcdcToGp() {
		return this.totShrDistWcdcToGp;
	}

	public void setTotShrDistWcdcToGp(BigDecimal totShrDistWcdcToGp) {
		this.totShrDistWcdcToGp = totShrDistWcdcToGp;
	}

	@Column(name = "tot_shr_dist_wcdc_to_wc", precision = 15, scale = 5)
	public BigDecimal getTotShrDistWcdcToWc() {
		return this.totShrDistWcdcToWc;
	}

	public void setTotShrDistWcdcToWc(BigDecimal totShrDistWcdcToWc) {
		this.totShrDistWcdcToWc = totShrDistWcdcToWc;
	}

	@Column(name = "tot_shr_rec_pia_of_wcdc", precision = 15, scale = 5)
	public BigDecimal getTotShrRecPiaOfWcdc() {
		return this.totShrRecPiaOfWcdc;
	}

	public void setTotShrRecPiaOfWcdc(BigDecimal totShrRecPiaOfWcdc) {
		this.totShrRecPiaOfWcdc = totShrRecPiaOfWcdc;
	}

	@Column(name = "tot_shr_rec_gp_of_wcdc", precision = 15, scale = 5)
	public BigDecimal getTotShrRecGpOfWcdc() {
		return this.totShrRecGpOfWcdc;
	}

	public void setTotShrRecGpOfWcdc(BigDecimal totShrRecGpOfWcdc) {
		this.totShrRecGpOfWcdc = totShrRecGpOfWcdc;
	}

	@Column(name = "tot_shr_rec_wc_of_wcdc", precision = 15, scale = 5)
	public BigDecimal getTotShrRecWcOfWcdc() {
		return this.totShrRecWcOfWcdc;
	}

	public void setTotShrRecWcOfWcdc(BigDecimal totShrRecWcOfWcdc) {
		this.totShrRecWcOfWcdc = totShrRecWcOfWcdc;
	}

	@Column(name = "tot_shr_dist_pia_to_gp", precision = 15, scale = 5)
	public BigDecimal getTotShrDistPiaToGp() {
		return this.totShrDistPiaToGp;
	}

	public void setTotShrDistPiaToGp(BigDecimal totShrDistPiaToGp) {
		this.totShrDistPiaToGp = totShrDistPiaToGp;
	}

	@Column(name = "tot_shr_dist_pia_to_wc", precision = 15, scale = 5)
	public BigDecimal getTotShrDistPiaToWc() {
		return this.totShrDistPiaToWc;
	}

	public void setTotShrDistPiaToWc(BigDecimal totShrDistPiaToWc) {
		this.totShrDistPiaToWc = totShrDistPiaToWc;
	}

	@Column(name = "tot_shr_rec_gp_of_pia", precision = 15, scale = 5)
	public BigDecimal getTotShrRecGpOfPia() {
		return this.totShrRecGpOfPia;
	}

	public void setTotShrRecGpOfPia(BigDecimal totShrRecGpOfPia) {
		this.totShrRecGpOfPia = totShrRecGpOfPia;
	}

	@Column(name = "tot_shr_rec_wc_of_pia", precision = 15, scale = 5)
	public BigDecimal getTotShrRecWcOfPia() {
		return this.totShrRecWcOfPia;
	}

	public void setTotShrRecWcOfPia(BigDecimal totShrRecWcOfPia) {
		this.totShrRecWcOfPia = totShrRecWcOfPia;
	}

	@Column(name = "tot_shr_dist_gp_to_wc", precision = 15, scale = 5)
	public BigDecimal getTotShrDistGpToWc() {
		return this.totShrDistGpToWc;
	}

	public void setTotShrDistGpToWc(BigDecimal totShrDistGpToWc) {
		this.totShrDistGpToWc = totShrDistGpToWc;
	}

	@Column(name = "tot_shr_rec_wc_of_gp", precision = 15, scale = 5)
	public BigDecimal getTotShrRecWcOfGp() {
		return this.totShrRecWcOfGp;
	}

	public void setTotShrRecWcOfGp(BigDecimal totShrRecWcOfGp) {
		this.totShrRecWcOfGp = totShrRecWcOfGp;
	}

	@Column(name = "act_flag", length = 1)
	public Character getActFlag() {
		return this.actFlag;
	}

	public void setActFlag(Character actFlag) {
		this.actFlag = actFlag;
	}

	@Column(name = "last_updated_by", length = 25)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@UpdateTimestamp
	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "isplanvillagewise", length = 1)
	public String getIsplanvillagewise() {
		return this.isplanvillagewise;
	}

	public void setIsplanvillagewise(String isplanvillagewise) {
		this.isplanvillagewise = isplanvillagewise;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "project_start_dt", length = 13)
	public Date getProjectStartDt() throws ParseException {

//		Date javaDate = projectStartDt;
//		try {
//			if (this.projectStartDt != null) {
//				SimpleDateFormat sdfrmt = new SimpleDateFormat("MM/dd/yyyy");
//				javaDate = sdfrmt.parse(this.projectStartDt.toString());
//			}
//		} catch (ParseException ex) {
//
//		}
		return this.projectStartDt;
	}

	public void setProjectStartDt(Date projectStartDt) {
		this.projectStartDt = projectStartDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "project_end_dt", length = 13)
	public Date getProjectEndDt() {
		return this.projectEndDt;
	}

	public void setProjectEndDt(Date projectEndDt) {
		this.projectEndDt = projectEndDt;
	}

	@Column(name = "project_seq_no", precision = 131089, scale = 0)
	public Integer getProjectSeqNo() {
		return this.projectSeqNo;
	}

	public void setProjectSeqNo(Integer projectSeqNo) {
		this.projectSeqNo = projectSeqNo;
	}

	@Column(name = "proj_name_old", length = 100)
	public String getProjNameOld() {
		return this.projNameOld;
	}

	public void setProjNameOld(String projNameOld) {
		this.projNameOld = projNameOld;
	}


	@Column(name = "dpr", length = 10)
	public String getDpr() {
		return this.dpr;
	}

	public void setDpr(String dpr) {
		this.dpr = dpr;
	}


	@Column(name = "phase_update_mis", length = 1)
	public Character getPhaseUpdateMis() {
		return this.phaseUpdateMis;
	}

	public void setPhaseUpdateMis(Character phaseUpdateMis) {
		this.phaseUpdateMis = phaseUpdateMis;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "neeranchal_project", length = 1)
	public Character getNeeranchalProject() {
		return this.neeranchalProject;
	}

	public void setNeeranchalProject(Character neeranchalProject) {
		this.neeranchalProject = neeranchalProject;
	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<Outcome2Data> getOutcome2Datas() {
        return this.outcome2Datas;
    }
    
    public void setOutcome2Datas(Set<Outcome2Data> outcome2Datas) {
        this.outcome2Datas = outcome2Datas;
    }
	@OneToMany(mappedBy = "iwmpMProject")
	public Set<IwmpUserProjectMap> getIwmpUserProjectMaps() {
		return this.iwmpUserProjectMaps;
	}

	public void setIwmpUserProjectMaps(Set<IwmpUserProjectMap> iwmpUserProjectMaps) {
		this.iwmpUserProjectMaps = iwmpUserProjectMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpMProject")
	public Set<IwmpMWc> getIwmpMWcs() {
		return this.iwmpMWcs;
	}

	public void setIwmpMWcs(Set<IwmpMWc> iwmpMWcs) {
		this.iwmpMWcs = iwmpMWcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpMProject")
	public Set<IwmpProjectLocation> getIwmpProjectLocations() {
		return this.iwmpProjectLocations;
	}

	public void setIwmpProjectLocations(Set<IwmpProjectLocation> iwmpProjectLocations) {
		this.iwmpProjectLocations = iwmpProjectLocations;
	}

	// fetch=FetchType.LAZY,
	// mappedBy="iwmpMenu",cascade=CascadeType.REMOVE,orphanRemoval = true
	@OneToMany(mappedBy = "iwmpMProject", cascade = CascadeType.REMOVE, orphanRemoval = true)
	public Set<IwmpProjectPrepare> getProjectPrepares() {
		return this.projectPrepares;
	}

	public void setProjectPrepares(Set<IwmpProjectPrepare> projectPrepares) {
		this.projectPrepares = projectPrepares;
	}

	@OneToMany(mappedBy = "iwmpMProject")
	public Set<IwmpProjectPhysicalPlan> getIwmpProjectPhysicalPlans() {
		return this.iwmpProjectPhysicalPlans;
	}

	public void setIwmpProjectPhysicalPlans(Set<IwmpProjectPhysicalPlan> iwmpProjectPhysicalPlans) {
		this.iwmpProjectPhysicalPlans = iwmpProjectPhysicalPlans;
	}
	  
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    @Column(name="project_status", length=20)
    public String getProjectStatus() {
        return this.projectStatus;
    }
    
    public void setProjectStatus(String projectStatus) {
        this.projectStatus = projectStatus;
    }
    @Column(name="project_phase", length=1)
    public Character getProjectPhase() {
        return this.projectPhase;
    }
    
    public void setProjectPhase(Character projectPhase) {
        this.projectPhase = projectPhase;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<IwmpProjectPhysicalAsset> getIwmpProjectPhysicalAssets() {
        return this.iwmpProjectPhysicalAssets;
    }
    
    public void setIwmpProjectPhysicalAssets(Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets) {
        this.iwmpProjectPhysicalAssets = iwmpProjectPhysicalAssets;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemp() {
        return this.iwmpProjectPhysicalAssetTemp;
    }
    
    public void setIwmpProjectPhysicalAssetTemp(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp) {
        this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<IwmpProjectAssetStatus> getIwmpProjectAssetStatuses() {
        return this.iwmpProjectAssetStatuses;
    }
    
    public void setIwmpProjectAssetStatuses(Set<IwmpProjectAssetStatus> iwmpProjectAssetStatuses) {
        this.iwmpProjectAssetStatuses = iwmpProjectAssetStatuses;
    }
    
	/*
	 * @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject") public
	 * Set<WdcpmksyProjectPhysicalAchievementDetails>
	 * getWdcpmksyProjectPhysicalAchievementDetailses() { return
	 * this.wdcpmksyProjectPhysicalAchievementDetailses; }
	 * 
	 * public void setWdcpmksyProjectPhysicalAchievementDetailses(Set<
	 * WdcpmksyProjectPhysicalAchievementDetails>
	 * wdcpmksyProjectPhysicalAchievementDetailses) {
	 * this.wdcpmksyProjectPhysicalAchievementDetailses =
	 * wdcpmksyProjectPhysicalAchievementDetailses; }
	 */

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<WdcpmksyProjectPhysicalAchievement> getWdcpmksyProjectPhysicalAchievements() {
        return this.wdcpmksyProjectPhysicalAchievements;
    }
    
    public void setWdcpmksyProjectPhysicalAchievements(Set<WdcpmksyProjectPhysicalAchievement> wdcpmksyProjectPhysicalAchievements) {
        this.wdcpmksyProjectPhysicalAchievements = wdcpmksyProjectPhysicalAchievements;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<WdcpmksyOutcomeTarget> getWdcpmksyOutcomeTargets() {
        return this.wdcpmksyOutcomeTargets;
    }
    
    public void setWdcpmksyOutcomeTargets(Set<WdcpmksyOutcomeTarget> wdcpmksyOutcomeTargets) {
        this.wdcpmksyOutcomeTargets = wdcpmksyOutcomeTargets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<GroundwaterMain> getGroundwaterMains() {
        return this.groundwaterMains;
    }
    
    public void setGroundwaterMains(Set<GroundwaterMain> groundwaterMains) {
        this.groundwaterMains = groundwaterMains;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<ShgMain> getShgMains() {
        return this.shgMains;
    }
    
    public void setShgMains(Set<ShgMain> shgMains) {
        this.shgMains = shgMains;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<LivelihoodEpaProd> getLivelihoodEpaProds() {
        return this.livelihoodEpaProds;
    }
    
    public void setLivelihoodEpaProds(Set<LivelihoodEpaProd> livelihoodEpaProds) {
        this.livelihoodEpaProds = livelihoodEpaProds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<FpoMain> getFpoMains() {
        return this.fpoMains;
    }
    
    public void setFpoMains(Set<FpoMain> fpoMains) {
        this.fpoMains = fpoMains;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<BaseLineSurveyMain> getBaseLineSurveyMains() {
        return this.baseLineSurveyMains;
    }
    
    public void setBaseLineSurveyMains(Set<BaseLineSurveyMain> baseLineSurveyMains) {
        this.baseLineSurveyMains = baseLineSurveyMains;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<BlsOutMain> getBlsOutMains() {
        return this.blsOutMains;
    }
    
    public void setBlsOutMains(Set<BlsOutMain> blsOutMains) {
        this.blsOutMains = blsOutMains;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<PfmsInvoiceProject> getPfmsInvoiceProjects() {
        return this.pfmsInvoiceProjects;
    }
    
    public void setPfmsInvoiceProjects(Set<PfmsInvoiceProject> pfmsInvoiceProjects) {
        this.pfmsInvoiceProjects = pfmsInvoiceProjects;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
   	public Set<IwmpActPlan> getIwmpActPlans() {
   		return iwmpActPlans;
   	}

   	public void setIwmpActPlans(Set<IwmpActPlan> iwmpActPlans) {
   		this.iwmpActPlans = iwmpActPlans;
   	}

	/*
	 * @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject") public
	 * Set<WdcpmksyConvergenceDetail> getConvergenceDetails() { return
	 * convergenceDetails; }
	 * 
	 * public void setConvergenceDetails(Set<WdcpmksyConvergenceDetail>
	 * convergenceDetails) { this.convergenceDetails = convergenceDetails; }
	 */
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<PfmsEatmisdataDetail> getPfmsEatmisdataDetails() {
        return this.pfmsEatmisdataDetails;
    }
    
    public void setPfmsEatmisdataDetails(Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails) {
        this.pfmsEatmisdataDetails = pfmsEatmisdataDetails;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<WdcpmksyLivelihoodWorkid> getWdcpmksyLivelihoodWorkids() {
        return this.wdcpmksyLivelihoodWorkids;
    }
    
    public void setWdcpmksyLivelihoodWorkids(Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids) {
        this.wdcpmksyLivelihoodWorkids = wdcpmksyLivelihoodWorkids;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<WdcpmksyPrdouctionWorkid> getWdcpmksyPrdouctionWorkids() {
        return this.wdcpmksyPrdouctionWorkids;
    }
    
    public void setWdcpmksyPrdouctionWorkids(Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids) {
        this.wdcpmksyPrdouctionWorkids = wdcpmksyPrdouctionWorkids;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
    public Set<WdcpmksyEpaWorkid> getWdcpmksyEpaWorkids() {
        return this.wdcpmksyEpaWorkids;
    }
    
    public void setWdcpmksyEpaWorkids(Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids) {
        this.wdcpmksyEpaWorkids = wdcpmksyEpaWorkids;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
	public Set<WdcpmksyBaselineupdateAchievement> getWdcpmksyBaselineupdateAchievements() {
		return wdcpmksyBaselineupdateAchievements;
	}

	public void setWdcpmksyBaselineupdateAchievements(
			Set<WdcpmksyBaselineupdateAchievement> wdcpmksyBaselineupdateAchievements) {
		this.wdcpmksyBaselineupdateAchievements = wdcpmksyBaselineupdateAchievements;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
	public Set<WdcpmksyProjectProfileEvaluation> getWdcpmksyProjectProfileEvaluation() {
		return wdcpmksyProjectProfileEvaluation;
	}

	public void setWdcpmksyProjectProfileEvaluation(
			Set<WdcpmksyProjectProfileEvaluation> wdcpmksyProjectProfileEvaluation) {
		this.wdcpmksyProjectProfileEvaluation = wdcpmksyProjectProfileEvaluation;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProject")
	public Set<JanbhagidariPratiyogita> getJanbhagidariPratiyogita() {
		return janbhagidariPratiyogita;
	}

	public void setJanbhagidariPratiyogita(Set<JanbhagidariPratiyogita> janbhagidariPratiyogita) {
		this.janbhagidariPratiyogita = janbhagidariPratiyogita;
	}
    
    
    
    
    

}
