package app.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IwmpActPlan generated by hbm2java
 */
@Entity
@Table(name="iwmp_act_plan"
    ,schema="public"
)
public class IwmpActPlan  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int actPlanId;
     private IwmpDistrict iwmpDistrict;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMProject iwmpMProject;
     private String authName;
     private String requestIp;
     private Date createdDt;
     private String createdBy;
     private Character status;
     private Character dprStatus;

    public IwmpActPlan() {
    }

	
    public IwmpActPlan(int actPlanId, IwmpDistrict iwmpDistrict, IwmpMProject iwmpMProject) {
        this.actPlanId = actPlanId;
        this.iwmpDistrict = iwmpDistrict;
        this.iwmpMProject = iwmpMProject;
    }
    public IwmpActPlan(int actPlanId, IwmpDistrict iwmpDistrict, IwmpMFinYear iwmpMFinYear, IwmpMProject iwmpMProject, String authName, String requestIp, Date createdDt, String createdBy, Character status, Character dprStatus) {
       this.actPlanId = actPlanId;
       this.iwmpDistrict = iwmpDistrict;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMProject = iwmpMProject;
       this.authName = authName;
       this.requestIp = requestIp;
       this.createdDt = createdDt;
       this.createdBy = createdBy;
       this.status = status;
       this.dprStatus = dprStatus;
    }
   
	@Id   
    @Column(name="act_plan_id", unique=true, nullable=false)
    public int getActPlanId() {
        return this.actPlanId;
    }
    
    public void setActPlanId(int actPlanId) {
        this.actPlanId = actPlanId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dcode", nullable=false)
    public IwmpDistrict getIwmpDistrict() {
        return this.iwmpDistrict;
    }
    
    public void setIwmpDistrict(IwmpDistrict iwmpDistrict) {
        this.iwmpDistrict = iwmpDistrict;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proj_id", nullable=false)
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="auth_name", length=100)
    public String getAuthName() {
        return this.authName;
    }
    
    public void setAuthName(String authName) {
        this.authName = authName;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_dt", length=29)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }
    
    @Column(name="dpr_status", length=1)
    public Character getDprStatus() {
		return dprStatus;
	}

	public void setDprStatus(Character dprStatus) {
		this.dprStatus = dprStatus;
	}





}
