package  app.model;
// Generated 13 Nov, 2020 1:53:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;

/**
 * IwmpMAreaType generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_area_type"
    ,schema="public"
)
public class IwmpMAreaType  implements java.io.Serializable {


	 @Min(value = 1, message = "Select Area Type") 
	 private int areaCd;
     private String areaDesc;
     private BigDecimal areaValue;
     private Character actFlag;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Set<IwmpMProject> iwmpMProjects = new HashSet<IwmpMProject>(0);

    public IwmpMAreaType() {
    }

	
    public IwmpMAreaType(int areaCd) {
        this.areaCd = areaCd;
    }
    public IwmpMAreaType(int areaCd, String areaDesc, BigDecimal areaValue, Character actFlag, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Set<IwmpMProject> iwmpMProjects) {
       this.areaCd = areaCd;
       this.areaDesc = areaDesc;
       this.areaValue = areaValue;
       this.actFlag = actFlag;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.iwmpMProjects = iwmpMProjects;
    }
   
     @Id 

    
    @Column(name="area_cd", unique=true, nullable=false)
    public int getAreaCd() {
        return this.areaCd;
    }
    
    public void setAreaCd(int areaCd) {
        this.areaCd = areaCd;
    }

    
    @Column(name="area_desc", length=9)
    public String getAreaDesc() {
        return this.areaDesc;
    }
    
    public void setAreaDesc(String areaDesc) {
        this.areaDesc = areaDesc;
    }

    
    @Column(name="area_value", precision=131089, scale=0)
    public BigDecimal getAreaValue() {
        return this.areaValue;
    }
    
    public void setAreaValue(BigDecimal areaValue) {
        this.areaValue = areaValue;
    }

    
    @Column(name="act_flag", length=1)
    public Character getActFlag() {
        return this.actFlag;
    }
    
    public void setActFlag(Character actFlag) {
        this.actFlag = actFlag;
    }

    
    @Column(name="created_by", length=25)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_date", length=13)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="last_updated_by", length=25)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(mappedBy="iwmpMAreaType")
    public Set<IwmpMProject> getIwmpMProjects() {
        return this.iwmpMProjects;
    }
    
    public void setIwmpMProjects(Set<IwmpMProject> iwmpMProjects) {
        this.iwmpMProjects = iwmpMProjects;
    }




}


