package app.model;
// Generated 12 Mar, 2021 11:11:23 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.janbhagidariPratiyogita.JanbhagidariPratiyogita;
import app.janbhagidariPratiyogita.JanbhagidariPratiyogitaTypeofWork;
import app.model.PfmsCgireceiptDetaildata;
import app.model.PfmsTreasuryreceiptDetaildata;
import app.model.master.PfmsEatmisdataDetail;
import app.model.master.SlnaStProfile;
import app.model.master.WdcpmksyMPhyOtherActivity;
import app.model.outcome.GroundwaterMain;
import app.model.project.IwmpApprovelLevel;
import app.watershedyatra.model.NodalOfficer;
import app.watershedyatra.model.PreYatraPreparation;
import app.watershedyatra.model.WatershedYatVill;
import app.watershedyatra.model.WatershedYatraInauguaration;
import app.watershedyatra.model.RoutePlanVanTravel;

/**
 * IwmpState generated by hbm2java
 */
@Entity
@Table(name = "iwmp_state")
public class IwmpState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int stCode;
	private int wdcpmksy;
	private String stName;
	private Long ddp;
	private Long dpap;
	private Long iwdp;
	private String northEast;
	private String payee;
	private String payeeofficer;
	private String payeecode;
	private String stCapital;
	private BigDecimal iwmp;
	private Character importType;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private Character isvillagewise;
	private String stateCode2001;
	private String stateCode2011;
	private String censusCodePortedData;
	private Character approvalReq;
	private Date approvalReqDate;
	private String stateCodelgd;
	private String lgdCodePortedData;
	private BigDecimal jalShakati;
	private Set<IwmpDistrict> iwmpDistricts = new HashSet<IwmpDistrict>(0);
	private List<UserMap> userMap;
	private Set<IwmpApprovelLevel> iwmpApprovelLevels = new HashSet<IwmpApprovelLevel>(0);
	private SlnaStProfile slnaStProfile;
	private Set<IwmpMCsShare> iwmpMCsShares = new HashSet<IwmpMCsShare>(0);
	 private Set<PfmsTreasuryreceiptDetaildata> pfmsTreasuryreceiptDetaildatas = new HashSet<PfmsTreasuryreceiptDetaildata>(0);
     private Set<PfmsCgireceiptDetaildata> pfmsCgireceiptDetaildatas = new HashSet<PfmsCgireceiptDetaildata>(0);
     private Set<PfmsEatmisdataDetail> pfmsEatmisdataDetailsForStateLgdCode = new HashSet<PfmsEatmisdataDetail>(0);
     private Set<PfmsEatmisdataDetail> pfmsEatmisdataDetailsForStCode = new HashSet<PfmsEatmisdataDetail>(0);
     private Set<WdcpmksyMPhyOtherActivity> wdcpmksyMPhyOtherActivities = new HashSet<WdcpmksyMPhyOtherActivity>(0);
     private Set<GetGoiReleaseToStateTreasury> getGoiReleaseToStateTreasury = new HashSet<GetGoiReleaseToStateTreasury>(0);
     private Set<NodalOfficer> nodalOfficer = new HashSet<NodalOfficer>(0);
	private Set<WatershedYatVill> watershedYatVill = new HashSet<WatershedYatVill>(0);
     private Set<WatershedYatraInauguaration> WatershedYatraInauguaration = new HashSet<WatershedYatraInauguaration>(0);
	private Set<RoutePlanVanTravel> routePlanVanTravel = new HashSet<RoutePlanVanTravel>(0);
	private Set<PreYatraPreparation> preYatraPreparation = new HashSet<PreYatraPreparation>(0);
	private Set<JanbhagidariPratiyogita> janbhagidariPratiyogita = new HashSet<JanbhagidariPratiyogita>(0);
	private Set<JanbhagidariPratiyogitaTypeofWork> janbhagidariPratiyogitaTypeofWork = new HashSet<JanbhagidariPratiyogitaTypeofWork>(0);
	
     
	public IwmpState() {
	}

	public IwmpState(int stCode, String stName) {
		this.stCode = stCode;
		this.stName = stName;
	}

	public IwmpState(int stCode, String stName, Long ddp, Long dpap, Long iwdp, String northEast, String payee,
			String payeeofficer, String payeecode, String stCapital, BigDecimal iwmp, Character importType, int wdcpmksy,
			String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Character isvillagewise, String stateCode2001,
			String stateCode2011, String censusCodePortedData, Character approvalReq, Date approvalReqDate,
			String stateCodelgd, String lgdCodePortedData, BigDecimal jalShakati, Set<IwmpDistrict> iwmpDistricts,
			Set<IwmpApprovelLevel> iwmpApprovelLevels, Set<PfmsTreasuryreceiptDetaildata> pfmsTreasuryreceiptDetaildatas, 
			Set<PfmsCgireceiptDetaildata> pfmsCgireceiptDetaildatas, Set<PfmsEatmisdataDetail> pfmsEatmisdataDetailsForStateLgdCode, 
			Set<PfmsEatmisdataDetail> pfmsEatmisdataDetailsForStCode, Set<WdcpmksyMPhyOtherActivity> wdcpmksyMPhyOtherActivities,
			Set<GetGoiReleaseToStateTreasury> getGoiReleaseToStateTreasury, Set<NodalOfficer> nodalOfficer, 
			Set<WatershedYatraInauguaration> WatershedYatraInauguaration, Set<WatershedYatVill> watershedYatVill, Set<PreYatraPreparation>preYatraPreparation,Set<RoutePlanVanTravel> routePlanVanTravel,
			Set<JanbhagidariPratiyogita> janbhagidariPratiyogita, Set<JanbhagidariPratiyogitaTypeofWork> janbhagidariPratiyogitaTypeofWork) {
		this.stCode = stCode;
		this.iwmpApprovelLevels = iwmpApprovelLevels;
		this.stName = stName;
		this.ddp = ddp;
		this.dpap = dpap;
		this.iwdp = iwdp;
		this.northEast = northEast;
		this.payee = payee;
		this.payeeofficer = payeeofficer;
		this.payeecode = payeecode;
		this.stCapital = stCapital;
		this.iwmp = iwmp;
		this.importType = importType;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
		this.isvillagewise = isvillagewise;
		this.stateCode2001 = stateCode2001;
		this.stateCode2011 = stateCode2011;
		this.censusCodePortedData = censusCodePortedData;
		this.approvalReq = approvalReq;
		this.approvalReqDate = approvalReqDate;
		this.stateCodelgd = stateCodelgd;
		this.lgdCodePortedData = lgdCodePortedData;
		this.jalShakati = jalShakati;
		this.iwmpDistricts = iwmpDistricts;
		this.wdcpmksy = wdcpmksy;
		this.pfmsTreasuryreceiptDetaildatas = pfmsTreasuryreceiptDetaildatas;
	    this.pfmsCgireceiptDetaildatas = pfmsCgireceiptDetaildatas;
	    this.pfmsEatmisdataDetailsForStateLgdCode = pfmsEatmisdataDetailsForStateLgdCode;
	    this.pfmsEatmisdataDetailsForStCode = pfmsEatmisdataDetailsForStCode;
	    this.wdcpmksyMPhyOtherActivities = wdcpmksyMPhyOtherActivities;
	    this.getGoiReleaseToStateTreasury = getGoiReleaseToStateTreasury;
	    this.nodalOfficer=nodalOfficer;
	    this.WatershedYatraInauguaration=WatershedYatraInauguaration;
	    this.watershedYatVill=watershedYatVill;
	    this.routePlanVanTravel=routePlanVanTravel;
	    this.preYatraPreparation=preYatraPreparation;
	    this.janbhagidariPratiyogita=janbhagidariPratiyogita;
	    this.janbhagidariPratiyogitaTypeofWork=janbhagidariPratiyogitaTypeofWork;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "st_code", unique = true, nullable = false)
	public int getStCode() {
		return this.stCode;
	}

	public void setStCode(int stCode) {
		this.stCode = stCode;
	}

	@Column(name = "st_name", nullable = false, length = 100)
	public String getStName() {
		return this.stName;
	}

	public void setStName(String stName) {
		this.stName = stName;
	}

	@Column(name = "ddp", precision = 11, scale = 0)
	public Long getDdp() {
		return this.ddp;
	}

	public void setDdp(Long ddp) {
		this.ddp = ddp;
	}

	@Column(name = "dpap", precision = 11, scale = 0)
	public Long getDpap() {
		return this.dpap;
	}

	public void setDpap(Long dpap) {
		this.dpap = dpap;
	}

	@Column(name = "iwdp", precision = 11, scale = 0)
	public Long getIwdp() {
		return this.iwdp;
	}

	public void setIwdp(Long iwdp) {
		this.iwdp = iwdp;
	}

	@Column(name = "north_east", length = 100)
	public String getNorthEast() {
		return this.northEast;
	}

	public void setNorthEast(String northEast) {
		this.northEast = northEast;
	}

	@Column(name = "payee", length = 500)
	public String getPayee() {
		return this.payee;
	}

	public void setPayee(String payee) {
		this.payee = payee;
	}

	@Column(name = "payeeofficer", length = 100)
	public String getPayeeofficer() {
		return this.payeeofficer;
	}

	public void setPayeeofficer(String payeeofficer) {
		this.payeeofficer = payeeofficer;
	}

	@Column(name = "payeecode", length = 100)
	public String getPayeecode() {
		return this.payeecode;
	}

	public void setPayeecode(String payeecode) {
		this.payeecode = payeecode;
	}

	@Column(name = "st_capital", length = 100)
	public String getStCapital() {
		return this.stCapital;
	}

	public void setStCapital(String stCapital) {
		this.stCapital = stCapital;
	}

	@Column(name = "iwmp", precision = 131089, scale = 0)
	public BigDecimal getIwmp() {
		return this.iwmp;
	}

	public void setIwmp(BigDecimal iwmp) {
		this.iwmp = iwmp;
	}

	
	@Column(name = "wdcpmksy", nullable = false)
	public int getWdcpmksy() {
		return wdcpmksy;
	}

	public void setWdcpmksy(int wdcpmksy) {
		this.wdcpmksy = wdcpmksy;
	}
	
	@Column(name = "import_type", length = 1)
	public Character getImportType() {
		return this.importType;
	}

	public void setImportType(Character importType) {
		this.importType = importType;
	}

	@Column(name = "last_updated_by", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "isvillagewise", length = 1)
	public Character getIsvillagewise() {
		return this.isvillagewise;
	}

	public void setIsvillagewise(Character isvillagewise) {
		this.isvillagewise = isvillagewise;
	}

	@Column(name = "state_code2001", length = 200)
	public String getStateCode2001() {
		return this.stateCode2001;
	}

	public void setStateCode2001(String stateCode2001) {
		this.stateCode2001 = stateCode2001;
	}

	@Column(name = "state_code2011", length = 200)
	public String getStateCode2011() {
		return this.stateCode2011;
	}

	public void setStateCode2011(String stateCode2011) {
		this.stateCode2011 = stateCode2011;
	}

	@Column(name = "census_code_ported_data", length = 1)
	public String getCensusCodePortedData() {
		return this.censusCodePortedData;
	}

	public void setCensusCodePortedData(String censusCodePortedData) {
		this.censusCodePortedData = censusCodePortedData;
	}

	@Column(name = "approval_req", length = 1)
	public Character getApprovalReq() {
		return this.approvalReq;
	}

	public void setApprovalReq(Character approvalReq) {
		this.approvalReq = approvalReq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approval_req_date", length = 13)
	public Date getApprovalReqDate() {
		return this.approvalReqDate;
	}

	public void setApprovalReqDate(Date approvalReqDate) {
		this.approvalReqDate = approvalReqDate;
	}

	@Column(name = "state_codelgd", length = 200)
	public String getStateCodelgd() {
		return this.stateCodelgd;
	}

	public void setStateCodelgd(String stateCodelgd) {
		this.stateCodelgd = stateCodelgd;
	}

	@Column(name = "lgd_code_ported_data", length = 1)
	public String getLgdCodePortedData() {
		return this.lgdCodePortedData;
	}

	public void setLgdCodePortedData(String lgdCodePortedData) {
		this.lgdCodePortedData = lgdCodePortedData;
	}

	@Column(name = "jal_shakati", precision = 1, scale = 1)
	public BigDecimal getJalShakati() {
		return this.jalShakati;
	}

	public void setJalShakati(BigDecimal jalShakati) {
		this.jalShakati = jalShakati;
	}

	@OneToMany(mappedBy = "iwmpState",fetch = FetchType.LAZY)
	public Set<IwmpDistrict> getIwmpDistricts() {
		return this.iwmpDistricts;
	}

	public void setIwmpDistricts(Set<IwmpDistrict> iwmpDistricts) {
		this.iwmpDistricts = iwmpDistricts;
	}

	@OneToMany(mappedBy = "iwmpState",fetch = FetchType.LAZY)
	public List<UserMap> getUserMap() {
		return this.userMap;
	}

	public void setUserMap(List<UserMap> userMap) {
		this.userMap = userMap;
	}

	@OneToMany(mappedBy = "iwmpState",fetch = FetchType.LAZY)
	public Set<IwmpApprovelLevel> getIwmpApprovelLevels() {
		return this.iwmpApprovelLevels;
	}

	public void setIwmpApprovelLevels(Set<IwmpApprovelLevel> iwmpApprovelLevels) {
		this.iwmpApprovelLevels = iwmpApprovelLevels;
	}
	
	@OneToOne(fetch=FetchType.LAZY, mappedBy="iwmpState")
    public SlnaStProfile getSlnaStProfile() {
        return this.slnaStProfile;
    }
    
    public void setSlnaStProfile(SlnaStProfile slnaStProfile) {
        this.slnaStProfile = slnaStProfile;
    }

//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "iwmpStates")
//	public Set<IwmpDolrSupport> getIwmpDolrSupports() {
//		return this.iwmpDolrSupports;
//	}
//
//	public void setIwmpDolrSupports(Set<IwmpDolrSupport> iwmpDolrSupports) {
//		this.iwmpDolrSupports = iwmpDolrSupports;
//	}

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
    public Set<IwmpMCsShare> getIwmpMCsShares() {
        return this.iwmpMCsShares;
    }
    
    public void setIwmpMCsShares(Set<IwmpMCsShare> iwmpMCsShares) {
        this.iwmpMCsShares = iwmpMCsShares;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
    public Set<PfmsTreasuryreceiptDetaildata> getPfmsTreasuryreceiptDetaildatas() {
        return this.pfmsTreasuryreceiptDetaildatas;
    }
    
    public void setPfmsTreasuryreceiptDetaildatas(Set<PfmsTreasuryreceiptDetaildata> pfmsTreasuryreceiptDetaildatas) {
        this.pfmsTreasuryreceiptDetaildatas = pfmsTreasuryreceiptDetaildatas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
    public Set<PfmsCgireceiptDetaildata> getPfmsCgireceiptDetaildatas() {
        return this.pfmsCgireceiptDetaildatas;
    }
    
    public void setPfmsCgireceiptDetaildatas(Set<PfmsCgireceiptDetaildata> pfmsCgireceiptDetaildatas) {
        this.pfmsCgireceiptDetaildatas = pfmsCgireceiptDetaildatas;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpStateByStateLgdCode")
    public Set<PfmsEatmisdataDetail> getPfmsEatmisdataDetailsForStateLgdCode() {
        return this.pfmsEatmisdataDetailsForStateLgdCode;
    }
    
    public void setPfmsEatmisdataDetailsForStateLgdCode(Set<PfmsEatmisdataDetail> pfmsEatmisdataDetailsForStateLgdCode) {
        this.pfmsEatmisdataDetailsForStateLgdCode = pfmsEatmisdataDetailsForStateLgdCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpStateByStCode")
    public Set<PfmsEatmisdataDetail> getPfmsEatmisdataDetailsForStCode() {
        return this.pfmsEatmisdataDetailsForStCode;
    }
    
    public void setPfmsEatmisdataDetailsForStCode(Set<PfmsEatmisdataDetail> pfmsEatmisdataDetailsForStCode) {
        this.pfmsEatmisdataDetailsForStCode = pfmsEatmisdataDetailsForStCode;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
    public Set<WdcpmksyMPhyOtherActivity> getWdcpmksyMPhyOtherActivities() {
        return this.wdcpmksyMPhyOtherActivities;
    }
    
    public void setWdcpmksyMPhyOtherActivities(Set<WdcpmksyMPhyOtherActivity> wdcpmksyMPhyOtherActivities) {
        this.wdcpmksyMPhyOtherActivities = wdcpmksyMPhyOtherActivities;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpStateByStCode")
	public Set<GetGoiReleaseToStateTreasury> getGetGoiReleaseToStateTreasury() {
		return getGoiReleaseToStateTreasury;
	}

	public void setGetGoiReleaseToStateTreasury(Set<GetGoiReleaseToStateTreasury> getGoiReleaseToStateTreasury) {
		this.getGoiReleaseToStateTreasury = getGoiReleaseToStateTreasury;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<NodalOfficer> getNodalOfficer() {
		return nodalOfficer;
	}

	public void setNodalOfficer(Set<NodalOfficer> nodalOfficer) {
		this.nodalOfficer = nodalOfficer;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<WatershedYatraInauguaration> getWatershedYatraInauguaration() {
		return WatershedYatraInauguaration;
	}

	public void setWatershedYatraInauguaration(Set<WatershedYatraInauguaration> watershedYatraInauguaration) {
		this.WatershedYatraInauguaration = watershedYatraInauguaration;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<WatershedYatVill> getWatershedYatVill() {
		return watershedYatVill;
	}

	public void setWatershedYatVill(Set<WatershedYatVill> watershedYatVill) {
		this.watershedYatVill = watershedYatVill;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<RoutePlanVanTravel> getRoutePlanVanTravel() {
		return routePlanVanTravel;
	}

	public void setRoutePlanVanTravel(Set<RoutePlanVanTravel> routePlanVanTravel) {
		this.routePlanVanTravel = routePlanVanTravel;
	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<PreYatraPreparation> getPreYatraPreparation() {
		return preYatraPreparation;
	}

	public void setPreYatraPreparation(Set<PreYatraPreparation> preYatraPreparation) {
		this.preYatraPreparation = preYatraPreparation;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<JanbhagidariPratiyogita> getJanbhagidariPratiyogita() {
		return janbhagidariPratiyogita;
	}

	public void setJanbhagidariPratiyogita(Set<JanbhagidariPratiyogita> janbhagidariPratiyogita) {
		this.janbhagidariPratiyogita = janbhagidariPratiyogita;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpState")
	public Set<JanbhagidariPratiyogitaTypeofWork> getJanbhagidariPratiyogitaTypeofWork() {
		return janbhagidariPratiyogitaTypeofWork;
	}

	public void setJanbhagidariPratiyogitaTypeofWork(
			Set<JanbhagidariPratiyogitaTypeofWork> janbhagidariPratiyogitaTypeofWork) {
		this.janbhagidariPratiyogitaTypeofWork = janbhagidariPratiyogitaTypeofWork;
	}
	
	
	
	
	
	
	
	
    
}
