package app.model;
// Generated 05-Apr-2022, 3:02:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MBlsOutcome generated by hbm2java
 */
@Entity
@Table(name="m_bls_outcome"
    ,schema="public"
)
public class MBlsOutcome  implements java.io.Serializable {


	private int MBlsOutIdPk;
    private MBlsOutType MBlsOutType;
    private String description;
    private BigDecimal seqNo;
    private Date createdOn;
    private Date updatedOn;
    private String requestIp;
    private String createdBy;
    private Set<BlsOutDetailCrop> blsOutDetailTranxesForCropTypeId = new HashSet<BlsOutDetailCrop>(0);
    private Set<BlsOutDetailCrop> blsOutDetailTranxesForSeasonId = new HashSet<BlsOutDetailCrop>(0);
    private Set<BlsOutDetail> blsOutDetailsForOwnershipId = new HashSet<BlsOutDetail>(0);
    private Set<BlsOutDetail> blsOutDetailsForNoOfCropId = new HashSet<BlsOutDetail>(0);
    private Set<BlsOutDetail> blsOutDetailsForClassificationLandId = new HashSet<BlsOutDetail>(0);
    private Set<BlsOutDetail> blsOutDetailsForForestLandTypeId = new HashSet<BlsOutDetail>(0);
    private Set<BlsOutMain> blsOutMainsForIrrigationStatusId = new HashSet<BlsOutMain>(0);

   public MBlsOutcome() {
   }

	
   public MBlsOutcome(int MBlsOutIdPk) {
       this.MBlsOutIdPk = MBlsOutIdPk;
   }
   public MBlsOutcome(int MBlsOutIdPk, MBlsOutType MBlsOutType, String description, BigDecimal seqNo, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<BlsOutDetailCrop> blsOutDetailTranxesForCropTypeId, Set<BlsOutDetailCrop> blsOutDetailTranxesForSeasonId, Set<BlsOutDetail> blsOutDetailsForOwnershipId, Set<BlsOutDetail> blsOutDetailsForNoOfCropId, Set<BlsOutDetail> blsOutDetailsForClassificationLandId, Set<BlsOutDetail> blsOutDetailsForForestLandTypeId, Set<BlsOutMain> blsOutMainsForIrrigationStatusId) {
      this.MBlsOutIdPk = MBlsOutIdPk;
      this.MBlsOutType = MBlsOutType;
      this.description = description;
      this.seqNo = seqNo;
      this.createdOn = createdOn;
      this.updatedOn = updatedOn;
      this.requestIp = requestIp;
      this.createdBy = createdBy;
      this.blsOutDetailTranxesForCropTypeId = blsOutDetailTranxesForCropTypeId;
      this.blsOutDetailTranxesForSeasonId = blsOutDetailTranxesForSeasonId;
      this.blsOutDetailsForOwnershipId = blsOutDetailsForOwnershipId;
      this.blsOutDetailsForNoOfCropId = blsOutDetailsForNoOfCropId;
      this.blsOutDetailsForClassificationLandId = blsOutDetailsForClassificationLandId;
      this.blsOutDetailsForForestLandTypeId = blsOutDetailsForForestLandTypeId;
      this.blsOutMainsForIrrigationStatusId = blsOutMainsForIrrigationStatusId;
   }
  
    @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
   @Column(name="m_bls_out_id_pk", unique=true, nullable=false)
   public int getMBlsOutIdPk() {
       return this.MBlsOutIdPk;
   }
   
   public void setMBlsOutIdPk(int MBlsOutIdPk) {
       this.MBlsOutIdPk = MBlsOutIdPk;
   }

@ManyToOne(fetch=FetchType.EAGER)
   @JoinColumn(name="type_id")
   public MBlsOutType getMBlsOutType() {
       return this.MBlsOutType;
   }
   
   public void setMBlsOutType(MBlsOutType MBlsOutType) {
       this.MBlsOutType = MBlsOutType;
   }

   
   @Column(name="description", length=100)
   public String getDescription() {
       return this.description;
   }
   
   public void setDescription(String description) {
       this.description = description;
   }

   
   @Column(name="seq_no", precision=10)
   public BigDecimal getSeqNo() {
       return this.seqNo;
   }
   
   public void setSeqNo(BigDecimal seqNo) {
       this.seqNo = seqNo;
   }

   @Temporal(TemporalType.DATE)
   @Column(name="created_on", length=13)
   public Date getCreatedOn() {
       return this.createdOn;
   }
   
   public void setCreatedOn(Date createdOn) {
       this.createdOn = createdOn;
   }

   @Temporal(TemporalType.DATE)
   @Column(name="updated_on", length=13)
   public Date getUpdatedOn() {
       return this.updatedOn;
   }
   
   public void setUpdatedOn(Date updatedOn) {
       this.updatedOn = updatedOn;
   }

   
   @Column(name="request_ip", length=20)
   public String getRequestIp() {
       return this.requestIp;
   }
   
   public void setRequestIp(String requestIp) {
       this.requestIp = requestIp;
   }

   
   @Column(name="created_by", length=20)
   public String getCreatedBy() {
       return this.createdBy;
   }
   
   public void setCreatedBy(String createdBy) {
       this.createdBy = createdBy;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeByCropTypeId")
   public Set<BlsOutDetailCrop> getBlsOutDetailTranxesForCropTypeId() {
       return this.blsOutDetailTranxesForCropTypeId;
   }
   
   public void setBlsOutDetailTranxesForCropTypeId(Set<BlsOutDetailCrop> blsOutDetailTranxesForCropTypeId) {
       this.blsOutDetailTranxesForCropTypeId = blsOutDetailTranxesForCropTypeId;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeBySeasonId")
   public Set<BlsOutDetailCrop> getBlsOutDetailTranxesForSeasonId() {
       return this.blsOutDetailTranxesForSeasonId;
   }
   
   public void setBlsOutDetailTranxesForSeasonId(Set<BlsOutDetailCrop> blsOutDetailTranxesForSeasonId) {
       this.blsOutDetailTranxesForSeasonId = blsOutDetailTranxesForSeasonId;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeByOwnershipId")
   public Set<BlsOutDetail> getBlsOutDetailsForOwnershipId() {
       return this.blsOutDetailsForOwnershipId;
   }
   
   public void setBlsOutDetailsForOwnershipId(Set<BlsOutDetail> blsOutDetailsForOwnershipId) {
       this.blsOutDetailsForOwnershipId = blsOutDetailsForOwnershipId;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeByNoOfCropId")
   public Set<BlsOutDetail> getBlsOutDetailsForNoOfCropId() {
       return this.blsOutDetailsForNoOfCropId;
   }
   
   public void setBlsOutDetailsForNoOfCropId(Set<BlsOutDetail> blsOutDetailsForNoOfCropId) {
       this.blsOutDetailsForNoOfCropId = blsOutDetailsForNoOfCropId;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeByClassificationLandId")
   public Set<BlsOutDetail> getBlsOutDetailsForClassificationLandId() {
       return this.blsOutDetailsForClassificationLandId;
   }
   
   public void setBlsOutDetailsForClassificationLandId(Set<BlsOutDetail> blsOutDetailsForClassificationLandId) {
       this.blsOutDetailsForClassificationLandId = blsOutDetailsForClassificationLandId;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeByForestLandTypeId")
   public Set<BlsOutDetail> getBlsOutDetailsForForestLandTypeId() {
       return this.blsOutDetailsForForestLandTypeId;
   }
   
   public void setBlsOutDetailsForForestLandTypeId(Set<BlsOutDetail> blsOutDetailsForForestLandTypeId) {
       this.blsOutDetailsForForestLandTypeId = blsOutDetailsForForestLandTypeId;
   }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutcomeByIrrigationStatusId")
   public Set<BlsOutMain> getBlsOutMainsForIrrigationStatusId() {
       return this.blsOutMainsForIrrigationStatusId;
   }
   
   public void setBlsOutMainsForIrrigationStatusId(Set<BlsOutMain> blsOutMainsForIrrigationStatusId) {
       this.blsOutMainsForIrrigationStatusId = blsOutMainsForIrrigationStatusId;
   }



}


