package app.model;
// Generated 05-Apr-2022, 3:02:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MBlsOutType generated by hbm2java
 */
@Entity
@Table(name="m_bls_out_type"
    ,schema="public"
)
public class MBlsOutType  implements java.io.Serializable {


     private int MBlsOutTypeIdPk;
     private String typeCode;
     private String description;
     private BigDecimal seqNo;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Set<MBlsOutcome> MBlsOutcomes = new HashSet<MBlsOutcome>(0);

    public MBlsOutType() {
    }

	
    public MBlsOutType(int MBlsOutTypeIdPk) {
        this.MBlsOutTypeIdPk = MBlsOutTypeIdPk;
    }
    public MBlsOutType(int MBlsOutTypeIdPk, String typeCode, String description, BigDecimal seqNo, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<MBlsOutcome> MBlsOutcomes) {
       this.MBlsOutTypeIdPk = MBlsOutTypeIdPk;
       this.typeCode = typeCode;
       this.description = description;
       this.seqNo = seqNo;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.MBlsOutcomes = MBlsOutcomes;
    }
   
     @Id 

    
    @Column(name="m_bls_out_type_id_pk", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getMBlsOutTypeIdPk() {
        return this.MBlsOutTypeIdPk;
    }
    
    public void setMBlsOutTypeIdPk(int MBlsOutTypeIdPk) {
        this.MBlsOutTypeIdPk = MBlsOutTypeIdPk;
    }

    
    @Column(name="type_code", length=20)
    public String getTypeCode() {
        return this.typeCode;
    }
    
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="seq_no", precision=10)
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MBlsOutType")
    public Set<MBlsOutcome> getMBlsOutcomes() {
        return this.MBlsOutcomes;
    }
    
    public void setMBlsOutcomes(Set<MBlsOutcome> MBlsOutcomes) {
        this.MBlsOutcomes = MBlsOutcomes;
    }




}


