package app.model;
// Generated 4 May, 2022 11:13:42 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.outcome.FpoDetail;
import app.model.outcome.ShgDetail;
/**
 * MDepartmentScheme generated by hbm2java
 */
@Entity
@Table(name="m_department_scheme" ,schema="public")

public class MDepartmentScheme  implements java.io.Serializable {


     private int departmentSchemeIdPk;
     private String schemeDescription;
     private String types;
     private BigDecimal seqNo;
     private Boolean status;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Set<ShgDetail> shgDetails = new HashSet<ShgDetail>(0);
     private Set<FpoDetail> fpoDetails = new HashSet<FpoDetail>(0);

    public MDepartmentScheme() {
    }

	
    public MDepartmentScheme(int departmentSchemeIdPk) {
        this.departmentSchemeIdPk = departmentSchemeIdPk;
    }

   
    public MDepartmentScheme(int departmentSchemeIdPk, String schemeDescription, String type, BigDecimal seqNo, Boolean status, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<ShgDetail> shgDetails, Set<FpoDetail> fpoDetails) {

       this.departmentSchemeIdPk = departmentSchemeIdPk;
       this.schemeDescription = schemeDescription;
       this.types=type;
       this.seqNo = seqNo;
       this.status = status;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.shgDetails = shgDetails;
       this.fpoDetails = fpoDetails;
    }
   
    @Id 
    @Column(name="department_scheme_id_pk", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getDepartmentSchemeIdPk() {
        return this.departmentSchemeIdPk;
    }
    
    public void setDepartmentSchemeIdPk(int departmentSchemeIdPk) {
        this.departmentSchemeIdPk = departmentSchemeIdPk;
    }

    @Column(name="scheme_description", length=100)
    public String getSchemeDescription() {
        return this.schemeDescription;
    }
    
    public void setSchemeDescription(String schemeDescription) {
        this.schemeDescription = schemeDescription;
    }

    @Column(name="scheme_type", length=20)
    public String getTypes() {
		return types;
	}


	public void setTypes(String types) {
		this.types = types;
	}


	@Column(name="seq_no", precision=10)
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MDepartmentScheme")
    public Set<ShgDetail> getShgDetails() {
        return this.shgDetails;
    }
    
    public void setShgDetails(Set<ShgDetail> shgDetails) {
        this.shgDetails = shgDetails;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MDepartmentScheme")
    public Set<FpoDetail> getFpoDetails() {
        return this.fpoDetails;
    }
    
    public void setFpoDetails(Set<FpoDetail> fpoDetails) {
        this.fpoDetails = fpoDetails;
    }
}


