package app.model;
// Generated 8 Jun, 2022 3:11:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Outcome2Data generated by hbm2java
 */
@Entity
@Table(name="outcome_2_data"
    ,schema="public"
)
public class Outcome2Data  implements java.io.Serializable {


     private int outcome2Id;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMMonth iwmpMMonth;
     private IwmpMProject iwmpMProject;
     private Long manDayGen;
     private Long farmerSc;
     private Long farmerSt;
     private Long farmerFemale;
     private Long farmerSmall;
     private Long farmerMirginal;
     private Long farmerLandless;
     private Long others;
     private Long farmerBpl;
     private Character status;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private String updatedBy;
     private BigDecimal degraded_rainfed;
     
    public Outcome2Data() {
    }

	
    public Outcome2Data(int outcome2Id) {
        this.outcome2Id = outcome2Id;
    }
    public Outcome2Data(int outcome2Id, IwmpMFinYear iwmpMFinYear, IwmpMMonth iwmpMMonth, IwmpMProject iwmpMProject, Long manDayGen, BigDecimal degraded_rainfed,  Long farmerSc, Long farmerSt, Long farmerFemale, Long farmerSmall, Long farmerMirginal, Long farmerLandless, Long others, Long farmerBpl, Character status, Date createdOn, Date updatedOn, String requestIp, String createdBy, String updatedBy) {
       this.outcome2Id = outcome2Id;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMMonth = iwmpMMonth;
       this.iwmpMProject = iwmpMProject;
       this.manDayGen = manDayGen;
       this.degraded_rainfed = degraded_rainfed;
       this.farmerSc = farmerSc;
       this.farmerSt = farmerSt;
       this.farmerFemale = farmerFemale;
       this.farmerSmall = farmerSmall;
       this.farmerMirginal = farmerMirginal;
       this.farmerLandless = farmerLandless;
       this.others = others;
       this.farmerBpl = farmerBpl;
       this.status = status;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="outcome2_id", unique=true, nullable=false)
    public int getOutcome2Id() {
        return this.outcome2Id;
    }
    
    public void setOutcome2Id(int outcome2Id) {
        this.outcome2Id = outcome2Id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="month_id")
    public IwmpMMonth getIwmpMMonth() {
        return this.iwmpMMonth;
    }
    
    public void setIwmpMMonth(IwmpMMonth iwmpMMonth) {
        this.iwmpMMonth = iwmpMMonth;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="man_day_gen", precision=10, scale=0)
    public Long getManDayGen() {
        return this.manDayGen;
    }
    
    public void setManDayGen(Long manDayGen) {
        this.manDayGen = manDayGen;
    }
 
    
   @Column(name="degraded_rainfed")
	public BigDecimal getDegraded_rainfed() {
		return degraded_rainfed;
	}


	public void setDegraded_rainfed(BigDecimal degraded_rainfed) {
		this.degraded_rainfed = degraded_rainfed;
	}


	@Column(name="farmer_sc", precision=10, scale=0)
    public Long getFarmerSc() {
        return this.farmerSc;
    }
    
    public void setFarmerSc(Long farmerSc) {
        this.farmerSc = farmerSc;
    }

    
    @Column(name="farmer_st", precision=10, scale=0)
    public Long getFarmerSt() {
        return this.farmerSt;
    }
    
    public void setFarmerSt(Long farmerSt) {
        this.farmerSt = farmerSt;
    }

    
    @Column(name="farmer_female", precision=10, scale=0)
    public Long getFarmerFemale() {
        return this.farmerFemale;
    }
    
    public void setFarmerFemale(Long farmerFemale) {
        this.farmerFemale = farmerFemale;
    }

    
    @Column(name="farmer_small", precision=10, scale=0)
    public Long getFarmerSmall() {
        return this.farmerSmall;
    }
    
    public void setFarmerSmall(Long farmerSmall) {
        this.farmerSmall = farmerSmall;
    }

    
    @Column(name="farmer_mirginal", precision=10, scale=0)
    public Long getFarmerMirginal() {
        return this.farmerMirginal;
    }
    
    public void setFarmerMirginal(Long farmerMirginal) {
        this.farmerMirginal = farmerMirginal;
    }

    
    @Column(name="farmer_landless", precision=10, scale=0)
    public Long getFarmerLandless() {
        return this.farmerLandless;
    }
    
    public void setFarmerLandless(Long farmerLandless) {
        this.farmerLandless = farmerLandless;
    }
    
    
    @Column(name="others", precision=10, scale=0)
    public Long getOthers() {
		return this.others;
	}


	public void setOthers(Long others) {
		this.others = others;
	}


	@Column(name="farmer_bpl", precision=10, scale=0)
    public Long getFarmerBpl() {
        return this.farmerBpl;
    }
    
    public void setFarmerBpl(Long farmerBpl) {
        this.farmerBpl = farmerBpl;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="updated_by", length=20)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }




}



