package app.model;


//Generated Nov 3, 2022, 12:37:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpState;

/**
* PfmsCgireceiptDetaildata generated by hbm2java
*/
@Entity
@Table(name="pfms_cgireceipt_detaildata")
public class PfmsCgireceiptDetaildata  implements java.io.Serializable {


  private int cgireceiptdetaildataId;
  private IwmpState iwmpState;
  private String financialYear;
  private String sanctionNo;
  private String transactionId;
  private Date transactionDate;
  private BigDecimal totalAmount;
  private String apiresponsestatus;
  private Date createdOn;

 public PfmsCgireceiptDetaildata() {
 }

	
 public PfmsCgireceiptDetaildata(int cgireceiptdetaildataId) {
     this.cgireceiptdetaildataId = cgireceiptdetaildataId;
 }
 public PfmsCgireceiptDetaildata(int cgireceiptdetaildataId, IwmpState iwmpState, String financialYear, String sanctionNo, String transactionId, Date transactionDate, BigDecimal totalAmount, String apiresponsestatus, Date createdOn) {
    this.cgireceiptdetaildataId = cgireceiptdetaildataId;
    this.iwmpState = iwmpState;
    this.financialYear = financialYear;
    this.sanctionNo = sanctionNo;
    this.transactionId = transactionId;
    this.transactionDate = transactionDate;
    this.totalAmount = totalAmount;
    this.apiresponsestatus = apiresponsestatus;
    this.createdOn = createdOn;
 }

  @Id 

 
 @Column(name="cgireceiptdetaildata_id", unique=true, nullable=false)
 public int getCgireceiptdetaildataId() {
     return this.cgireceiptdetaildataId;
 }
 
 public void setCgireceiptdetaildataId(int cgireceiptdetaildataId) {
     this.cgireceiptdetaildataId = cgireceiptdetaildataId;
 }

@ManyToOne(fetch=FetchType.EAGER)
 @JoinColumn(name="state_lgd_code")
 public IwmpState getIwmpState() {
     return this.iwmpState;
 }
 
 public void setIwmpState(IwmpState iwmpState) {
     this.iwmpState = iwmpState;
 }

 
 @Column(name="financial_year", length=10)
 public String getFinancialYear() {
     return this.financialYear;
 }
 
 public void setFinancialYear(String financialYear) {
     this.financialYear = financialYear;
 }

 
 @Column(name="sanction_no", length=20)
 public String getSanctionNo() {
     return this.sanctionNo;
 }
 
 public void setSanctionNo(String sanctionNo) {
     this.sanctionNo = sanctionNo;
 }

 
 @Column(name="transaction_id", length=20)
 public String getTransactionId() {
     return this.transactionId;
 }
 
 public void setTransactionId(String transactionId) {
     this.transactionId = transactionId;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="transaction_date", length=29)
 public Date getTransactionDate() {
     return this.transactionDate;
 }
 
 public void setTransactionDate(Date transactionDate) {
     this.transactionDate = transactionDate;
 }

 
 @Column(name="total_amount", precision=20, scale=4)
 public BigDecimal getTotalAmount() {
     return this.totalAmount;
 }
 
 public void setTotalAmount(BigDecimal totalAmount) {
     this.totalAmount = totalAmount;
 }

 
 @Column(name="apiresponsestatus", length=20)
 public String getApiresponsestatus() {
     return this.apiresponsestatus;
 }
 
 public void setApiresponsestatus(String apiresponsestatus) {
     this.apiresponsestatus = apiresponsestatus;
 }

 @Temporal(TemporalType.TIME)
 @Column(name="created_on", length=15)
 public Date getCreatedOn() {
     return this.createdOn;
 }
 
 public void setCreatedOn(Date createdOn) {
     this.createdOn = createdOn;
 }




}




