package app.model;
// Generated 19 Jan, 2021 11:09:56 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import app.model.project.WdcpmksyProjectPhysicalAchievementTranx;
import app.model.project.IwmpProjectPhysicalAssetTemp;
import app.model.project.IwmpProjectPhysicalTranx;
import app.model.project.WdcpmksyEpaWorkid;
import app.model.project.WdcpmksyLivelihoodWorkid;
import app.model.project.WdcpmksyOutcomeTargetTranx;
import app.model.project.WdcpmksyPrdouctionWorkid;

/**
 * IwmpUserReg generated by hbm2java
 */
@Entity
@Table(name = "iwmp_user_reg", schema = "public")
public class UserReg implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer regId;
	private String userId;
	private String userName;
	private String userType;
	private String designation;
	private String department;
	private String curAddress;
	private String phoneNo;
	private String mobileNo;
	private String faxNo;
	private String email;
	private Date creationDate;
	private String authorizerId;
	private Date authorizationDate;
	private String updatorId;
	private Date updationDate;
	private String status;
	private String encryptedPass;
	private String piaName;
	private String piaType;
	private String piaHead;
	private String disable;
	private Character firstLogin;
	private Date paswdModify;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private String encryptedPassSecond;
	private String creatorId;
	private String empCode;
	private String extensionNo;
	private String perAddress;
	private String profileId;
	private String remark;
	private String imei1;
	private String imei2;
	private String imei3;
	private String imei4;
	private String imei5;
	private String oldImeiNo;
	private String captcha;
	private String userNgoid;
	private String userRegwith;
	private Set<IwmpUserProjectMap> iwmpUserProjectMaps = new HashSet<IwmpUserProjectMap>(0);
	private Set<UserMap> iwmpUserMaps = new HashSet<UserMap>(0);
	private Set<IwmpUserActionLog> iwmpUserActionLogs = new HashSet<IwmpUserActionLog>(0);
	private Set<IwmpLoginLog> iwmpLoginLogs = new HashSet<IwmpLoginLog>(0);
	private Set<IwmpActiveUserHistory> iwmpActiveUserHistories = new HashSet<IwmpActiveUserHistory>(0);
	 private Set<IwmpProjectPhysicalTranx> iwmpProjectPhysicalTranxesForSentfrom = new HashSet<IwmpProjectPhysicalTranx>(0);
     private Set<IwmpProjectPhysicalTranx> iwmpProjectPhysicalTranxesForSentTo = new HashSet<IwmpProjectPhysicalTranx>(0);
     private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
     private Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxesForSentfrom = new HashSet<WdcpmksyProjectPhysicalAchievementTranx>(0);
     private Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxesForSentTo = new HashSet<WdcpmksyProjectPhysicalAchievementTranx>(0);
     private Set<WdcpmksyOutcomeTargetTranx> wdcpmksyOutcomeTargetTranxesForSentTo = new HashSet<WdcpmksyOutcomeTargetTranx>(0);
     private Set<WdcpmksyOutcomeTargetTranx> wdcpmksyOutcomeTargetTranxesForSentFrom = new HashSet<WdcpmksyOutcomeTargetTranx>(0);
     
     private Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkidsForSentFrom = new HashSet<WdcpmksyEpaWorkid>(0);
     private Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkidsForSentTo = new HashSet<WdcpmksyEpaWorkid>(0);
     private Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkidsForSentFrom = new HashSet<WdcpmksyLivelihoodWorkid>(0);
     private Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkidsForSentTo = new HashSet<WdcpmksyLivelihoodWorkid>(0);
     private Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkidsForSentFrom = new HashSet<WdcpmksyPrdouctionWorkid>(0);
     private Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkidsForSentTo = new HashSet<WdcpmksyPrdouctionWorkid>(0);
     
	public UserReg() {
	}

	public UserReg(Integer regId) {
		this.regId = regId;
	}

	public UserReg(Integer regId, String userId, String userName, String userType, String designation, String department,
			String curAddress, String phoneNo, String mobileNo, String faxNo, String email, Date creationDate,
			String authorizerId, Date authorizationDate, String updatorId, Date updationDate, String status,
			String encryptedPass, String piaName, String piaType, String piaHead, String disable, Character firstLogin,
			Date paswdModify, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, String encryptedPassSecond,
			String creatorId, String empCode, String extensionNo, String perAddress, String profileId, String remark,
			String imei1, String imei2, String imei3, String imei4, String imei5, String oldImeiNo, String captcha, String userNgoid, String userRegwith,
			Set<IwmpUserProjectMap> iwmpUserProjectMaps, Set<UserMap> iwmpUserMaps,
			Set<IwmpUserActionLog> iwmpUserActionLogs, Set<IwmpLoginLog> iwmpLoginLogs, Set<IwmpActiveUserHistory> iwmpActiveUserHistories
			, Set<IwmpProjectPhysicalTranx> iwmpProjectPhysicalTranxesForSentfrom, Set<IwmpProjectPhysicalTranx> iwmpProjectPhysicalTranxesForSentTo,
			Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp, Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkidsForSentFrom, 
			Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkidsForSentTo, Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkidsForSentFrom, 
			Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkidsForSentTo, Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkidsForSentFrom, 
			Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkidsForSentTo) {
		this.regId = regId;
		this.userId = userId;
		this.userName = userName;
		this.userType = userType;
		this.designation = designation;
		this.department = department;
		this.curAddress = curAddress;
		this.phoneNo = phoneNo;
		this.mobileNo = mobileNo;
		this.faxNo = faxNo;
		this.email = email;
		this.creationDate = creationDate;
		this.authorizerId = authorizerId;
		this.authorizationDate = authorizationDate;
		this.updatorId = updatorId;
		this.updationDate = updationDate;
		this.status = status;
		this.encryptedPass = encryptedPass;
		this.piaName = piaName;
		this.piaType = piaType;
		this.piaHead = piaHead;
		this.disable = disable;
		this.firstLogin = firstLogin;
		this.paswdModify = paswdModify;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
		this.encryptedPassSecond = encryptedPassSecond;
		this.creatorId = creatorId;
		this.empCode = empCode;
		this.extensionNo = extensionNo;
		this.perAddress = perAddress;
		this.profileId = profileId;
		this.remark = remark;
		this.imei1 = imei1;
		this.imei2 = imei2;
		this.imei3 = imei3;
		this.imei4 = imei4;
		this.imei5 = imei5;
		this.oldImeiNo = oldImeiNo;
		this.captcha = captcha;
		this.userNgoid = userNgoid;
		this.userRegwith = userRegwith;
		this.iwmpUserProjectMaps = iwmpUserProjectMaps;
		this.iwmpUserMaps = iwmpUserMaps;
		this.iwmpUserActionLogs = iwmpUserActionLogs;
		this.iwmpLoginLogs = iwmpLoginLogs;
		this.iwmpActiveUserHistories = iwmpActiveUserHistories;
		this.iwmpProjectPhysicalTranxesForSentfrom = iwmpProjectPhysicalTranxesForSentfrom;
	    this.iwmpProjectPhysicalTranxesForSentTo = iwmpProjectPhysicalTranxesForSentTo;
	    this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
	    this.wdcpmksyEpaWorkidsForSentFrom = wdcpmksyEpaWorkidsForSentFrom;
	    this.wdcpmksyEpaWorkidsForSentTo = wdcpmksyEpaWorkidsForSentTo;
	    this.wdcpmksyLivelihoodWorkidsForSentFrom = wdcpmksyLivelihoodWorkidsForSentFrom;
	    this.wdcpmksyLivelihoodWorkidsForSentTo = wdcpmksyLivelihoodWorkidsForSentTo;
	    this.wdcpmksyPrdouctionWorkidsForSentFrom = wdcpmksyPrdouctionWorkidsForSentFrom;
	    this.wdcpmksyPrdouctionWorkidsForSentTo = wdcpmksyPrdouctionWorkidsForSentTo;
	}

	@Id
	@Column(name = "reg_id", unique = true, nullable = false)
	public Integer getRegId() {
		return this.regId;
	}

	public void setRegId(Integer regId) {
		this.regId = regId;
	}

	@Column(name = "user_id")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_type")
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "designation")
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "department")
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "cur_address", length = 500)
	public String getCurAddress() {
		return this.curAddress;
	}

	public void setCurAddress(String curAddress) {
		this.curAddress = curAddress;
	}

	@Column(name = "phone_no", length = 40)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "mobile_no", length = 40)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "fax_no", length = 40)
	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 29)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "authorizer_id", length = 150)
	public String getAuthorizerId() {
		return this.authorizerId;
	}

	public void setAuthorizerId(String authorizerId) {
		this.authorizerId = authorizerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "authorization_date", length = 29)
	public Date getAuthorizationDate() {
		return this.authorizationDate;
	}

	public void setAuthorizationDate(Date authorizationDate) {
		this.authorizationDate = authorizationDate;
	}

	@Column(name = "updator_id", length = 150)
	public String getUpdatorId() {
		return this.updatorId;
	}

	public void setUpdatorId(String updatorId) {
		this.updatorId = updatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updation_date", length = 29)
	public Date getUpdationDate() {
		return this.updationDate;
	}

	public void setUpdationDate(Date updationDate) {
		this.updationDate = updationDate;
	}

	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "encrypted_pass", length = 200)
	public String getEncryptedPass() {
		return this.encryptedPass;
	}

	public void setEncryptedPass(String encryptedPass) {
		this.encryptedPass = encryptedPass;
	}

	@Column(name = "pia_name")
	public String getPiaName() {
		return this.piaName;
	}

	public void setPiaName(String piaName) {
		this.piaName = piaName;
	}

	@Column(name = "pia_type")
	public String getPiaType() {
		return this.piaType;
	}

	public void setPiaType(String piaType) {
		this.piaType = piaType;
	}

	@Column(name = "pia_head")
	public String getPiaHead() {
		return this.piaHead;
	}

	public void setPiaHead(String piaHead) {
		this.piaHead = piaHead;
	}

	@Column(name = "disable", length = 20)
	public String getDisable() {
		return this.disable;
	}

	public void setDisable(String disable) {
		this.disable = disable;
	}

	@Column(name = "first_login", length = 1)
	public Character getFirstLogin() {
		return this.firstLogin;
	}

	public void setFirstLogin(Character firstLogin) {
		this.firstLogin = firstLogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "paswd_modify", length = 13)
	public Date getPaswdModify() {
		return this.paswdModify;
	}

	public void setPaswdModify(Date paswdModify) {
		this.paswdModify = paswdModify;
	}

	@Column(name = "last_updated_by", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "encrypted_pass_second", length = 200)
	public String getEncryptedPassSecond() {
		return this.encryptedPassSecond;
	}

	public void setEncryptedPassSecond(String encryptedPassSecond) {
		this.encryptedPassSecond = encryptedPassSecond;
	}

	@Column(name = "creator_id")
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	@Column(name = "emp_code")
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "extension_no")
	public String getExtensionNo() {
		return this.extensionNo;
	}

	public void setExtensionNo(String extensionNo) {
		this.extensionNo = extensionNo;
	}

	@Column(name = "per_address")
	public String getPerAddress() {
		return this.perAddress;
	}

	public void setPerAddress(String perAddress) {
		this.perAddress = perAddress;
	}

	@Column(name = "profile_id")
	public String getProfileId() {
		return this.profileId;
	}

	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "imei1")
	public String getImei1() {
		return this.imei1;
	}

	public void setImei1(String imei1) {
		this.imei1 = imei1;
	}

	@Column(name = "imei2")
	public String getImei2() {
		return this.imei2;
	}

	public void setImei2(String imei2) {
		this.imei2 = imei2;
	}

	@Column(name = "imei3")
	public String getImei3() {
		return this.imei3;
	}

	public void setImei3(String imei3) {
		this.imei3 = imei3;
	}

	@Column(name = "imei4")
	public String getImei4() {
		return this.imei4;
	}

	public void setImei4(String imei4) {
		this.imei4 = imei4;
	}

	@Column(name = "imei5")
	public String getImei5() {
		return this.imei5;
	}

	public void setImei5(String imei5) {
		this.imei5 = imei5;
	}

	@Column(name = "old_imei_no")
	public String getOldImeiNo() {
		return this.oldImeiNo;
	}

	public void setOldImeiNo(String oldImeiNo) {
		this.oldImeiNo = oldImeiNo;
	}

	@Column(name = "captcha")
	public String getCaptcha() {
		return this.captcha;
	}

	public void setCaptcha(String captcha) {
		this.captcha = captcha;
	}
	
	@Column(name = "ngo_id")
	public String getUserNgoid() {
		return userNgoid;
	}

	public void setUserNgoid(String userNgoid) {
		this.userNgoid = userNgoid;
	}

	@Column(name = "register_with")
	public String getUserRegwith() {
		return userRegwith;
	}

	public void setUserRegwith(String userRegwith) {
		this.userRegwith = userRegwith;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userReg")
	public Set<IwmpUserProjectMap> getIwmpUserProjectMaps() {
		return this.iwmpUserProjectMaps;
	}

	public void setIwmpUserProjectMaps(Set<IwmpUserProjectMap> iwmpUserProjectMaps) {
		this.iwmpUserProjectMaps = iwmpUserProjectMaps;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userReg")
	@Cascade({CascadeType.ALL})
	public Set<UserMap> getIwmpUserMaps() {
		return this.iwmpUserMaps;
	}

	public void setIwmpUserMaps(Set<UserMap> iwmpUserMaps) {
		this.iwmpUserMaps = iwmpUserMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userReg")
	public Set<IwmpUserActionLog> getIwmpUserActionLogs() {
		return this.iwmpUserActionLogs;
	}

	public void setIwmpUserActionLogs(Set<IwmpUserActionLog> iwmpUserActionLogs) {
		this.iwmpUserActionLogs = iwmpUserActionLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userReg")
	public Set<IwmpLoginLog> getIwmpLoginLogs() {
		return this.iwmpLoginLogs;
	}

	public void setIwmpLoginLogs(Set<IwmpLoginLog> iwmpLoginLogs) {
		this.iwmpLoginLogs = iwmpLoginLogs;
	}
	@OneToMany(mappedBy="userReg")
    public Set<IwmpActiveUserHistory> getIwmpActiveUserHistories() {
        return this.iwmpActiveUserHistories;
    }
    
    public void setIwmpActiveUserHistories(Set<IwmpActiveUserHistory> iwmpActiveUserHistories) {
        this.iwmpActiveUserHistories = iwmpActiveUserHistories;
    }

    @OneToMany(mappedBy="iwmpUserRegBySentfrom")
    public Set<IwmpProjectPhysicalTranx> getIwmpProjectPhysicalTranxesForSentfrom() {
        return this.iwmpProjectPhysicalTranxesForSentfrom;
    }
    
    public void setIwmpProjectPhysicalTranxesForSentfrom(Set<IwmpProjectPhysicalTranx> iwmpProjectPhysicalTranxesForSentfrom) {
        this.iwmpProjectPhysicalTranxesForSentfrom = iwmpProjectPhysicalTranxesForSentfrom;
    }

    @OneToMany( mappedBy="iwmpUserRegBySentTo")
    public Set<IwmpProjectPhysicalTranx> getIwmpProjectPhysicalTranxesForSentTo() {
        return this.iwmpProjectPhysicalTranxesForSentTo;
    }
    
    public void setIwmpProjectPhysicalTranxesForSentTo(Set<IwmpProjectPhysicalTranx> iwmpProjectPhysicalTranxesForSentTo) {
        this.iwmpProjectPhysicalTranxesForSentTo = iwmpProjectPhysicalTranxesForSentTo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpUserRegBySentTo")
	public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemp() {
		return iwmpProjectPhysicalAssetTemp;
	}

	public void setIwmpProjectPhysicalAssetTemp(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp) {
		this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
	}
    
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentfrom")
    public Set<WdcpmksyProjectPhysicalAchievementTranx> getWdcpmksyProjectPhysicalAchievementTranxesForSentfrom() {
        return this.wdcpmksyProjectPhysicalAchievementTranxesForSentfrom;
    }
    
    public void setWdcpmksyProjectPhysicalAchievementTranxesForSentfrom(Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxesForSentfrom) {
        this.wdcpmksyProjectPhysicalAchievementTranxesForSentfrom = wdcpmksyProjectPhysicalAchievementTranxesForSentfrom;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentTo")
    public Set<WdcpmksyProjectPhysicalAchievementTranx> getWdcpmksyProjectPhysicalAchievementTranxesForSentTo() {
        return this.wdcpmksyProjectPhysicalAchievementTranxesForSentTo;
    }
    
    public void setWdcpmksyProjectPhysicalAchievementTranxesForSentTo(Set<WdcpmksyProjectPhysicalAchievementTranx> wdcpmksyProjectPhysicalAchievementTranxesForSentTo) {
        this.wdcpmksyProjectPhysicalAchievementTranxesForSentTo = wdcpmksyProjectPhysicalAchievementTranxesForSentTo;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentTo")
    public Set<WdcpmksyOutcomeTargetTranx> getWdcpmksyOutcomeTargetTranxesForSentTo() {
        return this.wdcpmksyOutcomeTargetTranxesForSentTo;
    }
    
    public void setWdcpmksyOutcomeTargetTranxesForSentTo(Set<WdcpmksyOutcomeTargetTranx> wdcpmksyOutcomeTargetTranxesForSentTo) {
        this.wdcpmksyOutcomeTargetTranxesForSentTo = wdcpmksyOutcomeTargetTranxesForSentTo;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentFrom")
    public Set<WdcpmksyOutcomeTargetTranx> getWdcpmksyOutcomeTargetTranxesForSentFrom() {
        return this.wdcpmksyOutcomeTargetTranxesForSentFrom;
    }
    
    public void setWdcpmksyOutcomeTargetTranxesForSentFrom(Set<WdcpmksyOutcomeTargetTranx> wdcpmksyOutcomeTargetTranxesForSentFrom) {
        this.wdcpmksyOutcomeTargetTranxesForSentFrom = wdcpmksyOutcomeTargetTranxesForSentFrom;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentFrom")
    public Set<WdcpmksyEpaWorkid> getWdcpmksyEpaWorkidsForSentFrom() {
        return this.wdcpmksyEpaWorkidsForSentFrom;
    }
    
    public void setWdcpmksyEpaWorkidsForSentFrom(Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkidsForSentFrom) {
        this.wdcpmksyEpaWorkidsForSentFrom = wdcpmksyEpaWorkidsForSentFrom;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentTo")
    public Set<WdcpmksyEpaWorkid> getWdcpmksyEpaWorkidsForSentTo() {
        return this.wdcpmksyEpaWorkidsForSentTo;
    }
    
    public void setWdcpmksyEpaWorkidsForSentTo(Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkidsForSentTo) {
        this.wdcpmksyEpaWorkidsForSentTo = wdcpmksyEpaWorkidsForSentTo;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentFrom")
    public Set<WdcpmksyLivelihoodWorkid> getWdcpmksyLivelihoodWorkidsForSentFrom() {
        return this.wdcpmksyLivelihoodWorkidsForSentFrom;
    }
    
    public void setWdcpmksyLivelihoodWorkidsForSentFrom(Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkidsForSentFrom) {
        this.wdcpmksyLivelihoodWorkidsForSentFrom = wdcpmksyLivelihoodWorkidsForSentFrom;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentTo")
    public Set<WdcpmksyLivelihoodWorkid> getWdcpmksyLivelihoodWorkidsForSentTo() {
        return this.wdcpmksyLivelihoodWorkidsForSentTo;
    }
    
    public void setWdcpmksyLivelihoodWorkidsForSentTo(Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkidsForSentTo) {
        this.wdcpmksyLivelihoodWorkidsForSentTo = wdcpmksyLivelihoodWorkidsForSentTo;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentFrom")
    public Set<WdcpmksyPrdouctionWorkid> getWdcpmksyPrdouctionWorkidsForSentFrom() {
        return this.wdcpmksyPrdouctionWorkidsForSentFrom;
    }
    
    public void setWdcpmksyPrdouctionWorkidsForSentFrom(Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkidsForSentFrom) {
        this.wdcpmksyPrdouctionWorkidsForSentFrom = wdcpmksyPrdouctionWorkidsForSentFrom;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUserRegBySentTo")
    public Set<WdcpmksyPrdouctionWorkid> getWdcpmksyPrdouctionWorkidsForSentTo() {
        return this.wdcpmksyPrdouctionWorkidsForSentTo;
    }
    
    public void setWdcpmksyPrdouctionWorkidsForSentTo(Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkidsForSentTo) {
        this.wdcpmksyPrdouctionWorkidsForSentTo = wdcpmksyPrdouctionWorkidsForSentTo;
    }
    
}
