package app.model;
// Generated 13 Aug, 2021 2:32:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.project.IwmpProjectPhysicalAsset;
import app.model.project.WdcpmksyLivelihoodWorkid;

/**
 * IwmpProjectAssetStatus generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_project_asset_livelihood_status",schema="public" )
public class WdcpmksyProjectAssetLivelihoodStatus  implements java.io.Serializable {

	 private static final long serialVersionUID = 1L;
	 private long statusid;
     private IwmpMProject iwmpMProject;
     private WdcpmksyLivelihoodWorkid wdcpmksyLivelihoodWorkid;
     private Date startdate;
     private Character status;
     private Date completiondate;
     private String reason;
     private Character headtype;
     private Date last_updated_date;
     
    public WdcpmksyProjectAssetLivelihoodStatus() {
    }

	
    public WdcpmksyProjectAssetLivelihoodStatus(long statusid) {
        this.statusid = statusid;
    }
    public WdcpmksyProjectAssetLivelihoodStatus(long statusid, IwmpMProject iwmpMProject, WdcpmksyLivelihoodWorkid wdcpmksyLivelihoodWorkid, Date startdate, Character status, Date last_updated_date, Date completiondate, String reason, Character headtype) {
       this.statusid = statusid;
       this.iwmpMProject = iwmpMProject;
       this.wdcpmksyLivelihoodWorkid = wdcpmksyLivelihoodWorkid;
       this.startdate = startdate;
       this.status = status;
       this.completiondate = completiondate;
       this.last_updated_date = last_updated_date;
       this.reason = reason;
       this.headtype = headtype;
      
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="statusid", unique=true, nullable=false)
    public long getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(long statusid) {
        this.statusid = statusid;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="projid")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="assetid")
    public WdcpmksyLivelihoodWorkid getWdcpmksyLivelihoodWorkid() {
        return this.wdcpmksyLivelihoodWorkid;
    }
    
    public void setWdcpmksyLivelihoodWorkid(WdcpmksyLivelihoodWorkid wdcpmksyLivelihoodWorkid) {
        this.wdcpmksyLivelihoodWorkid = wdcpmksyLivelihoodWorkid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startdate", length=13)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="completiondate", length=13)
    public Date getCompletiondate() {
        return this.completiondate;
    }
    
    public void setCompletiondate(Date completiondate) {
        this.completiondate = completiondate;
    }

    
    @Column(name="reason", length=100)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Column(name="headtype", length=1)
	public Character getHeadtype() {
		return headtype;
	}


	public void setHeadtype(Character headtype) {
		this.headtype = headtype;
	}

	@Column(name="last_updated_date")
	public Date getLast_updated_date() {
		return last_updated_date;
	}


	public void setLast_updated_date(Date last_updated_date) {
		this.last_updated_date = last_updated_date;
	}

    
    
    




}


