package app.model.outcome;
// Generated 11 Jan, 2022 10:24:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import app.model.project.WdcpmksyEpaWorkid;
/**
 * EpaDetail generated by hbm2java
 */
@Entity
@Table(name="epa_detail"
    ,schema="public"
)
public class EpaDetail  implements java.io.Serializable {


     public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}

	private int epaDetailId;
     private MEpaCoreactivity MEpaCoreactivity;
     private Date createdOn;
     private LivelihoodEpaProd livelihoodEpaProd;
     private Integer noActivities;
     private String requestIp;
     private Date updatedOn;
     private String status;
     private Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids = new HashSet<WdcpmksyEpaWorkid>(0);

    public EpaDetail() {
    }

	
    public EpaDetail(int epaDetailId, LivelihoodEpaProd livelihoodEpaProd) {
        this.epaDetailId = epaDetailId;
        this.livelihoodEpaProd = livelihoodEpaProd;
    }
    public EpaDetail(int epaDetailId, String status, MEpaCoreactivity MEpaCoreactivity, Date createdOn, LivelihoodEpaProd livelihoodEpaProd, Integer noActivities, String requestIp, Date updatedOn, Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids) {
       this.epaDetailId = epaDetailId;
       this.MEpaCoreactivity = MEpaCoreactivity;
       this.createdOn = createdOn;
       this.livelihoodEpaProd = livelihoodEpaProd;
       this.noActivities = noActivities;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.status=status;
       this.wdcpmksyEpaWorkids = wdcpmksyEpaWorkids;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    @Column(name="epa_detail_id", unique=true, nullable=false)
    public int getEpaDetailId() {
        return this.epaDetailId;
    }
    
    public void setEpaDetailId(int epaDetailId) {
        this.epaDetailId = epaDetailId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="epa_activity_id")
    public MEpaCoreactivity getMEpaCoreactivity() {
        return this.MEpaCoreactivity;
    }
    
    public void setMEpaCoreactivity(MEpaCoreactivity MEpaCoreactivity) {
        this.MEpaCoreactivity = MEpaCoreactivity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="lep_id", nullable=false)
    public LivelihoodEpaProd getLivelihoodEpaProd() {
        return this.livelihoodEpaProd;
    }
    
    public void setLivelihoodEpaProd(LivelihoodEpaProd livelihoodEpaProd) {
        this.livelihoodEpaProd = livelihoodEpaProd;
    }

    
    @Column(name="no_activities")
    public Integer getNoActivities() {
        return this.noActivities;
    }
    
    public void setNoActivities(Integer noActivities) {
        this.noActivities = noActivities;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="epaDetail")
    public Set<WdcpmksyEpaWorkid> getWdcpmksyEpaWorkids() {
        return this.wdcpmksyEpaWorkids;
    }
    
    public void setWdcpmksyEpaWorkids(Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids) {
        this.wdcpmksyEpaWorkids = wdcpmksyEpaWorkids;
    }


}


