package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FpoCoreaactivityDetail generated by hbm2java
 */
@Entity
@Table(name="fpo_coreaactivity_detail"
    ,schema="public"
)
public class FpoCoreaactivityDetail  implements java.io.Serializable {


     private int fpoCoreactivityDetailId;
     private FpoDetail fpoDetail;
     private MFpoCoreactivity MFpoCoreactivity;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private String createdBy;
     //private String status;
    public FpoCoreaactivityDetail() {
    }

	
    public FpoCoreaactivityDetail(int fpoCoreactivityDetailId) {
        this.fpoCoreactivityDetailId = fpoCoreactivityDetailId;
    }
    public FpoCoreaactivityDetail(int fpoCoreactivityDetailId, FpoDetail fpoDetail, MFpoCoreactivity MFpoCoreactivity, Date createdOn, String requestIp, Date updatedOn, String createdBy) {
       this.fpoCoreactivityDetailId = fpoCoreactivityDetailId;
       this.fpoDetail = fpoDetail;
       this.MFpoCoreactivity = MFpoCoreactivity;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="fpo_coreactivity_detail_id", unique=true, nullable=false)
    public int getFpoCoreactivityDetailId() {
        return this.fpoCoreactivityDetailId;
    }
    
    public void setFpoCoreactivityDetailId(int fpoCoreactivityDetailId) {
        this.fpoCoreactivityDetailId = fpoCoreactivityDetailId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fpo_detail_id")
    public FpoDetail getFpoDetail() {
        return this.fpoDetail;
    }
    
    public void setFpoDetail(FpoDetail fpoDetail) {
        this.fpoDetail = fpoDetail;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fpo_coreactivity_id")
    public MFpoCoreactivity getMFpoCoreactivity() {
        return this.MFpoCoreactivity;
    }
    
    public void setMFpoCoreactivity(MFpoCoreactivity MFpoCoreactivity) {
        this.MFpoCoreactivity = MFpoCoreactivity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }


	




}


