package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMProject;

/**
 * FpoMain generated by hbm2java
 */
@Entity
@Table(name="fpo_main"
    ,schema="public"
)
public class FpoMain  implements java.io.Serializable {


     private int fpoId;
     private IwmpMProject iwmpMProject;
     private String fpoType;
     private Integer totalno;
     private String status;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Set<FpoDetail> fpoDetails = new HashSet<FpoDetail>(0);

    public FpoMain() {
    }

	
    public FpoMain(int fpoId) {
        this.fpoId = fpoId;
    }
    public FpoMain(int fpoId, IwmpMProject iwmpMProject, String fpoType, Integer totalno, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<FpoDetail> fpoDetails) {
       this.fpoId = fpoId;
       this.iwmpMProject = iwmpMProject;
       this.fpoType = fpoType;
       this.totalno = totalno;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.fpoDetails = fpoDetails;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="fpo_id", unique=true, nullable=false)
    public int getFpoId() {
        return this.fpoId;
    }
    
    public void setFpoId(int fpoId) {
        this.fpoId = fpoId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="fpo_type", length=30)
    public String getFpoType() {
        return this.fpoType;
    }
    
    public void setFpoType(String fpoType) {
        this.fpoType = fpoType;
    }

    
    @Column(name="totalno")
    public Integer getTotalno() {
        return this.totalno;
    }
    
    public void setTotalno(Integer totalno) {
        this.totalno = totalno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fpoMain", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<FpoDetail> getFpoDetails() {
        return this.fpoDetails;
    }
    
    public void setFpoDetails(Set<FpoDetail> fpoDetails) {
        this.fpoDetails = fpoDetails;
    }


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}




}


