package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMFinYear;
import app.model.IwmpMProject;

/**
 * GroundwaterMain generated by hbm2java
 */
@Entity
@Table(name="groundwater_main" ,schema="public")
public class GroundwaterMain  implements java.io.Serializable {


     private int groundwaterId;
     private IwmpMFinYear iwmpMFinYear;
     private IwmpMProject iwmpMProject;
     private String levelTime;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private String createdBy;
     private Set<GroundwaterDetail> groundwaterDetails = new HashSet<GroundwaterDetail>(0);
     private Character status;

    public GroundwaterMain() {
    }

	
    public GroundwaterMain(int groundwaterId) {
        this.groundwaterId = groundwaterId;
    }
    public GroundwaterMain(int groundwaterId, IwmpMFinYear iwmpMFinYear, IwmpMProject iwmpMProject, String levelTime, Date createdOn, String requestIp, Date updatedOn, String createdBy, Set<GroundwaterDetail> groundwaterDetails, Character status) {
       this.groundwaterId = groundwaterId;
       this.iwmpMFinYear = iwmpMFinYear;
       this.iwmpMProject = iwmpMProject;
       this.levelTime = levelTime;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
       this.groundwaterDetails = groundwaterDetails;
       this.status=status;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="groundwater_id", unique=true, nullable=false)
    public int getGroundwaterId() {
        return this.groundwaterId;
    }
    
    public void setGroundwaterId(int groundwaterId) {
        this.groundwaterId = groundwaterId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fin_yr_cd")
    public IwmpMFinYear getIwmpMFinYear() {
        return this.iwmpMFinYear;
    }
    
    public void setIwmpMFinYear(IwmpMFinYear iwmpMFinYear) {
        this.iwmpMFinYear = iwmpMFinYear;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="level_time", length=100)
    public String getLevelTime() {
        return this.levelTime;
    }
    
    public void setLevelTime(String levelTime) {
        this.levelTime = levelTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="groundwaterMain")
    public Set<GroundwaterDetail> getGroundwaterDetails() {
        return this.groundwaterDetails;
    }
    
    public void setGroundwaterDetails(Set<GroundwaterDetail> groundwaterDetails) {
        this.groundwaterDetails = groundwaterDetails;
    }

    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }



}


