package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import app.model.project.WdcpmksyLivelihoodWorkid;
/**
 * LivelihoodDetail generated by hbm2java
 */
@Entity
@Table(name="livelihood_detail"
    ,schema="public"
)
public class LivelihoodDetail  implements java.io.Serializable {


     private int livelihoodDetailId;
     private LivelihoodEpaProd livelihoodEpaProd;
     private MLivelihoodCoreactivity mLivelihoodCoreactivity;
     private String detailType;
     private Integer sc;
     private Integer st;
     private Integer other;
     private Integer women;
     private BigDecimal postAvgIncome;
     private BigDecimal preAvgIncome;
     private String poststatus;
     private Integer noActivities;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String status;
     private Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids = new HashSet<WdcpmksyLivelihoodWorkid>(0);


	public LivelihoodDetail() {
    }

	
    public LivelihoodDetail(int livelihoodDetailId, LivelihoodEpaProd livelihoodEpaProd) {
        this.livelihoodDetailId = livelihoodDetailId;
        this.livelihoodEpaProd = livelihoodEpaProd;
    }
    public LivelihoodDetail(String status,int livelihoodDetailId, LivelihoodEpaProd livelihoodEpaProd, MLivelihoodCoreactivity MLivelihoodCoreactivity, String detailType, Integer sc, Integer st, Integer other, Integer women, BigDecimal increaseIncome, Integer noActivities, Date createdOn, Date updatedOn, String requestIp, Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids) {
       this.livelihoodDetailId = livelihoodDetailId;
       this.livelihoodEpaProd = livelihoodEpaProd;
       this.mLivelihoodCoreactivity = MLivelihoodCoreactivity;
       this.detailType = detailType;
       this.sc = sc;
       this.st = st;
       this.other = other;
       this.women = women;
       this.postAvgIncome = increaseIncome;
       this.noActivities = noActivities;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.status=status;
       this.wdcpmksyLivelihoodWorkids = wdcpmksyLivelihoodWorkids;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="livelihood_detail_id", unique=true, nullable=false)
    public int getLivelihoodDetailId() {
        return this.livelihoodDetailId;
    }
    
    public void setLivelihoodDetailId(int livelihoodDetailId) {
        this.livelihoodDetailId = livelihoodDetailId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="lep_id", nullable=false)
    public LivelihoodEpaProd getLivelihoodEpaProd() {
        return this.livelihoodEpaProd;
    }
    
    public void setLivelihoodEpaProd(LivelihoodEpaProd livelihoodEpaProd) {
        this.livelihoodEpaProd = livelihoodEpaProd;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="livelihood_coreactivity_id")
    public MLivelihoodCoreactivity getMLivelihoodCoreactivity() {
        return this.mLivelihoodCoreactivity;
    }
    
    public void setMLivelihoodCoreactivity(MLivelihoodCoreactivity MLivelihoodCoreactivity) {
        this.mLivelihoodCoreactivity = MLivelihoodCoreactivity;
    }

    
    @Column(name="detail_type", length=150)
    public String getDetailType() {
        return this.detailType;
    }
    
    public void setDetailType(String detailType) {
        this.detailType = detailType;
    }

    
    @Column(name="sc")
    public Integer getSc() {
        return this.sc;
    }
    
    public void setSc(Integer sc) {
        this.sc = sc;
    }

    
    @Column(name="st")
    public Integer getSt() {
        return this.st;
    }
    
    public void setSt(Integer st) {
        this.st = st;
    }

    
    @Column(name="other")
    public Integer getOther() {
        return this.other;
    }
    
    public void setOther(Integer other) {
        this.other = other;
    }

    
    @Column(name="women")
    public Integer getWomen() {
        return this.women;
    }
    
    public void setWomen(Integer women) {
        this.women = women;
    }

    
    @Column(name="post_avg_income", precision=10)
    public BigDecimal getPostAvgIncome() {
        return this.postAvgIncome;
    }
    
    public void setPostAvgIncome(BigDecimal increaseIncome) {
        this.postAvgIncome = increaseIncome;
    }
    
    @Column(name="pre_avg_income", precision=10)
    public BigDecimal getPreAvgIncome() {
        return this.preAvgIncome;
    }
    
    public void setPreAvgIncome(BigDecimal increaseIncome) {
        this.preAvgIncome = increaseIncome;
    }

    @Column(name="post_status")
    public String getPoststatus() {
		return poststatus;
	}


	public void setPoststatus(String poststatus) {
		this.poststatus = poststatus;
	}


	@Column(name="no_activities")
    public Integer getNoActivities() {
        return this.noActivities;
    }
    
    public void setNoActivities(Integer noActivities) {
        this.noActivities = noActivities;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }


    public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="livelihoodDetail")
    public Set<WdcpmksyLivelihoodWorkid> getWdcpmksyLivelihoodWorkids() {
        return this.wdcpmksyLivelihoodWorkids;
    }
    
    public void setWdcpmksyLivelihoodWorkids(Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids) {
        this.wdcpmksyLivelihoodWorkids = wdcpmksyLivelihoodWorkids;
    }


}


