package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import app.model.IwmpMProject;

/**
 * LivelihoodEpaProd generated by hbm2java
 */
@Entity
@Table(name="livelihood_epa_prod"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="proj_id") 
)
public class LivelihoodEpaProd  implements java.io.Serializable {


	@Transient
     public List<LivelihoodDetail> getLivelihoodDetailsList() {
		return livelihoodDetailsList;
	}


	public void setLivelihoodDetailsList(List<LivelihoodDetail> livelihoodDetailsList) {
		this.livelihoodDetailsList = livelihoodDetailsList;
	}

	private int lepId;
	 @NotNull(message = "Please Select Project.")
     private IwmpMProject iwmpMProject;
	 
	 @NotNull(message = "Please Select Head Type")
     private String headType;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Set<EpaDetail> epaDetails = new HashSet<EpaDetail>();
     private Set<LivelihoodDetail> livelihoodDetails = new HashSet<LivelihoodDetail>();
     private Set<ProductionDetail> productionDetails = new HashSet<ProductionDetail>();
     
     @Transient
     private List<LivelihoodDetail> livelihoodDetailsList =new ArrayList<LivelihoodDetail>();
     
     @Transient
     private List<ProductionDetail> productionDetailList =new ArrayList<ProductionDetail>();
     
     @Transient
     private List<EpaDetail> epaDetailList =new ArrayList<EpaDetail>();
     
     @Transient
     public List<EpaDetail> getEpaDetailList() {
		return epaDetailList;
	}


	public void setEpaDetailList(List<EpaDetail> epaDetailList) {
		this.epaDetailList = epaDetailList;
	}


	@Transient
    public List<ProductionDetail> getProductionDetailList() {
		return this.productionDetailList;
	}


	public void setProductionDetailList(List<ProductionDetail> productionDetailList) {
		this.productionDetailList = productionDetailList;
	}


	public LivelihoodEpaProd() {
    }

	
    public LivelihoodEpaProd(int lepId) {
        this.lepId = lepId;
    }
    public LivelihoodEpaProd(int lepId, IwmpMProject iwmpMProject, String headType, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<EpaDetail> epaDetails, Set<LivelihoodDetail> livelihoodDetails, Set<ProductionDetail> productionDetails) {
       this.lepId = lepId;
       this.iwmpMProject = iwmpMProject;
       this.headType = headType;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.epaDetails = epaDetails;
       this.livelihoodDetails = livelihoodDetails;
       this.productionDetails = productionDetails;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="lep_id", unique=true, nullable=false)
    public int getLepId() {
        return this.lepId;
    }
    
    public void setLepId(int lepId) {
        this.lepId = lepId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="head_type", length=30)
    public String getHeadType() {
        return this.headType;
    }
    
    public void setHeadType(String headType) {
        this.headType = headType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="livelihoodEpaProd",cascade = javax.persistence.CascadeType.ALL, orphanRemoval = true)
    public Set<EpaDetail> getEpaDetails() {
        return this.epaDetails;
    }
    
    public void setEpaDetails(Set<EpaDetail> epaDetails) {
        this.epaDetails = epaDetails;
    }
    
//    @OneToMany(cascade=CascadeType.ALL)
  //  @JoinTable(name="EMPLOYEE_ACCOUNT", joinColumns={@JoinColumn(name="EMPLOYEE_ID", referencedColumnName="ID")}
  //  , inverseJoinColumns={@JoinColumn(name="ACCOUNT_ID", referencedColumnName="ID")})

@OneToMany(fetch=FetchType.LAZY, mappedBy="livelihoodEpaProd",cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<LivelihoodDetail> getLivelihoodDetails() {
        return this.livelihoodDetails;
    }
    
    public void setLivelihoodDetails(Set<LivelihoodDetail> livelihoodDetails) {
        this.livelihoodDetails = livelihoodDetails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="livelihoodEpaProd" ,cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<ProductionDetail> getProductionDetails() {
        return this.productionDetails;
    }
    
    public void setProductionDetails(Set<ProductionDetail> productionDetails) {
        this.productionDetails = productionDetails;
    }




}


