package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MCroptype generated by hbm2java
 */
@Entity
@Table(name="m_croptype"
    ,schema="public"
)
public class MCroptype  implements java.io.Serializable {


     private int cropId;
     private String cropDesc;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private Boolean isActive;
     private Set<ProductionDetail> productionDetails = new HashSet<ProductionDetail>(0);

    public MCroptype() {
    }

	
    public MCroptype(int cropId) {
        this.cropId = cropId;
    }
    public MCroptype(int cropId, String cropDesc, Date createdOn, String requestIp, Date updatedOn, Boolean isActive, Set<ProductionDetail> productionDetails) {
       this.cropId = cropId;
       this.cropDesc = cropDesc;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.isActive = isActive;
       this.productionDetails = productionDetails;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="crop_id", unique=true, nullable=false)
    public int getCropId() {
        return this.cropId;
    }
    
    public void setCropId(int cropId) {
        this.cropId = cropId;
    }

    
    @Column(name="crop_desc", length=150)
    public String getCropDesc() {
        return this.cropDesc;
    }
    
    public void setCropDesc(String cropDesc) {
        this.cropDesc = cropDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MCroptype")
    public Set<ProductionDetail> getProductionDetails() {
        return this.productionDetails;
    }
    
    public void setProductionDetails(Set<ProductionDetail> productionDetails) {
        this.productionDetails = productionDetails;
    }




}


