package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.project.WdcpmksyEpaWorkid;

/**
 * MEpaCoreactivity generated by hbm2java
 */
@Entity
@Table(name="m_epa_coreactivity"
    ,schema="public"
)
public class MEpaCoreactivity  implements java.io.Serializable {


     private int epaActivityId;
     private String epaDesc;
     private Boolean isActive;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private String createdBy;
     private Set<EpaDetail> epaDetails = new HashSet<EpaDetail>(0);
     private Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids = new HashSet<WdcpmksyEpaWorkid>(0);

    public MEpaCoreactivity() {
    }

	
    public MEpaCoreactivity(int epaActivityId) {
        this.epaActivityId = epaActivityId;
    }
    public MEpaCoreactivity(int epaActivityId, String epaDesc, Boolean isActive, Date createdOn, String requestIp, Date updatedOn, String createdBy, Set<EpaDetail> epaDetails, Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids) {
       this.epaActivityId = epaActivityId;
       this.epaDesc = epaDesc;
       this.isActive = isActive;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
       this.epaDetails = epaDetails;
       this.wdcpmksyEpaWorkids = wdcpmksyEpaWorkids;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="epa_activity_id", unique=true, nullable=false)
    public int getEpaActivityId() {
        return this.epaActivityId;
    }
    
    public void setEpaActivityId(int epaActivityId) {
        this.epaActivityId = epaActivityId;
    }

    
    @Column(name="epa_desc", length=250)
    public String getEpaDesc() {
        return this.epaDesc;
    }
    
    public void setEpaDesc(String epaDesc) {
        this.epaDesc = epaDesc;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MEpaCoreactivity")
    public Set<EpaDetail> getEpaDetails() {
        return this.epaDetails;
    }
    
    public void setEpaDetails(Set<EpaDetail> epaDetails) {
        this.epaDetails = epaDetails;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="MEpaCoreactivity")
    public Set<WdcpmksyEpaWorkid> getWdcpmksyEpaWorkids() {
        return this.wdcpmksyEpaWorkids;
    }
    
    public void setWdcpmksyEpaWorkids(Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids) {
        this.wdcpmksyEpaWorkids = wdcpmksyEpaWorkids;
    }




}


