package app.model.outcome;
// Generated 4 May, 2022 2:59:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MFpoCoreactivity generated by hbm2java
 */
@Entity
@Table(name="m_fpo_coreactivity"
    ,schema="public"
)
public class MFpoCoreactivity  implements java.io.Serializable {


     private int fpoCoreactivityId;
     private String fpoCoreactivityDesc;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private Boolean isActive;
     private String createdBy;
     private Set<FpoCoreaactivityDetail> fpoCoreaactivityDetails = new HashSet<FpoCoreaactivityDetail>(0);

    public MFpoCoreactivity() {
    }

	
    public MFpoCoreactivity(int fpoCoreactivityId) {
        this.fpoCoreactivityId = fpoCoreactivityId;
    }
    public MFpoCoreactivity(int fpoCoreactivityId, String fpoCoreactivityDesc, Date createdOn, String requestIp, Date updatedOn, Boolean isActive, String createdBy, Set<FpoCoreaactivityDetail> fpoCoreaactivityDetails) {
       this.fpoCoreactivityId = fpoCoreactivityId;
       this.fpoCoreactivityDesc = fpoCoreactivityDesc;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.fpoCoreaactivityDetails = fpoCoreaactivityDetails;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)    
    @Column(name="fpo_coreactivity_id", unique=true, nullable=false)
    public int getFpoCoreactivityId() {
        return this.fpoCoreactivityId;
    }
    
    public void setFpoCoreactivityId(int fpoCoreactivityId) {
        this.fpoCoreactivityId = fpoCoreactivityId;
    }

    
    @Column(name="fpo_coreactivity_desc", length=50)
    public String getFpoCoreactivityDesc() {
        return this.fpoCoreactivityDesc;
    }
    
    public void setFpoCoreactivityDesc(String fpoCoreactivityDesc) {
        this.fpoCoreactivityDesc = fpoCoreactivityDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MFpoCoreactivity")
    public Set<FpoCoreaactivityDetail> getFpoCoreaactivityDetails() {
        return this.fpoCoreaactivityDetails;
    }
    
    public void setFpoCoreaactivityDetails(Set<FpoCoreaactivityDetail> fpoCoreaactivityDetails) {
        this.fpoCoreaactivityDetails = fpoCoreaactivityDetails;
    }




}


