package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.project.WdcpmksyLivelihoodWorkid;

/**
 * MLivelihoodCoreactivity generated by hbm2java
 */
@Entity
@Table(name="m_livelihood_coreactivity" ,schema="public")
public class MLivelihoodCoreactivity  implements java.io.Serializable {


     private int livelihoodCoreactivityId;
     private String livelihoodCoreactivityDesc;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private Boolean isActive;
     private Set<LivelihoodDetail> livelihoodDetails = new HashSet<LivelihoodDetail>(0);
     private Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids = new HashSet<WdcpmksyLivelihoodWorkid>(0);

    public MLivelihoodCoreactivity() {
    }

	
    public MLivelihoodCoreactivity(int livelihoodCoreactivityId) {
        this.livelihoodCoreactivityId = livelihoodCoreactivityId;
    }
    public MLivelihoodCoreactivity(int livelihoodCoreactivityId, String livelihoodCoreactivityDesc, Date createdOn, String requestIp, Date updatedOn, Boolean isActive, Set<LivelihoodDetail> livelihoodDetails, Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids) {
       this.livelihoodCoreactivityId = livelihoodCoreactivityId;
       this.livelihoodCoreactivityDesc = livelihoodCoreactivityDesc;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.isActive = isActive;
       this.livelihoodDetails = livelihoodDetails;
       this.wdcpmksyLivelihoodWorkids = wdcpmksyLivelihoodWorkids;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="livelihood_coreactivity_id", unique=true, nullable=false)
    public int getLivelihoodCoreactivityId() {
        return this.livelihoodCoreactivityId;
    }
    
    public void setLivelihoodCoreactivityId(int livelihoodCoreactivityId) {
        this.livelihoodCoreactivityId = livelihoodCoreactivityId;
    }

    
    @Column(name="livelihood_coreactivity_desc", length=50)
    public String getLivelihoodCoreactivityDesc() {
        return this.livelihoodCoreactivityDesc;
    }
    
    public void setLivelihoodCoreactivityDesc(String livelihoodCoreactivityDesc) {
        this.livelihoodCoreactivityDesc = livelihoodCoreactivityDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MLivelihoodCoreactivity")
    public Set<LivelihoodDetail> getLivelihoodDetails() {
        return this.livelihoodDetails;
    }
    
    public void setLivelihoodDetails(Set<LivelihoodDetail> livelihoodDetails) {
        this.livelihoodDetails = livelihoodDetails;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MLivelihoodCoreactivity")
    public Set<WdcpmksyLivelihoodWorkid> getWdcpmksyLivelihoodWorkids() {
        return this.wdcpmksyLivelihoodWorkids;
    }
    
    public void setWdcpmksyLivelihoodWorkids(Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids) {
        this.wdcpmksyLivelihoodWorkids = wdcpmksyLivelihoodWorkids;
    }


}


