package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.project.WdcpmksyPrdouctionWorkid;

/**
 * MProductivityCoreactivity generated by hbm2java
 */
@Entity
@Table(name="m_productivity_coreactivity"
    ,schema="public"
)
public class MProductivityCoreactivity  implements java.io.Serializable {


     private int productivityCoreactivityId;
     private String productivityCoreactivityDesc;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private Boolean isActive;
     private Set<ProductionDetail> productionDetails = new HashSet<ProductionDetail>(0);
     private Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids = new HashSet<WdcpmksyPrdouctionWorkid>(0);
     private Character coverArea;
     
    public MProductivityCoreactivity() {
    }

	
    public MProductivityCoreactivity(int productivityCoreactivityId) {
        this.productivityCoreactivityId = productivityCoreactivityId;
    }
    public MProductivityCoreactivity(int productivityCoreactivityId, String productivityCoreactivityDesc, Date createdOn, String requestIp, Date updatedOn, Boolean isActive, Set<ProductionDetail> productionDetails, Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids, Character coverArea) {
       this.productivityCoreactivityId = productivityCoreactivityId;
       this.productivityCoreactivityDesc = productivityCoreactivityDesc;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.isActive = isActive;
       this.productionDetails = productionDetails;
       this.wdcpmksyPrdouctionWorkids = wdcpmksyPrdouctionWorkids;
       this.coverArea=coverArea;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="productivity_coreactivity_id", unique=true, nullable=false)
    public int getProductivityCoreactivityId() {
        return this.productivityCoreactivityId;
    }
    
    public void setProductivityCoreactivityId(int productivityCoreactivityId) {
        this.productivityCoreactivityId = productivityCoreactivityId;
    }

    
    @Column(name="productivity_coreactivity_desc", length=50)
    public String getProductivityCoreactivityDesc() {
        return this.productivityCoreactivityDesc;
    }
    
    public void setProductivityCoreactivityDesc(String productivityCoreactivityDesc) {
        this.productivityCoreactivityDesc = productivityCoreactivityDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MProductivityCoreactivity")
    public Set<ProductionDetail> getProductionDetails() {
        return this.productionDetails;
    }
    
    public void setProductionDetails(Set<ProductionDetail> productionDetails) {
        this.productionDetails = productionDetails;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MProductivityCoreactivity")
    public Set<WdcpmksyPrdouctionWorkid> getWdcpmksyPrdouctionWorkids() {
        return this.wdcpmksyPrdouctionWorkids;
    }
    
    public void setWdcpmksyPrdouctionWorkids(Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids) {
        this.wdcpmksyPrdouctionWorkids = wdcpmksyPrdouctionWorkids;
    }

    @Column(name="cover_area", length=1)
	public Character getCoverArea() {
		return coverArea;
	}


	public void setCoverArea(Character coverArea) {
		this.coverArea = coverArea;
	}


}


