package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MShgCoreactivity generated by hbm2java
 */
@Entity
@Table(name="m_shg_coreactivity"
    ,schema="public"
)
public class MShgCoreactivity  implements java.io.Serializable {


     private int shgCoreactivityId;
     private String shgCoreactivityDesc;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private Boolean isActive;
     private String createdBy;
     private Set<ShgCoreactivityDetail> shgCoreactivityDetails = new HashSet<ShgCoreactivityDetail>(0);

    public MShgCoreactivity() {
    }

	
    public MShgCoreactivity(int shgCoreactivityId) {
        this.shgCoreactivityId = shgCoreactivityId;
    }
    public MShgCoreactivity(int shgCoreactivityId, String shgCoreactivityDesc, Date createdOn, String requestIp, Date updatedOn, Boolean isActive, String createdBy, Set<ShgCoreactivityDetail> shgCoreactivityDetails) {
       this.shgCoreactivityId = shgCoreactivityId;
       this.shgCoreactivityDesc = shgCoreactivityDesc;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.shgCoreactivityDetails = shgCoreactivityDetails;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="shg_coreactivity_id", unique=true, nullable=false)
    public int getShgCoreactivityId() {
        return this.shgCoreactivityId;
    }
    
    public void setShgCoreactivityId(int shgCoreactivityId) {
        this.shgCoreactivityId = shgCoreactivityId;
    }

    
    @Column(name="shg_coreactivity_desc", length=50)
    public String getShgCoreactivityDesc() {
        return this.shgCoreactivityDesc;
    }
    
    public void setShgCoreactivityDesc(String shgCoreactivityDesc) {
        this.shgCoreactivityDesc = shgCoreactivityDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MShgCoreactivity")
    public Set<ShgCoreactivityDetail> getShgCoreactivityDetails() {
        return this.shgCoreactivityDetails;
    }
    
    public void setShgCoreactivityDetails(Set<ShgCoreactivityDetail> shgCoreactivityDetails) {
        this.shgCoreactivityDetails = shgCoreactivityDetails;
    }




}


