package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MTrainingSubject generated by hbm2java
 */
@Entity
@Table(name="m_training_subject",schema="public")
public class MTrainingSubject  implements java.io.Serializable {


     private int trainingSubId;
     private String trainingSubDesc;
     private Boolean isActive;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private String createdBy;
     private Set<TrainingSubjectDetail> trainingSubjectDetails = new HashSet<TrainingSubjectDetail>(0);

    public MTrainingSubject() {
    }

	
    public MTrainingSubject(int trainingSubId) {
        this.trainingSubId = trainingSubId;
    }
    public MTrainingSubject(int trainingSubId, String trainingSubDesc, Boolean isActive, Date createdOn, String requestIp, Date updatedOn, String createdBy, Set<TrainingSubjectDetail> trainingSubjectDetails) {
       this.trainingSubId = trainingSubId;
       this.trainingSubDesc = trainingSubDesc;
       this.isActive = isActive;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
       this.trainingSubjectDetails = trainingSubjectDetails;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="training_sub_id", unique=true, nullable=false)
    public int getTrainingSubId() {
        return this.trainingSubId;
    }
    
    public void setTrainingSubId(int trainingSubId) {
        this.trainingSubId = trainingSubId;
    }

    
    @Column(name="training_sub_desc", length=250)
    public String getTrainingSubDesc() {
        return this.trainingSubDesc;
    }
    
    public void setTrainingSubDesc(String trainingSubDesc) {
        this.trainingSubDesc = trainingSubDesc;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="MTrainingSubject")
    public Set<TrainingSubjectDetail> getTrainingSubjectDetails() {
        return this.trainingSubjectDetails;
    }
    
    public void setTrainingSubjectDetails(Set<TrainingSubjectDetail> trainingSubjectDetails) {
        this.trainingSubjectDetails = trainingSubjectDetails;
    }




}


