package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import app.model.project.WdcpmksyPrdouctionWorkid;
/**
 * ProductionDetail generated by hbm2java
 */
@Entity
@Table(name="production_detail"
    ,schema="public"
)
public class ProductionDetail  implements java.io.Serializable {


     private int productionDetailId;
     private MCroptype MCroptype;
     private MProductivityCoreactivity MProductivityCoreactivity;
     private BigDecimal postAvgIncome;
     private BigDecimal preAvgIncome;
     private Date createdOn;
     private LivelihoodEpaProd livelihoodEpaProd;
     private Integer noActivities;
     private Integer other;
     private String requestIp;
     private Integer sc;
     private Integer st;
     private Date updatedOn;
     private Integer women;
     private String status;
     private String poststatus;
     private Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids = new HashSet<WdcpmksyPrdouctionWorkid>(0);

    public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public ProductionDetail() {
    }

	
    public ProductionDetail(int productionDetailId, LivelihoodEpaProd livelihoodEpaProd) {
        this.productionDetailId = productionDetailId;
        this.livelihoodEpaProd = livelihoodEpaProd;
    }
    public ProductionDetail(int productionDetailId,String status, MCroptype MCroptype, MProductivityCoreactivity MProductivityCoreactivity, BigDecimal averageIncome, Date createdOn, LivelihoodEpaProd livelihoodEpaProd, Integer noActivities, Integer other, String requestIp, Integer sc, Integer st, Date updatedOn, Integer women, Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids) {
       this.productionDetailId = productionDetailId;
       this.MCroptype = MCroptype;
       this.MProductivityCoreactivity = MProductivityCoreactivity;
       this.preAvgIncome = averageIncome;
       this.createdOn = createdOn;
       this.livelihoodEpaProd = livelihoodEpaProd;
       this.noActivities = noActivities;
       this.other = other;
       this.requestIp = requestIp;
       this.sc = sc;
       this.st = st;
       this.updatedOn = updatedOn;
       this.women = women;
       this.status=status;
       this.wdcpmksyPrdouctionWorkids = wdcpmksyPrdouctionWorkids;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="production_detail_id", unique=true, nullable=false)
    public int getProductionDetailId() {
        return this.productionDetailId;
    }
    
    public void setProductionDetailId(int productionDetailId) {
        this.productionDetailId = productionDetailId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="crop_id")
    public MCroptype getMCroptype() {
        return this.MCroptype;
    }
    
    public void setMCroptype(MCroptype MCroptype) {
        this.MCroptype = MCroptype;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="livelihood_coreactivity_id")
    public MProductivityCoreactivity getMProductivityCoreactivity() {
        return this.MProductivityCoreactivity;
    }
    
    public void setMProductivityCoreactivity(MProductivityCoreactivity MProductivityCoreactivity) {
        this.MProductivityCoreactivity = MProductivityCoreactivity;
    }

    
    @Column(name="post_avg_income", precision=10)
    public BigDecimal getPostAvgIncome() {
        return this.postAvgIncome;
    }
    
    public void setPostAvgIncome(BigDecimal increaseIncome) {
        this.postAvgIncome = increaseIncome;
    }
    
    @Column(name="pre_avg_income", precision=10)
    public BigDecimal getPreAvgIncome() {
        return this.preAvgIncome;
    }
    
    public void setPreAvgIncome(BigDecimal increaseIncome) {
        this.preAvgIncome = increaseIncome;
    }

    @Column(name="post_status")
    public String getPoststatus() {
		return poststatus;
	}


	public void setPoststatus(String poststatus) {
		this.poststatus = poststatus;
	}


	@Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="lep_id", nullable=false)
    public LivelihoodEpaProd getLivelihoodEpaProd() {
        return this.livelihoodEpaProd;
    }
    
    public void setLivelihoodEpaProd(LivelihoodEpaProd livelihoodEpaProd) {
        this.livelihoodEpaProd = livelihoodEpaProd;
    }

    
    @Column(name="no_activities")
    public Integer getNoActivities() {
        return this.noActivities;
    }
    
    public void setNoActivities(Integer noActivities) {
        this.noActivities = noActivities;
    }

    
    @Column(name="other")
    public Integer getOther() {
        return this.other;
    }
    
    public void setOther(Integer other) {
        this.other = other;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="sc")
    public Integer getSc() {
        return this.sc;
    }
    
    public void setSc(Integer sc) {
        this.sc = sc;
    }

    
    @Column(name="st")
    public Integer getSt() {
        return this.st;
    }
    
    public void setSt(Integer st) {
        this.st = st;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="women")
    public Integer getWomen() {
        return this.women;
    }
    
    public void setWomen(Integer women) {
        this.women = women;
    }
    @OneToMany(fetch=FetchType.LAZY, mappedBy="productionDetail")
    public Set<WdcpmksyPrdouctionWorkid> getWdcpmksyPrdouctionWorkids() {
        return this.wdcpmksyPrdouctionWorkids;
    }
    
    public void setWdcpmksyPrdouctionWorkids(Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids) {
        this.wdcpmksyPrdouctionWorkids = wdcpmksyPrdouctionWorkids;
    }



}


