package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShgCoreactivityDetail generated by hbm2java
 */
@Entity
@Table(name="shg_coreactivity_detail"
    ,schema="public"
)
public class ShgCoreactivityDetail  implements java.io.Serializable {


     private int shgCoreactivityDetailId;
     private MShgCoreactivity MShgCoreactivity;
     private ShgDetail shgDetail;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private String createdBy;

    public ShgCoreactivityDetail() {
    }

	
    public ShgCoreactivityDetail(int shgCoreactivityDetailId) {
        this.shgCoreactivityDetailId = shgCoreactivityDetailId;
    }
    public ShgCoreactivityDetail(int shgCoreactivityDetailId, MShgCoreactivity MShgCoreactivity, ShgDetail shgDetail, Date createdOn, String requestIp, Date updatedOn, String createdBy) {
       this.shgCoreactivityDetailId = shgCoreactivityDetailId;
       this.MShgCoreactivity = MShgCoreactivity;
       this.shgDetail = shgDetail;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="shg_coreactivity_detail_id", unique=true, nullable=false)
    public int getShgCoreactivityDetailId() {
        return this.shgCoreactivityDetailId;
    }
    
    public void setShgCoreactivityDetailId(int shgCoreactivityDetailId) {
        this.shgCoreactivityDetailId = shgCoreactivityDetailId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="shg_coreactivity_id")
    public MShgCoreactivity getMShgCoreactivity() {
        return this.MShgCoreactivity;
    }
    
    public void setMShgCoreactivity(MShgCoreactivity MShgCoreactivity) {
        this.MShgCoreactivity = MShgCoreactivity;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="shg_detail_id")
    public ShgDetail getShgDetail() {
        return this.shgDetail;
    }
    
    public void setShgDetail(ShgDetail shgDetail) {
        this.shgDetail = shgDetail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


