package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import app.model.MDepartmentScheme;
/**
 * ShgDetail generated by hbm2java
 */
@Entity
@Table(name="shg_detail" ,schema="public")

public class ShgDetail  implements java.io.Serializable {


     private int shgDetailId;
     private ShgMain shgMain;
     private String name;
     private Integer sc;
     private Integer st;
     private Integer other;
     private Integer women;
     private BigDecimal avgTurnover;
     private BigDecimal avgIncome;
     private Integer pmBimaYogana;
     private Boolean federated;
     private Date createdOn;
     private String requestIp;
     private Date updatedOn;
     private String createdBy;
     private Set<ShgCoreactivityDetail> shgCoreactivityDetails = new HashSet<ShgCoreactivityDetail>(0);
     private MDepartmentScheme MDepartmentScheme;
     private Date regDate;
     private BigDecimal revolvingAmount;
     private Boolean thriftCredit;
     
 	 private String accountDetail;
 	 private Character status;
 	 private String ifsCode;
 	
    public ShgDetail() {
    }

	
    public ShgDetail(int shgDetailId) {
        this.shgDetailId = shgDetailId;
    }
    public ShgDetail(int shgDetailId, ShgMain shgMain, String name, Integer sc, Integer st, Integer other, Integer women, BigDecimal avgTurnover, 
    		BigDecimal avgIncome, Integer pmBimaYogana, Boolean federated, Date createdOn, String requestIp, Date updatedOn, String createdBy, 
    		Set<ShgCoreactivityDetail> shgCoreactivityDetails, MDepartmentScheme MDepartmentScheme, String accountDetail, Character status, String ifsCode) {
       this.shgDetailId = shgDetailId;
       this.shgMain = shgMain;
       this.name = name;
       this.sc = sc;
       this.st = st;
       this.other = other;
       this.women = women;
       this.avgTurnover = avgTurnover;
       this.avgIncome = avgIncome;
       this.pmBimaYogana = pmBimaYogana;
       this.federated = federated;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.updatedOn = updatedOn;
       this.createdBy = createdBy;
       this.shgCoreactivityDetails = shgCoreactivityDetails;
       this.accountDetail = accountDetail;
       this.status = status;
       this.ifsCode = ifsCode;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="shg_detail_id", unique=true, nullable=false)
    public int getShgDetailId() {
        return this.shgDetailId;
    }
    
    public void setShgDetailId(int shgDetailId) {
        this.shgDetailId = shgDetailId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="shg_id")
    public ShgMain getShgMain() {
        return this.shgMain;
    }
    
    public void setShgMain(ShgMain shgMain) {
        this.shgMain = shgMain;
    }

    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="sc")
    public Integer getSc() {
        return this.sc;
    }
    
    public void setSc(Integer sc) {
        this.sc = sc;
    }

    
    @Column(name="st")
    public Integer getSt() {
        return this.st;
    }
    
    public void setSt(Integer st) {
        this.st = st;
    }

    
    @Column(name="other")
    public Integer getOther() {
        return this.other;
    }
    
    public void setOther(Integer other) {
        this.other = other;
    }

    
    @Column(name="women")
    public Integer getWomen() {
        return this.women;
    }
    
    public void setWomen(Integer women) {
        this.women = women;
    }

    
    @Column(name="avg_turnover", precision=10)
    public BigDecimal getAvgTurnover() {
        return this.avgTurnover;
    }
    
    public void setAvgTurnover(BigDecimal avgTurnover) {
        this.avgTurnover = avgTurnover;
    }

    
    @Column(name="avg_income", precision=10)
    public BigDecimal getAvgIncome() {
        return this.avgIncome;
    }
    
    public void setAvgIncome(BigDecimal avgIncome) {
        this.avgIncome = avgIncome;
    }

    
    @Column(name="pm_bima_yogana")
    public Integer getPmBimaYogana() {
        return this.pmBimaYogana;
    }
    
    public void setPmBimaYogana(Integer pmBimaYogana) {
        this.pmBimaYogana = pmBimaYogana;
    }

    
    @Column(name="federated")
    public Boolean getFederated() {
        return this.federated;
    }
    
    public void setFederated(Boolean federated) {
        this.federated = federated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="shgDetail")
    public Set<ShgCoreactivityDetail> getShgCoreactivityDetails() {
        return this.shgCoreactivityDetails;
    }
    
    public void setShgCoreactivityDetails(Set<ShgCoreactivityDetail> shgCoreactivityDetails) {
        this.shgCoreactivityDetails = shgCoreactivityDetails;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_scheme_id")
    public MDepartmentScheme getMDepartmentScheme() {
        return this.MDepartmentScheme;
    }
    
    public void setMDepartmentScheme(MDepartmentScheme MDepartmentScheme) {
        this.MDepartmentScheme = MDepartmentScheme;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="reg_date", length=13)
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    
    @Column(name="revolving_amount", precision=10)
    public BigDecimal getRevolvingAmount() {
        return this.revolvingAmount;
    }
    
    public void setRevolvingAmount(BigDecimal revolvingAmount) {
        this.revolvingAmount = revolvingAmount;
    }

    
    @Column(name="thrift_credit")
    public Boolean getThriftCredit() {
        return this.thriftCredit;
    }
    
    public void setThriftCredit(Boolean thriftCredit) {
        this.thriftCredit = thriftCredit;
    }

    @Column(name="account_detail")
	public String getAccountDetail() {
		return accountDetail;
	}


	public void setAccountDetail(String accountDetail) {
		this.accountDetail = accountDetail;
	}

	@Column(name="status")
	public Character getStatus() {
		return status;
	}


	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name="ifsc_code")
	public String getIfsCode() {
		return ifsCode;
	}


	public void setIfsCode(String ifsCode) {
		this.ifsCode = ifsCode;
	}


    
}


