package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMProject;

/**
 * ShgMain generated by hbm2java
 */
@Entity
@Table(name="shg_main"
    ,schema="public"
)
public class ShgMain  implements java.io.Serializable {


     private int shgId;
     private IwmpMProject iwmpMProject;
     private String groupType;
     private Integer totalno;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Character status;
     private Set<ShgDetail> shgDetails = new HashSet<ShgDetail>(0);

    public ShgMain() {
    }

	
    public ShgMain(int shgId) {
        this.shgId = shgId;
    }
    public ShgMain(int shgId, IwmpMProject iwmpMProject, String groupType, Integer totalno, Date createdOn, Date updatedOn, String requestIp, String createdBy, Set<ShgDetail> shgDetails) {
       this.shgId = shgId;
       this.iwmpMProject = iwmpMProject;
       this.groupType = groupType;
       this.totalno = totalno;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.shgDetails = shgDetails;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="shg_id", unique=true, nullable=false)
    public int getShgId() {
        return this.shgId;
    }
    
    public void setShgId(int shgId) {
        this.shgId = shgId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

    
    @Column(name="group_type", length=30)
    public String getGroupType() {
        return this.groupType;
    }
    
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    
    @Column(name="totalno")
    public Integer getTotalno() {
        return this.totalno;
    }
    
    public void setTotalno(Integer totalno) {
        this.totalno = totalno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    
    @Column(name="status", length=1)
public Character getStatus() {
		return status;
	}


	public void setStatus(Character status) {
		this.status = status;
	}


@OneToMany(fetch=FetchType.LAZY, mappedBy="shgMain")
    public Set<ShgDetail> getShgDetails() {
        return this.shgDetails;
    }
    
    public void setShgDetails(Set<ShgDetail> shgDetails) {
        this.shgDetails = shgDetails;
    }




}


