package app.model.outcome;
// Generated 9 Dec, 2021 3:12:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrainingSubjectDetail generated by hbm2java
 */
@Entity
@Table(name="training_subject_detail",schema="public")
public class TrainingSubjectDetail  implements java.io.Serializable {


     private int trainingSubjectId;
     private MTrainingSubject MTrainingSubject;
     private TrainingDetail trainingDetail;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;

    public TrainingSubjectDetail() {
    }

	
    public TrainingSubjectDetail(int trainingSubjectId, TrainingDetail trainingDetail) {
        this.trainingSubjectId = trainingSubjectId;
        this.trainingDetail = trainingDetail;
    }
    public TrainingSubjectDetail(int trainingSubjectId, MTrainingSubject MTrainingSubject, TrainingDetail trainingDetail, Date createdOn, Date updatedOn, String requestIp, String createdBy) {
       this.trainingSubjectId = trainingSubjectId;
       this.MTrainingSubject = MTrainingSubject;
       this.trainingDetail = trainingDetail;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="training_subject_id", unique=true, nullable=false)
    public int getTrainingSubjectId() {
        return this.trainingSubjectId;
    }
    
    public void setTrainingSubjectId(int trainingSubjectId) {
        this.trainingSubjectId = trainingSubjectId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="training_sub_id")
    public MTrainingSubject getMTrainingSubject() {
        return this.MTrainingSubject;
    }
    
    public void setMTrainingSubject(MTrainingSubject MTrainingSubject) {
        this.MTrainingSubject = MTrainingSubject;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="training_detail_id", nullable=false)
    public TrainingDetail getTrainingDetail() {
        return this.trainingDetail;
    }
    
    public void setTrainingDetail(TrainingDetail trainingDetail) {
        this.trainingDetail = trainingDetail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


