package app.model.outcome;
// Generated 9 Dec, 2021 12:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrainingMain generated by hbm2java
 */
@Entity
@Table(name="training_main",schema="public")
public class TrainingMain  implements java.io.Serializable {


     private int trainingId;
     private String trainingLevel;
     private Integer totalno;
     private Date createdOn;
     private Date updatedOn;
     private String requestIp;
     private String createdBy;
     private Integer state_cd;
     private Set<TrainingDetail> trainingDetails = new HashSet<TrainingDetail>(0);

    public TrainingMain() {
    }

	
    public TrainingMain(int trainingId) {
        this.trainingId = trainingId;
    }
    public TrainingMain(int trainingId, String trainingLevel, Integer totalno, Date createdOn, Date updatedOn, String requestIp, String createdBy, Integer state_cd, Set<TrainingDetail> trainingDetails) {
       this.trainingId = trainingId;
       this.trainingLevel = trainingLevel;
       this.totalno = totalno;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.createdBy = createdBy;
       this.state_cd = state_cd;
       this.trainingDetails = trainingDetails;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="training_id", unique=true, nullable=false)
    public int getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(int trainingId) {
        this.trainingId = trainingId;
    }

    
    @Column(name="training_level", length=2)
    public String getTrainingLevel() {
        return this.trainingLevel;
    }
    
    public void setTrainingLevel(String trainingLevel) {
        this.trainingLevel = trainingLevel;
    }

    
    @Column(name="totalno")
    public Integer getTotalno() {
        return this.totalno;
    }
    
    public void setTotalno(Integer totalno) {
        this.totalno = totalno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_on", length=13)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="trainingMain")
    public Set<TrainingDetail> getTrainingDetails() {
        return this.trainingDetails;
    }
    
    public void setTrainingDetails(Set<TrainingDetail> trainingDetails) {
        this.trainingDetails = trainingDetails;
    }

    @Column(name="st_code")
	public Integer getState_cd() {
		return state_cd;
	}


	public void setState_cd(Integer state_cd) {
		this.state_cd = state_cd;
	}
    
    




}


