package app.bean.menu;
// Generated 22 Nov, 2021 11:39:34 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.bean.IwmpMenu;

/**
 * IwmpMMenu generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_menu"
    ,schema="public"
)
public class IwmpMMenu  implements java.io.Serializable {


     private int menuId;
     private String menuName;
     private String menuHindiName;
     private BigDecimal hseqNo;
     private Boolean isactive;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Set<IwmpMenu> iwmpMSubmenus = new HashSet<IwmpMenu>(0);

    public IwmpMMenu() {
    }

	
    public IwmpMMenu(int menuId, String menuName, String menuHindiName) {
        this.menuId = menuId;
        this.menuName = menuName;
        this.menuHindiName = menuHindiName;
    }
    public IwmpMMenu(int menuId, String menuName, String menuHindiName ,BigDecimal hseqNo, Boolean isactive, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Set<IwmpMenu> iwmpMSubmenus) {
       this.menuId = menuId;
       this.menuName = menuName;
       this.menuHindiName = menuHindiName;
       this.hseqNo = hseqNo;
       this.isactive = isactive;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.iwmpMSubmenus = iwmpMSubmenus;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="menu_id", unique=true, nullable=false)
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }

    
    @Column(name="menu_name", nullable=false, length=100)
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    
    
    @Column(name="menu_hindi_name",  length=400)
    public String getMenuHindiName() {
		return menuHindiName;
	}


	public void setMenuHindiName(String menuHindiName) {
		this.menuHindiName = menuHindiName;
	}


	@Column(name="hseq_no", precision=6)
    public BigDecimal getHseqNo() {
        return this.hseqNo;
    }
    
    public void setHseqNo(BigDecimal hseqNo) {
        this.hseqNo = hseqNo;
    }

    
    @Column(name="isactive")
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMMenu",cascade=CascadeType.REMOVE,orphanRemoval = true)
    public Set<IwmpMenu> getIwmpMSubmenus() {
        return this.iwmpMSubmenus;
    }
    
    public void setIwmpMSubmenus(Set<IwmpMenu> iwmpMSubmenus) {
        this.iwmpMSubmenus = iwmpMSubmenus;
    }




}


