package app.bean.pfms;
// Generated 13 Apr, 2022 1:45:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfmsInvoiceData generated by hbm2java
 */
@Entity
@Table(name="pfms_invoice_data"
    ,schema="public"
)
public class PfmsInvoiceData  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pfmsid;
     private int invoiceno;
     private Integer stCode;
     private Integer distCode;
     private Integer blockCode;
     private String finCode;
     private Date invoiceDt;
     private BigDecimal amount;
     private Date createdon;
     private String createdby;
     private String projectName;
     private String headComponentName;
     private String stateName;
     private String districtName;
     private String subHeadCompnent;
     private String projectCode;
     private Integer transactionId;
     private Integer stateLgd;
     private Integer districtLgd;
     private Set<PfmsInvoiceProject> pfmsInvoiceProjects = new HashSet<PfmsInvoiceProject>(0);

    public PfmsInvoiceData() {
    }

	
    public PfmsInvoiceData(int pfmsid, int invoiceno) {
        this.pfmsid = pfmsid;
        this.invoiceno = invoiceno;
    }
    public PfmsInvoiceData(int pfmsid, int invoiceno, Integer stCode, Integer distCode, Integer blockCode, String finCode, Date invoiceDt, BigDecimal amount, Date createdon, String createdby, String projectName, String headComponentName, String stateName, String districtName, String subHeadCompnent, String projectCode, Integer transactionId, Integer stateLgd, Integer districtLgd, Set<PfmsInvoiceProject> pfmsInvoiceProjects) {
       this.pfmsid = pfmsid;
       this.invoiceno = invoiceno;
       this.stCode = stCode;
       this.distCode = distCode;
       this.blockCode = blockCode;
       this.finCode = finCode;
       this.invoiceDt = invoiceDt;
       this.amount = amount;
       this.createdon = createdon;
       this.createdby = createdby;
       this.projectName = projectName;
       this.headComponentName = headComponentName;
       this.stateName = stateName;
       this.districtName = districtName;
       this.subHeadCompnent = subHeadCompnent;
       this.projectCode = projectCode;
       this.transactionId = transactionId;
       this.stateLgd = stateLgd;
       this.districtLgd = districtLgd;
       this.pfmsInvoiceProjects = pfmsInvoiceProjects;
    }
   
     @Id 

    
    @Column(name="pfmsid", unique=true, nullable=false)
    public int getPfmsid() {
        return this.pfmsid;
    }
    
    public void setPfmsid(int pfmsid) {
        this.pfmsid = pfmsid;
    }

    
    @Column(name="invoiceno", nullable=false)
    public int getInvoiceno() {
        return this.invoiceno;
    }
    
    public void setInvoiceno(int invoiceno) {
        this.invoiceno = invoiceno;
    }

    
    @Column(name="st_code")
    public Integer getStCode() {
        return this.stCode;
    }
    
    public void setStCode(Integer stCode) {
        this.stCode = stCode;
    }

    
    @Column(name="dist_code")
    public Integer getDistCode() {
        return this.distCode;
    }
    
    public void setDistCode(Integer distCode) {
        this.distCode = distCode;
    }

    
    @Column(name="block_code")
    public Integer getBlockCode() {
        return this.blockCode;
    }
    
    public void setBlockCode(Integer blockCode) {
        this.blockCode = blockCode;
    }

    
    @Column(name="fin_code", length=9)
    public String getFinCode() {
        return this.finCode;
    }
    
    public void setFinCode(String finCode) {
        this.finCode = finCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="invoice_dt", length=13)
    public Date getInvoiceDt() {
        return this.invoiceDt;
    }
    
    public void setInvoiceDt(Date invoiceDt) {
        this.invoiceDt = invoiceDt;
    }

    
    @Column(name="amount", precision=10)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=35)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="createdby", length=10)
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    
    @Column(name="project_name", length=50)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    
    @Column(name="head_component_name", length=50)
    public String getHeadComponentName() {
        return this.headComponentName;
    }
    
    public void setHeadComponentName(String headComponentName) {
        this.headComponentName = headComponentName;
    }

    
    @Column(name="state_name", length=60)
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    
    @Column(name="district_name", length=70)
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    
    @Column(name="sub_head_compnent", length=70)
    public String getSubHeadCompnent() {
        return this.subHeadCompnent;
    }
    
    public void setSubHeadCompnent(String subHeadCompnent) {
        this.subHeadCompnent = subHeadCompnent;
    }

    
    @Column(name="project_code", length=50)
    public String getProjectCode() {
        return this.projectCode;
    }
    
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    
    @Column(name="transaction_id")
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    
    @Column(name="state_lgd")
    public Integer getStateLgd() {
        return this.stateLgd;
    }
    
    public void setStateLgd(Integer stateLgd) {
        this.stateLgd = stateLgd;
    }

    
    @Column(name="district_lgd")
    public Integer getDistrictLgd() {
        return this.districtLgd;
    }
    
    public void setDistrictLgd(Integer districtLgd) {
        this.districtLgd = districtLgd;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pfmsInvoiceData")
    public Set<PfmsInvoiceProject> getPfmsInvoiceProjects() {
        return this.pfmsInvoiceProjects;
    }
    
    public void setPfmsInvoiceProjects(Set<PfmsInvoiceProject> pfmsInvoiceProjects) {
        this.pfmsInvoiceProjects = pfmsInvoiceProjects;
    }




}


