package app.model.master;
// Generated 12 Mar, 2021 11:27:35 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import app.janbhagidariPratiyogita.JanbhagidariPratiyogitaNgovillage;
import app.janbhagidariPratiyogita.JanbhagidariPratiyogitaTypeofWork;
import app.mahotsav.model.MahotsavPrabhatPheri;
import app.mahotsav.model.WatershedMahotsavVideoDetails;
import app.model.BlsOutMain;
import app.model.BlsOutMainAchiev;
import app.model.BlsOutMainHis;
import app.model.project.IwmpProjectPhysicalAsset;
import app.model.project.IwmpProjectPhysicalAssetTemp;
import app.model.project.WdcpmksyEpaWorkid;
import app.model.project.WdcpmksyLivelihoodWorkid;
import app.model.project.WdcpmksyPrdouctionWorkid;
import app.punarutthan.model.Wdcpmksy1PunarutthanPlan;
import app.watershedyatra.model.PreYatraPreparation;
import app.watershedyatra.model.RoutePlanVanTravel;
import app.watershedyatra.model.WatershedYatVill;
import app.watershedyatra.model.WatershedYatVillDuplicate;

/**
 * IwmpVillage generated by hbm2java
 */
@Entity
@Table(name = "iwmp_village", schema = "public")
public class IwmpVillage implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int vcode;
	private IwmpGramPanchayat iwmpGramPanchayat;
	private int stCode;
	private int distCode;
	private int blockCode;
	private int gramPanchayatLgdcode;
	private int villageLgdcode;
	private String villageName;
	private String importType;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private String stateCode2001;
	private String stateCode2011;
	private String districtCode2001;
	private String districtCode2011;
	private String subdistrictCode2001;
	private String subdistrictCode2011;
	private String villageCode2001;
	private String villageCode2011;
	private String censusCodePortedData;
	private Boolean active;
	private Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets = new HashSet<IwmpProjectPhysicalAsset>(0);
	private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
	private Set<BlsOutMain> blsOutMains = new HashSet<BlsOutMain>(0);
	private Set<BlsOutMainAchiev> blsOutMainAchievs = new HashSet<BlsOutMainAchiev>(0);
    private Set<BlsOutMainHis> blsOutMainHises = new HashSet<BlsOutMainHis>(0);
    private Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids = new HashSet<WdcpmksyPrdouctionWorkid>(0);
    private Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids = new HashSet<WdcpmksyEpaWorkid>(0);
    private Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids = new HashSet<WdcpmksyLivelihoodWorkid>(0);
    private Set<WatershedYatVill> watershedYatVill = new HashSet<WatershedYatVill>(0);
    private Set<RoutePlanVanTravel> routePlanVanTravel = new HashSet<RoutePlanVanTravel>(0);
    private Set<PreYatraPreparation> preYatraPreparation = new HashSet<PreYatraPreparation>(0);
    private Set<WatershedYatVillDuplicate> watershedYatVillDuplicate = new HashSet<WatershedYatVillDuplicate>(0);
    private Set<JanbhagidariPratiyogitaNgovillage> janbhagidariPratiyogitaNgovillage = new HashSet<JanbhagidariPratiyogitaNgovillage>(0);
    private Set<JanbhagidariPratiyogitaTypeofWork> janbhagidariPratiyogitaTypeofWork = new HashSet<JanbhagidariPratiyogitaTypeofWork>(0);
    private Set<WatershedMahotsavVideoDetails> watershedMahotsavVideoDetails = new HashSet<WatershedMahotsavVideoDetails>(0);
    private Set<MahotsavPrabhatPheri> wmPrabhatPheri = new HashSet<MahotsavPrabhatPheri>(0);
    private Set<Wdcpmksy1PunarutthanPlan> wdcpmksy1PunarutthanPlan = new HashSet<Wdcpmksy1PunarutthanPlan>(0);
    
    
    
	@Transient
	private boolean updatestatus;

	@Transient
	public boolean getUpdatestatus() {
		return updatestatus;
	}

	public void setUpdatestatus(boolean updatestatus) {
		this.updatestatus = updatestatus;
	}

	public IwmpVillage() {
	}

	public IwmpVillage(int vcode, int stCode, int distCode, int blockCode, int gramPanchayatLgdcode, int villageLgdcode,
			String villageName) {
		this.vcode = vcode;
		this.stCode = stCode;
		this.distCode = distCode;
		this.blockCode = blockCode;
		this.gramPanchayatLgdcode = gramPanchayatLgdcode;
		this.villageLgdcode = villageLgdcode;
		this.villageName = villageName;
	}

	public IwmpVillage(int vcode, IwmpGramPanchayat iwmpGramPanchayat, int stCode, int distCode, int blockCode,
			int gramPanchayatLgdcode, int villageLgdcode, String villageName, String importType,
			String lastUpdatedBy, Date lastUpdatedDate, String requestIp, String stateCode2001, String stateCode2011,
			String districtCode2001, String districtCode2011, String subdistrictCode2001, String subdistrictCode2011,
			String villageCode2001, String villageCode2011, String censusCodePortedData, Boolean active, Set<WatershedYatVill> watershedYatVill,
			Set<RoutePlanVanTravel> routePlanVanTravel, Set<PreYatraPreparation> preYatraPreparation, Set<WatershedYatVillDuplicate> watershedYatVillDuplicate,
			Set<JanbhagidariPratiyogitaTypeofWork> janbhagidariPratiyogitaTypeofWork, Set<WatershedMahotsavVideoDetails> watershedMahotsavVideoDetails,Set<MahotsavPrabhatPheri> wmPrabhatPheri,
			Set<Wdcpmksy1PunarutthanPlan> wdcpmksy1PunarutthanPlan) {
		this.vcode = vcode;
		this.iwmpGramPanchayat = iwmpGramPanchayat;
		this.stCode = stCode;
		this.distCode = distCode;
		this.blockCode = blockCode;
		this.gramPanchayatLgdcode = gramPanchayatLgdcode;
		this.villageLgdcode = villageLgdcode;
		this.villageName = villageName;
		this.importType = importType;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
		this.stateCode2001 = stateCode2001;
		this.stateCode2011 = stateCode2011;
		this.districtCode2001 = districtCode2001;
		this.districtCode2011 = districtCode2011;
		this.subdistrictCode2001 = subdistrictCode2001;
		this.subdistrictCode2011 = subdistrictCode2011;
		this.villageCode2001 = villageCode2001;
		this.villageCode2011 = villageCode2011;
		this.censusCodePortedData = censusCodePortedData;
		this.active = active;
		this.watershedYatVill=watershedYatVill;
		this.routePlanVanTravel=routePlanVanTravel;
		this.preYatraPreparation=preYatraPreparation;
		this.watershedYatVillDuplicate=watershedYatVillDuplicate;
		this.janbhagidariPratiyogitaTypeofWork=janbhagidariPratiyogitaTypeofWork;
		this.watershedMahotsavVideoDetails = watershedMahotsavVideoDetails;
		this.wmPrabhatPheri = wmPrabhatPheri;
		this.wdcpmksy1PunarutthanPlan=wdcpmksy1PunarutthanPlan;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "vcode", unique = true, nullable = false)
	public int getVcode() {
		return this.vcode;
	}

	public void setVcode(int vcode) {
		this.vcode = vcode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gcode")
	public IwmpGramPanchayat getIwmpGramPanchayat() {
		return this.iwmpGramPanchayat;
	}

	public void setIwmpGramPanchayat(IwmpGramPanchayat iwmpGramPanchayat) {
		this.iwmpGramPanchayat = iwmpGramPanchayat;
	}

	@Column(name = "st_code", nullable = false)
	public int getStCode() {
		return this.stCode;
	}

	public void setStCode(int stCode) {
		this.stCode = stCode;
	}

	@Column(name = "dist_code", nullable = false)
	public int getDistCode() {
		return this.distCode;
	}

	public void setDistCode(int distCode) {
		this.distCode = distCode;
	}

	@Column(name = "block_code", nullable = false)
	public int getBlockCode() {
		return this.blockCode;
	}

	public void setBlockCode(int blockCode) {
		this.blockCode = blockCode;
	}

	@Column(name = "gram_panchayat_lgdcode", nullable = false)
	public int getGramPanchayatLgdcode() {
		return this.gramPanchayatLgdcode;
	}

	public void setGramPanchayatLgdcode(int gramPanchayatLgdcode) {
		this.gramPanchayatLgdcode = gramPanchayatLgdcode;
	}

	@Column(name = "village_lgdcode", nullable = false)
	public int getVillageLgdcode() {
		return this.villageLgdcode;
	}

	public void setVillageLgdcode(int villageLgdcode) {
		this.villageLgdcode = villageLgdcode;
	}

	@Column(name = "village_name", nullable = false, length = 200)
	public String getVillageName() {
		return this.villageName;
	}

	public void setVillageName(String villageName) {
		this.villageName = villageName;
	}

	@Column(name = "import_type", length = 4)
	public String getImportType() {
		return this.importType;
	}

	public void setImportType(String importType) {
		this.importType = importType;
	}

	@Column(name = "last_updated_by", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "state_code2001", length = 200)
	public String getStateCode2001() {
		return this.stateCode2001;
	}

	public void setStateCode2001(String stateCode2001) {
		this.stateCode2001 = stateCode2001;
	}

	@Column(name = "state_code2011", length = 200)
	public String getStateCode2011() {
		return this.stateCode2011;
	}

	public void setStateCode2011(String stateCode2011) {
		this.stateCode2011 = stateCode2011;
	}

	@Column(name = "district_code2001", length = 200)
	public String getDistrictCode2001() {
		return this.districtCode2001;
	}

	public void setDistrictCode2001(String districtCode2001) {
		this.districtCode2001 = districtCode2001;
	}

	@Column(name = "district_code2011", length = 200)
	public String getDistrictCode2011() {
		return this.districtCode2011;
	}

	public void setDistrictCode2011(String districtCode2011) {
		this.districtCode2011 = districtCode2011;
	}

	@Column(name = "subdistrict_code2001", length = 200)
	public String getSubdistrictCode2001() {
		return this.subdistrictCode2001;
	}

	public void setSubdistrictCode2001(String subdistrictCode2001) {
		this.subdistrictCode2001 = subdistrictCode2001;
	}

	@Column(name = "subdistrict_code2011", length = 200)
	public String getSubdistrictCode2011() {
		return this.subdistrictCode2011;
	}

	public void setSubdistrictCode2011(String subdistrictCode2011) {
		this.subdistrictCode2011 = subdistrictCode2011;
	}

	@Column(name = "village_code2001", length = 200)
	public String getVillageCode2001() {
		return this.villageCode2001;
	}

	public void setVillageCode2001(String villageCode2001) {
		this.villageCode2001 = villageCode2001;
	}

	@Column(name = "village_code2011", length = 200)
	public String getVillageCode2011() {
		return this.villageCode2011;
	}

	public void setVillageCode2011(String villageCode2011) {
		this.villageCode2011 = villageCode2011;
	}

	@Column(name = "census_code_ported_data", length = 1)
	public String getCensusCodePortedData() {
		return this.censusCodePortedData;
	}

	public void setCensusCodePortedData(String censusCodePortedData) {
		this.censusCodePortedData = censusCodePortedData;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}


	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<IwmpProjectPhysicalAsset> getIwmpProjectPhysicalAssets() {
        return this.iwmpProjectPhysicalAssets;
    }
    
    public void setIwmpProjectPhysicalAssets(Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets) {
        this.iwmpProjectPhysicalAssets = iwmpProjectPhysicalAssets;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemp() {
        return this.iwmpProjectPhysicalAssetTemp;
    }
    
    public void setIwmpProjectPhysicalAssetTemp(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp) {
        this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<BlsOutMain> getBlsOutMains() {
        return this.blsOutMains;
    }
    
    public void setBlsOutMains(Set<BlsOutMain> blsOutMains) {
        this.blsOutMains = blsOutMains;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<BlsOutMainAchiev> getBlsOutMainAchievs() {
        return this.blsOutMainAchievs;
    }
    
    public void setBlsOutMainAchievs(Set<BlsOutMainAchiev> blsOutMainAchievs) {
        this.blsOutMainAchievs = blsOutMainAchievs;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<BlsOutMainHis> getBlsOutMainHises() {
        return this.blsOutMainHises;
    }
    
    public void setBlsOutMainHises(Set<BlsOutMainHis> blsOutMainHises) {
        this.blsOutMainHises = blsOutMainHises;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<WdcpmksyPrdouctionWorkid> getWdcpmksyPrdouctionWorkids() {
        return this.wdcpmksyPrdouctionWorkids;
    }
    
    public void setWdcpmksyPrdouctionWorkids(Set<WdcpmksyPrdouctionWorkid> wdcpmksyPrdouctionWorkids) {
        this.wdcpmksyPrdouctionWorkids = wdcpmksyPrdouctionWorkids;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<WdcpmksyEpaWorkid> getWdcpmksyEpaWorkids() {
        return this.wdcpmksyEpaWorkids;
    }
    
    public void setWdcpmksyEpaWorkids(Set<WdcpmksyEpaWorkid> wdcpmksyEpaWorkids) {
        this.wdcpmksyEpaWorkids = wdcpmksyEpaWorkids;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
    public Set<WdcpmksyLivelihoodWorkid> getWdcpmksyLivelihoodWorkids() {
        return this.wdcpmksyLivelihoodWorkids;
    }
    
    public void setWdcpmksyLivelihoodWorkids(Set<WdcpmksyLivelihoodWorkid> wdcpmksyLivelihoodWorkids) {
        this.wdcpmksyLivelihoodWorkids = wdcpmksyLivelihoodWorkids;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<WatershedYatVill> getWatershedYatVill() {
		return watershedYatVill;
	}

	public void setWatershedYatVill(Set<WatershedYatVill> watershedYatVill) {
		this.watershedYatVill = watershedYatVill;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<RoutePlanVanTravel> getRoutePlanVanTravel() {
		return routePlanVanTravel;
	}

	public void setRoutePlanVanTravel(Set<RoutePlanVanTravel> routePlanVanTravel) {
		this.routePlanVanTravel = routePlanVanTravel;
	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<PreYatraPreparation> getPreYatraPreparation() {
		return preYatraPreparation;
	}

	public void setPreYatraPreparation(Set<PreYatraPreparation> preYatraPreparation) {
		this.preYatraPreparation = preYatraPreparation;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<WatershedYatVillDuplicate> getWatershedYatVillDuplicate() {
		return watershedYatVillDuplicate;
	}

	public void setWatershedYatVillDuplicate(Set<WatershedYatVillDuplicate> watershedYatVillDuplicate) {
		this.watershedYatVillDuplicate = watershedYatVillDuplicate;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<JanbhagidariPratiyogitaNgovillage> getJanbhagidariPratiyogitaNgovillage() {
		return janbhagidariPratiyogitaNgovillage;
	}

	public void setJanbhagidariPratiyogitaNgovillage(
			Set<JanbhagidariPratiyogitaNgovillage> janbhagidariPratiyogitaNgovillage) {
		this.janbhagidariPratiyogitaNgovillage = janbhagidariPratiyogitaNgovillage;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<JanbhagidariPratiyogitaTypeofWork> getJanbhagidariPratiyogitaTypeofWork() {
		return janbhagidariPratiyogitaTypeofWork;
	}

	public void setJanbhagidariPratiyogitaTypeofWork(
			Set<JanbhagidariPratiyogitaTypeofWork> janbhagidariPratiyogitaTypeofWork) {
		this.janbhagidariPratiyogitaTypeofWork = janbhagidariPratiyogitaTypeofWork;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<WatershedMahotsavVideoDetails> getWatershedMahotsavVideoDetails() {
		return watershedMahotsavVideoDetails;
	}

	public void setWatershedMahotsavVideoDetails(Set<WatershedMahotsavVideoDetails> watershedMahotsavVideoDetails) {
		this.watershedMahotsavVideoDetails = watershedMahotsavVideoDetails;
	}
    
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<MahotsavPrabhatPheri> getMahotsavPrabhatPheri() {
		return wmPrabhatPheri;
	}

	public void setMahotsavPrabhatPheri(Set<MahotsavPrabhatPheri> wmPrabhatPheri) {
		this.wmPrabhatPheri = wmPrabhatPheri;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpVillage")
	public Set<Wdcpmksy1PunarutthanPlan> getWdcpmksy1PunarutthanPlan() {
		return wdcpmksy1PunarutthanPlan;
	}

	public void setWdcpmksy1PunarutthanPlan(Set<Wdcpmksy1PunarutthanPlan> wdcpmksy1PunarutthanPlan) {
		this.wdcpmksy1PunarutthanPlan = wdcpmksy1PunarutthanPlan;
	}
    
	
	
}
