package app.model.master;
// Generated 26 Jul, 2021 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IwmpUploadCategory generated by hbm2java
 */
@Entity
@Table(name="iwmp_upload_category"
    ,schema="public"
)
public class IwmpUploadCategory  implements java.io.Serializable {


     private int id;
     private String categoryType;
     private String uploadCategory;
     private Set<IwmpUserUploadDetails> iwmpUserUploadDetailses = new HashSet<IwmpUserUploadDetails>(0);

    public IwmpUploadCategory() {
    }

	
    public IwmpUploadCategory(int id) {
        this.id = id;
    }
    public IwmpUploadCategory(int id, String categoryType, String uploadCategory, Set<IwmpUserUploadDetails> iwmpUserUploadDetailses) {
       this.id = id;
       this.categoryType = categoryType;
       this.uploadCategory = uploadCategory;
       this.iwmpUserUploadDetailses = iwmpUserUploadDetailses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="category_type", length=10)
    public String getCategoryType() {
        return this.categoryType;
    }
    
    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType;
    }

    
    @Column(name="upload_category", length=100)
    public String getUploadCategory() {
        return this.uploadCategory;
    }
    
    public void setUploadCategory(String uploadCategory) {
        this.uploadCategory = uploadCategory;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpUploadCategory")
    public Set<IwmpUserUploadDetails> getIwmpUserUploadDetailses() {
        return this.iwmpUserUploadDetailses;
    }
    
    public void setIwmpUserUploadDetailses(Set<IwmpUserUploadDetails> iwmpUserUploadDetailses) {
        this.iwmpUserUploadDetailses = iwmpUserUploadDetailses;
    }




}


