package app.model.master;
// Generated 12 Mar, 2021 11:27:35 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import app.model.IwmpDistrict;

/**
 * IwmpBlock generated by hbm2java
 */
@Entity
@Table(name = "iwmp_block", schema = "public")
public class IwmpBlock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int bcode;
	private IwmpDistrict iwmpDistrict;
	private int stCode;
	private int distCode;
	private int blockCode;
	private String blockName;
	private String ddp;
	private String dpap;
	private String iwdp;
	private Integer iwmp;
	private String importType;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private String stateCode2001;
	private String stateCode2011;
	private String districtCode2001;
	private String districtCode2011;
	private String subdistrictCode2001;
	private String subdistrictCode2011;
	private String censusCodePortedData;
	private Integer stateCodelgd;
	private Integer districtCodelgd;
	private Integer blockCodelgd;
	private Boolean active;
	private Set<IwmpGramPanchayat> iwmpGramPanchayats = new HashSet<IwmpGramPanchayat>(0);
	private Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails = new HashSet<PfmsEatmisdataDetail>(0);
	 
	@Transient
	private boolean updatestatus;

	@Transient
	public boolean getUpdatestatus() {
		return updatestatus;
	}

	public void setUpdatestatus(boolean updatestatus) {
		this.updatestatus = updatestatus;
	}

	public IwmpBlock() {
	}

	public IwmpBlock(int bcode, int stCode, int distCode, int blockCode, String blockName) {
		this.bcode = bcode;
		this.stCode = stCode;
		this.distCode = distCode;
		this.blockCode = blockCode;
		this.blockName = blockName;
	}

	public IwmpBlock(int bcode, IwmpDistrict iwmpDistrict, int stCode, int distCode, int blockCode, String blockName,
			String ddp, String dpap, String iwdp, Integer iwmp, String importType, String lastUpdatedBy,
			Date lastUpdatedDate, String requestIp, String stateCode2001, String stateCode2011, String districtCode2001,
			String districtCode2011, String subdistrictCode2001, String subdistrictCode2011,
			String censusCodePortedData, Integer stateCodelgd, Integer districtCodelgd, Integer blockCodelgd,
			Boolean active, Set<IwmpGramPanchayat> iwmpGramPanchayats, Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails) {
		this.bcode = bcode;
		this.iwmpDistrict = iwmpDistrict;
		this.stCode = stCode;
		this.distCode = distCode;
		this.blockCode = blockCode;
		this.blockName = blockName;
		this.ddp = ddp;
		this.dpap = dpap;
		this.iwdp = iwdp;
		this.iwmp = iwmp;
		this.importType = importType;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
		this.stateCode2001 = stateCode2001;
		this.stateCode2011 = stateCode2011;
		this.districtCode2001 = districtCode2001;
		this.districtCode2011 = districtCode2011;
		this.subdistrictCode2001 = subdistrictCode2001;
		this.subdistrictCode2011 = subdistrictCode2011;
		this.censusCodePortedData = censusCodePortedData;
		this.stateCodelgd = stateCodelgd;
		this.districtCodelgd = districtCodelgd;
		this.blockCodelgd = blockCodelgd;
		this.active = active;
		this.iwmpGramPanchayats = iwmpGramPanchayats;
		this.pfmsEatmisdataDetails = pfmsEatmisdataDetails;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "bcode", unique = true, nullable = false)
	public int getBcode() {
		return this.bcode;
	}

	public void setBcode(int bcode) {
		this.bcode = bcode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "dcode")
	public IwmpDistrict getIwmpDistrict() {
		return this.iwmpDistrict;
	}

	public void setIwmpDistrict(IwmpDistrict iwmpDistrict) {
		this.iwmpDistrict = iwmpDistrict;
	}

	@Column(name = "st_code", nullable = false)
	public int getStCode() {
		return this.stCode;
	}

	public void setStCode(int stCode) {
		this.stCode = stCode;
	}

	@Column(name = "dist_code", nullable = false)
	public int getDistCode() {
		return this.distCode;
	}

	public void setDistCode(int distCode) {
		this.distCode = distCode;
	}

	@Column(name = "block_code", nullable = false)
	public int getBlockCode() {
		return this.blockCode;
	}

	public void setBlockCode(int blockCode) {
		this.blockCode = blockCode;
	}

	@Column(name = "block_name", nullable = false, length = 50)
	public String getBlockName() {
		return this.blockName;
	}

	public void setBlockName(String blockName) {
		this.blockName = blockName;
	}

	@Column(name = "ddp", length = 11)
	public String getDdp() {
		return this.ddp;
	}

	public void setDdp(String ddp) {
		this.ddp = ddp;
	}

	@Column(name = "dpap", length = 11)
	public String getDpap() {
		return this.dpap;
	}

	public void setDpap(String dpap) {
		this.dpap = dpap;
	}

	@Column(name = "iwdp", length = 11)
	public String getIwdp() {
		return this.iwdp;
	}

	public void setIwdp(String iwdp) {
		this.iwdp = iwdp;
	}

	@Column(name = "iwmp")
	public Integer getIwmp() {
		return this.iwmp;
	}

	public void setIwmp(Integer iwmp) {
		this.iwmp = iwmp;
	}

	@Column(name = "import_type", length = 4)
	public String getImportType() {
		return this.importType;
	}

	public void setImportType(String importType) {
		this.importType = importType;
	}

	@Column(name = "last_updated_by", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "state_code2001", length = 200)
	public String getStateCode2001() {
		return this.stateCode2001;
	}

	public void setStateCode2001(String stateCode2001) {
		this.stateCode2001 = stateCode2001;
	}

	@Column(name = "state_code2011", length = 200)
	public String getStateCode2011() {
		return this.stateCode2011;
	}

	public void setStateCode2011(String stateCode2011) {
		this.stateCode2011 = stateCode2011;
	}

	@Column(name = "district_code2001", length = 200)
	public String getDistrictCode2001() {
		return this.districtCode2001;
	}

	public void setDistrictCode2001(String districtCode2001) {
		this.districtCode2001 = districtCode2001;
	}

	@Column(name = "district_code2011", length = 200)
	public String getDistrictCode2011() {
		return this.districtCode2011;
	}

	public void setDistrictCode2011(String districtCode2011) {
		this.districtCode2011 = districtCode2011;
	}

	@Column(name = "subdistrict_code2001", length = 200)
	public String getSubdistrictCode2001() {
		return this.subdistrictCode2001;
	}

	public void setSubdistrictCode2001(String subdistrictCode2001) {
		this.subdistrictCode2001 = subdistrictCode2001;
	}

	@Column(name = "subdistrict_code2011", length = 200)
	public String getSubdistrictCode2011() {
		return this.subdistrictCode2011;
	}

	public void setSubdistrictCode2011(String subdistrictCode2011) {
		this.subdistrictCode2011 = subdistrictCode2011;
	}

	@Column(name = "census_code_ported_data", length = 1)
	public String getCensusCodePortedData() {
		return this.censusCodePortedData;
	}

	public void setCensusCodePortedData(String censusCodePortedData) {
		this.censusCodePortedData = censusCodePortedData;
	}

	@Column(name = "state_codelgd")
	public Integer getStateCodelgd() {
		return this.stateCodelgd;
	}

	public void setStateCodelgd(Integer stateCodelgd) {
		this.stateCodelgd = stateCodelgd;
	}

	@Column(name = "district_codelgd")
	public Integer getDistrictCodelgd() {
		return this.districtCodelgd;
	}

	public void setDistrictCodelgd(Integer districtCodelgd) {
		this.districtCodelgd = districtCodelgd;
	}

	@Column(name = "block_codelgd")
	public Integer getBlockCodelgd() {
		return this.blockCodelgd;
	}

	public void setBlockCodelgd(Integer blockCodelgd) {
		this.blockCodelgd = blockCodelgd;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpBlock")
	public Set<IwmpGramPanchayat> getIwmpGramPanchayats() {
		return this.iwmpGramPanchayats;
	}

	public void setIwmpGramPanchayats(Set<IwmpGramPanchayat> iwmpGramPanchayats) {
		this.iwmpGramPanchayats = iwmpGramPanchayats;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpBlock")
    public Set<PfmsEatmisdataDetail> getPfmsEatmisdataDetails() {
        return this.pfmsEatmisdataDetails;
    }
    
    public void setPfmsEatmisdataDetails(Set<PfmsEatmisdataDetail> pfmsEatmisdataDetails) {
        this.pfmsEatmisdataDetails = pfmsEatmisdataDetails;
    }

}
