package app.model.master;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpMProject;
import app.model.project.IwmpProjectWc;

/**
* IwmpMWc generated by hbm2java
*/
@Entity
@Table(name="iwmp_m_wc",schema="public")
public class IwmpMWc  implements java.io.Serializable {

  private int wcId;
  private IwmpMProject iwmpMProject;
  private String wcname;
  private String createdBy;
  private Date createdDt;
  private String lastUpdatedBy;
  private Date lastUpdatedDate;
  private String requestIp;
  private Set<IwmpProjectWc> iwmpProjectWcs = new HashSet<IwmpProjectWc>(0);

 public IwmpMWc() {
 }

	
 public IwmpMWc(int wcId) {
     this.wcId = wcId;
 }
 public IwmpMWc(int wcId, IwmpMProject iwmpMProject, String wcname, String createdBy, Date createdDt, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Set<IwmpProjectWc> iwmpProjectWcs) {
    this.wcId = wcId;
    this.iwmpMProject = iwmpMProject;
    this.wcname = wcname;
    this.createdBy = createdBy;
    this.createdDt = createdDt;
    this.lastUpdatedBy = lastUpdatedBy;
    this.lastUpdatedDate = lastUpdatedDate;
    this.requestIp = requestIp;
    this.iwmpProjectWcs = iwmpProjectWcs;
 }

 @Id 
 @GeneratedValue(strategy=GenerationType.AUTO)
 @Column(name="wc_id", unique=true, nullable=false)
 public int getWcId() {
     return this.wcId;
 }
 
 public void setWcId(int wcId) {
     this.wcId = wcId;
 }

 @ManyToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="proj_id")
 public IwmpMProject getIwmpMProject() {
     return this.iwmpMProject;
 }
 
 public void setIwmpMProject(IwmpMProject iwmpMProject) {
     this.iwmpMProject = iwmpMProject;
 }
 
 @Column(name="wcname", length=70)
 public String getWcname() {
     return this.wcname;
 }
 
 public void setWcname(String wcname) {
     this.wcname = wcname;
 }
 
 @Column(name="created_by", length=20)
 public String getCreatedBy() {
     return this.createdBy;
 }
 
 public void setCreatedBy(String createdBy) {
     this.createdBy = createdBy;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="created_dt", length=29)
 public Date getCreatedDt() {
     return this.createdDt;
 }
 
 public void setCreatedDt(Date createdDt) {
     this.createdDt = createdDt;
 }
 
 @Column(name="last_updated_by", length=25)
 public String getLastUpdatedBy() {
     return this.lastUpdatedBy;
 }
 
 public void setLastUpdatedBy(String lastUpdatedBy) {
     this.lastUpdatedBy = lastUpdatedBy;
 }

 @Temporal(TemporalType.DATE)
 @Column(name="last_updated_date", length=13)
 public Date getLastUpdatedDate() {
     return this.lastUpdatedDate;
 }
 
 public void setLastUpdatedDate(Date lastUpdatedDate) {
     this.lastUpdatedDate = lastUpdatedDate;
 }
 
 @Column(name="request_ip", length=20)
 public String getRequestIp() {
     return this.requestIp;
 }
 
 public void setRequestIp(String requestIp) {
     this.requestIp = requestIp;
 }

 @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMWc")
 public Set<IwmpProjectWc> getIwmpProjectWcs() {
     return this.iwmpProjectWcs;
 }
 
 public void setIwmpProjectWcs(Set<IwmpProjectWc> iwmpProjectWcs) {
     this.iwmpProjectWcs = iwmpProjectWcs;
 }




}


