package app.model.master;
// Generated 8 Mar, 2021 4:17:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.BaseLineSurveyActivityDetails;
import app.model.IwmpActivityAssetAddonParameter;
import app.model.project.IwmpProjectPhysicalAap;
import app.model.project.WdcpmksyProjectPhysicalAchievementDetails;
import app.model.project.IwmpProjectPhysicalAsset;
import app.model.project.IwmpProjectPhysicalAssetTemp;

/**
 * IwmpMPhyActivity generated by hbm2java
 */
@Entity
@Table(name = "iwmp_m_phy_activity", schema = "public")
public class IwmpMPhyActivity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int activityCode;
	private IwmpMPhyHeads iwmpMPhyHeads;
	private IwmpMUnit iwmpMUnit;
	private String activityDesc;
	private Character status;
	private String createdBy;
	private Date createdon;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private String requestIp;
	private Integer seqNo;
	private Integer asset;
	private Set<IwmpActivityAssetAddonParameter> iwmpAssetParameters = new HashSet<IwmpActivityAssetAddonParameter>(0);
	private Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses = new HashSet<WdcpmksyProjectPhysicalAchievementDetails>(0);
	private Set<IwmpProjectPhysicalAap> iwmpProjectPhysicalAaps = new HashSet<IwmpProjectPhysicalAap>(0);
	private Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets = new HashSet<IwmpProjectPhysicalAsset>(0);
	private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
	private Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses = new HashSet<BaseLineSurveyActivityDetails>(0);
	private Set<IwmpMPhySubactivity> iwmpMPhySubactivities = new HashSet<IwmpMPhySubactivity>(0);
	private Set<WdcpmksyMPhyOtherActivity> wdcpmksyMPhyOtherActivities = new HashSet<WdcpmksyMPhyOtherActivity>(0);

	public IwmpMPhyActivity() {
	}

	public IwmpMPhyActivity(int activityCode) {
		this.activityCode = activityCode;
	}

	public IwmpMPhyActivity(int activityCode, IwmpMPhyHeads iwmpMPhyHeads, IwmpMUnit iwmpMUnit, String activityDesc,
			Character status, String createdBy, Date createdon, String lastUpdatedBy, Date lastUpdatedDate,
			String requestIp, Integer seqNo, Set<IwmpProjectPhysicalAap> iwmpProjectPhysicalAaps,Integer asset, 
			Set<WdcpmksyMPhyOtherActivity> wdcpmksyMPhyOtherActivities) {
		this.activityCode = activityCode;
		this.iwmpMPhyHeads = iwmpMPhyHeads;
		this.iwmpMUnit = iwmpMUnit;
		this.activityDesc = activityDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdon = createdon;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.requestIp = requestIp;
		this.seqNo = seqNo;
		this.iwmpProjectPhysicalAaps = iwmpProjectPhysicalAaps;
		this.asset=asset;
		this.wdcpmksyMPhyOtherActivities = wdcpmksyMPhyOtherActivities;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "activity_code", unique = true, nullable = false)
	public int getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(int activityCode) {
		this.activityCode = activityCode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "head_code")
	public IwmpMPhyHeads getIwmpMPhyHeads() {
		return this.iwmpMPhyHeads;
	}

	public void setIwmpMPhyHeads(IwmpMPhyHeads iwmpMPhyHeads) {
		this.iwmpMPhyHeads = iwmpMPhyHeads;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "unit_code")
	public IwmpMUnit getIwmpMUnit() {
		return this.iwmpMUnit;
	}

	public void setIwmpMUnit(IwmpMUnit iwmpMUnit) {
		this.iwmpMUnit = iwmpMUnit;
	}

	@Column(name = "activity_desc", length = 100)
	public String getActivityDesc() {
		return this.activityDesc;
	}

	public void setActivityDesc(String activityDesc) {
		this.activityDesc = activityDesc;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "created_by", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdon", length = 13)
	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	@Column(name = "last_updated_by", length = 20)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_updated_date", length = 13)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Column(name = "request_ip", length = 20)
	public String getRequestIp() {
		return this.requestIp;
	}

	public void setRequestIp(String requestIp) {
		this.requestIp = requestIp;
	}

	@Column(name = "seq_no")
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpMPhyActivity")
	public Set<IwmpProjectPhysicalAap> getIwmpProjectPhysicalAaps() {
		return this.iwmpProjectPhysicalAaps;
	}

	public void setIwmpProjectPhysicalAaps(Set<IwmpProjectPhysicalAap> iwmpProjectPhysicalAaps) {
		this.iwmpProjectPhysicalAaps = iwmpProjectPhysicalAaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpMPhyActivity")
	public Set<IwmpProjectPhysicalAsset> getIwmpProjectPhysicalAssets() {
		return this.iwmpProjectPhysicalAssets;
	}

	public void setIwmpProjectPhysicalAssets(Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets) {
		this.iwmpProjectPhysicalAssets = iwmpProjectPhysicalAssets;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iwmpMPhyActivity")
	public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemp() {
		return this.iwmpProjectPhysicalAssetTemp;
	}

	public void setIwmpProjectPhysicalAssetTemp(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemp) {
		this.iwmpProjectPhysicalAssetTemp = iwmpProjectPhysicalAssetTemp;
	}
	
	@Column(name="asset")
	public Integer getAsset() {
		return asset;
	}


	public void setAsset(Integer asset) {
		this.asset = asset;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyActivity")
    public Set<IwmpActivityAssetAddonParameter> getIwmpAssetParameters() {
        return this.iwmpAssetParameters;
    }
    
    public void setIwmpAssetParameters(Set<IwmpActivityAssetAddonParameter> iwmpAssetParameters) {
        this.iwmpAssetParameters = iwmpAssetParameters;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyActivity")
    public Set<WdcpmksyProjectPhysicalAchievementDetails> getWdcpmksyProjectPhysicalAchievementDetailses() {
        return this.wdcpmksyProjectPhysicalAchievementDetailses;
    }
    
    public void setWdcpmksyProjectPhysicalAchievementDetailses(Set<WdcpmksyProjectPhysicalAchievementDetails> wdcpmksyProjectPhysicalAchievementDetailses) {
        this.wdcpmksyProjectPhysicalAchievementDetailses = wdcpmksyProjectPhysicalAchievementDetailses;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyActivity")
    public Set<BaseLineSurveyActivityDetails> getBaseLineSurveyActivityDetailses() {
        return this.baseLineSurveyActivityDetailses;
    }
    
    public void setBaseLineSurveyActivityDetailses(Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses) {
        this.baseLineSurveyActivityDetailses = baseLineSurveyActivityDetailses;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyActivity")
    public Set<IwmpMPhySubactivity> getIwmpMPhySubactivities() {
        return this.iwmpMPhySubactivities;
    }
    
    public void setIwmpMPhySubactivities(Set<IwmpMPhySubactivity> iwmpMPhySubactivities) {
        this.iwmpMPhySubactivities = iwmpMPhySubactivities;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyActivity")
    public Set<WdcpmksyMPhyOtherActivity> getWdcpmksyMPhyOtherActivities() {
		return wdcpmksyMPhyOtherActivities;
	}

	public void setWdcpmksyMPhyOtherActivities(Set<WdcpmksyMPhyOtherActivity> wdcpmksyMPhyOtherActivities) {
		this.wdcpmksyMPhyOtherActivities = wdcpmksyMPhyOtherActivities;
	}


}
