package app.model.master;
// Generated 15 Feb, 2022 11:24:07 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.project.IwmpProjectPhysicalAsset;
import app.model.project.IwmpProjectPhysicalAssetTemp;

/**
 * IwmpMPhySubactivity generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_phy_subactivity"
    ,schema="public"
)
public class IwmpMPhySubactivity  implements java.io.Serializable {


     private int subActivityCode;
     private IwmpMPhyActivity iwmpMPhyActivity;
     private String subActivityDesc;
     private Character status;
     private String createdBy;
     private Date createdon;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private BigDecimal seqNo;
     private Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemps = new HashSet<IwmpProjectPhysicalAssetTemp>(0);
     private Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets = new HashSet<IwmpProjectPhysicalAsset>(0);

    public IwmpMPhySubactivity() {
    }

	
    public IwmpMPhySubactivity(int subActivityCode) {
        this.subActivityCode = subActivityCode;
    }
    public IwmpMPhySubactivity(int subActivityCode, IwmpMPhyActivity iwmpMPhyActivity, String subActivityDesc, Character status, String createdBy, Date createdon, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, BigDecimal seqNo) {
       this.subActivityCode = subActivityCode;
       this.iwmpMPhyActivity = iwmpMPhyActivity;
       this.subActivityDesc = subActivityDesc;
       this.status = status;
       this.createdBy = createdBy;
       this.createdon = createdon;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.seqNo = seqNo;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="sub_activity_code", unique=true, nullable=false)
    public int getSubActivityCode() {
        return this.subActivityCode;
    }
    
    public void setSubActivityCode(int subActivityCode) {
        this.subActivityCode = subActivityCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="activity_code")
    public IwmpMPhyActivity getIwmpMPhyActivity() {
        return this.iwmpMPhyActivity;
    }
    
    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
        this.iwmpMPhyActivity = iwmpMPhyActivity;
    }

    
    @Column(name="sub_activity_desc", length=100)
    public String getSubActivityDesc() {
        return this.subActivityDesc;
    }
    
    public void setSubActivityDesc(String subActivityDesc) {
        this.subActivityDesc = subActivityDesc;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdon", length=13)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="seq_no", precision=5)
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhySubactivity")
    public Set<IwmpProjectPhysicalAssetTemp> getIwmpProjectPhysicalAssetTemps() {
        return this.iwmpProjectPhysicalAssetTemps;
    }
    
    public void setIwmpProjectPhysicalAssetTemps(Set<IwmpProjectPhysicalAssetTemp> iwmpProjectPhysicalAssetTemps) {
        this.iwmpProjectPhysicalAssetTemps = iwmpProjectPhysicalAssetTemps;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhySubactivity")
    public Set<IwmpProjectPhysicalAsset> getIwmpProjectPhysicalAssets() {
        return this.iwmpProjectPhysicalAssets;
    }
    
    public void setIwmpProjectPhysicalAssets(Set<IwmpProjectPhysicalAsset> iwmpProjectPhysicalAssets) {
        this.iwmpProjectPhysicalAssets = iwmpProjectPhysicalAssets;
    }
}


