package app.model.master;
// Generated 26 Jul, 2021 4:30:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IwmpUserUploadDetails generated by hbm2java
 */
@Entity
@Table(name="iwmp_user_upload_details"
    ,schema="public"
)
public class IwmpUserUploadDetails  implements java.io.Serializable {


     private int id;
     private IwmpUploadCategory iwmpUploadCategory;
     private String createdBy;
     private Date createdDate;
     private Date dateOfPublish;
     private String fileExtension;
     private String fileName;
     private Boolean isNew;
     private String path;
     private Boolean publish;
     private String requestedIp;
     private Integer stCode;
     private String subject;
     private String updatedBy;
     private Date updatedDate;
     private String language;
    public IwmpUserUploadDetails() {
    }

	
    public IwmpUserUploadDetails(int id) {
        this.id = id;
    }
    public IwmpUserUploadDetails(int id, IwmpUploadCategory iwmpUploadCategory, String createdBy, Date createdDate, Date dateOfPublish, String fileExtension, String fileName, String language, Boolean isNew, String path, Boolean publish, String requestedIp, Integer stCode, String subject, String updatedBy, Date updatedDate) {
       this.id = id;
       this.iwmpUploadCategory = iwmpUploadCategory;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.dateOfPublish = dateOfPublish;
       this.fileExtension = fileExtension;
       this.fileName = fileName;
       this.language = language;
       this.isNew = isNew;
       this.path = path;
       this.publish = publish;
       this.requestedIp = requestedIp;
       this.stCode = stCode;
       this.subject = subject;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="upload_category_id")
    public IwmpUploadCategory getIwmpUploadCategory() {
        return this.iwmpUploadCategory;
    }
    
    public void setIwmpUploadCategory(IwmpUploadCategory iwmpUploadCategory) {
        this.iwmpUploadCategory = iwmpUploadCategory;
    }

    
    @Column(name="created_by", length=25)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_date", length=13)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_publish", length=13)
    public Date getDateOfPublish() {
        return this.dateOfPublish;
    }
    
    public void setDateOfPublish(Date dateOfPublish) {
        this.dateOfPublish = dateOfPublish;
    }

    
    @Column(name="file_extension", length=10)
    public String getFileExtension() {
        return this.fileExtension;
    }
    
    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    
    @Column(name="file_name", length=25)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    
    @Column(name="language")
    public String getLanguage() {
		return language;
	}


	public void setLanguage(String language) {
		this.language = language;
	}


	@Column(name="is_new")
    public Boolean getIsNew() {
        return this.isNew;
    }
    
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    
    @Column(name="path", length=500)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="publish")
    public Boolean getPublish() {
        return this.publish;
    }
    
    public void setPublish(Boolean publish) {
        this.publish = publish;
    }

    
    @Column(name="requested_ip", length=25)
    public String getRequestedIp() {
        return this.requestedIp;
    }
    
    public void setRequestedIp(String requestedIp) {
        this.requestedIp = requestedIp;
    }

    
    @Column(name="st_code")
    public Integer getStCode() {
        return this.stCode;
    }
    
    public void setStCode(Integer stCode) {
        this.stCode = stCode;
    }

    
    @Column(name="subject", length=2000)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="updated_by", length=25)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updated_date", length=13)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


