package app.model.master;
// Generated 19 Mar, 2021 11:57:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.project.IwmpProjectPrepare;

/**
 * IwmpMProjectPrepare generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_project_prepare",schema="public")
public class IwmpMProjectPrepare  implements java.io.Serializable {

     private int projectMprepareId;
     private String prepareDesc;
     private String shortDesc;
     private String selectedDesc1;
     private String selectedDesc2;
     private Integer parentid;
     private Boolean active;
     private String createdBy;
     private Date createdOn;
     private String updatedBy;
     private Date updatedOn;
     private String requestIp;
     private Integer sequence;
     private Set<IwmpProjectPrepare> iwmpProjectPrepares = new HashSet<IwmpProjectPrepare>(0);

    public IwmpMProjectPrepare() {
    }

	
    public IwmpMProjectPrepare(int projectMprepareId, String prepareDesc, String shortDesc, String selectedDesc1, String selectedDesc2) {
        this.projectMprepareId = projectMprepareId;
        this.prepareDesc = prepareDesc;
        this.shortDesc = shortDesc;
        this.selectedDesc1 = selectedDesc1;
        this.selectedDesc2 = selectedDesc2;
    }
    public IwmpMProjectPrepare(int projectMprepareId, String prepareDesc, String shortDesc, String selectedDesc1, String selectedDesc2, Integer parentid, Boolean active, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String requestIp, Integer sequence, Set<IwmpProjectPrepare> iwmpProjectPrepares) {
       this.projectMprepareId = projectMprepareId;
       this.prepareDesc = prepareDesc;
       this.shortDesc = shortDesc;
       this.selectedDesc1 = selectedDesc1;
       this.selectedDesc2 = selectedDesc2;
       this.parentid = parentid;
       this.active = active;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.updatedBy = updatedBy;
       this.updatedOn = updatedOn;
       this.requestIp = requestIp;
       this.sequence = sequence;
       this.iwmpProjectPrepares = iwmpProjectPrepares;
    }
   
    @Id 
    @Column(name="project_mprepare_id", unique=true, nullable=false)
    public int getProjectMprepareId() {
        return this.projectMprepareId;
    }
    
    public void setProjectMprepareId(int projectMprepareId) {
        this.projectMprepareId = projectMprepareId;
    }

    
    @Column(name="prepare_desc", nullable=false, length=80)
    public String getPrepareDesc() {
        return this.prepareDesc;
    }
    
    public void setPrepareDesc(String prepareDesc) {
        this.prepareDesc = prepareDesc;
    }

    
    @Column(name="short_desc", nullable=false, length=30)
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }

    
    @Column(name="selected_desc1", nullable=false, length=30)
    public String getSelectedDesc1() {
        return this.selectedDesc1;
    }
    
    public void setSelectedDesc1(String selectedDesc1) {
        this.selectedDesc1 = selectedDesc1;
    }

    
    @Column(name="selected_desc2", nullable=false, length=30)
    public String getSelectedDesc2() {
        return this.selectedDesc2;
    }
    
    public void setSelectedDesc2(String selectedDesc2) {
        this.selectedDesc2 = selectedDesc2;
    }

    
    @Column(name="parentid")
    public Integer getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="created_on", length=21)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="updated_by", length=20)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="updated_on", length=21)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="sequence")
    public Integer getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMProjectPrepare")
    public Set<IwmpProjectPrepare> getIwmpProjectPrepares() {
        return this.iwmpProjectPrepares;
    }
    
    public void setIwmpProjectPrepares(Set<IwmpProjectPrepare> iwmpProjectPrepares) {
        this.iwmpProjectPrepares = iwmpProjectPrepares;
    }




}


