package app.model.master;
// Generated 8 Mar, 2021 4:17:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.BaseLineSurveyActivityDetails;

/**
 * IwmpMPhyHeads generated by hbm2java
 */
@Entity
@Table(name="iwmp_m_phy_heads"
    ,schema="public"
)
public class IwmpMPhyHeads  implements java.io.Serializable {


     private int headCode;
     private String headDesc;
     private Character status;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private Integer seqNo;
    private Boolean blsRequired;
     private Set<IwmpMPhyActivity> iwmpMPhyActivities = new HashSet<IwmpMPhyActivity>(0);
     private Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses = new HashSet<BaseLineSurveyActivityDetails>(0);

    public IwmpMPhyHeads() {
    }

	
    public IwmpMPhyHeads(int headCode) {
        this.headCode = headCode;
    }
    public IwmpMPhyHeads(int headCode, String headDesc, Character status, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, Integer seqNo, Set<IwmpMPhyActivity> iwmpMPhyActivities) {
       this.headCode = headCode;
       this.headDesc = headDesc;
       this.status = status;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.seqNo = seqNo;
       this.iwmpMPhyActivities = iwmpMPhyActivities;
    }
   
     @Id 

    
    @Column(name="head_code", unique=true, nullable=false)
    public int getHeadCode() {
        return this.headCode;
    }
    
    public void setHeadCode(int headCode) {
        this.headCode = headCode;
    }

    
    @Column(name="head_desc", length=100)
    public String getHeadDesc() {
        return this.headDesc;
    }
    
    public void setHeadDesc(String headDesc) {
        this.headDesc = headDesc;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    
    @Column(name="seq_no")
    public Integer getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyHeads")
    public Set<IwmpMPhyActivity> getIwmpMPhyActivities() {
        return this.iwmpMPhyActivities;
    }
    
    public void setIwmpMPhyActivities(Set<IwmpMPhyActivity> iwmpMPhyActivities) {
        this.iwmpMPhyActivities = iwmpMPhyActivities;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="iwmpMPhyHeads")
    public Set<BaseLineSurveyActivityDetails> getBaseLineSurveyActivityDetailses() {
        return this.baseLineSurveyActivityDetailses;
    }
    
    public void setBaseLineSurveyActivityDetailses(Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses) {
        this.baseLineSurveyActivityDetailses = baseLineSurveyActivityDetailses;
    }

    @Column(name="bls_required")
	public Boolean getBlsRequired() {
		return blsRequired;
	}


	public void setBlsRequired(Boolean blsRequired) {
		this.blsRequired = blsRequired;
	}



}


