package app.model.master;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpDistrict;
import app.model.IwmpMProject;
import app.model.IwmpState;
import app.model.PFMSEatmisExpDetail;

/**
 * PfmsEatmisdataDetail generated by hbm2java
 */
@Entity
@Table(name="pfms_eatmisdata_detail", schema="public")
public class PfmsEatmisdataDetail  implements java.io.Serializable {


     private int eatmisdataId;
     private IwmpBlock iwmpBlock;
     private IwmpDistrict iwmpDistrict;
     private IwmpGramPanchayat iwmpGramPanchayat;
     private IwmpMProject iwmpMProject;
     private IwmpState iwmpStateByStateLgdCode;
     private IwmpState iwmpStateByStCode;
     private IwmpVillage iwmpVillage;
     private Integer agencyId;
     private String agencyUniqueCode;
     private String agencyName;
     private Integer districtLgdCode;
     private Integer blockLgdCode;
     private Integer panchayatLgdCode;
     private Integer villageCode;
     private Integer tehsilLgdCode;
     private Integer townLgdCode;
     private Integer wardLgdCode;
     private String schemeCode;
     private String projectId;
     private String projectName;
     private String componentCode;
     private String componentName;
     private Date date;
     private String transactionId;
     private Integer financialYear;
     private BigDecimal totalAmount;
     private String invoiceNo;
     private String apiresponsestatus;
     private Date createdon;
     private Character status;
     private Integer totalworks;
     private Character wistatus;
     private Set<PFMSEatmisExpDetail> PFMSEatmisExpDetail = new HashSet<PFMSEatmisExpDetail>(0);
		/* private String[] workDetail; */

		/*
		 * public String[] getWorkDetail() { return workDetail; }
		 * 
		 * 
		 * public void setWorkDetail(String[] workDetail) { this.workDetail =
		 * workDetail; }
		 */


	public PfmsEatmisdataDetail() {
    }

	
    public PfmsEatmisdataDetail(int eatmisdataId) {
        this.eatmisdataId = eatmisdataId;
    }
    public PfmsEatmisdataDetail(int eatmisdataId, IwmpBlock iwmpBlock, IwmpDistrict iwmpDistrict, IwmpGramPanchayat iwmpGramPanchayat, IwmpMProject iwmpMProject, IwmpState iwmpStateByStateLgdCode, IwmpState iwmpStateByStCode, IwmpVillage iwmpVillage, Integer agencyId, String agencyUniqueCode, String agencyName, Integer districtLgdCode, Integer blockLgdCode, Integer panchayatLgdCode, Integer villageCode, Integer tehsilLgdCode, Integer townLgdCode, Integer wardLgdCode, String schemeCode, String projectId, String projectName, String componentCode, String componentName, Date date, String transactionId, Integer financialYear, BigDecimal totalAmount, String invoiceNo, String apiresponsestatus, Date createdon, Character status, Set<PFMSEatmisExpDetail> PFMSEatmisExpDetail) {
       this.eatmisdataId = eatmisdataId;
       this.iwmpBlock = iwmpBlock;
       this.iwmpDistrict = iwmpDistrict;
       this.iwmpGramPanchayat = iwmpGramPanchayat;
       this.iwmpMProject = iwmpMProject;
       this.iwmpStateByStateLgdCode = iwmpStateByStateLgdCode;
       this.iwmpStateByStCode = iwmpStateByStCode;
       this.iwmpVillage = iwmpVillage;
       this.agencyId = agencyId;
       this.agencyUniqueCode = agencyUniqueCode;
       this.agencyName = agencyName;
       this.districtLgdCode = districtLgdCode;
       this.blockLgdCode = blockLgdCode;
       this.panchayatLgdCode = panchayatLgdCode;
       this.villageCode = villageCode;
       this.tehsilLgdCode = tehsilLgdCode;
       this.townLgdCode = townLgdCode;
       this.wardLgdCode = wardLgdCode;
       this.schemeCode = schemeCode;
       this.projectId = projectId;
       this.projectName = projectName;
       this.componentCode = componentCode;
       this.componentName = componentName;
       this.date = date;
       this.transactionId = transactionId;
       this.financialYear = financialYear;
       this.totalAmount = totalAmount;
       this.invoiceNo = invoiceNo;
       this.apiresponsestatus = apiresponsestatus;
       this.createdon = createdon;
       this.status = status;
       this.PFMSEatmisExpDetail= PFMSEatmisExpDetail;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="eatmisdata_id", unique=true, nullable=false)
    public int getEatmisdataId() {
        return this.eatmisdataId;
    }
    
    public void setEatmisdataId(int eatmisdataId) {
        this.eatmisdataId = eatmisdataId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcode")
    public IwmpBlock getIwmpBlock() {
        return this.iwmpBlock;
    }
    
    public void setIwmpBlock(IwmpBlock iwmpBlock) {
        this.iwmpBlock = iwmpBlock;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dcode")
    public IwmpDistrict getIwmpDistrict() {
        return this.iwmpDistrict;
    }
    
    public void setIwmpDistrict(IwmpDistrict iwmpDistrict) {
        this.iwmpDistrict = iwmpDistrict;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gcode")
    public IwmpGramPanchayat getIwmpGramPanchayat() {
        return this.iwmpGramPanchayat;
    }
    
    public void setIwmpGramPanchayat(IwmpGramPanchayat iwmpGramPanchayat) {
        this.iwmpGramPanchayat = iwmpGramPanchayat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proj_id")
    public IwmpMProject getIwmpMProject() {
        return this.iwmpMProject;
    }
    
    public void setIwmpMProject(IwmpMProject iwmpMProject) {
        this.iwmpMProject = iwmpMProject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="state_lgd_code")
    public IwmpState getIwmpStateByStateLgdCode() {
        return this.iwmpStateByStateLgdCode;
    }
    
    public void setIwmpStateByStateLgdCode(IwmpState iwmpStateByStateLgdCode) {
        this.iwmpStateByStateLgdCode = iwmpStateByStateLgdCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_code")
    public IwmpState getIwmpStateByStCode() {
        return this.iwmpStateByStCode;
    }
    
    public void setIwmpStateByStCode(IwmpState iwmpStateByStCode) {
        this.iwmpStateByStCode = iwmpStateByStCode;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vcode")
    public IwmpVillage getIwmpVillage() {
		return iwmpVillage;
	}

	public void setIwmpVillage(IwmpVillage iwmpVillage) {
		this.iwmpVillage = iwmpVillage;
	}


	@Column(name="agency_id")
    public Integer getAgencyId() {
        return this.agencyId;
    }
    
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    
    @Column(name="agency_unique_code", length=70)
    public String getAgencyUniqueCode() {
        return this.agencyUniqueCode;
    }
    
    public void setAgencyUniqueCode(String agencyUniqueCode) {
        this.agencyUniqueCode = agencyUniqueCode;
    }

    
    @Column(name="agency_name", length=570)
    public String getAgencyName() {
        return this.agencyName;
    }
    
    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }

    
    @Column(name="district_lgd_code")
    public Integer getDistrictLgdCode() {
        return this.districtLgdCode;
    }
    
    public void setDistrictLgdCode(Integer districtLgdCode) {
        this.districtLgdCode = districtLgdCode;
    }

    
    @Column(name="block_lgd_code")
    public Integer getBlockLgdCode() {
        return this.blockLgdCode;
    }
    
    public void setBlockLgdCode(Integer blockLgdCode) {
        this.blockLgdCode = blockLgdCode;
    }

    
    @Column(name="panchayat_lgd_code")
    public Integer getPanchayatLgdCode() {
        return this.panchayatLgdCode;
    }
    
    public void setPanchayatLgdCode(Integer panchayatLgdCode) {
        this.panchayatLgdCode = panchayatLgdCode;
    }

    
    @Column(name="village_code")
    public Integer getVillageCode() {
        return this.villageCode;
    }
    
    public void setVillageCode(Integer villageCode) {
        this.villageCode = villageCode;
    }

    
    @Column(name="tehsil_lgd_code")
    public Integer getTehsilLgdCode() {
        return this.tehsilLgdCode;
    }
    
    public void setTehsilLgdCode(Integer tehsilLgdCode) {
        this.tehsilLgdCode = tehsilLgdCode;
    }

    
    @Column(name="town_lgd_code")
    public Integer getTownLgdCode() {
        return this.townLgdCode;
    }
    
    public void setTownLgdCode(Integer townLgdCode) {
        this.townLgdCode = townLgdCode;
    }

    
    @Column(name="ward_lgd_code")
    public Integer getWardLgdCode() {
        return this.wardLgdCode;
    }
    
    public void setWardLgdCode(Integer wardLgdCode) {
        this.wardLgdCode = wardLgdCode;
    }

    
    @Column(name="scheme_code")
    public String getSchemeCode() {
        return this.schemeCode;
    }
    
    public void setSchemeCode(String schemeCode) {
        this.schemeCode = schemeCode;
    }

    
    @Column(name="project_id", length=30)
    public String getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    
    @Column(name="project_name", length=30)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    
    @Column(name="component_code", length=10)
    public String getComponentCode() {
        return this.componentCode;
    }
    
    public void setComponentCode(String componentCode) {
        this.componentCode = componentCode;
    }

    
    @Column(name="component_name", length=90)
    public String getComponentName() {
        return this.componentName;
    }
    
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=29)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="transaction_id", length=40)
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    
    @Column(name="financial_year")
    public Integer getFinancialYear() {
        return this.financialYear;
    }
    
    public void setFinancialYear(Integer financialYear) {
        this.financialYear = financialYear;
    }

    
    @Column(name="total_amount", precision=12, scale=4)
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @Column(name="invoice_no", length=40)
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    
    @Column(name="apiresponsestatus", length=10)
    public String getApiresponsestatus() {
        return this.apiresponsestatus;
    }
    
    public void setApiresponsestatus(String apiresponsestatus) {
        this.apiresponsestatus = apiresponsestatus;
    }

    @Column(name="totalworks")
    public Integer getTotalworks() {
		return totalworks;
	}


	public void setTotalworks(Integer totalworks) {
		this.totalworks = totalworks;
	}

	 @Column(name="wistatus")
	public Character getWistatus() {
		return wistatus;
	}


	public void setWistatus(Character wistatus) {
		this.wistatus = wistatus;
	}


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", length=29)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="pfmsEatmisdataDetail")
	public Set<PFMSEatmisExpDetail> getPFMSEatmisExpDetail() {
		return PFMSEatmisExpDetail;
	}


	public void setPFMSEatmisExpDetail(Set<PFMSEatmisExpDetail> pFMSEatmisExpDetail) {
		PFMSEatmisExpDetail = pFMSEatmisExpDetail;
	}


}
