package app.model.master;
// Generated 2 Feb, 2022 11:41:29 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import app.model.IwmpState;

/**
 * SlnaStProfile generated by hbm2java
 */
@Entity
@Table(name="slna_st_profile"
    ,schema="public"
)
public class SlnaStProfile  implements java.io.Serializable {


     private int stateCd;
     private IwmpState iwmpState;
     private Integer noOfDist;
     private Integer noOfBlock;
     private BigDecimal totGeoAreaHec;
     private BigDecimal areaByPreiwmpProj;
     private BigDecimal totAreaAsurIrrig;
     private Integer totNoMicroWs;
     private BigDecimal totUntreatAreaHec;
     private BigDecimal areaByOtherWs;
     private String createdBy;
     private Date createdDt;
     private String status;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     private BigDecimal iwmpwdcpmksyarea;

    public SlnaStProfile() {
    }

	
    public SlnaStProfile(IwmpState iwmpState) {
        this.iwmpState = iwmpState;
    }
    public SlnaStProfile(IwmpState iwmpState, Integer noOfDist, Integer noOfBlock, BigDecimal totGeoAreaHec, BigDecimal areaByPreiwmpProj, BigDecimal totAreaAsurIrrig, Integer totNoMicroWs, BigDecimal totUntreatAreaHec, BigDecimal areaByOtherWs, String createdBy, Date createdDt, String status, String lastUpdatedBy, Date lastUpdatedDate, String requestIp, BigDecimal iwmpwdcpmksyarea) {
       this.iwmpState = iwmpState;
       this.noOfDist = noOfDist;
       this.noOfBlock = noOfBlock;
       this.totGeoAreaHec = totGeoAreaHec;
       this.areaByPreiwmpProj = areaByPreiwmpProj;
       this.totAreaAsurIrrig = totAreaAsurIrrig;
       this.totNoMicroWs = totNoMicroWs;
       this.totUntreatAreaHec = totUntreatAreaHec;
       this.areaByOtherWs = areaByOtherWs;
       this.createdBy = createdBy;
       this.createdDt = createdDt;
       this.status = status;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
       this.iwmpwdcpmksyarea=iwmpwdcpmksyarea;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="iwmpState"))
     @Id @GeneratedValue(generator="generator")

    
    @Column(name="state_cd", unique=true, nullable=false)
    public int getStateCd() {
        return this.stateCd;
    }
    
    public void setStateCd(int stateCd) {
        this.stateCd = stateCd;
    }

    @OneToOne(fetch=FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public IwmpState getIwmpState() {
        return this.iwmpState;
    }
    
    public void setIwmpState(IwmpState iwmpState) {
        this.iwmpState = iwmpState;
    }

    
    @Column(name="no_of_dist")
    public Integer getNoOfDist() {
        return this.noOfDist;
    }
    
    public void setNoOfDist(Integer noOfDist) {
        this.noOfDist = noOfDist;
    }

    
    @Column(name="no_of_block")
    public Integer getNoOfBlock() {
        return this.noOfBlock;
    }
    
    public void setNoOfBlock(Integer noOfBlock) {
        this.noOfBlock = noOfBlock;
    }

    
    @Column(name="tot_geo_area_hec", precision=20, scale=5)
    public BigDecimal getTotGeoAreaHec() {
        return this.totGeoAreaHec;
    }
    
    public void setTotGeoAreaHec(BigDecimal totGeoAreaHec) {
        this.totGeoAreaHec = totGeoAreaHec;
    }

    
    @Column(name="area_by_preiwmp_proj", precision=20, scale=5)
    public BigDecimal getAreaByPreiwmpProj() {
        return this.areaByPreiwmpProj;
    }
    
    public void setAreaByPreiwmpProj(BigDecimal areaByPreiwmpProj) {
        this.areaByPreiwmpProj = areaByPreiwmpProj;
    }

    
    @Column(name="tot_area_asur_irrig", precision=20, scale=5)
    public BigDecimal getTotAreaAsurIrrig() {
        return this.totAreaAsurIrrig;
    }
    
    public void setTotAreaAsurIrrig(BigDecimal totAreaAsurIrrig) {
        this.totAreaAsurIrrig = totAreaAsurIrrig;
    }

    
    @Column(name="tot_no_micro_ws")
    public Integer getTotNoMicroWs() {
        return this.totNoMicroWs;
    }
    
    public void setTotNoMicroWs(Integer totNoMicroWs) {
        this.totNoMicroWs = totNoMicroWs;
    }

    
    @Column(name="tot_untreat_area_hec", precision=20, scale=5)
    public BigDecimal getTotUntreatAreaHec() {
        return this.totUntreatAreaHec;
    }
    
    public void setTotUntreatAreaHec(BigDecimal totUntreatAreaHec) {
        this.totUntreatAreaHec = totUntreatAreaHec;
    }

    
    @Column(name="area_by_other_ws", precision=20, scale=5)
    public BigDecimal getAreaByOtherWs() {
        return this.areaByOtherWs;
    }
    
    public void setAreaByOtherWs(BigDecimal areaByOtherWs) {
        this.areaByOtherWs = areaByOtherWs;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_dt", length=13)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="status", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    @Column(name="iwmp_wdcpmksy_area", precision=20, scale=5)
	public BigDecimal getIwmpwdcpmksyarea() {
		return iwmpwdcpmksyarea;
	}


	public void setIwmpwdcpmksyarea(BigDecimal iwmpwdcpmksyarea) {
		this.iwmpwdcpmksyarea = iwmpwdcpmksyarea;
	}




}


