package app.model.master;
// Generated 15 Sep, 2021 12:21:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.BaseLineSurveyActivityDetails;

/**
 * WdcpmksyMOutcomeDetail generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_m_outcome_detail",schema="public") 
public class WdcpmksyMOutcomeDetail  implements java.io.Serializable {

     private int outcomeDetailId;
     private WdcpmksyMOutcome wdcpmksyMOutcome;
     private String outcomeDetailDesc;
     private String createdBy;
     private Date createdOn;
     private String requestIp;
     private BigDecimal seqNo;
     private Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses = new HashSet<BaseLineSurveyActivityDetails>(0);

    public WdcpmksyMOutcomeDetail() {
    }

	
    public WdcpmksyMOutcomeDetail(int outcomeDetailId) {
        this.outcomeDetailId = outcomeDetailId;
    }
    public WdcpmksyMOutcomeDetail(int outcomeDetailId, WdcpmksyMOutcome wdcpmksyMOutcome, String outcomeDetailDesc, String createdBy, BigDecimal seqNo, Date createdOn, String requestIp) {
       this.outcomeDetailId = outcomeDetailId;
       this.wdcpmksyMOutcome = wdcpmksyMOutcome;
       this.outcomeDetailDesc = outcomeDetailDesc;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.requestIp = requestIp;
       this.seqNo = seqNo;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="outcome_detail_id", unique=true, nullable=false)
    public int getOutcomeDetailId() {
        return this.outcomeDetailId;
    }
    
    public void setOutcomeDetailId(int outcomeDetailId) {
        this.outcomeDetailId = outcomeDetailId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="outcome_id")
    public WdcpmksyMOutcome getWdcpmksyMOutcome() {
        return this.wdcpmksyMOutcome;
    }
    
    public void setWdcpmksyMOutcome(WdcpmksyMOutcome wdcpmksyMOutcome) {
        this.wdcpmksyMOutcome = wdcpmksyMOutcome;
    }
    
    @Column(name="outcome_detail_desc", length=200)
    public String getOutcomeDetailDesc() {
        return this.outcomeDetailDesc;
    }
    
    public void setOutcomeDetailDesc(String outcomeDetailDesc) {
        this.outcomeDetailDesc = outcomeDetailDesc;
    }
    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", length=13)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }
    
    @Column(name="seq_no")
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="wdcpmksyMOutcomeDetail")
    public Set<BaseLineSurveyActivityDetails> getBaseLineSurveyActivityDetailses() {
        return this.baseLineSurveyActivityDetailses;
    }
    
    public void setBaseLineSurveyActivityDetailses(Set<BaseLineSurveyActivityDetails> baseLineSurveyActivityDetailses) {
        this.baseLineSurveyActivityDetailses = baseLineSurveyActivityDetailses;
    }

}


