package app.model.master;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import app.model.IwmpState;

/**
 * WdcpmksyMPhyOtherActivity generated by hbm2java
 */
@Entity
@Table(name="wdcpmksy_m_phy_other_activity"
    ,schema="public"
)
public class WdcpmksyMPhyOtherActivity  implements java.io.Serializable {


     private int otherActivityCode;
     private IwmpMPhyActivity iwmpMPhyActivity;
     private IwmpState iwmpState;
     private String otherActivityDesc;
     private BigDecimal seqNo;
     private Character status;
     private String createdBy;
     private Date createdon;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String requestIp;
     
     @Override
 	public String toString() {
 		return "WdcpmksyMPhyOtherActivity [otherActivityCode=" + otherActivityCode + ", iwmpMPhyActivity="
 				+ iwmpMPhyActivity + ", iwmpState=" + iwmpState + ", otherActivityDesc=" + otherActivityDesc
 				+ ", seqNo=" + seqNo + ", status=" + status + ", createdBy=" + createdBy + ", createdon=" + createdon
 				+ ", lastUpdatedBy=" + lastUpdatedBy + ", lastUpdatedDate=" + lastUpdatedDate + ", requestIp="
 				+ requestIp + "]";
 	}

    public WdcpmksyMPhyOtherActivity() {
    }

	
    public WdcpmksyMPhyOtherActivity(int otherActivityCode) {
        this.otherActivityCode = otherActivityCode;
    }
    public WdcpmksyMPhyOtherActivity(int otherActivityCode, IwmpMPhyActivity iwmpMPhyActivity, IwmpState iwmpState, String otherActivityDesc, BigDecimal seqNo, Character status, String createdBy, Date createdon, String lastUpdatedBy, Date lastUpdatedDate, String requestIp) {
       this.otherActivityCode = otherActivityCode;
       this.iwmpMPhyActivity = iwmpMPhyActivity;
       this.iwmpState = iwmpState;
       this.otherActivityDesc = otherActivityDesc;
       this.seqNo = seqNo;
       this.status = status;
       this.createdBy = createdBy;
       this.createdon = createdon;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.requestIp = requestIp;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="other_activity_code", unique=true, nullable=false)
    public int getOtherActivityCode() {
        return this.otherActivityCode;
    }
    
    public void setOtherActivityCode(int otherActivityCode) {
        this.otherActivityCode = otherActivityCode;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="activity_code")
    public IwmpMPhyActivity getIwmpMPhyActivity() {
        return this.iwmpMPhyActivity;
    }
    
    public void setIwmpMPhyActivity(IwmpMPhyActivity iwmpMPhyActivity) {
        this.iwmpMPhyActivity = iwmpMPhyActivity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_code")
    public IwmpState getIwmpState() {
        return this.iwmpState;
    }
    
    public void setIwmpState(IwmpState iwmpState) {
        this.iwmpState = iwmpState;
    }

    
    @Column(name="other_activity_desc", length=100)
    public String getOtherActivityDesc() {
        return this.otherActivityDesc;
    }
    
    public void setOtherActivityDesc(String otherActivityDesc) {
        this.otherActivityDesc = otherActivityDesc;
    }

    
    @Column(name="seq_no", precision=5)
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }

    
    @Column(name="status", length=1)
    public Character getStatus() {
        return this.status;
    }
    
    public void setStatus(Character status) {
        this.status = status;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdon", length=13)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="last_updated_by", length=20)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="last_updated_date", length=13)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="request_ip", length=20)
    public String getRequestIp() {
        return this.requestIp;
    }
    
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }




}

