<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" errorPage="error.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ include file="/WEB-INF/jspf/header.jspf"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<%-- <c:choose> --%>
<%-- 	<c:when test="${sessionScope.loginid eq null }"> --%>
<%-- 		<%@include file="/WEB-INF/jspf/header.jspf"%> --%>
<%-- 	</c:when> --%>
<%-- 	<c:otherwise> --%>
<%-- 		<%@include file="/WEB-INF/jspf/header2.jspf"%> --%>
<%-- 	</c:otherwise> --%>
<%-- </c:choose> --%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<html>
<head>
<title>Report T2- State-wise, District-wise, Project-wise and Year-wise Details of Annual Physical Action Plan/Achievement/works as per List of Activities</title>
<script src='<c:url value="/resources/js/jquery-3.5.1.js" />'></script>
<script
	src='<c:url value="/resources/js/1.12.1jquery.dataTables.min.js" />'></script>
<script
	src='<c:url value="/resources/js/2.2.3dataTables.buttons.min.js" />'></script>
<script src='<c:url value="/resources/js/jszip.min.js" />'></script>
<script src='<c:url value="/resources/js/pdfmake.min.js" />'></script>
<script src='<c:url value="/resources/js/1.53vfs_fonts.js" />'></script>
<script
	src='<c:url value="/resources/js/export/buttons.html5.min.js" />'></script>
<%-- <script src='<c:url value="/resources/js/buttons.print.min.js" />'></script> --%>
<link rel="stylesheet" type="text/css"
	href="<c:url  value="/resources/css/bootstrap/jquery.dataTables.min.css" />" />
<link rel="stylesheet" type="text/css"
	href="<c:url  value="/resources/css/2.2.3buttons.dataTables.min.css" />" />
<link rel="stylesheet" type="text/css"
	href="<c:url  value="/resources/css/phystyle.css" />">

<script src='<c:url value="/resources/js/physicalActionAchievement.js" />'></script>
<script type="text/javascript">
function validation1() 
{
    var stName = document.getElementById("state").options[document.getElementById("state").selectedIndex].text;
    var distName = document.getElementById("district").options[document.getElementById("district").selectedIndex].text;
    var projName = document.getElementById("project").options[document.getElementById("project").selectedIndex].text;
    var yearName = document.getElementById("fromyear").options[document.getElementById("fromyear").selectedIndex].text;
//    alert(stName+distName+projName+yearName);
    document.getElementById("stName").value=stName;
    document.getElementById("distName").value=distName;
    document.getElementById("projName").value=projName;
    document.getElementById("yearName").value=yearName;
	var fromYear = document.getElementById("fromyear").value;
	var state= document.getElementById("state").value;
	if(state=='')
	{
		alert('Please select State ');
		document.getElementById("state").focus();
		e.preventDefault();
	}
	/* if(fromYear=='')
	{
		alert('Please select Year ');
		document.getElementById("fromyear").focus();
		e.preventDefault();
	} */
	else{
		
		document.activityWiseUpto.action="activityWiseUptoPlanAchievWork";
		document.activityWiseUpto.method="post";
		document.activityWiseUpto.submit();
	}
	return false;

}

/* function exportExcel(){
	var now = new Date();
	var jsDate = now.getDate()+ '-'+ (now.getMonth() + 1)+ '-'+ now.getFullYear();
	var tableName = "#tblReport";
	 var colLength=$(tableName+" tr:first th").length;
	 var headerTitle = "Watershed Development Component-Pradhan Mantri Krishi Sinchayee Yojana (WDC-PMKSY)";
	var reportName = "Report T2- State-wise, District-wise and Project-wise Details of Targets, Achievement and Works of Activities till the Selected Financial Year";
	var fileName="Report T2";
	 var headerHtml = "<table>"+
	 "<tr><td colspan='"+colLength+"' style='text-align:center'>"+headerTitle+"</td></tr>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>"+reportName+"</td></tr>"+
	    
	    "<tr><td></td></tr></table>";
	    var footerHtml = "<table>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>Report Generated by WDC-PMKSY software on: "+jsDate+"</td></tr></table>";  
	 exportTableToExcel('tblReport', fileName,headerHtml,footerHtml);
	} */

function downloadPDF()
{
	 var stName = document.getElementById("state").options[document.getElementById("state").selectedIndex].text;
	 var distName = document.getElementById("district").options[document.getElementById("district").selectedIndex].text;
	 var projName = document.getElementById("project").options[document.getElementById("project").selectedIndex].text;
	 var yearName = document.getElementById("fromyear").options[document.getElementById("fromyear").selectedIndex].text;
//	    alert(stName+distName+projName+yearName);
	 document.getElementById("stName").value=stName;
	 document.getElementById("distName").value=distName;
	 document.getElementById("projName").value=projName;
	 document.getElementById("yearName").value=yearName;
	var fromYear = document.getElementById("fromyear").value;
	var state= document.getElementById("state").value;
	if(state=='')
	{
		alert('Please select State ');
		document.getElementById("state").focus();
		e.preventDefault();
	}
/* 	if(fromYear=='')
	{
		alert('Please select Year ');
		document.getElementById("fromyear").focus();
		e.preventDefault();
	} */
	else{
		
		document.activityWiseUpto.action="activityWiseUptoPlanAchievWorkPDF";
		document.activityWiseUpto.method="post";
		document.activityWiseUpto.submit();
	}
	return false;
	
}

function exportExcel()
{
	 var stName = document.getElementById("state").options[document.getElementById("state").selectedIndex].text;
	 var distName = document.getElementById("district").options[document.getElementById("district").selectedIndex].text;
	 var projName = document.getElementById("project").options[document.getElementById("project").selectedIndex].text;
	 var yearName = document.getElementById("fromyear").options[document.getElementById("fromyear").selectedIndex].text;
//	    alert(stName+distName+projName+yearName);
	 document.getElementById("stName").value=stName;
	 document.getElementById("distName").value=distName;
	 document.getElementById("projName").value=projName;
	 document.getElementById("yearName").value=yearName;
	var fromYear = document.getElementById("fromyear").value;
	var state= document.getElementById("state").value;
	if(state=='')
	{
		alert('Please select State ');
		document.getElementById("state").focus();
		e.preventDefault();
	}
	/* if(fromYear=='')
	{
		alert('Please select Year ');
		document.getElementById("fromyear").focus();
		e.preventDefault();
	} */
	else{
		
		document.activityWiseUpto.action="downloadExcelactivityWiseUptoPlanAchievWork";
		document.activityWiseUpto.method="post";
		document.activityWiseUpto.submit();
	}
	return false;
	
}

</script>
</head>


<body>
 <br>
<div class="offset-md-2 col-8 formheading" style="text-align:center;"  ><h5><label id="head"></label>Report T2- State-wise, District-wise and Project-wise Details of Targets, Achievement and Works of Activities till the Selected Financial Year</h5></div>

<br>
<div class ="card">
<div class="row">
<div class="col-1" ></div>
<div class="col-10">

<div class="table-responsive" id="exportHtmlToPdf1">

 <form:form action="activityWiseUptoPlanAchievWork" method="post" name="activityWiseUpto" id="activityWiseUpto">
 	<input type="hidden" id="stCode" name="stCode" value="${stCode}" />
 	<input type="hidden" id="distCode" name="distCode" value="${distCode}" />
	<input type="hidden" id="projId" name="projId" value="${projectId}" />
	<input type="hidden" id="fYear" name="fYear" value="${fromYear}" />
	<input type="hidden" id="userdate1" name="userdate1" value="${userdate1}" />
	<input type="hidden" id="userdateto1" name="userdateto1" value="${userdateto1}" /> 
	
	<input type="hidden" name="stName" id="stName" value="" />
	<input type="hidden" name="distName" id="distName" value="" />
	<input type="hidden" name="projName" id="projName" value="" />
	<input type="hidden" name="yearName" id="yearName" value="" />
	
      <table >
        <tr align="center" >
        
          <td><b>State<span style="color: red;">*</span></b></td>
          <td>
             <select class="form-control project" id="state" name="state" required>
    			<option value="">--Select--</option>
    		<!-- 	<option value="0">--All State--</option> -->
     			<c:forEach items="${stateList}" var="state">
							<option value="<c:out value="${state.key}"/>" <c:out value="${state.key== stCode ?'selected':'' }"/>>
							<c:out 	value="${state.value}" /></option>
				</c:forEach>
    		</select>
          </td>
          <td><b>District<span style="color: red;">*</span></b></td>
          <td>
             <select class="form-control district" id="district" name="district" required="required" >
      			<option value="0">--All--</option>
    		</select>
          </td>
          <td ><b>Project<span style="color: red;">*</span></b></td>
          <td >
             <select class="form-control project" id="project" name="project" required="required">
      			<option value="0">--All--</option>
    		</select>
          </td>
          <td ><b>Financial Year </b></td>
          <td >
              <select class="form-control finyear" id="fromyear" name="fromYear" required="required">
      			<option value="">--Select Year--</option>
      			<c:forEach items="${yearList}" var="yearl">
							<option value="<c:out value="${yearl.key}"/>" <c:out value="${yearl.key== fromYear ?'selected':'' }"/>>
							<c:out 	value="${yearl.value}" /></option>
				</c:forEach>
    		  </select>
          </td>
          <td ><b>From Date</b></td>
          <td>
      		  <input type="date" name="userdate" id="userdate" class="form-control activity" style="width: 100%;" />
		  </td>
		  <td ><b>To Date</b></td> 
		  <td>
      		  <input type="date" name="userdateto" id="userdateto" class="form-control activity" style="width: 100%;" />
		  </td>
          <td  align="center" class="label"> 
          <input type="button" class="btn btn-info" id="btnGetReport" onclick="validation1()" name="btnGetReport" value="Get Report" />
         <!--  <input type="submit" class="btn btn-info form-control" id="btnGetReport2" name="btnGetReport" value="Get Report"> </td> -->
       </tr>
      </table>
 </form:form>
 </div>
 </div>
<br>
	</div>
	
	<div class="row">
	<div class="col-1" ></div>
	<div class="col-10"  id="exportHtmlToPdf">
	<c:if test="${dataListSize > 0}">
	<br>
	
	<button name="exportExcel" id="exportExcel" onclick="exportExcel()" class="btn btn-info">Excel</button>
	<button name="exportPDF" id="exportPDF" onclick="downloadPDF();" class="btn btn-info">PDF</button>
<!--<button name="exportExcel" id="exportExcel" onclick="exportExcel('${stCode}','${distCode}','${projectId}','${fromYear}')" class="btn btn-info">Excel</button>	
 <button name="exportPDF" id="exportPDF" onclick="exportPDF()" class="btn btn-info">PDF</button> -->
 	</c:if>
<p align="right"> Report as on: <%=app.util.Util.dateToString(null,"dd/MM/yyyy hh:mm aaa")%> </p>
<table id="tblReport" cellspacing="0" class="table">
  <thead>
	<tr>
		<th colspan="10" >State : &nbsp; <c:out value='${stName}' /> &nbsp;&nbsp;&nbsp; District : &nbsp; <c:out value='${distName}' /> &nbsp;&nbsp;&nbsp; 
		Project : &nbsp; <c:out value='${projName}' />&nbsp;&nbsp;&nbsp; <c:if test = "${fromYear ne '' }"> Financial Year : &nbsp; <c:out value='${yearName}' /> </c:if> 
		<c:if test = "${fromYear eq '' }"> From Date : &nbsp; <c:out value='${fromDateStr}' /> &nbsp;&nbsp;&nbsp; To Date : &nbsp; <c:out value='${toDateStr}' /></c:if>
		
		
		</th>
	</tr>
    <tr>
      <th style="text-align:center; vertical-align: middle; width: 20%;">Name of the Activity</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Unit</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Physical Target</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Physical Achievement</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;"> Achievement %</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Total No. of Work</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Total No. of Work Ongoing</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Total No. of Work Completed</th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Total No. of Work Completed for  <c:out value='${yearName}' /></th>
      <th style="text-align:center; vertical-align: middle; width: 5%;">Total No. of Work forClosed</th>
     </tr>
   
  </thead>

  <tbody>
    <tr>
		<th class="text-center">1</th>
		<th class="text-center">2</th>
		<th class="text-center">3</th>
		<th class="text-center">4</th>
		<th class="text-center">5</th>
		<th class="text-center">6</th>
		<th class="text-center">7</th>
		<th class="text-center">8</th>
		<th class="text-center">9</th>
		<th class="text-center">10</th>
	</tr>
	
		<c:set var="counter" value="0" />
		<c:set var="count1" value="1" />
		<c:set var="headVal" value="" />
		<c:set var="actVal" value="" />
		<c:set var="hdCount" value="1" />
		<c:set var="actCount" value="1" />
		<c:set var="subActCount" value="1" />
		<c:set var="colTotal" value="0" />

		<c:set var="countHead" value="0" />
		<c:set var="headOld" value="" />
		<c:set var="keyPlc" value="0" />
		<c:set var="headYrSum" value="0" />
		
		<c:set var="totPhyTar" value="" />
		<c:set var="totPhyAch" value="" />
		<c:set var="totWrk" value="" />
		<c:set var="totOnWrk" value="" />
		<c:set var="totCoWrk" value="" />
		<c:set var="totYrlyWrk" value="" />
		<c:set var="totClsWrk" value="" />
		<c:set var="unitName" value="" />
		
		<c:set var="grndtotWrk" value="" />
		<c:set var="grndtotOnWrk" value="" />
		<c:set var="grndtotCoWrk" value="" />
		<c:set var="grndtotYrlyWrk" value="" />
		<c:set var="grndtotClsWrk" value="" />
	
	<c:forEach items="${dataList}" var="dataListSh">
	
			<c:if test="${countHead == 0}">
				<c:set var="countHead" value="1" />
				<c:set var="headOld" value="${dataListSh[2]}" />
			</c:if>

			<c:if test="${headOld != dataListSh[2]}">
				<c:set var="headYrSum" value="0" />
				
				<c:set var="countHead" value="${countHead + 1}" />
				<c:set var="headOld" value="${dataListSh[2]}" />
				<c:set var="keyPlc" value="${keyPlc + 1}" />
			</c:if>
			
			<c:if test="${dataListSh[1] != null}">
						<c:if test="${headVal != dataListSh[0]}">
							<c:if test="${hdCount != 1 && dataListSh[0] lt 9}">
							<tr>
							<th colspan ="2" class="text-center">Sub-Total</th>
							<c:if test = "${unitName eq 'ha' }">
							<th class="text-right"><fmt:formatNumber type="number" maxFractionDigits="2" minFractionDigits="2" value="${totPhyTar}"/></th>
							<th class="text-right"><fmt:formatNumber type="number" maxFractionDigits="2" minFractionDigits="2" value="${totPhyAch}"/></th>
							</c:if>
							<c:if test = "${unitName eq 'nos' }">
							<th class="text-right"><fmt:formatNumber type="number" maxFractionDigits="0" minFractionDigits="0" value="${totPhyTar}"/></th>
							<th class="text-right"><fmt:formatNumber type="number" maxFractionDigits="0" minFractionDigits="0" value="${totPhyAch}"/></th>
							</c:if>
							<th class="text-right"><fmt:formatNumber type="number" maxFractionDigits="2" minFractionDigits="2" value="${(totPhyAch*100)/totPhyTar}"/>%</th>
							<th class="text-right"><c:out value="${totWrk}"/></th>
							<th class="text-right"><c:out value="${totOnWrk}"/></th>
							<th class="text-right"><c:out value="${totCoWrk}"/></th>
							<th class="text-right"><c:out value="${totYrlyWrk}"/></th>
							<th class="text-right"><c:out value="${totClsWrk}"/></th>
							</tr>
							</c:if>
								<c:set var="totPhyTar" value="" />
								<c:set var="totPhyAch" value="" />
								<c:set var="totWrk" value="" />
								<c:set var="totOnWrk" value="" />
								<c:set var="totCoWrk" value="" />
								<c:set var="totYrlyWrk" value="" />
								<c:set var="totClsWrk" value="" />
							<tr>
								<td class="altrow">
								<SPAN>
								<c:out value="${dataListSh[1]}" /> 
								</SPAN> 
								<br> 
								<c:set	var="headVal" value="${dataListSh[0]}" /> 
								<c:set  var="hdCount" value="${hdCount + 1}" /> 
								<c:set var="actCount" value="1" /> 
								<c:set var="subActCount" value="1" />
								</td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
						</c:if>
						
						<c:if test="${actVal != dataListSh[2]}">
							<tr>
								<td class="altrow">
									<span style="padding-left: 20px;">
										<c:out value="${dataListSh[3]}" /> 
									</span> 
									<br>
									<c:set var="actVal" value="${dataListSh[2]}" />
									<c:set var="actCount" value="${actCount + 1}" />
								</td>
								<td class="altrow">
									<c:out value="${dataListSh[4]}" />
								</td>
									
								<td align="right"> 
									<c:if test="${dataListSh[4]=='nos'}"> 
										<fmt:formatNumber type="number" maxFractionDigits="0" minFractionDigits="0" value="${dataListSh[5]}"/>
									</c:if>
									<c:if test="${dataListSh[4]!='nos'}"> 
										<fmt:formatNumber type="number" maxFractionDigits="2" minFractionDigits="2" value="${dataListSh[5]}"/>
									</c:if>
								</td>
								<td align="right">
									<c:if test="${dataListSh[4]=='nos'}"> 
										<fmt:formatNumber type="number" maxFractionDigits="0" minFractionDigits="0" value="${dataListSh[6]}"/>
									</c:if>
									<c:if test="${dataListSh[4]!='nos'}"> 
										<fmt:formatNumber type="number" maxFractionDigits="2" minFractionDigits="2" value="${dataListSh[6]}"/>
									</c:if>
								</td>
								<td align="right">
									<c:out value="${dataListSh[11]}" /><b>%</b>
								</td>
								<td align="right">
									<c:out value="${dataListSh[7]}" />
								</td>
								<td align="right">
									<c:out value="${dataListSh[8]}" />
								</td>
								<td align="right">
									<c:out value="${dataListSh[9]}" />
								</td>
								<td align="right">
									<c:out value="${dataListSh[12]}" />
								</td>
								<td align="right">
									<c:out value="${dataListSh[10]}" />
								</td>
								<c:set var="unitName" value="${dataListSh[4]}" />
								<c:set var="totPhyTar" value="${totPhyTar + dataListSh[5]}" />
								<c:set var="totPhyAch" value="${totPhyAch + dataListSh[6]}" />
								<c:set var="totWrk" value="${totWrk + dataListSh[7]}" />
								<c:set var="totOnWrk" value="${totOnWrk + dataListSh[8]}" />
								<c:set var="totCoWrk" value="${totCoWrk + dataListSh[9]}" />
								<c:set var="totYrlyWrk" value="${totYrlyWrk + dataListSh[12]}" />
								<c:set var="totClsWrk" value="${totClsWrk + dataListSh[10]}" />
								
						</c:if>
							
					</c:if>
								<c:set var="grndtotWrk" value="${grndtotWrk + dataListSh[7]}" />
								<c:set var="grndtotOnWrk" value="${grndtotOnWrk + dataListSh[8]}" />
								<c:set var="grndtotCoWrk" value="${grndtotCoWrk + dataListSh[9]}" />
								<c:set var="grndtotYrlyWrk" value="${grndtotYrlyWrk + dataListSh[12]}" />
								<c:set var="grndtotClsWrk" value="${grndtotClsWrk + dataListSh[10]}" />
	
	</c:forEach>
		<c:if test="${dataListSize gt 0}">
			<tr>
				<th colspan ="5" class="text-center">Grand Total</th>
				<th class="text-right"><c:out value= "${grndtotWrk}"/></th>
				<th class="text-right"><c:out value= "${grndtotOnWrk}"/></th>
				<th class="text-right"><c:out value= "${grndtotCoWrk}"/></th>
				<th class="text-right"><c:out value= "${grndtotYrlyWrk}"/></th>
				<th class="text-right"><c:out value= "${grndtotClsWrk}"/></th>
				
			</tr>
		</c:if>
	
    
    	<c:if test="${dataListSize==0}">
			<tr>
				<td align="center" colspan="10" class="required">Data Not Found</td>
			</tr>
		</c:if>
   
  </tbody>
</table>
   
<br/>  
        </div>
        </div>
    <br>
	
	</div>

<script type="text/javascript">
		$(document).ready(function() {
			$(".sidebar-btn").click(function() {
				$(".wrapper").toggleClass("collapse");
			});
		});
		
		
		document.getElementById('userdateto').addEventListener('change', function() {
		    var fromDate = document.getElementById('userdate').value;
		  //  alert(fromDate);
		    if (!fromDate) {
		        alert('Please select From Date first.');
		        this.value = ''; // Reset the To Date
		        $('#userdate').focus();
		    }
		    else {
		        const currentDate = new Date();
		        const dateToCheck = new Date(this.value);
		        
		        currentDate.setHours(0, 0, 0, 0);
		        dateToCheck.setHours(0, 0, 0, 0);

		        if (currentDate < dateToCheck) {
		            alert("To date cannot be greater than the current date.");
		            document.getElementById('userdateto').value = '';
		          //  document.getElementById('userdate').value='';
		          //  document.getElementById('userdate').focus();
		            document.getElementById('userdateto').focus();
		        }
		    }
		});

		
		
		
		
	</script>
	<footer class=" text-center">
<%-- 		<c:choose> --%>
<%-- 			<c:when test="${sessionScope.loginid eq null }"> --%>
<%-- 				<%@include file="/WEB-INF/jspf/footer.jspf"%> --%>
<%-- 			</c:when> --%>
<%-- 			<c:otherwise> --%>
<%-- 				<%@include file="/WEB-INF/jspf/footer2.jspf"%> --%>
<%-- 			</c:otherwise> --%>
<%-- 		</c:choose> --%>

	</footer>
</body>
</html>