<%@include file="/WEB-INF/jspf/header2.jspf"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>  

<!DOCTYPE html>
<html>

<head>
<meta charset="ISO-8859-1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
<link rel="stylesheet" type="text/css" href="<c:url  value="/resources/css/report.css" />">

<script type="text/javascript">


function exportPDF(){
	var table="";
	var reportName = "Project Location Details";
	var tableName = "#example";
	var columnSpan =false;
	var colLength=$("#example tr:first th").length;
	if ( ! $.fn.DataTable.isDataTable( tableName ) ) {
		createDataTable(reportName,tableName,columnSpan,colLength);
		}
	//createDataTable(headerTitle,reportName,tableName);
	//trigger pdf button of datatable
	table=$(tableName).DataTable().buttons(0,1).trigger();
	table.buttons('.buttons-pdf').nodes().css("display", "none");
	table.buttons('.buttons-excel').nodes().css("display", "none");
	}


	/***************************************************** Excel Button Click ************************************* */
	function exportExcel(){
	var now = new Date();
	var jsDate = now.getDate()+ '-'+ (now.getMonth() + 1)+ '-'+ now.getFullYear();
	var tableName = "#example";
	 var colLength=$(tableName+" tr:first th").length;
	 var headerTitle = "Watershed Development Component-Pradhan Mantri Krishi Sinchayee Yojana (WDC-PMKSY)";
	var reportName = "Project Location and Baseline Status";
	var fileName="Project Location and Baseline Status";
	 var headerHtml = "<table>"+
	 "<tr><td colspan='"+colLength+"' style='text-align:center'>"+headerTitle+"</td></tr>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>"+reportName+"</td></tr>"+
	    
	    "<tr><td></td></tr></table>";
	    var footerHtml = "<table>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>Report Generated by WDC-PMKSY software on: "+jsDate+"</td></tr></table>";  
	 exportTableToExcel('example', fileName,headerHtml,footerHtml);
	}


</script>

</head>
<div class ="card">

<div class="table-responsive">

<div class="col" style="text-align:center;"><h5>Project Location and Baseline Status</h5></div>
 <form:form autocomplete="off" name="locationAndBaselinnNotRepoted" id="locationAndBaselinnNotRepoted"  modelAttribute="locationAndBaselinnNotRepoted" >
 
     <%--  <table >
        <tr>
          <td class="label">State <span style="color: red;">*</span></td>
          <td>
              <select name="state" id="state" onchange="this.form.submit();">
              		<option value="">--Select--</option>
              		<c:if test='${sessionScope.userType=="ADMIN" || sessionScope.userType=="DL"}'> 
              			<c:if test="${state=='0' }"> 
              				<option value="0" selected="selected" >--All--</option>
              			</c:if>
              			<c:if test="${state==null || state gt '0' || state==''}"> 
              				<option value="0" >--All--</option>
              			</c:if>
              		</c:if>
                  	<c:if test="${not empty stateList}">
               			<c:forEach items="${stateList}" var="lists">
               				<c:if test="${lists.key eq state}">
       								<option value="<c:out value='${lists.key}'/>"  selected="selected" ><c:out value="${lists.value}" /></option>
       						</c:if>	
       						<c:if test="${lists.key ne state}">
       								<option value="<c:out value='${lists.key}'/>"  ><c:out value="${lists.value}" /></option>
       						</c:if>
						</c:forEach>
					</c:if> 
              </select>
          </td>
          
           <td class="label">District <span style="color: red;">*</span></td>
          <td>
              <select name="district" id="district" onchange="this.form.submit();">
              		<option value="0">--All--</option>
                  	 <c:if test="${not empty districtList}">
               					<c:forEach items="${districtList}" var="lists">
               						<c:if test="${lists.key eq district}">
       									<option value="<c:out value='${lists.key}'/>" selected="selected" ><c:out value="${lists.value}" /></option>
       								</c:if>	
       								<c:if test="${lists.key ne district}">
       									<option value="<c:out value='${lists.key}'/>"  ><c:out value="${lists.value}" /></option>
       								</c:if>	
								</c:forEach>
					</c:if> 
              </select>
          </td>
          
           <td class="label">Block &nbsp;&nbsp;&nbsp;</td>
          <td>
              <select name="block" id="block" onchange="this.form.submit();">
              		<option value="0">--All--</option>
                  	<c:if test="${not empty blockList}">
               			<c:forEach items="${blockList}" var="lists">
               				<c:if test="${lists.key eq block}">
       								<option value="<c:out value='${lists.key}'/>"  selected="selected" ><c:out value="${lists.value}" /></option>
       						</c:if>	
       						<c:if test="${lists.key ne block}">
       								<option value="<c:out value='${lists.key}'/>"  ><c:out value="${lists.value}" /></option>
       						</c:if>
						</c:forEach>
					</c:if> 
              </select>
          </td>
          
          <td class="label">Gram Panchayat &nbsp;&nbsp;&nbsp;</td>
          <td>
              <select name="gp" id="gp">
              		<option value="0">--All--</option>
                  	<c:if test="${not empty gpList}">
               			<c:forEach items="${gpList}" var="lists">
               				<c:if test="${lists.key eq gp}">
       								<option value="<c:out value='${lists.key}'/>"  selected="selected" ><c:out value="${lists.value}" /></option>
       						</c:if>	
       						<c:if test="${lists.key ne gp}">
       								<option value="<c:out value='${lists.key}'/>"  ><c:out value="${lists.value}" /></option>
       						</c:if>
						</c:forEach>
					</c:if> 
              </select>
          </td>
          <c:if test='${sessionScope.userType=="ADMIN" || sessionScope.userType=="DL"}'> 
           <td class="label">Status &nbsp;</td>
          <td>
          <c:if test="${state ne '0' }"> 
          <c:if test="${unviewlgd==null || unviewlgd=='true' }"> 
              <select name="unviewlgd" id="unviewlgd">
              		<option value="true">Active</option>
              		<option value="false">InActive</option>
              		<option value="0">Both</option>
              </select>
           </c:if> 
           <c:if test="${unviewlgd=='false' }"> 
              <select name="unviewlgd" id="unviewlgd">
              		<option value="false">InActive</option>
              		<option value="true">Active</option>
              		<option value="0">Both</option>
              </select>
           </c:if> 
           <c:if test="${unviewlgd=='0' }"> 
              <select name="unviewlgd" id="unviewlgd">
              		<option value="0">Both</option>
              		<option value="true">Active</option>
              		<option value="false">InActive</option>
              </select>
           </c:if> 
           </c:if> 
           <c:if test="${state=='0' }"> 
           <select name="unviewlgd" id="unviewlgd">
              		<option value="false">InActive</option>
              		<option value="true" disabled="disabled">Active</option>
              		<option value="0" disabled="disabled">Both</option>
              </select>
           </c:if> 
          </td>
          </c:if>
          
          <td align="left"> &nbsp; &nbsp;&nbsp;&nbsp;<input type="button" class="btn btn-info" id="view" onclick="showReportSTVill(this);" name="view" value='View Report' /> </td>
       </tr>
      </table> --%>
 </form:form>

<button name="exportExcel" id="exportExcel" onclick="exportExcel()" class="btn btn-info">Excel</button>

        <table class="table">
          <tr>
            <td>
            	<table id="example" class="table">
            	<thead>
              		<tr>
              			<th class="displ" align="center">Sl. No.</th>
              			<c:if test="${userType ne 'DI'}"> 
              				<th class="displ" align="center">District Name</th>
              			</c:if>
		              	<th class="displ" align="center">Project Name</th>
		              	<th class="displ" align="center">Project Location Status</th>
                        <th class="displ" align="center">Total Plot Area Draft</th>
                        <th class="displ" align="center">Baseline Status</th>
               		</tr>
               	</thead>
               	<tbody>
               		<tr>
	               		<th align="center"><b> 1 </b></th>
	               		<th align="center"><b> 2 </b></th>
	               		<th align="center"><b> 3 </b></th>
	               		<th align="center"><b> 4 </b></th>
	               		<th align="center"><b> 5 </b></th>
	               		<c:if test="${userType ne 'DI'}"> 
	               		<th align="center"><b> 6 </b></th>
	               		</c:if>
               		</tr>
                	<c:if test="${Listofstatetovill ne null}"> 
                	<c:forEach var="list" items="${Listofstatetovill}" varStatus="status">
	                	<tr>
	                	   	<td> ${status.count}</td> 
	                	   	<c:if test="${userType ne 'DI'}"> 
		                	   	<td> <c:if test="${distname ne list.dist_name}">
			           						<c:out value="${list.dist_name}"></c:out>
			           						<c:set value="${list.dist_name}" var="distname"/>
			           				</c:if> 
			           			</td>
		           			</c:if>
	                	    <td> <c:out value="${list.projectname}" /> </td>
		           			<td> <c:out value="${list.locstatus}" /> </td>
		           			<td> <c:out value="${list.plot_area_basel}" /> </td>
		           			<td> <c:out value="${list.basestatus}" /> </td>
	                	</tr>
                	</c:forEach>
                	</c:if>
                	</tbody>
              </table>
            </td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
        </table>
    <br>
    
    <%-- <c:if test="${Listofstatetovill.size()>0 }">
     <c:if test='${sessionScope.userType=="ADMIN" || sessionScope.userType=="DL"}'> 
	    <table>
	    <tr>
	    <td>
	   		<b>Note: &nbsp; <input type="checkbox" id="villname" name="villname" checked="checked" disabled="disabled" /> show InActive  </b>
	    </td>
	    </tr>
	    </table>  
	    </c:if>
	</c:if> --%>
  <c:if test="${Listofstatetovill eq null}">
   <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr class="tabs">
            <td><center>No Data Found !</center></td>
            <td >&nbsp;</td>
          </tr>
        </table>
  </c:if>
	
	</div>
	</div>


<script type="text/javascript">
$(document).ready(function(){
$(".sidebar-btn").click(function(){
$(".wrapper").toggleClass("collapse");
	});
	});

</script>
<footer class=" ">
	<%@include file="/WEB-INF/jspf/footer2.jspf"%>
</footer>
</body>
</html>