<%@include file="/WEB-INF/jspf/header2.jspf"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>  

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
<link rel="stylesheet" type="text/css" href="<c:url  value="/resources/css/report.css" />">
<script type="text/javascript">

function exportExcel(){
	var now = new Date();
	var jsDate = now.getDate()+ '-'+ (now.getMonth() + 1)+ '-'+ now.getFullYear();
	var tableName = "#example";
	var colLength=$(tableName+" tr:first th").length;
	var headerTitle = "Watershed Development Component-Pradhan Mantri Krishi Sinchayee Yojana (WDC-PMKSY)";
	var reportName = "List of Physical Head and Activities";
	var fileName="List of Physical Head and Activities";
	var headerHtml = "<table>"+
	 "<tr><td colspan='"+colLength+"' style='text-align:center'>"+headerTitle+"</td></tr>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>"+reportName+"</td></tr>"+
	    "<tr><td></td></tr></table>";
	var footerHtml = "<table>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>Report Generated by WDC software on: "+jsDate+"</td></tr></table>";  
	 exportTableToExcel('example', fileName,headerHtml,footerHtml);
	}



</script>
</head>


<body>
 <br>
<div style="text-align:center;"  ><h5>List of Physical Head and Activities</h5></div>

<br>
<div class ="card">

	<div class="row">
	<div class="col-2" ></div>
	<div class="col-8"  id="exportHtmlToPdf">
	
<button name="exportExcel" id="exportExcel" onclick="exportExcel()" class="btn btn-info">Excel</button>
<!-- <button name="exportPDF" id="exportPDF" onclick="exportPDF()" class="btn btn-info">PDF</button> -->
<!-- <button name="exportPDF"  onclick="javascript:generatePDF()" class="btn btn-info">PDF</button> -->
<p align="right"> Report as on: <%=app.util.Util.dateToString(null,"dd/MM/yyyy hh:mm aaa")%> </p>
<table id="example" cellspacing="0" class="table"   width="auto">
  <thead>
	
    <tr>
      <th style="text-align:center; vertical-align: middle;">S.No.</th>
      <th style="text-align:center; vertical-align: middle;">Head Name</th>
      <th style="text-align:center; vertical-align: middle;">Activity Name</th>
     </tr>
  </thead>
  <tbody>
    <tr>
		<th class="text-center">1</th>
		<th class="text-center">2</th>
		<th class="text-center">3</th>
	</tr>
	
	 <c:if test="${dataList != null}">
		<c:set var="stname" value="" />
		<c:set var="count" value="1" />
		<c:forEach items="${dataList}" var="dataV" varStatus="status">
		<tr>	
			<%-- <td><c:out value='${status.count}' /></td>	 --%>
			<c:choose>
				<c:when test="${stname ne dataV.head_desc}">
					<c:set var="stname" value="${dataV.head_desc}" />
					<td><c:out value='${count}' /></td>
					<td><c:out value='${stname}' /></td>
					<c:set var="count" value="${count+1}" />
				</c:when>	
				<c:otherwise>
					<td></td>
					<td></td>
				</c:otherwise>
			</c:choose>
			<td align="left"><c:out value='${dataV.activity_desc}' /></td>
		</tr>		
		</c:forEach>
    </c:if> 
    	<c:if test="${dataListsize==0}">
			<tr>
				<td align="center" colspan="3" class="required">Data Not Found</td>
			</tr>
		</c:if>
    
  </tbody>
</table>
   
<br/>  
        </div>
        </div>
    <br>
	
	</div>

 <!-- Footer -->
<footer class="text-center">
	<%@include file="/WEB-INF/jspf/footer2.jspf"%>
</footer>
</body>
</html>