<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" errorPage="error.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ include file="/WEB-INF/jspf/header.jspf"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
<link rel="stylesheet" type="text/css" href="<c:url  value="/resources/css/report.css" />">
<script type="text/javascript">

 function exportPDF(){
	var table="";
	var reportName = "State wise Expenditure in a Financial Year";
	var tableName = "#example";
	var columnSpan =false;
	var colLength=$("#example tr:first th").length;
	if ( ! $.fn.DataTable.isDataTable( tableName ) ) {
		createDataTable(reportName,tableName,columnSpan,colLength);
		}
	createDataTable(headerTitle,reportName,tableName);
	//trigger pdf button of datatable
	table=$(tableName).DataTable().buttons(0,1).trigger();
	table.buttons('.buttons-pdf').nodes().css("display", "none");
	table.buttons('.buttons-excel').nodes().css("display", "none");
	} 

function exportExcel(){
	var now = new Date();
	var jsDate = now.getDate()+ '-'+ (now.getMonth() + 1)+ '-'+ now.getFullYear();
	var tableName = "#example";
	 var colLength=$(tableName+" tr:first th").length;
	 var headerTitle = "Watershed Development Component-Pradhan Mantri Krishi Sinchayee Yojana (WDC-PMKSY)";
	var reportName = "Format PF5- State wise PFMS Component Expenditure";
	var fileName="Format PF5- State wise PFMS Component Expenditure";
	 var headerHtml = "<table>"+
	 "<tr><td colspan='"+colLength+"' style='text-align:center'>"+headerTitle+"</td></tr>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>"+reportName+"</td></tr>"+
	    
	    "<tr><td></td></tr></table>";
	    var footerHtml = "<table>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>Report Generated by WDC-PMKSY software on: "+jsDate+"</td></tr></table>";  
	 exportTableToExcel('example', fileName,headerHtml,footerHtml);
	}

function ShowContent(d) 
{
	var dd = document.getElementById(d);
	var width = dd.style.width;
	var index = width.indexOf("px");
	document.getElementById("waitDiv").style.display = "";
	width = width.substring(0,index);
	dd.style.left = ((document.body.clientWidth-width)/2) + "px";
	dd.style.display = "";
}

function showReport(e) 
{
	//alert('kedar');
    var finName = document.getElementById("year").options[document.getElementById("year").selectedIndex].text;
 
    document.getElementById("finName").value=finName;
 
	if(document.getElementById("year").value==='')
	{
		alert('Please select Financial Year ! ');
		$('#year').focus();
		e.preventDefault();
	}
	else{
		
		ShowContent("previewDiv");
		document.stateExpenditure.action="getStateWisePFMSComponent";
		document.stateExpenditure.method="post";
		document.stateExpenditure.submit();
	}
	return false;

}

</script>

<body>
<br>
<div style="text-align:center;"  ><h5>Format PF5- State wise PFMS Component Expenditure</h5></div>
<br>
<div class ="card">
<div class="row">
<div class="col-1" ></div>
<div class="col-8">

<div class="table-responsive" id="exportHtmlToPdf1">

 <form:form action="getStateWisePFMSComponent" name="stateExpenditure" id="stateExpenditure" method="post">
	<div id="waitDiv" 
			style="display: none; line-height: 20px; z-index: 98; position: absolute; background: #ffffff; left: 25px;  height: 800px;
			 width: 1600px; filter: alpha(opacity = 60); -moz-opacity: .60; opacity: .60; text-align: center; float: left;">
			<table>  
				<tr>
					<td>
						<div align="center">
							<span style="padding-right:3px;  display:inline-block; width: 1600px;">
									<img class="manImg" src="resources/images/load.gif"></img>
							</span>
						</div>
					</td>
				</tr>
			</table> 
			</div>
		
    <input type="hidden" name="stName" id="stName" value="" />
	<input type="hidden" name="finName" id="finName" value="" />
	
      <table style="width:50%; align-content: center;" >
        <tr align="center" >
        
         
          <td><b>Financial Year <span style="color: red;">*</span></b></td>
           <td>
              <select name="year" id="year"  required="required" onchange="showReport(this);">
              		<option value="">--Select Year--</option>
						  <c:if test="${not empty financialYear}">
               					<c:forEach items="${financialYear}" var="lists">
               					<c:if test="${lists.finYrCd eq year}">
       								<option value="<c:out value='${lists.finYrCd}'/>" selected="selected" ><c:out value="${lists.finYrDesc}" /></option>
       							</c:if>	
       							<c:if test="${lists.finYrCd ne year}">
       								<option value="<c:out value='${lists.finYrCd}'/>" ><c:out value="${lists.finYrDesc}" /></option>
       							</c:if>
								</c:forEach>
						</c:if>  
              </select>
          </td>
        
           
       </tr>
      </table>
      <div id="previewDiv" class="hiddenDivStyle" align="center"
			style="position: absolute; top: 100px; left: 25px; display: none; width: 300px; height: 50px; vertical-scrol: auto; background-color: gray;">
			<table align="center">
				<tr>
					<td>
						<div align="center">
							<span style="font-size: 25px;">Please Wait ...</span>
						</div>
					</td>
				</tr>
			</table>
		</div>
 </form:form>
 </div>
 </div>
<br>
	</div>
	
	<div class="row">
	<div class="col-1" ></div>
	<div class="col-9"  id="exportHtmlToPdf">
	<br/>
	<br/>
	<button name="exportExcel" id="exportExcel" onclick="exportExcel()" class="btn btn-info">Excel</button>
	<!-- <button name="exportPDF" id="exportPDF" onclick="exportPDF()" class="btn btn-info">PDF</button> -->    
	<p align="right"> Report as on: <%=app.util.Util.dateToString(null,"dd/MM/yyyy hh:mm aaa")%> </p>
	<table id="example" cellspacing="0" class="table" width="50%">
  	<thead>
  		
    	<tr>
      		<th rowspan="2" style="text-align:center; vertical-align: middle; width: 2%;">S.No.</th>
      		<th rowspan="2" style="text-align:center; vertical-align: middle; width: 15%;">State Name</th>
      		<th style="text-align:center; vertical-align: middle;" colspan="3">Area brought under Afforestation / Agriculture / Pasture etc.</th>
      		<th style="text-align:center; vertical-align: middle;" colspan="2">Area covered under Soil and Moisture conservation activities</th>
      		<th style="text-align:center; vertical-align: middle;" colspan="3">Water Harvesting Structure (New created)</th>
      		<th style="text-align:center; vertical-align: middle;" colspan="3">Water Harvesting Structure (Renovated)</th>
      		<th style="text-align:center; vertical-align: middle;" colspan="1">Area brought under Protective Irrigation (Command area - New created WHS)</th>
      </tr>
      <tr>		
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Afforestation</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Agriculture</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Others</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Countour Bunding</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Others</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Farm Ponds</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Nallah Bunds</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Others</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Check Dams</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Others</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Nallah Bunds</th>
      		<th style="text-align:center; vertical-align: middle; width: 3%;">Farm Ponds</th>
      		
     	</tr>
  	</thead>
  	<tbody>
    	<tr>
			<th class="text-center">1</th>
			<th class="text-center">2</th>
			<th class="text-center">3</th>
			<th class="text-center">4</th>
			<th class="text-center">5</th>
			<th class="text-center">6</th>
			<th class="text-center">7</th>
			<th class="text-center">8</th>
			<th class="text-center">9</th>
			<th class="text-center">10</th>
			<th class="text-center">11</th>
			<th class="text-center">12</th>
			<th class="text-center">13</th>
			<th class="text-center">14</th>
		</tr>
		<c:if test="${dataListsize>0}">
		<c:set var="count" value="1" />
		 <c:forEach var="list" items="${dataList}">
			<tr>
				<td align="left"><c:out value='${count}' /></td>
				<td align="left"><c:out value='${list.st_name}' /></td>
				<td align="right"><c:out value='${list.afforestation1}' /></td>
				<td align="right"><c:out value='${list.agriculture1}' /></td>
				<td align="right"><c:out value='${list.others1}' /></td>
				<td align="right"><c:out value='${list.countourbunding3}' /></td>
				<td align="right"><c:out value='${list.others3}' /></td>
				<td align="right"><c:out value='${list.farmponds4}' /></td>
				<td align="right"><c:out value='${list.nallahbunds4}' /></td>
				<td align="right"><c:out value='${list.others4}' /></td>
				<td align="right"><c:out value='${list.checkdams5}' /></td>
				<td align="right"><c:out value='${list.others5}' /></td>
				<td align="right"><c:out value='${list.nallahbunding5}' /></td>
				<td align="right"><c:out value='${list.farmponds6}' /></td>
					
				<c:set var="count" value="${count+1}" />
			</tr>
		</c:forEach>

	 	<c:forEach items="${dataListNetTotal}" var="netTotal" varStatus="seqTotal">
			<tr>
				<td align="right" class="table-primary" colspan="2"><b>Grand Total </b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[0]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[1]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[2]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[3]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[4]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[5]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[6]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[7]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[8]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[9]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[10]}"/></b></td>
				<td align="right" class="table-primary" ><b><fmt:formatNumber type="number" maxFractionDigits="5" minFractionDigits="4" value="${netTotal[11]}"/></b></td>
			</tr>
		</c:forEach> 
		</c:if> 
		<c:if test="${dataListsize==0}">
			<tr>
				<td align="center" colspan="14" class="required" style="color:red;">Data Not Found</td>
			</tr>
		</c:if>

	</tbody>
  </table>
</div>
</div>
</div>


<footer class="text-center">
	<%@include file="/WEB-INF/jspf/footer2.jspf"%>
</footer>
</body>
</html>