<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" errorPage="error.jsp"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@include file="/WEB-INF/jspf/header.jspf"%>

<!DOCTYPE html>
<html>
<head>
<title>Report OT1- To View Best Practices/Innovations/Success Stories uploaded by States</title>
<meta charset="ISO-8859-1">


<link rel="stylesheet" href="resources/css/all.min.css">
<link rel="stylesheet" type="text/css" href="<c:url  value="/resources/css/report.css" />">

<script type="text/javascript">

function getUploadDtlRpt(){
	var state = $('#state').val();
	
	if(state==='')
	{
		alert('Please select state ');
		$('#state').focus();
		e.preventDefault();
	}
	
	else{
		
		document.userUploadDetails.action="getUploadDtlRpt";
		document.userUploadDetails.method="post";
		document.userUploadDetails.submit();
	}
	return false;
}

function exportPDF(){
	var table="";
	var reportName = "Report OT1- To View Best Practices/Innovations/Success Stories uploaded by States";
	var tableName = "#example";
	var columnSpan =false;
	var colLength=$("#example tr:first th").length;
	if ( ! $.fn.DataTable.isDataTable( tableName ) ) {
		createDataTable(reportName,tableName,columnSpan,colLength);
		}
	//createDataTable(headerTitle,reportName,tableName);
	//trigger pdf button of datatable
	table=$(tableName).DataTable().buttons(0,1).trigger();
	table.buttons('.buttons-pdf').nodes().css("display", "none");
	table.buttons('.buttons-excel').nodes().css("display", "none");
	}


	/***************************************************** Excel Button Click ************************************* */
	function exportExcel(){
	var now = new Date();
	var jsDate = now.getDate()+ '-'+ (now.getMonth() + 1)+ '-'+ now.getFullYear();
	var tableName = "#example";
	 var colLength=$(tableName+" tr:first th").length;
	 var headerTitle = "Watershed Development Component-Pradhan Mantri Krishi Sinchayee Yojana (WDC-PMKSY)";
	var reportName = "Report OT1- To View Best Practices/Innovations/Success Stories uploaded by States";
	var fileName="uploaded by States";
	 var headerHtml = "<table>"+
	 "<tr><td colspan='"+colLength+"' style='text-align:center'>"+headerTitle+"</td></tr>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>"+reportName+"</td></tr>"+
	    
	    "<tr><td></td></tr></table>";
	    var footerHtml = "<table>"+
	    "<tr><td colspan='"+colLength+"' style='text-align:center'>Report Generated by WDC-PMKSY software on: "+jsDate+"</td></tr></table>";  
	 exportTableToExcel('example', fileName,headerHtml,footerHtml);
	}


</script>
</head>


<body>
 
<div class="offset-md-3 col-6 formheading" style="text-align:center;"  ><h5>Report OT1- To View Best Practices/Innovations/Success Stories uploaded by States</h5></div>

<br>
<div class ="card">
<div class="row">
<div class="col-2" ></div>
<div class="col-9">

<div class="table-responsive">

 <form:form autocomplete="off" name="userUploadDetails" id="userUploadDetails"  modelAttribute="userUploadDetails" action="getUploadDtlRpt" method="post">
 
      <table style="width:88%; align-content: center;" >
        <tr align="center" >
        
          <td style="width:25%"><b>State <span style="color: red;">*</span></b></td>
          <td style="width:35%">
              <select name="state" id="state" >
              		<option value="0">--All States--</option>
                  	<c:if test="${not empty stateList}">
               			<c:forEach items="${stateList}" var="lists">
               				<c:if test="${lists.key eq state}">
       								<option value="<c:out value='${lists.key}'/>"  selected="selected" ><c:out value="${lists.value}" /></option>
       						</c:if>	
       						<c:if test="${lists.key ne state}">
       								<option value="<c:out value='${lists.key}'/>"  ><c:out value="${lists.value}" /></option>
       						</c:if>
						</c:forEach>
					</c:if> 
              </select>
          </td>
         
          <td style="width:28%" align="center" class="label"> 
          <input type="button" class="btn btn-info" id="view" onclick="getUploadDtlRpt();" name="view" value='View Report' /> </td>
       </tr>
      </table>
 </form:form>
 </div>
 </div>
<br>
	</div>
	
	<div class="row">
	<div class="col-2" ></div>
	<div class="col-8">
	<p align="right"> Report as on: <%=app.util.Util.dateToString(null,"dd/MM/yyyy hh:mm aaa")%> </p>
	<c:if test="${dataListsize>0}">
	<button name="exportExcel" id="exportExcel" onclick="exportExcel()" class="btn btn-info">Excel</button>
	<button name="exportPDF" id="exportPDF" onclick="exportPDF()" class="btn btn-info">PDF</button>
	
	</c:if>
        <table class="table">
          <tr>
            <td>
            
            	<table id="example" class="table">
            	<thead>
              		<tr align="center">
              			<th align="center" width="2">S.No.</th>
		              	<th align="center" width="20">State Name</th>
                        <th align="center" >Subject</th>
                        <th align="center" width="5">Last Updated on</th>
                        
               		</tr>	</thead>
               	<tbody>	
               		<tr>
	               		<th align="center"><b> 1 </b></th>
	               		<th align="center"><b> 2 </b></th>
	               		<th align="center"><b> 3 </b></th>
		               	<th align="center"><b> 4 </b></th>
		               	
               		</tr>
               
               		 <c:if test="${dataListsize>0}">
						<c:forEach items="${dataList}" var="dataV" varStatus="count">
							<tr>
								<td><c:out value='${dataV[0]}' /></td>
								<td><c:out value='${dataV[2]}' /></td>
								<td>
								<c:if test="${dataV[6] != null }">
									 <a target="_blank" href="http://wdcpmksy.dolr.gov.in/filepath/PRD/CircularMessageAlert/${dataV[6]}"  ><c:out value='${dataV[5]}' /></a> 
									<%-- <a target="_blank" href="http://wdcpmksy.dolr.gov.in/TESTING/CircularMessageAlert/${dataV[6]}"  ><c:out value='${dataV[5]}' /></a> --%>
									<c:if test="${dataV[13] == 'true' }">
										<img src="<c:url value="/resources/images/new.gif" />" />
									</c:if>
								</c:if>	
								<c:if test="${dataV[6]== null }">
									<c:out value='${dataV[5]}' />
									<c:if test="${dataV[13] == 'true' }">
										<img src="<c:url value="/resources/images/new.gif" />" />
									</c:if>
								</c:if>
								</td>
								<td><c:out value='${dataV[12]}' /></td>
							</tr>
						</c:forEach>
					</c:if> 
					<c:if test="${dataListsize==0 }">
					<tr><td colspan="4"><center><span style="color: red;"> No Data Found !</span></center></td></tr>
					</c:if>
              </tbody>
              </table>
            </td>
          </tr>
          <tr>
            <td>
            	<c:if test="${dataListsize<=0 }">
   					<!-- <table width="100%" border="0" cellspacing="0" cellpadding="0"> -->
          				<!-- <tr class="tabs">
            				<td> --><!-- </td>
            				
          				</tr> -->
        			<!-- </table> -->
  				</c:if>
  			</td>
          </tr>
        </table>
        </div>
        </div>
    <br>
	
	</div>

 <!-- Footer -->
<footer class="text-center">
	<%@include file="/WEB-INF/jspf/footer.jspf"%>
</footer>
</body>
</html>