<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" errorPage="error.jsp"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@include file="/WEB-INF/jspf/header.jspf"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<head>
<title>Report O6- State wise Distribution of Area According to Irrigation Status, Ownership Status, Land Classification and No of Crops as On Date</title>
<script type="text/javascript">


function downloadPDF()
{
		
		document.getreport.action="downloadblOutcomePDF";
		document.getreport.method="post";
		document.getreport.submit();
	
} 

function exportExcel()
{
		
		document.getreport.action="downloadExcelblsareaoutcomedtlrpt";
		document.getreport.method="post";
		document.getreport.submit();
	
} 

// function exportExcel(){
// 	var now = new Date();
// 	var jsDate = now.getDate()+ '-'+ (now.getMonth() + 1)+ '-'+ now.getFullYear();
// 	var tableName = "#tblReport";
// 	 var colLength=$(tableName+" tr:first th").length;
// 	 var headerTitle = "Watershed Development Component-Pradhan Mantri Krishi Sinchayee Yojana (WDC-PMKSY)";
// 	var reportName = "Report O6- State wise Details of Baseline Outcome";
// 	var fileName="Report O6- State wise Details of Baseline Outcome";
// 	 var headerHtml = "<table>"+
// 	 "<tr><td colspan='"+colLength+"' style='text-align:center'>"+headerTitle+"</td></tr>"+
// 	    "<tr><td colspan='"+colLength+"' style='text-align:center'>"+reportName+"</td></tr>"+
	    
// 	    "<tr><td></td></tr></table>";
// 	    var footerHtml = "<table>"+
// 	    "<tr><td colspan='"+colLength+"' style='text-align:center'>Report Generated by WDC-PMKSY software on: "+jsDate+"</td></tr></table>";  
// 	 exportTableToExcel('tblReport', fileName,headerHtml,footerHtml);
// 	}

</script>
</head>


<form action="downloadblOutcomePDF" method="post" name="getreport"></form>
<div class="container-fluid">
	<div class="offset-md-3 col-6 formheading" style="text-align: center;">
		<h5>Report O6- State wise Distribution of Area According to Irrigation Status, Ownership Status, Land Classification and No of Crops as On Date</h5>
	</div>
	<button name="exportExcel" id="exportExcel" onclick="exportExcel()"	class="btn btn-info">Excel</button>
	<button name="exportPDF" id="exportPDF" onclick="downloadPDF()"	class="btn btn-info">PDF</button>
	<p align="right"> Report as on: <%=app.util.Util.dateToString(null,"dd/MM/yyyy hh:mm aaa")%> </p>
	<table id="tblReport" class="table">
		<thead>
			<tr>
				<th class="text-right" colspan="21">All area in ha. </th>
			</tr>
			<tr>
				<th rowspan="3" class="text-center">S.No.</th>
				<th rowspan="3" class="text-center">State</th>
				<th rowspan="3" class="text-center">Total Project Area</th>
				<th rowspan="3" class="text-center">Plot Area</th>
				<th colspan="3" class="text-center">Irrigation Status(Area)</th>
				<th colspan="4" class="text-center">Ownership(Area)</th>
				<th colspan="6" class="text-center">Classification of Land(Area)</th>
				<th colspan="4" class="text-center">No. of Crops(Area)</th>
			</tr>
			<tr>
				<th rowspan="2" class="text-center">Protective Irrigation</th>
				<th rowspan="2" class="text-center">Assured Irrigation</th>
				<th rowspan="2" class="text-center">No Irrigation</th>
				<th rowspan="2" class="text-center">Private</th>
				<th rowspan="2" class="text-center">Government</th>
				<th rowspan="2" class="text-center">Community</th>
				<th rowspan="2" class="text-center">Others</th>
				<th rowspan="2" class="text-center">Cultural Wasteland</th>
				<th rowspan="2" class="text-center">Degraded Land</th>
				<th rowspan="2" class="text-center">Rainfed Land</th>
				<th colspan="2" class="text-center">Forest Land</th>
				<th rowspan="2" class="text-center">Others</th>
				<th rowspan="2" class="text-center">No Crops</th>
				<th rowspan="2" class="text-center">Single Crops</th>
				<th rowspan="2" class="text-center">Double Crops</th>
				<th rowspan="2" class="text-center">Multiple Crops</th>
			</tr>
			<tr>
				<th class="text-center">Plantation</th>
				<th class="text-center">No Plantation</th>
			</tr>
			<tr>
				<th class="text-center">1</th>
				<th class="text-center">2</th>
				<th class="text-center">3</th>
				<th class="text-center">4</th>
				<th class="text-center">5</th>
				<th class="text-center">6</th>
				<th class="text-center">7</th>
				<th class="text-center">8</th>
				<th class="text-center">9</th>
				<th class="text-center">10</th>
				<th class="text-center">11</th>
				<th class="text-center">12</th>
				<th class="text-center">13</th>
				<th class="text-center">14</th>
				<th class="text-center">15</th>
				<th class="text-center">16</th>
				<th class="text-center">17</th>
				<th class="text-center">18</th>
				<th class="text-center">19</th>
				<th class="text-center">20</th>
				<th class="text-center">21</th>
			</tr>
		</thead>

		<tbody id="stwiseAreaRptTbody">

			<c:forEach items="${stwiseAreaAchDtlList}" var="project" varStatus="sno">
				<tr>
					<td class="text-center"><c:out value="${sno.count}" /></td>
<%-- 					<td><a href="blsrptdist?id=<c:out value="${project.stcode}"/>"><c:out --%>
<%-- 								value="${project.stname}" /></a></td> --%>
<%-- 					<td><c:out value="${project.stname}" /></td> --%>
<td><a href="getDistwiseAreaAchieveDetail?stcode=<c:out value="${project.stcode}"/>&stname=<c:out value="${project.stname}" />"><c:out value="${project.stname}" /></a></td>
					<td class="text-right"><fmt:formatNumber minFractionDigits="4"><c:out value="${project.project_area}" /></fmt:formatNumber></td>
					<td class="text-right"><c:out value="${project.plot_area_ach}" /></td>
					<td class="text-right"><c:out value="${project.protective_irrigation_ach}" /></td>
					<td class="text-right"><c:out value="${project.assured_irrigation_ach}" /></td>
					<td class="text-right"><c:out value="${project.no_irrigation_ach}" /></td>
					<td class="text-right"><c:out value="${project.private_owner_ach}" /></td>
					<td class="text-right"><c:out value="${project.govt_owned_ach}" /></td>
					<td class="text-right"><c:out value="${project.community_owned_ach}" /></td>
					<td class="text-right"><c:out value="${project.others_owned_ach}" /></td>
					<td class="text-right"><c:out value="${project.cultivable_wasteland_ach}" /></td>
					<td class="text-right"><c:out value="${project.degraded_ach}" /></td>
					<td class="text-right"><c:out value="${project.rainfed_ach}" /></td>
					<td class="text-right"><c:out value="${project.plantation_ach}" /></td>
					<td class="text-right"><c:out value="${project.no_plantation_ach}" /></td>
					<td class="text-right"><c:out value="${project.others_classification_ach}" /></td>
					<td class="text-right"><c:out value="${project.no_crop_ach}" /></td>
					<td class="text-right"><c:out value="${project.single_crop_ach}" /></td>
					<td class="text-right"><c:out value="${project.double_crop_ach}" /></td>
					<td class="text-right"><c:out value="${project.multiple_crop_ach}" /></td>
				</tr>

				<c:set var="totalproject_area"
 					value="${totalproject_area+ project.project_area}" />
 				<c:set var="totalplot_area_ach" 
 					value="${ totalplot_area_ach+project.plot_area_ach}" /> 
 				<c:set var="totalprotective_irrigation_ach" 
 					value="${ totalprotective_irrigation_ach+project.protective_irrigation_ach}" /> 
 					<c:set var="totalassured_irrigation_ach" 
 					value="${ totalassured_irrigation_ach+project.assured_irrigation_ach}" /> 
 					<c:set var="totalno_irrigation_ach" 
 					value="${ totalno_irrigation_ach+project.no_irrigation_ach}" /> 
 					<c:set var="totalprivate_owner_ach" 
 					value="${ totalprivate_owner_ach+project.private_owner_ach}" /> 
 					<c:set var="totalgovt_owned_ach" 
 					value="${ totalgovt_owned_ach+project.govt_owned_ach}" /> 
 					<c:set var="totalcommunity_owned_ach" 
 					value="${ totalcommunity_owned_ach+project.community_owned_ach}" /> 
 					<c:set var="totalothers_owned_ach" 
 					value="${ totalothers_owned_ach+project.others_owned_ach}" /> 
 					<c:set var="totalcultivable_wasteland_ach" 
 					value="${ totalcultivable_wasteland_ach+project.cultivable_wasteland_ach}" /> 
 					<c:set var="totaldegraded_ach" 
 					value="${ totaldegraded_ach+project.degraded_ach}" /> 
 					<c:set var="totalrainfed_ach" 
 					value="${ totalrainfed_ach+project.rainfed_ach}" />
 					<c:set var="totalplantation_ach" 
 					value="${ totalplantation_ach+project.plantation_ach}" />
 					<c:set var="totalno_plantation_ach" 
 					value="${ totalno_plantation_ach+project.no_plantation_ach}" />
 					<c:set var="totalothers_classification_ach" 
 					value="${ totalothers_classification_ach+project.others_classification_ach}" /> 
 					<c:set var="totalno_crop_ach" 
 					value="${ totalno_crop_ach+project.no_crop_ach}" /> 
 					<c:set var="totalsingle_crop_ach" 
 					value="${ totalsingle_crop_ach+project.single_crop_ach}" /> 
 					<c:set var="totaldouble_crop_ach" 
 					value="${ totaldouble_crop_ach+project.double_crop_ach}" /> 
 					<c:set var="totalmultiple_crop_ach" 
 					value="${ totalmultiple_crop_ach+project.multiple_crop_ach}" /> 
 					

			</c:forEach>
			<tr>
				<td  colspan="2" class="table-primary"align="right"><b>Grand Total</b></td>
				<td align="right" class="table-primary"><b><fmt:formatNumber minFractionDigits="4"><c:out value="${totalproject_area}" /></fmt:formatNumber></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalplot_area_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalprotective_irrigation_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalassured_irrigation_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalno_irrigation_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalprivate_owner_ach}"/></b></td> 
				<td align="right" class="table-primary"><b><c:out value="${totalgovt_owned_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalcommunity_owned_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalothers_owned_ach}"/></b></td> 
				<td align="right" class="table-primary"><b><c:out value="${totalcultivable_wasteland_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totaldegraded_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalrainfed_ach}"/></b></td> 
				<td align="right" class="table-primary"><b><c:out value="${totalplantation_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalno_plantation_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalothers_classification_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalno_crop_ach}"/></b></td> 
				<td align="right" class="table-primary"><b><c:out value="${totalsingle_crop_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totaldouble_crop_ach}" /></b></td>
				<td align="right" class="table-primary"><b><c:out value="${totalmultiple_crop_ach}"/></b></td> 
				
			</tr>


		</tbody>
	</table>
</div>